### ISSUE TITLE
Tungsten Seeds' Tier

### ISSUE THREAD

**Issue by ResminZ** [Freebi85/Dungeons-Dragons-Space-Shuttles#100]
Tungsten seed shows that it's tier 5, although it requires tier 6 crafting seed.
![2019-03-15_01 56 10](https://user-images.githubusercontent.com/42918091/54394157-87a8d080-46c5-11e9-9f08-f67cb8ce9d49.png)

**Comment by Freebi85** [comment]
Okay, I'll see if I can change that.
