### ISSUE TITLE
Tips for this beautiful modpack

### ISSUE THREAD

**Issue by cris195** [Freebi85/Dungeons-Dragons-Space-Shuttles#103]
Hello! I love your modpack, and it often makes me angry about its difficult recipes, but I love it. I wanted to advise you of the possible mods to add in the future maybe that could be useful, even if some are OP I'm sure you will modify the recipes.
-ore excavating + integration
-building gadget
-huds armor status and damage indicator (for adventure)
and for the end game TORCHERINO XD

Thank you so much for all the work you do in building this beautiful modpack!

P.S.:if you understand little what I wrote is because I'm Italian and I'm using google translator :)

**Comment by Freebi85** [comment]
Thanks! happy that you like it! but at the moment I am careful with new mods. The pack already has many and is very resource intensive.

Allora mi dispiace ma al moment non vorrei angguigere di piu mods. Scuca se il mio italiano fa schifo ma lo uso pocho xD Forse solo Damage indicator / armor status hud.  Li non ce niente di male.
cmq il pack e gia molto grande e quindi devo fare attenzione che non mi seplode in faccia :D

**Comment by cris195** [comment]
it was just a suggestion, the pack is already so amazing! and your Italian is very good;)

**Comment by Freebi85** [comment]
Thx =) But i will close for now. Maybe later when I'm done with the modpack.
