### ISSUE TITLE
You can craft 4 chests with 8 wooden logs, but you should only be able to craft 2.

### ISSUE THREAD

**Issue by Autowinto** [Freebi85/Dungeons-Dragons-Space-Shuttles#104]
![image](https://user-images.githubusercontent.com/24361128/54474093-be273e00-47e0-11e9-87ef-fc30df725fae.png)

Since you only get two planks from crafting a log in a regular crafting table, you should only be able to make two chests with the log recipe.

**Comment by DarkSideofDawn** [comment]
This was the case in another modpacks as well. Think this one is okay :)

**Comment by Freebi85** [comment]
thx for the hint. i will remove the log recipe completely.
