### ISSUE TITLE
Energy Cubes recipes from Mekanism does not appear to work

### ISSUE THREAD

**Issue by Xnosis** [Freebi85/Dungeons-Dragons-Space-Shuttles#106]
![image](https://user-images.githubusercontent.com/12546871/54484012-366b1f00-4834-11e9-8ead-7978fc0d2505.png)

**Comment by Xnosis** [comment]
![image](https://user-images.githubusercontent.com/12546871/54484090-81396680-4835-11e9-8d92-b39fc9f6fa7f.png)

**Comment by Freebi85** [comment]
yes confirmed. Thx for reporting. Fix asap
