### ISSUE TITLE
Liquid Magma

### ISSUE THREAD

**Issue by DarkSideofDawn** [Freebi85/Dungeons-Dragons-Space-Shuttles#107]
Upon accidentally making two invar large sword blade from Tinkers, I learned that lava wasn't hot enough to melt it again. We made liquid magma, but the tool tip says 300k temp and when it's in the Tinkers smeltery it only says 300 temp and t wouldn't melt the sword blade (we got the blue bar says temp not hot enough).

Game version Version 4.6b

**Comment by Freebi85** [comment]
Ok thank you. I don't know if i can customize the tooltip but what i can say is you need liquid pyrotheum. You can melt everything with it.

**Comment by DarkSideofDawn** [comment]
Aye- we ended up going to blazing pyrotheum:)

**Comment by Freebi85** [comment]
seems like I can't change that right now. I have to look for other methods if there are any. I will close the issue because your problem has been solved. But I will continue to work on finding a solution.
