### ISSUE TITLE
Dank/null recipe

### ISSUE THREAD

**Issue by Gh0stic** [Freebi85/Dungeons-Dragons-Space-Shuttles#108]
![Dank null](https://user-images.githubusercontent.com/19212791/54495652-aff62200-48b3-11e9-99a8-cdaa371f9b65.PNG)

the new dank null recipes don't seem to be working. they show up in JEI but doesn't work when trying it.

**Comment by Freebi85** [comment]
Oh thats weird. Thx for reporting. I will look into that. Try if this happens again after a relog in your world 🌎
