### ISSUE TITLE
Suggested rebalance

### ISSUE THREAD

**Issue by billyty08** [Freebi85/Dungeons-Dragons-Space-Shuttles#11]
I suggest the recipe for cardboard box from Mekanism be nerfed along the same line as the chest transporters. As of now it is 4 sawdust which is cheap in comparison for an item that can move chests as well as monster spawner cages. Loving the pack

**Comment by Freebi85** [comment]
Hallo billyty ;)
Thanks for reporting this!
I definitely have to rebalance this Transport Box Until  next Update^^

**Comment by Freebi85** [comment]
Fixed this for netx update. Yeeeey!
