### ISSUE TITLE
'integrateddynamics' is very useful like ‘xnet’, but very cheap

### ISSUE THREAD

**Issue by Leaveleaf** [Freebi85/Dungeons-Dragons-Space-Shuttles#111]
'integrateddynamics' is very useful like ‘xnet’, but very cheap

**Comment by Freebi85** [comment]
Hi =)
What do you mean exactly? The most machines / cables are balanced. A Specific item maybe?
Ok the cables may be a little cheap.

**Comment by Leaveleaf** [comment]
yep, cables and 'integratedtunnels' , They can be used very easily to do some automation, Even wireless(<integrateddynamics:part_connector_mono_directional_item>)

**Comment by Freebi85** [comment]
ok thanks i will look into it and let some of my evil ideas flow in^^

**Comment by dierke9** [comment]
Freebi uses nerf. It was super effective
