### ISSUE TITLE
Lots of crafting recipies and even furnace recipies not working

### ISSUE THREAD

**Issue by ThaBazZz** [Freebi85/Dungeons-Dragons-Space-Shuttles#112]
Hi,

Im trying to work my way through tier 0 in the questbook , but im having trouble to craft things because recipies are not working..jei shows the plus sign to shift click the ingredients into the crafting table but it still cant be crafted..the rice quests where some and also the copper plate quest with the hammer is an example..
I'm having to use cheats allot just to playthrough wich makes the pack not playable for me..
hope you can confirm and fix..i don't have the time to go through every recipy to check for you whats broken exactly but at least i give you a hint..

take care

**Comment by dierke9** [comment]
Is this in a server? If yes then there is a problem with the serverfiles. You will need to redownload them.

**Comment by ThaBazZz** [comment]
No its in the latest single player version.. but i will re-install and try again none the less

**Comment by Freebi85** [comment]
sounds like broken crafting scripts. I Can't confirm this because the recipes works fine. Either the files are corruptet or a mod was removed from the pack.

**Comment by cyber01** [comment]
Can you upload your config and scripts folder in zip archive?

**Comment by ThaBazZz** [comment]
darn i just deleted and re-installed the pack..starting it up now..if it is still not working i will upload them..

**Comment by ThaBazZz** [comment]
oke sorry for taking your time for nothing...all seems to work fine now #rolleyes
thank you for the rapid response though 👍

**Comment by dierke9** [comment]
Its better to make an issue then to keep playing with a broken pack 😉
Have fun with the pack 😁

**Comment by Freebi85** [comment]
Have fun :D GG!
