### ISSUE TITLE
Ur-Ghast quest may be broken

### ISSUE THREAD

**Issue by MrScrewIt** [Freebi85/Dungeons-Dragons-Space-Shuttles#115]
Hello again. I defeated a ur-ghast from the twilight forest, and the quest never recognized it. I thought it may be a bug from better questing, but someone else reported the metallurgic infuser quest, so I decided to type up a report. Is this anything you can fix? Thanks :)

**Comment by Freebi85** [comment]
That's odd. I'll take a look at it =)
