### ISSUE TITLE
Quests: "Your Hands; The Pulverizer" and "Bronze Blend" ratios are wrong

### ISSUE THREAD

**Issue by Willshaper** [Freebi85/Dungeons-Dragons-Space-Shuttles#116]
Edit:

I'm dumb. Might be a good idea to look at other quests before posting here. Just noticed that the 6 leftover copper is for the redstone related quest. Please ignore this :p

In the Ores, Alloys & Smeltery [Tier 1] chapter, the "Your Hands; The Pulverizer" and "Bronze Blend" quests have wrong item ratios for the quests:

Your Hands; The Pulverizer asks you to get the following:

Pulverized Tin: 6
Pulverized Copper: 18

The next quest, Bronze Blend, asks you to get 12 Bronze Blend by hand crafting it.
The recipe to get this, is the following:

Pulverized Tin: 6
Pulverized Copper: 12

Meaning the first of the quests wants you to get 6 more Pulverized Copper than is required.

https://i.imgur.com/iKNi9Pw.png

**Comment by Freebi85** [comment]
:P
