### ISSUE TITLE
Two bug, Pneu(liquid_hopper), and TR(rolling_machine)

### ISSUE THREAD

**Issue by Leaveleaf** [Freebi85/Dungeons-Dragons-Space-Shuttles#118]
I am not a native English speaker, So the author needs you to contact.   :)
![image](https://user-images.githubusercontent.com/19620848/55554354-1fbe3680-5715-11e9-98a4-57b975befc98.png)
![image](https://user-images.githubusercontent.com/19620848/55554359-23ea5400-5715-11e9-9e02-ce880d995726.png)
![image](https://user-images.githubusercontent.com/19620848/55554368-28167180-5715-11e9-8931-99baf9a8fc36.png)

![image](https://user-images.githubusercontent.com/19620848/55554318-0cab6680-5715-11e9-8267-4716c3631e72.png)
![image](https://user-images.githubusercontent.com/19620848/55554322-103eed80-5715-11e9-8458-1e200ad60de5.png)
![image](https://user-images.githubusercontent.com/19620848/55554332-146b0b00-5715-11e9-84ee-fe8c2799f735.png)
![image](https://user-images.githubusercontent.com/19620848/55554338-17fe9200-5715-11e9-86b1-2e28f2a1b107.png)

**Comment by Leaveleaf** [comment]
：）

**Comment by Leaveleaf** [comment]
hey Freebi85 , we're should updata 'ExtendedCrafting'

![image](https://user-images.githubusercontent.com/19620848/56137355-3a22ca80-5fc7-11e9-92a0-f39a79b2f6ab.png)
![image](https://user-images.githubusercontent.com/19620848/56137373-46a72300-5fc7-11e9-9cae-6d4ad1f5e266.png)


Release 1.5.4 for MC 1.12.2

Changes:

Fixed the Automation Interface not detecting tables when no recipe is saved

**Comment by Freebi85** [comment]
In next update =) (weekend)
