### ISSUE TITLE
Underground Biomes/transparency-seethrough

### ISSUE THREAD

**Issue by squillis** [Freebi85/Dungeons-Dragons-Space-Shuttles#120]
Issue is pretty self explanatory, you can see through all the ores generated from Underground biome blocks. I don't know if this is a modpack issue or just underground biome issue? I can post about it on the Underground Biome mod if it's them.

![2019-04-05_18 40 12](https://user-images.githubusercontent.com/14357840/55660207-2ad79c00-57d3-11e9-8fa5-a00fa0785ec6.png)
![2019-04-05_18 40 16](https://user-images.githubusercontent.com/14357840/55660208-2c08c900-57d3-11e9-92b3-f6c1b13fb9df.png)

**Comment by dierke9** [comment]
This is a problem with UB which has already been reported there. https://github.com/Aang23/UndergroundBiomesConstructs/issues/70

**Comment by Freebi85** [comment]
Is unfortunately a known bug that is in progress at underground biomes. Unfortunately we can only wait for a fix. Since this problem is already handled by the mod author I'm closing here. Nevertheless thanks for Reporting!
