### ISSUE TITLE
[Suggestion] Make Liquid Lumium Recipes a multiple of 144

### ISSUE THREAD

**Issue by skills697** [Freebi85/Dungeons-Dragons-Space-Shuttles#122]
Just wanted to leave a suggestion on something that I feel should be changed. All of the liquid lumium recipes which is used for a number of cables and batteries are all made to be a multiple 1000mb each. However you only get 144mb per lumium ingot or craft of lumium dust. This makes it so that it doesn't add anywhere near correctly or evenly when used.

This is me after smelting 7 ingots:
![DDSS_Suggestion1](https://user-images.githubusercontent.com/2799001/56098402-da90c600-5ec5-11e9-8a3d-a32b7cdbb2ab.png)

This is the recipe I was making:
![DDSS_Suggestion2](https://user-images.githubusercontent.com/2799001/56098403-debce380-5ec5-11e9-8137-cb12d111c7a5.png)

Edit: Oh also just wanted to say thanks for the amazing pack and all of the hard work you have put in to making it! 🥇

**Comment by Freebi85** [comment]
Thank you =)
Yes, this basically applies to all liquids that arise from an ingot. There are also other recipes that need for example molten inferium or manyullin. An ingot is basically 144 mb and therefore all values of the smerltery and of all machines have to be adjusted. That would be too much work and the possibility of dupes would be big.
I might change the number of mb needed for the recipes as soon as I have more time.

**Comment by Scheills** [comment]
14 ingots will produce 2 full buckets and 1 nugget exactly, so there is no waste.

**Comment by Freebi85** [comment]
I'll leave the values as they are for now. But in my next project I will come up with something better =)
