### ISSUE TITLE
[Spelling Error] "Trasure" slime

### ISSUE THREAD

**Issue by AnimatorOfSouls** [Freebi85/Dungeons-Dragons-Space-Shuttles#123]
I believe it should be "treasure" slime.
Found in the "Slime Bucket Challenge!" quest in the first section of the quest book.
![trasure slime](https://user-images.githubusercontent.com/33594615/56098737-5eb17080-5efb-11e9-9867-233696eadb61.PNG)

**Comment by Freebi85** [comment]
Thanks my friend =)

**Comment by AnimatorOfSouls** [comment]
np
