### ISSUE TITLE
Crash & world corruption from Malisis and Cyclic interaction

### ISSUE THREAD

**Issue by Brettflan** [Freebi85/Dungeons-Dragons-Space-Shuttles#124]
I'm reporting this over on the Malisis Github as well, since it seems the slightly more likely culprit.

I tried and was able to replicate this, so it should be easy enough. 

1. Place an Iron Glass Door (from Malisis).
2. Place an Entity Detector (from Cyclic) on top of it.
3. Right-click the Entity Detector, and lower the "Count before trigger" on the right side to 0.
The game immediately crashes with this NPE:
https://paste.dimdev.org/qidiyewivo.mccrash
Attempting to load back into that world will result immediately in the same crash. I was able to use MCEdit to remove the tile entity from the Entity Detector block so that I could safely access that world again.

**Comment by Brettflan** [comment]
Actually, just tested and found it happens with a vanilla Minecraft door as well, so Cyclic is the culprit.

**Comment by dierke9** [comment]
I see in your post that you have also posted this on Malasis github. Would you be able to send a link of the issue in here so we can follow it up aswell?

**Comment by dierke9** [comment]
And i would also look to post it on cyclic github

**Comment by Brettflan** [comment]
Cyclic report:
https://github.com/Lothrazar/Cyclic/issues/1107

**Comment by dierke9** [comment]
It can still be malisis as this overwrites the vanilla door (ie for its smoother opening) so keep the issue open there if you already created it. And throw a link in here aswell

**Comment by Brettflan** [comment]
OK, I just tested removing Malisis Doors and Malisis Doors and tried again. Got a crash again:
https://paste.dimdev.org/metiwevofu.mccrash

So it does appear to be Cyclic specifically, not Malisis.

**Comment by Freebi85** [comment]
Thx for reporting this to cyclic. There is no much i can do against it. Lets wait and see for next cyclic update.

**Comment by Freebi85** [comment]
sadly no fix in the last 2 cyclic updates. I will remove this item as long as it causes problems.

**Comment by Brettflan** [comment]
Apparently it should be fixed in Cyclic now in 1.19.4.
