### ISSUE TITLE
Gas Tank quest not detecting item

### ISSUE THREAD

**Issue by Brettflan** [Freebi85/Dungeons-Dragons-Space-Shuttles#125]
I've just gotten into the Blacksmith's Workshop questline. The second one in, Gas Tank, is to craft a basic gas tank. I just crafted one, and it's not being detected properly by the quest. I tried placing it down and picking it back up, but that didn't fix it.

https://imgur.com/a/9KtvdrK

**Comment by Freebi85** [comment]
this issue was resolved in 4.9. Did you play on latest version AND refresh the questbook?

**Comment by Brettflan** [comment]
I am playing on 4.9, but I think the game might have been started on an earlier version. I haven't refreshed the quest book, so I imagine that was the problem.
I've just done that, and I see the quest book has new sections.

Apologies.

**Comment by Freebi85** [comment]
All right, I'm glad this is working. =)
