### ISSUE TITLE
4.11 - Best mining level you've ever seen! Quest broken

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#127]
I am running 4.11 dedicated server/client.  I just completed the "Best mining level you've ever seen!" quest, and attempted to claim the rewards.  Clicking "Claim", I only got the solarium ingot, and the quest was not marked as completed.  Furthermore, the Claim button was still enabled, and clicking it repeatedly kept rewarding me more "free" solarium ingots!

I'd rather have the Iridium, frankly, since I've already smelted several blocks of solarium (more than I'll practically need in the foreseeable future). ;2)

Anyways, please fix.  Thanks for a great modpack!!

--- Danek Jovax :2D

**Comment by Freebi85** [comment]
Thank you. Latest Better Questing Update is a desaster. I have to roleback tonight.

**Comment by Danekjovax** [comment]
You're welcome!

**Comment by Danekjovax** [comment]
Thanks for the prompt response, Freebie.  I liked the new GUI it had, but yeah, if it's still buggy, it's best to wait until the bugs are ironed out by the mod author.
--- Ethan "Danekjovax"


    On Tuesday, April 23, 2019, 1:23:34 AM EDT, Freebi85 <notifications@github.com> wrote:  
 
 
Thank you. Latest Better Questing Update is a desaster. I have to roleback tonight.
