### ISSUE TITLE
Have both the changed and unchanged recipes (can use both)

### ISSUE THREAD

**Issue by CentOfLife** [Freebi85/Dungeons-Dragons-Space-Shuttles#128]
My friend and I are running into a problem where we see both the hard and normal recipes and can use either. We have tried uninstalling and reinstalling the pack and it is still showing both.

**Comment by Freebi85** [comment]
Seems to be some mismatch with the script files. I assume you are playing on a server? If yes check your singelplayer recipes, to ensure that client data is not corrupted.

**Comment by CentOfLife** [comment]
I checked in single player and it was still showing both. We are both uninstalling and reinstalling to check if it would work right

**Comment by Freebi85** [comment]
Die you removed/added mods from the pack?

**Comment by CentOfLife** [comment]
we removed the spice of life mod but this time we are going to leave it in. I was assuming that was the problem, but didn't think that it would affect it, because I played with it out in a single player game a couple a month ago

**Comment by Freebi85** [comment]
it affect it^^ All Mods are linked to each other with recipes. If you remove a mod all recipes are broken. And no worries Spice of life is disabled in the pack due to SOL carrot edition. The Mod its just there for the launchbox^^
