### ISSUE TITLE
Evil Craft Sanguinary Environmental Accumulator multiblock incompatible with non Evil Craft tanks

### ISSUE THREAD

**Issue by SilventheThrid** [Freebi85/Dungeons-Dragons-Space-Shuttles#129]
In order for the SEA from Evil Craft to work it requires 8 tanks of blood around the block, however it does not recognize tanks from "Fluid Tanks" as valid even when filled with Evil Craft blood, and it only seems to accept Dark Tanks from Evil Craft itself (they were obtained through the creative tabs).

**Comment by SilventheThrid** [comment]
Nvm, I'm just a lazy PoS who didn't do enough testing, TechReborn Quantum Tanks, Industrial Foregoing Black Hole Tanks, Extra Utilities 2 Drums and EnderStorage Ender Tanks are all recognized as valid tanks. I guess Fluid Tanks just isnt popular/well known enough for the Evil Craft dev to have added compatibility already.

**Comment by Freebi85** [comment]
https://github.com/Kotori316/FluidTank/issues/14
