### ISSUE TITLE
Obsidorite Blocks not giving correct metal in alloy smeltery and Obsidorite Cobble has no use

### ISSUE THREAD

**Issue by SilventheThrid** [Freebi85/Dungeons-Dragons-Space-Shuttles#133]
Pack Version 4.11a

When melting down Obsidorite Blocks in the Tinkers smeltery it gives 2 ingots of meteorite fluid instead of the expected 1 Block of Obsidorite Fluid, and checking in JEI gives it two uses in the smeltery, one at 404C for 2 ingots of meteorite fluid and one at 750C for 1 Block of Obsidiorite Fluid. Also Obsidorite Cobble (Is called meteorite cobble ingame, but has a different item name, tagia:obsidoritecobble_block vs tagia:meteoritecobble_block and item ID, 6766 vs 6765) has no use, despite being the main type of Obsidorite block gained from mining the nodes in the End.

**Comment by Temeriki** [comment]
Which version of the client/server are you using?

**Comment by Freebi85** [comment]
Can confirm that. 
I will rework the fluid amounts in the smeltery, rename the wrong block and make it great again^^
