### ISSUE TITLE
Floral Fertilizer Recipe has changed from default.

### ISSUE THREAD

**Issue by ryantheleach** [Freebi85/Dungeons-Dragons-Space-Shuttles#134]
![image](https://user-images.githubusercontent.com/141554/56761512-ad54e980-67dc-11e9-9c46-693d6c660154.png)

Suggests the default recipe is the correct way to get floral fertilizer, the recipe has been changed to depend on forrestry hommus, instead of floral powders.

**Comment by Freebi85** [comment]
Thx my friend, gonna change this 💪
