### ISSUE TITLE
Adamant Alloying problem

### ISSUE THREAD

**Issue by arwentonks** [Freebi85/Dungeons-Dragons-Space-Shuttles#136]
Because Vibranium and Solarium combine to make Nihilite, the alloying of Vibranium , Solarium and Iox to make Adamant never works right you end up getting both Nihilite and Adamant making getting Adamant overly hard and rather random as the amounts never seem to be consistent.

**Comment by Freebi85** [comment]
Thanks for the hint! I will rework adamant alloy until the next patch. Sorry for the inconvenience.
