### ISSUE TITLE
RFTools Tablet not "ejecting" installed modules in crafting screen.

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#137]
v 4.11a

RFTools' tablet should be able to "eject" any installed modules (memory/wireless/storage) by placing the tablet into the crafting area; the installed module comes out at the result space.

However this is not happening in DDSS.  Placing the tablet with an installed module in the crafting area doesn't show the installed module in the result space; nothing is there.

Please advise.  Thanks!

**Comment by Freebi85** [comment]
I think I found the mistake. All you have to do is hold out until the next patch =)

**Comment by Danekjovax** [comment]
Ah, ok.  I'm ok for now.  Worst case, I'll craft more tablets.  At least you've not made their crafting recipe advanced/elite. ;2)

**Comment by Danekjovax** [comment]
Thanks!!
