### ISSUE TITLE
Void backpack disappearing on death

### ISSUE THREAD

**Issue by Seth0067** [Freebi85/Dungeons-Dragons-Space-Shuttles#140]
I realize this may be an edge case since there would be a huge public outcry if everyone was seeing this, but after changing my backpack to a void backpack, each time I die and then collect my grave, the pack is not in my inventory, forcing me to reload from backup.  

Of course, I'm assuming that the expected behavior is that when you key into your gravestone, the backpack should appear with your other inventory items. If that's not the case, pls let me know. 

I'm happy to provide further information to help troubleshoot this. As a start, I'm playing a single player world.

**Comment by Freebi85** [comment]
Corail's Tombstone auto equip the backpack on your back. You can get it back with shift + B

**Comment by Seth0067** [comment]
ok - i thought it might be something silly like this.  Thanks, Freebi.

**Comment by Freebi85** [comment]
np! the main thing is he's not gone :D
