### ISSUE TITLE
Requirements Mismatch in White Magic Quest: Mystical Flowers!

### ISSUE THREAD

**Issue by Scheills** [Freebi85/Dungeons-Dragons-Space-Shuttles#141]
The description on the left says:
4x Mystical White Flowers
4x Mystical *Cyan* Flowers
2x Mystical Blue Flowers

The description and images on the right and the quest flag are for:
4x Mystical White Flowers
4x Mystical *Light Blue* Flowers
2x Mystical Blue Flowers

**Comment by Scheills** [comment]
The next quest asks for white, light blue, and blue petals, but then two quests later you're asked to make cyan dust, so I'm not sure which way this was supposed to flow.

**Comment by Freebi85** [comment]
Thank You my friend <3
