### ISSUE TITLE
Clayconia recipe

### ISSUE THREAD

**Issue by MarieCaroline** [Freebi85/Dungeons-Dragons-Space-Shuttles#142]
In Botania the petal apothecary doesn't accept the molten inferium cell as a valid input and it is thus not possible to craft the Clayconia functional flower with the current changed recipe.

**Comment by Freebi85** [comment]
Hello =)
Yes the bug is known but already fixed in the new updates. You are probably still playing on an older version of the pack. Updating to 4.11a should resolve the problem.

**Comment by MarieCaroline** [comment]
Thanks! Yes, I just checked and my server hasn't pulled the updated yet.
