### ISSUE TITLE
Certain ways of putting items into Remote Storage Tablet "auto-voids" item!?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#143]
v 4.11a
Not sure if this relates to DDSS or the mod I'm using (RFTools), but I have observed the following:

Inventory:
Storage Tablet with remote storage module installed.
Remote Storage module is linked to memory modules stored in a Remote storage.  (currently there are 3 modules installed, a lvl-2 module and 2 lvl-1 modules.)  Remote storage is placed and sufficiently powered and in a chunk-loaded area.
One of the lvl-1 modules has 100 slots already full of random stuff.  I also have other items which may or may not match items in remote storage list...

In my inventory GUI, I page to that full memory module and note an item already in there (in this example, one majestic ingot).  I have one identical item in my inventory.  I would like to merge them to make them appear as "2" of that item in that remote storage slot (to save space, right?).

Here's issue #1: With the above scenario, I click on that ingot in my inventory to pick it up, then click it into the memory module page with the other majestic ingot listed, nothing happens visually.  The ingot isn't placed with the other ingot to show "2" of them.  The ingot still appears to be on my cursor.  So I click back into my inventory to see if I still "have" the ingot.  It seems to place back into my inventory, but when clicking it again it disappears.  I also click the ingot in the remote storage - there is still only 1 ingot.  It got voided!

Issue #2:  With the above scenario, I shift-click any item into the remote storage, and if the item doesn't match any of the already-present items, it will be voided!  If it matches an item already present in the storage list, it will fill it to the full stack amount, then void any extra! If you have an open hotbar slot, it appears the GUI attempts to shift the item to the open hotbar slot instead (as normal), but clicking on the just-moved stack in the hotbar refreshes and its gone!

With these "unintended mechanics" with remote storage, it is not what I would call reliable.  If this is intended, there needs to be some warnings in the mod manual (RFTools), or in the tooltip of the remote storage.  If it is not intended, then please fix!  I've lost many valuable items to this "auto-void" mechanic.

(See attached screen shots where I demonstrate this with a stack of gravel.)
1. Here is my GUI, and I'm about to shift-click gravel into the remote storage...
![2019-04-30_07 11 55](https://user-images.githubusercontent.com/10191173/56958376-27a4a700-6b18-11e9-9e0a-89e7d32e046a.png)

2.  Shift-click it appeared to have failed; minecraft's GUI seems to have "diverted" it to my hotbar instead...
![2019-04-30_07 12 01](https://user-images.githubusercontent.com/10191173/56958387-2f644b80-6b18-11e9-91ed-dd0bb2bae494.png)

3.  Clicking on the hotbar slot where the "diverted" items went results in a GUI refresh where the items are not there.
![2019-04-30_07 12 05](https://user-images.githubusercontent.com/10191173/56958397-3428ff80-6b18-11e9-8bc3-74bf9841a564.png)

**Comment by Freebi85** [comment]
I'm afraid I can't help you here. I can only change recipes in workbenches or machines and write quests but not the way a mod mechanic works (or should not work^^).
I'm not familiar with the RFTools storage system either so i don't know if this is inteded or not. But i don't think so^^
You have to report this directly to the mod author im sorry.

**Comment by Danekjovax** [comment]
Thanks, Freebie.  I'll do that.  I appreciate your time.
