### ISSUE TITLE
Advanced Infusing Factory Autocraft

### ISSUE THREAD

**Issue by UnstablePineapple** [Freebi85/Dungeons-Dragons-Space-Shuttles#144]
When setting up the pattern for autocrafting an advanced infusing factory, if the pattern is shift clicked from JEI uses a basic infusing factory that is different from the basic infusion factory that can be crafted. If you try to change the shift-clicked pattern recipe to the basic infusion factory that is craftable, then the pattern does not have an output. 

I do have other advanced factories on auto craft that do work. (Purifying, injecting, enriching, crushing)

**Comment by Freebi85** [comment]
Thank you for pointing that out. Found a small NBT discrepancy in the script that's why it dosent work correctly. Fixed in next Update =)
