### ISSUE TITLE
Little Tiles, Little Chisel recipe conflict.

### ISSUE THREAD

**Issue by ParadoxedHope** [Freebi85/Dungeons-Dragons-Space-Shuttles#145]
Hey!

When trying to craft the Little Chisel, from Little Blocks;

![2019-05-03_13 36 09](https://user-images.githubusercontent.com/37836439/57137771-bfb8bf80-6da8-11e9-9c3a-8c0f77c9d434.png)

The result of the JEI crafting is conflicted and producing the RF Tools Smart Wrench instead;

![2019-05-03_13 36 46](https://user-images.githubusercontent.com/37836439/57137773-c0e9ec80-6da8-11e9-8519-3dc638f09ade.png)

P.s. Thank-you for such a thoughtfully created modpack <3

**Comment by Freebi85** [comment]
thank you =) fixed in next update.
