### ISSUE TITLE
Akashic Tome Deleted by loading stored Dungeon Tactics Book

### ISSUE THREAD

**Issue by NBlood** [Freebi85/Dungeons-Dragons-Space-Shuttles#146]
Give self Akashic Tome

Give self the Dungeonpedia from Dungeon Tactics

Store the Dungeonpedia in the Tome by crafting them together

Right click the tome and pick the dungeonpedia

Observe the Tome is turned into the dungeonpedia, and is unable to be changed back to the tome via normal left click.

**Comment by Freebi85** [comment]
Thx. Reported to the mod author.

**Comment by cosmosgenius** [comment]
If one is looking for a way to recovery you can use the grave mod recovery/restore command. This just resets the items with you.

**Comment by drhaber** [comment]
It appears this issue might be fixed as of august 27th 
[https://www.curseforge.com/minecraft/mc-mods/dungeon-tactics/issues/68](https://www.curseforge.com/minecraft/mc-mods/dungeon-tactics/issues/68 )

**Comment by Freebi85** [comment]
It is but the new dungeon tactic update breaks a lot of quests and recipes and have some op stuff which i may can’t tweak. There are some things that need to be adapted and changed. This has not been a priority yet but I will check it out soon.

**Comment by Freebi85** [comment]
Removed Dungeon tactics books from the pack for now. Maybe in the future the mod as well due to recent changes.
