### ISSUE TITLE
RF Tools Spawner does not accept any living matter

### ISSUE THREAD

**Issue by Oraxian** [Freebi85/Dungeons-Dragons-Space-Shuttles#148]
The 4.12a update seems to have broken RF Tools Spawners.  They no longer accept living matter of any type from matter beamers.  I tried all vanilla food (potatoes, pumpkins, wheat, fish, meats, etc.) with no luck.  Also tried some random modded foods (Pam's, etc,) with no luck, but I don't think those ever worked, which is fine.  Before the update, in version 4.11a, I was using potatoes successfully in the matter beamers for a mob farm.

The beamers do still seem to be able to transmit other item and block types to the spawner (rotten flesh, dirt, string, etc.)  It's just the living matter - nothing seems to work.  But without living matter, the spawner can't spawn anything.

**Comment by Freebi85** [comment]
Hello =)
Hi this is a mod specific problem since latest rf tools update. Was already reported here
https://github.com/McJtyMods/RFTools/issues/1943
There is not much i can do. Just waiting for next update or downgrade your rf tools version. I don’t make a hotfix of the whole pack because of this.
