### ISSUE TITLE
unable to make enori 

### ISSUE THREAD

**Issue by LWmods** [Freebi85/Dungeons-Dragons-Space-Shuttles#150]
after updating to 4.12a im unable to make enori crystals or blocks with the atomic reconstructor 

this is on a server I've tried replacing the scrips but it doesn't make a difference.

edit -   a quick test in single player has the same results it's not working.

**Comment by Freebi85** [comment]
Hi =)
It works fine for me.  You can't use a pressureplate in front of the reconstructor, that doesn't work anymore for some reason. You have to use a button. I don't know why that was changed.

**Comment by LWmods** [comment]
ah well that explains that thank you .

**Comment by Freebi85** [comment]
The line of sight is interrupted now with a pressure plate. :(

**Comment by LWmods** [comment]
hopefully they revert it ive always used plates lol
