### ISSUE TITLE
Items have a chance to vanish when broken with certain pickaxes

### ISSUE THREAD

**Issue by freundlich** [Freebi85/Dungeons-Dragons-Space-Shuttles#151]
When breaking blocks with certain pickaxes, they have a chance to vanish. I started noticing this when I upgraded my pickaxe to Dyonite and broke a wood tank. Instead of it going in my inventory, it was just gone. It doesn't happen every time, but I can reproduce it pretty quickly. Most of the time it takes less than 10 tries. I switched my pickaxe to Duranite and it still happens. On the other hand, I wasn't able to reproduce this with a Cobalt pickaxe so far. Yesterday I was careless enough to break my shulker box with my Duranite pickaxe and it was just gone. My pack version is 4.12a, but I ran into this problem in earlier versions as well. To reproduce, just cheat in the Duranite pickaxe from JEI and try breaking a wood tank a few times.

**Comment by Freebi85** [comment]
Hello =)
What kind of traits do you have on your pickaxe?

**Comment by freundlich** [comment]
My pickaxe currently has Botanical, Ecological, Analysing, Prosperous, Haster and Luck III. The Duranite pickaxe shown in JEI, which just has Analysing, also has the same problem.

**Comment by Freebi85** [comment]
i'm afraid this isn't a issue but just a "bad" trait from the TAIGA creator. Analysing has a chance to void an ore or to get less ores out of it. But gives you more xp for it. (and maybe same with chests and tanks whitout extra xp)
Same thing is with URU ore from Taiga. It has the Trait "Diffuse" there is just a chance to void mined item, ores, chests and shulkerboxes whitout benefit -.-

I try to ask the mod dev maybe he can "fix" or change that with the mod analysing so it only works on ores but don't expect too much.

**Comment by freundlich** [comment]
Ok, thank you.

**Comment by Freebi85** [comment]
doesn't seem like the devs are active. sadly... last message was about that the mod is being reprogrammed for 1.13. So for now nothing will change in 1.12. I can only recommend to bypass these 2 traits, I'm sorry.
