### ISSUE TITLE
Ender Tank: Right-Clicking colored buttons with colored wool in-hand will not assign colors.

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#152]
v 4.12a

I just crafted 2 ender tanks, and wanted to assign them to a particular color "channel".  Typically, you do this by placing the desired color(s) of wool in your hand (hotbar) then right-clicking one of the three buttons on the top of the tank to make the selected button change color to match the one in-hand.

What I'm seeing is that doing this still does not assign the color in-hand; the buttons remain white/white/white.  If there is sufficient space above the tank, the wool you right-clicked with will be placed on top of the tank instead.

Please see attached.

Thanks!

![2019-05-05_13 52 21](https://user-images.githubusercontent.com/10191173/57198186-f116c400-6f3d-11e9-8782-b10f3688c41c.png)
![2019-05-05_13 52 19](https://user-images.githubusercontent.com/10191173/57198187-f116c400-6f3d-11e9-876f-e8b48eeec7c0.png)

**Comment by dierke9** [comment]
I remember it using dyes and not colored wool. The colored wool was only in the craftinh recipe?

**Comment by Danekjovax** [comment]
You're right!  My bad!  I used the wrong items.
