### ISSUE TITLE
Inferium Arrowheads quest not registering completion (v 4.12a)

### ISSUE THREAD

**Issue by Seth0067** [Freebi85/Dungeons-Dragons-Space-Shuttles#156]
see screenshot.  i have updated the quest db after last update. this is the first quest i've had any trouble with.  

let me know if i can get you more info.

[imgur screen](https://imgur.com/a/Rqa2D3b)

**Comment by Freebi85** [comment]
Weirdomatic! Thanks for reporting. I’ll take look 👀
