### ISSUE TITLE
Ultimate energy cube

### ISSUE THREAD

**Issue by Cormenthor** [Freebi85/Dungeons-Dragons-Space-Shuttles#157]
Attempted to make an Ultimate Energy cube, crafting table accepts all pieces (have checked both auto fill via the (+) in the recipe and filling it manually) however the output remains empty. I had no problem with the lower tier cube that are needed to build it. I do see how ever that unlike the previous ones the recipe calls for two elite energy cubes in an odd place instead of two lithium batteries. I also tried replacing the errant energy cube with a lithium battery but that also failed to form the Ultimate energy cube.

![2019-05-08_12 08 31](https://user-images.githubusercontent.com/50423213/57401547-be154000-718a-11e9-94c2-e68b1d6d6853.png)

**Comment by Freebi85** [comment]
Thanks for reporting :)
I have a hunch what it might be.  I will fix it until the next update.
