### ISSUE TITLE
anti-rad balance 

### ISSUE THREAD

**Issue by picklehead8521** [Freebi85/Dungeons-Dragons-Space-Shuttles#159]
The anti rad needs tier 4 minimum to acquire the salt to make and by then your hit with a ton of radiation maybe balance the recipe a little for tier 2 or 3 

And the Space suits once they are working are not balanced with the tiers that you would level up as you go IE if they did work im only on tier 3 rocket but i could make the highest tier spacesuit 

The whole space part seems off balance

**Comment by Freebi85** [comment]
Thanks for reporting.
I'm looking at the first point. 
The second one is not a issue for me especially because radiation is very heavy. And yes the Galacticraft / Extra Planets part is still WIP there can still change some things. The balancing is not finished yet and will take a while.

**Comment by Freebi85** [comment]
i have decided to leave the cost of Anti-Rad as it is in order to adjust various radiation levels on planets and make the decontamination chambre more useful and earlier available.
