### ISSUE TITLE
[Suggestion] Adding Abyssalcraft and/or Betweenlands

### ISSUE THREAD

**Issue by Temeriki** [Freebi85/Dungeons-Dragons-Space-Shuttles#160]
Just want to start with saying im loving this modpack, its so fun me and my normal minecraft buddy were able to convince another friend to join us.  In fact its so fun I just recently spent a few days fixing a broken server instead of my normal giving up and starting a new modpack (ssd filled up while the server was running and lots of files got corrupted).  During the downtime I was poking around with some other modpacks to kill the time while waiting between server reboots and ran across abyssalcraft and betweenlands which I havnt touched in a while.  I got to thinking that while this pack is really exploration based which is awesome its mostly tech exploration based in terms of planets and doesnt have too much in terms of magical dimension exploration outside the twilight forest dimension.  Both abyssalcraft and betweenlands have a lot going with them and integration would take a while but I think either or both could really help significantly expand the magical exploration of this pack and also let you significantly expand the magical quest lines.  

At the end of the day you do what you think is right for this pack and please dont burn out on it :-p.

**Comment by Freebi85** [comment]
I decided not to add these two mods for now. Abyssalcraft probably one day. I keep it in mind. Sry :/

**Comment by Temeriki** [comment]
Dude, you have nothing to be sorry about.  I got bored and drew up a rough roadmap of integrating abyssalcraft into your modpack (recipes and gating) and integrating the abyssalcraft progression unlocks with the normal pack progression.  Were only about 1/3 of the way through tier 3 on my server so my roadmap may not even fit with your pack.  It would not be an easy task to integrate, and most likely require a restructuring of black magic quests (were about to make evil powder so not sure how much further that goes).   Plus youd have to implement some alternative shoggoth options for existing servers also server owners generally want some protection cause a few components of abyssalcraft can damage the overworld (think like old school thaumcraft taint).  Shoggoths can really screw things up, in both hilarious and terrible ways.

As always amazing pack, me and my buddies are having a great time with it.  Weve been trying to get one of my friends into modded minecraft since you had to do whatever to meta.inf a billion years ago (I was there gandalf).  Your pack is what finally got him hooked, he may have more active hours on the sever than me and my normal modded minecraft friend.  As in you have 3 32 year olds logging into a modded minecraft sever almost nightly after work and the kids are in bed.  Thanks for the awesome pack!

**Comment by SextupleTap** [comment]
In my personal opinion Abyssal Crafts progression is nothing special and is tedious (lacking in engagement to make the task not feel tedious) for the rather disappointing reward you get after defeating the final boss in comparison to the plethora of other tools, weapons, and armor at your disposal in the pack currently. It was also already mentioned that Abyssal Craft also has the potential to become a rather destructive mod as well, this is absolutely true (in which some could even consider it to be destructive in unfair ways too). I would certainly pick the Betweenlands over Abyssal Craft but it seems that you've taken the Betweenlands off the table, which is fine and I can respect that.
