### ISSUE TITLE
Clear glass after dye produces wrong glass

### ISSUE THREAD

**Issue by NeoremMeepswonder** [Freebi85/Dungeons-Dragons-Space-Shuttles#161]
Tinkers clear glass when dyed changes into Minecraft version of the glass. I did try black dye from actual additions and inc sack both giving same result. The crafting recipe itself shows correctly  on the menus.
I went to check on updated pack and its still there, I did check every variation of the dye and same result. I use Tinker table to do coloring and I checked Tconstruct mod itself that had no issue.

**Comment by NeoremMeepswonder** [comment]
![image](https://user-images.githubusercontent.com/50044356/57461593-f8acd480-727f-11e9-9983-e84707309ac3.png)

**Comment by NeoremMeepswonder** [comment]
![image](https://user-images.githubusercontent.com/50044356/57461630-0eba9500-7280-11e9-94b1-41f9eb48a879.png)

**Comment by NeoremMeepswonder** [comment]
![image](https://user-images.githubusercontent.com/50044356/57465912-40cff500-7288-11e9-94d2-6d1a7ba19c2c.png)


This recipe is what it shows

**Comment by Freebi85** [comment]
Found the problem =) Is fixed in the next patch.
