### ISSUE TITLE
[Suggestion] Add Applied Energistics2

### ISSUE THREAD

**Issue by ReiRokusanami0010** [Freebi85/Dungeons-Dragons-Space-Shuttles#163]
Would you like to use Applied Energistics 2?
When I set up a large network with Refined Storage, TPS suddenly falls and I can not work properly.
(If I reinstall the Controller of RefinedStorage, TPS will be restored, but it will still fall again ...)

Perhaps there is a reason for choosing RefinedStorage, but please consider introducing this mod.

The image below is a measurement of TPS using Lag Goggles.
![2019-05-11_23 03 31](https://user-images.githubusercontent.com/30286391/57571236-54c15580-7446-11e9-9141-f5ce60ff2899.png)

**Comment by Freebi85** [comment]
Hello =)
I'll consider it. But AE2 has a shitload of recipes to tweak for DD&SS.  That takes a lot of time to bring it up to the same level as RS. Don't expect this implementation to be done quickly. I have a few other prio's before. No promises^^

**Comment by mrdeadlocked** [comment]
I have seen this on my server as well. You run a big pull order out of an RS network and TPS drops significantly.

**Comment by warplord** [comment]
Please do not remove RS though. It would be devastating if you do.

**Comment by Freebi85** [comment]
I'll implement it in the next update. And RS stays inside of course. One should be able to choose which way to go. This modpack should be versatile.

**Comment by ReiRokusanami0010** [comment]
Thank you for correspondence!
