### ISSUE TITLE
Natura fences and gates 

### ISSUE THREAD

**Issue by DidNotZero** [Freebi85/Dungeons-Dragons-Space-Shuttles#164]
Can't create the fences or gates from Natura as it wants sticks specific to the wood it adds, for example, it would ask for eucalyptus sticks instead of regular sticks. Eucalyptus planks create regular sticks and there is no recipe for eucalyptus sticks. The gates and fences from Natura should be changed to use the regular stick variety in my opinion.

**Comment by Freebi85** [comment]
Hello =)
I know because i unified all sticks.
But don't worry, I have integrated the natura and other fences into the chisel. You can just craft vanilla fences and change them as you like. Made extra a little chisel quests in tier 0 for it. You will surely discover yet =)

**Comment by DidNotZero** [comment]
No problem, just finished the sheep quest and was trying to get a pen for the sheep egg.
