### ISSUE TITLE
Radiation not right 

### ISSUE THREAD

**Issue by picklehead8521** [Freebi85/Dungeons-Dragons-Space-Shuttles#165]
When using the cry chamber or sleeping i get 6% or 5%
It says reduced by 8% but does not lower it by the said amount.

Have not tested the decontamination unit yet

**Comment by picklehead8521** [comment]
https://i.imgur.com/S7dMnKb.png

**Comment by picklehead8521** [comment]
https://i.imgur.com/vCs8kSW.png

**Comment by Freebi85** [comment]
Hello =)
There ist not much i can do against it. Seems to be a mod specific issue. Have you reported it to Extra Planets yet?

**Comment by Freebi85** [comment]
As far as I've found out, sleeping has diminishing returns. The more you sleep the less effective it is supposed to be.

**Comment by picklehead8521** [comment]
Not yet I thought it may have been a config since I saw those levels were
changed in the last update. Even sleeping and the decontamination chamber
it says lowered by X percent but it doesn't accurately lower it by that
percent. Not really that big of an issue anyways.

**Comment by Freebi85** [comment]
Well it seems to be intended of what I've read about it now.
