### ISSUE TITLE
Hardened Jetpack quest not triggering

### ISSUE THREAD

**Issue by 123zane321** [Freebi85/Dungeons-Dragons-Space-Shuttles#169]
Pretty much what it says on the tin, I crafted a Hardened Jetpack, but the relevant quest in Stage 3 didn't trigger - yes I have stage 3 quests unlocked, yes I have all prerequisite quests completed, yes I have the Hardened Jetpack in my inventory, yes I have tried spam-clicking the Detect button for the quest, but nothing works

**Comment by Freebi85** [comment]
Alright i look into it. Did you refresh also the Questdatabase? Just to be sure.
