### ISSUE TITLE
Mowzie’s Mobs and Infernal Mobs interaction is super OP

### ISSUE THREAD

**Issue by IPods-and-spree-candy** [Freebi85/Dungeons-Dragons-Space-Shuttles#170]
I have been trying to kill a Ferrous Wroughtnaut that has ninja and clocking among other powers and it is impossible I just started the pack not 10 hours ago I cheated in avarita end game swords and armor it can't kill me but I can't touch it, it will go invisible if I get to close and teleport around to attack I am out of ideas then again I am new to the pack. I also used the kill command.

**Comment by Temeriki** [comment]
You have to hit the sword on its back after it attacks, only way to damage it.

**Comment by Freebi85** [comment]
As Termeriki said, the sword in the back is the only way to damage him. 
But maybe you shouldn't mess with such an opponent after 10 hours of gameplay^^
Especially not in this pack :D Since this is a intended mechanic by mozwiesmobs, I close the issue.

**Comment by IPods-and-spree-candy** [comment]
I know that but it doesn't attack like that anymore due to Infernal Mobs giving it extra abilities
