### ISSUE TITLE
Crash when display frame recipe appears in items GUI

### ISSUE THREAD

**Issue by rng235** [Freebi85/Dungeons-Dragons-Space-Shuttles#171]
**What?**
Thought it was a one time thing but this has occurred twice on separate days. Game crashes to menu when certain recipes appear in the Items GUI (JEI GUI?). From the error report it looks like an item from EvilCraft.

`-- Ingredient being rendered --
  Ingredient Mod: EvilCraft
  Ingredient Info: 1xtile.blocks.evilcraft.display_stand@0 evilcraft:display_stand nbt:{displayStandType:{id:"forestry:planks.1",Count:1b,Damage:4s}}
`

**Error Report:**
https://paste.dimdev.org/uhuxuwaziq.mccrash

**Version/System:**
Windows 10
i7-7700k
GTX 1080ti
16gb RAM (8gb allocated)
DD&SS: 4.13 

**Server System:**
i7-3770k
GTX 1070
16gb RAM (8gb allocated)

**How to reproduce?**
Doesn't happen all the time. No method of reproduction yet.

**Comment by Freebi85** [comment]
Hello 😉
It‘s a crash due to otifine. I do not recommend using optifine under any circumstances. Never then optifine changes the whole rendering system, which causes tons of incompatibilities. Not in this pack by default.

**Comment by rng235** [comment]
@Freebi85 Thanks! I should have read the instructions clearer.
