### ISSUE TITLE
Broken Turn In - Elite Bin! Quest

### ISSUE THREAD

**Issue by Solarrus** [Freebi85/Dungeons-Dragons-Space-Shuttles#173]
It seems I cannot turn in/detect the elite bin! quest in the Tier 3 - main questline. I have made 2 of these and even had the server admin spawn on in my inventory. The quest book wont detect my completion.

**Comment by Freebi85** [comment]
Ok thank you ill tanke a look :)
Have you already updated the questbook after the updates?

**Comment by Solarrus** [comment]
I’ve updated a few weeks ago. I will give it shot.

Thanks

**Comment by Solarrus** [comment]
I have updated the questbook using /bq_admin default load.

I still have an error trying to detect/submit the Elite Bin! quest in Tier 3

DD&SS - 4.9
MC 1.12.2

**Comment by Freebi85** [comment]
4.9? Well we are on 4.13 right now. Try latest version. a lot's happened in the meantime.

**Comment by Solarrus** [comment]
thanks, i will give it a shot.

**Comment by Solarrus** [comment]
Updated to version 4.13 and reloaded the quest book. Everything seems to be working great.
