### ISSUE TITLE
A few more little bugs

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#174]
I found some more minor bugs, do you mind that I post them all in one issue, so long as they're just like config or script changes?
- Quest "Smeltery #1" doesn't accept \<ore:gravel\>
- Can't uncraft any stairs/slabs (like tweaked by Quark)
- No way to make Project Red's marble bricks (makes Underground Biome's wall)
- Suggestion to convert NetherEX bricks to default with an artisan chisel
- Vanilla nether bricks takes 9 bricks for 1 block, but NetherEX bricks are still 4 for 4 blocks
- Amaranth, eucalyptus, and tigerwood fences and gates missing from chisel variant recipes
- The six wools from Animania should also be added to \<ore:woolBlock\>
- Rustic slate is not included in \<ore:stone\>

**Comment by Freebi85** [comment]
Hello. 

1. Fixed in next Update.
2. I don't want to change this.
3. There is a recipe for that. Check JEI pls. This type of bricks is crafted differently.
4. Fixed in next Update.
5. Fixed in next Update.
6. Fixed in next Update.
7. Fixed in next Update.
8. Fixed in next Update.

**Comment by DarkYuan** [comment]
I should explain in more depth:
A - The recipe I'm trying to craft
B - The different way of crafting you might be referring to
C - The overlapping recipe
D - What I actually get from crafting it

![image](https://user-images.githubusercontent.com/3029695/58150073-ddf13d00-7c3b-11e9-8d7e-6d405ad53c74.png)

**Comment by Freebi85** [comment]
Ok i get it^^ Will make this special kind of marble accessible via artisan chisel for now
