### ISSUE TITLE
Easy fix for ruins issues

### ISSUE THREAD

**Issue by Xetaxheb** [Freebi85/Dungeons-Dragons-Space-Shuttles#176]
the "unbalanced nesting" issue with ruins means that any of those entries will not load into the game, it's caused by " characters being escaped because 6 months ago the Ruins mod changed to stricter syntax https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1282339-1-13-2-ruins-structure-spawning-system?comment=4535

it's easy to fix, replace all instances of \" with " in .tml files in /ruins_config/ folder with something like notepad++ ; or I can upload a zip of fixed ones

**Comment by Freebi85** [comment]
I would be glad if you could give me a zip file so I can see what you mean exactly^^

**Comment by Xetaxheb** [comment]
So a lot of the Ruins mod templates (in /.minecraft/config/ruins_config/*.tml) for world gen structures got broken by being outdated. If they contain \" instead of just " then it won't load that entire file. It can be fixed by replacing those. Here is the zip I fixed for my game.
[ruins_config.zip](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/3217976/ruins_config.zip)

**Comment by Xetaxheb** [comment]
If you're curious, WinMerge or Notepad++(with compare plugin) are good comparing tools.

**Comment by Xetaxheb** [comment]
oh i hadn't noticed, this explains the confusion better, what I was saying was:

\\" needs replacing with "
