### ISSUE TITLE
Gaiasteel ingot

### ISSUE THREAD

**Issue by picklehead8521** [Freebi85/Dungeons-Dragons-Space-Shuttles#179]
There is no recipe for this Gaiasteel ingot that is used for Draconic Energy Core

**Comment by Freebi85** [comment]
The Gaia Agglomeration Plate is used to make Terrasteel more efficiently and Gaiasteel Ingots. Both have no JEI recipe. There's nothing I can do about it. Only a mod dev can implement this.
