### ISSUE TITLE
Can't get methane gas out of squeezer to empty cell

### ISSUE THREAD

**Issue by arturgaweski** [Freebi85/Dungeons-Dragons-Space-Shuttles#18]
Hi

I was following quest book, but i got stuck at "Squeezer" and Filling empty cell with methane gas part.
As it was said in quest book i've placed that machine, put biomass inside and squezed it until i got methane gas. At this point i tried to right click it with empty cell with no result, then i tried to use redstone torch (reseting squezzer) and still empty cell didn't get methane gas out of it.

**Comment by billyty08** [comment]
You need to use the fluid duct and servo to pull it out into a tank. then when you get 1000 mb then you can pull it out with the cell.
