### ISSUE TITLE
[Suggestion] Add higher tier Carpenter machine for mid+ players

### ISSUE THREAD

**Issue by saianna** [Freebi85/Dungeons-Dragons-Space-Shuttles#180]
We start with artisan benches, then we get carpenter and then.. Nothing. We are left with either really clunky and inefficient starter workbench, or carpenter that's super slow and cannot be really automated for multiple recipes. Could we get "better carpenter" of some sorts for mid+ progression ?

**Comment by Freebi85** [comment]
There is currently no other machine that can store recipes, store items, have 9 slots and provide a liquid tank. As Pack Dev I can't build my own machines im sorry.
But I'm currently working on a boosting project with the Carpenter for the lategame. Let me surprise you :D

**Comment by saianna** [comment]
Actually, this pack already has 1 machine that could potentially work as higher tier carpenter, namely cyclic assembler from Thermal Expansion. It has its own inventory, works with fluids (altho can't remember if only in bucket form) and can be upgraded further.
My biggest issue with carpenters is their speed tbh. Having few of them is fine.

Also now i'll be waiting eagerly for your surprise ;)

**Comment by Freebi85** [comment]
I Love the Cyclic Assembler! (New Name in 1.12 Sequential Fabricator) but sadly this machine has no crafttweaker integration. This means i can't add my own recipes to this machine :/

**Comment by Targren** [comment]
>  As Pack Dev I can't build my own machines im sorry.

Not for nothing, but that's exactly why Modular Machines was created, so Pack Devs can. Might want to have a butcher's, when you've got all that free time. ;)

**Comment by Freebi85** [comment]
> 
> 
> > As Pack Dev I can't build my own machines im sorry.
> 
> Not for nothing, but that's exactly why Modular Machines was created, so Pack Devs can. Might want to have a butcher's, when you've got all that free time. ;)

IF I want to use this mod certainly. But I don't want to. Im Sorry =)
