### ISSUE TITLE
[Sugestion] Downgrade DungeonTactics, or add another mod that helps with getting loot while exploring

### ISSUE THREAD

**Issue by saianna** [Freebi85/Dungeons-Dragons-Space-Shuttles#181]
With latest DungeonTactic update the mod had removed its "pressure plates + chests underneath" generation in OW, which added some early good stuff while exploring. If we cannot downgrade the mod version, could we at least find some replacement for it? 
Also several of generated structures (i'm not sure from what mod, unfortunately) still do not have updated chest loot, often having nothing in it.

**Comment by Freebi85** [comment]
Yeah, I don't like how Dungeon Tactics is developing right now. It looks like the mod is being completely reworked at the moment. I'm thinking about that for my next patch. But don't make any promises.

**Comment by Danekjovax** [comment]
I don't see this happening in my world.  I'm running 5.0, and in new OW chunks I am still seeing the pressure plates, although they do appear a little different as in they are smaller and have different appearances depending on what type of plate they are, so they are a little harder to spot from a distance.  They are rather rare, and may be more rare than the earlier versions.  I don't see any need to downgrade, IMHO.

**Comment by Freebi85** [comment]
Thank you for the screenshots @Danekjovax  =) You're right. These are exactly the new trap types.
Then I see no reason to downgrade the version.
