### ISSUE TITLE
Wrong Quest Requirement: Protectors Of The Earth - Upgrade Efficiency

### ISSUE THREAD

**Issue by dyingdemon2** [Freebi85/Dungeons-Dragons-Space-Shuttles#182]
Quest calls for Efficiency upgrade in title and text but asks for the Fire Rate upgrade

![unknown](https://user-images.githubusercontent.com/50985431/58317133-2c8d0b80-7de3-11e9-990b-e2ee8a1f1440.png)

Forge: 14.23.5.2836

DD&SS Version: 4.13

Releaseed: May 10th, 2019

> The Blood Moon is apparently Rising

**Comment by Freebi85** [comment]
Oh thanks for reporting this! Fixed in next Update =)

And Yes.... The Bloodmoon is everywhere :0^^
