### ISSUE TITLE
armor smelting recipe in Industrial blast furnace

### ISSUE THREAD

**Issue by tsonayoshi** [Freebi85/Dungeons-Dragons-Space-Shuttles#183]
there are recipes for smelting iron gold and diamond armors in Industrial blast furnace that arent working i tried it in 4.13 and 4.12 
![Screenshot (36)](https://user-images.githubusercontent.com/29760625/58368529-17090600-7ef7-11e9-9b79-b7a539622556.png)

**Comment by Freebi85** [comment]
Hello =)
Shouldn't be displayed because all armour should be recycled via the arc furnace. I'm afraid I overlooked that. I will remove it from JEI. Thanks for reporting :)

**Comment by tsonayoshi** [comment]
aww XD np
