### ISSUE TITLE
Ultimate Stew

### ISSUE THREAD

**Issue by UnstablePineapple** [Freebi85/Dungeons-Dragons-Space-Shuttles#185]
While trying to craft the ultimate stew, there are a few Pam's Harvestcraft items that are unattainable. 
Agave, Amaranth, Chickpeas, Green Grape, Mulberry, Sisal, Taro

The config option to drop from grass is off and the gardens (Arid, Soggy, Tropical, Windy) are turned off. They are also not available in the quest shop or craftable with a sifter.

**Comment by Freebi85** [comment]
Thanks for reporting. I'll take a closer look =)

**Comment by Freebi85** [comment]
Will implement sifting recipes for this seeds in next update.
