### ISSUE TITLE
Reducing the size of files - Usage of loops in scripts

### ISSUE THREAD

**Issue by MrTK-Dev** [Freebi85/Dungeons-Dragons-Space-Shuttles#188]
You could use loops in your CT-scripts and make them smaller.
e.g.:
Workshops/Blacksmiths Workshop/Draconic Evolution.zs
_Before_
RecipeBuilder.get("blacksmith")
  .setShaped([
	[<ore:plateDraconium>, <ore:plateDraconium>, <draconicevolution:wyvern_core>, <ore:plateDraconium>, <ore:plateDraconium>], 
	[<ore:plateDraconium>, <ore:blockDyonite>, <evilcraft:promise_acceptor:2>, <ore:blockDyonite>, <ore:plateDraconium>], 
	[<ore:plateDraconium>, <draconicevolution:wyvern_energy_core>, <minecraft:diamond_helmet>, <draconicevolution:wyvern_energy_core>, <ore:plateDraconium>], 
	[null, null, null, null, null], 
	[null, null, null, null, null]])
  .setFluid(<liquid:methane> * 16000)
  .addOutput(<draconicevolution:wyvern_helm>)
  .addTool(<ore:artisansBurner>, 30)
  .addTool(<ore:artisansHammer>, 30)
  .addTool(<ore:artisansPliers>, 30)
  .create();
  
RecipeBuilder.get("blacksmith")
  .setShaped([
	[<ore:plateDraconium>, <ore:plateDraconium>, <draconicevolution:wyvern_core>, <ore:plateDraconium>, <ore:plateDraconium>], 
	[<ore:plateDraconium>, <ore:blockDyonite>, <evilcraft:promise_acceptor:2>, <ore:blockDyonite>, <ore:plateDraconium>], 
	[<ore:plateDraconium>, <draconicevolution:wyvern_energy_core>, <minecraft:diamond_helmet>, <draconicevolution:wyvern_energy_core>, <ore:plateDraconium>], 
	[null, null, null, null, null], 
	[null, null, null, null, null]])
  .setFluid(<liquid:syngas> * 15000)
  .addOutput(<draconicevolution:wyvern_helm>)
  .addTool(<ore:artisansBurner>, 30)
  .addTool(<ore:artisansHammer>, 30)
  .addTool(<ore:artisansPliers>, 30)
  .create();
  
RecipeBuilder.get("blacksmith")
  .setShaped([
	[<ore:plateDraconium>, <ore:plateDraconium>, <draconicevolution:wyvern_core>, <ore:plateDraconium>, <ore:plateDraconium>], 
	[<ore:plateDraconium>, <ore:blockDyonite>, <evilcraft:promise_acceptor:2>, <ore:blockDyonite>, <ore:plateDraconium>], 
	[<ore:plateDraconium>, <draconicevolution:wyvern_energy_core>, <minecraft:diamond_helmet>, <draconicevolution:wyvern_energy_core>, <ore:plateDraconium>], 
	[null, null, null, null, null], 
	[null, null, null, null, null]])
  .setFluid(<liquid:argon> * 14000)
  .addOutput(<draconicevolution:wyvern_helm>)
  .addTool(<ore:artisansBurner>, 30)
  .addTool(<ore:artisansHammer>, 30)
  .addTool(<ore:artisansPliers>, 30)
  .create();

**After:**
import crafttweaker.liquid.ILiquidStack;
var input_fluids_list = [
  <liquid:methane> * 16000,
  <liquid:syngas> * 15000,
  <liquid:argon> * 14000
] as ILiquidStack[];

for input_fluid in input_fluids_list {

RecipeBuilder.get("blacksmith")
  .setShaped([
	[<ore:plateDraconium>, <ore:plateDraconium>, <draconicevolution:wyvern_core>, <ore:plateDraconium>, <ore:plateDraconium>], 
	[<ore:plateDraconium>, <ore:blockDyonite>, <evilcraft:promise_acceptor:2>, <ore:blockDyonite>, <ore:plateDraconium>], 
	[<ore:plateDraconium>, <draconicevolution:wyvern_energy_core>, <minecraft:diamond_helmet>, <draconicevolution:wyvern_energy_core>, <ore:plateDraconium>], 
	[null, null, null, null, null], 
	[null, null, null, null, null]])
  .setFluid(input_fluid)
  .addOutput(<draconicevolution:wyvern_helm>)
  .addTool(<ore:artisansBurner>, 30)
  .addTool(<ore:artisansHammer>, 30)
  .addTool(<ore:artisansPliers>, 30)
  .create();
}

**Comment by Freebi85** [comment]
Thanks for the tip! Amazing! I will definitely use it for my new scripts. I will replace the old scripts when I have more time because there are quite a lot of them.  I don't have a team to do it for me sadly 😁

**Comment by MrTK-Dev** [comment]
Glad I could help : )
This system is even more variable than this example!

**Comment by Danekjovax** [comment]
Doing this would help load times?

**Comment by MrTK-Dev** [comment]
Yes, but the main "issues" for the long loading time are the large amount of big content mods. Cleaning up your scripts can help but the differences are _really_ small.

**Comment by Freebi85** [comment]
I won't make any changes in this modpack for now. Also because it has many different fluid values in most Workshops. Nevertheless, thanks for the info, I will take over the idea in my next project.
