### ISSUE TITLE
Tree leaves not decaying

### ISSUE THREAD

**Issue by GldnSabre74** [Freebi85/Dungeons-Dragons-Space-Shuttles#189]
I have noticed some of the tree leaves do not decay when you remove all the logs. Zoesteria Biomes trees seem to be the culprit. Manuka Trees are the ones I am having issues with.

**Comment by Freebi85** [comment]
Hello =) Yes i know ,we reported the bug to Zoesteria. Should be fixed soon.

**Comment by Danekjovax** [comment]
Also observed this last night with same tree.  Not a game breaker, though a little annoying. ;2P ;2)

**Comment by Freebi85** [comment]
Finally solved. 
Unfortunately, only newly generated trees are affected. Old Zoesteria trees will always keep the leaves on and it is best to use a sickle.
