### ISSUE TITLE
"dummy Singularity" in tier 4 void ore controller

### ISSUE THREAD

**Issue by dyingdemon2** [Freebi85/Dungeons-Dragons-Space-Shuttles#190]
Was trying to upgrade to a Tier 4 Void ore miner when I ran into a issue with the recipe. one of the singularities is now calling for a "dummy singularity" which cant be crafted.
![2019-05-31_15 25 13](https://user-images.githubusercontent.com/50985431/58730146-4e752800-83b9-11e9-8c89-50e3eb47bf2f.png)
![2019-05-31_15 25 17](https://user-images.githubusercontent.com/50985431/58730151-51701880-83b9-11e9-8dae-fbf649133c9d.png)

Pack version: Dungeons Dragons and Space Shuttles Version 5.0

**Comment by Freebi85** [comment]
Oh Thanks for reporting. found the problem. Fixed in next update.

**Comment by Freebi85** [comment]
It's a Triberium Singularity if you want to prepare the ingots^^
