### ISSUE TITLE
Quantum Entangleporter power change

### ISSUE THREAD

**Issue by picklehead8521** [Freebi85/Dungeons-Dragons-Space-Shuttles#192]
Since the last update there has been a difference in the power output of the entangleporters. 
Input is still unlimited it seems  but output itself seems to be at 32k rf/t. not sure if the move to mekanism has effected this but this machine is supposed to be unlimited input and output of power. I cant diagnose correctly but it seems the output of items may have changed a bit also

**Comment by Freebi85** [comment]
-Should be fixed with next mekanism update.
