### ISSUE TITLE
Tier 1 Space Suit - Enchantable??

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#193]
Version 5.0
Looking at the JEI "use" of the various space suit parts, you observe they can be enchanted with various enchants.  However, when placing the item(s) into the anvil (with or without being charged with RF), the item shows that it is not enchantable.

Is this intended, or is there something messed up in the enchantment configs for these items?
![2019-06-02_17 31 49](https://user-images.githubusercontent.com/10191173/58844853-f9e6dc80-8646-11e9-86e7-867b9b876318.png)
![2019-06-02_17 31 52](https://user-images.githubusercontent.com/10191173/58844859-ffdcbd80-8646-11e9-80ea-2a9a7881acd4.png)
![2019-06-02_17 29 32](https://user-images.githubusercontent.com/10191173/58844860-02d7ae00-8647-11e9-8b7d-c27e0fdb5f65.png)

See attached screenshots.

**Comment by Freebi85** [comment]
Sorry i can't interact with enchantments whitout adding other mods. Which I don't want right now. Also, there are no configs in which I can add or remove enchantments.
Either it's a mod issue then you have to report it to extra planets or JEI will show you just crap^^

**Comment by Danekjovax** [comment]
I'll forward this to Extra Planets dev team.  Thanks.
