### ISSUE TITLE
Tech Reborn-Industrial Blast Furnace: Recipe discrepancies?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#194]
Version 5.0

I am reviewing the various recipes for creating steel with the IBF, and notice that in JEI, one recipe:
1 Iron (ingot/pulverized) + 1 pulverized coal = 1 Steel Ingot.

However, when I place these items in the IBF, nothing happens.  I realize that I have to add a second pulverized coal to get the Steel ingot.

I would guess one of these things need to be adjusted for consistency?

As a note, using pulverized charcoal only requires 1 unit for smelting with iron to make steel.
![2019-06-02_16 43 25](https://user-images.githubusercontent.com/10191173/58845061-bfca0a80-8647-11e9-88f2-b2ea4f15ce0c.png)
![2019-06-02_16 43 42](https://user-images.githubusercontent.com/10191173/58845068-c2c4fb00-8647-11e9-9e59-b1acf76d082b.png)
![2019-06-02_16 43 50](https://user-images.githubusercontent.com/10191173/58845070-c48ebe80-8647-11e9-8482-4354e1400d48.png)

See attached screenshots.

**Comment by Freebi85** [comment]
Interesting. I'll check it out.
