### ISSUE TITLE
Gaiasteel ingots have no recipe

### ISSUE THREAD

**Issue by freundlich** [Freebi85/Dungeons-Dragons-Space-Shuttles#195]
Modpack version 5.0

How are you supposed to obtain these?

**Comment by Freebi85** [comment]
The Gaia Agglomeration Plate is used to make Terrasteel more efficiently and Gaiasteel Ingots. Both have no JEI recipe. There's nothing I can do about it. 
But check Lexica Bortania for more detailed information =)

**Comment by freundlich** [comment]
Sorry, I missed that. I actually searched for Gaiasteel in the Lexica Botania, but there is no entry for that. The only way to find the recipe is to click on the Gaia Agglomeration Plate section. Maybe a quest that tells you how Gaiasteel is made would be useful.

**Comment by Freebi85** [comment]
i will do =)
