### ISSUE TITLE
game wont load

### ISSUE THREAD

**Issue by ChibiLG** [Freebi85/Dungeons-Dragons-Space-Shuttles#199]
game loads then before finishes it stops and wont load anymore, already uninstalled and reinstalled and also allowed more ram to go to it and nothing is working

**Comment by Freebi85** [comment]
Join our Discord Server an post some crash logs/logs in our #tech-support channel. It's a bit difficult to help whitout further infomations.

Discord Server Link: https://discord.gg/eUajYmK
