### ISSUE TITLE
"Bug" teleported me inside wall and i've lost everything

### ISSUE THREAD

**Issue by arturgaweski** [Freebi85/Dungeons-Dragons-Space-Shuttles#20]
Hi, while i was exploring cave near surface level where world was generated very recently i stepped on some white flower from dungeon tactics (that all i could see) and instantly when i touched that flower i got teleported inside nearby cave blocks. At place where i died all torches i placed were missing and my grave couldn't find location to spawn. Death list said grave is at 0,0,0 but i cannot go under bedrock. Please help, how can i get back my "soul"? :( 
I have no backup since i didn't expect crazy like this bug to happen...

**Comment by billyty08** [comment]
I don't know if it is enabled or not but try  /tmg_restore (playersname) latest
