### ISSUE TITLE
Can not craft T2 Solar panel

### ISSUE THREAD

**Issue by klon1568** [Freebi85/Dungeons-Dragons-Space-Shuttles#200]
I put all the materials in correct order in the advanced crafting table (also tried another one and reconnecting multiple times), but if I want to put the finished product in my inventory it resets itself inside the crafting table. Would'nt be a problem if it was'nt for the quest, but I cant cheat, because I am not the admin on the server :/. The server has not restarted so far so maybe this will work, but so far I don't see what I was doing wrong

**Comment by Freebi85** [comment]
Can't find any issues there. Try to craft it in a singleplayer world. If it works somthing is wrong with the server script files.

**Comment by Freebi85** [comment]
Closed due to inactivity and lack of information.
