### ISSUE TITLE
Lava Sigil stops working when used on magma Anvil

### ISSUE THREAD

**Issue by Emperorraccoon** [Freebi85/Dungeons-Dragons-Space-Shuttles#201]
If you attempt to fill a magma anvil with the blood magic lava sigil it will stop working on anything else after. A complete client reboot fixes it. (SP)

**Comment by Freebi85** [comment]
Hey =)
Sry, it's nothing I can fix :( Please report mod specific bugs directly to the corresponding devs. [BloodMagic and/or Cyclic Github if not already reported]
Cheers Freebi
