### ISSUE TITLE
Deconstructor not returning rocket components?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#203]
Not sure if this is intended, but given the progression nature of GalactiCraft and the expense of rockets, using a deconstructor helps a lot in reducing the cost of building the next tier rocket by returning a % of the original materials.

Currently it is returning 0% (see screenshots).  Is this intended?  I hope not.  At least allow it to return half of the original materials (plates at least) to keep the grind a little less groan-inducing.

Thanks!
![2019-06-14_22 28 15](https://user-images.githubusercontent.com/10191173/59545954-66d65e00-8ef4-11e9-87e8-0b4b71d7e9e7.png)
![2019-06-14_22 28 19](https://user-images.githubusercontent.com/10191173/59545955-66d65e00-8ef4-11e9-8346-f74c830c9828.png)
![2019-06-14_22 28 30](https://user-images.githubusercontent.com/10191173/59545956-66d65e00-8ef4-11e9-867c-dab75359c208.png)

**Comment by Freebi85** [comment]
Thx for Reporting

This machine seems to be completely useless with changed rocket recipes. Unfortunately I can't change anything about it because only very few Galacticraft machine-recipes can be tweaked. This device is unfortunately not one of them.
I'll see if I can port the rockets to another machine for recycling.

**Comment by Danekjovax** [comment]
Thanks!

**Comment by Freebi85** [comment]
gonna add rocket recycling recipes for every Tier to the arc furnace to recover a bunch of heavy duty plates and NAK Coolant cells.

**Comment by Danekjovax** [comment]
You are too kind!
