### ISSUE TITLE
World crash

### ISSUE THREAD

**Issue by Sakamoto0110** [Freebi85/Dungeons-Dragons-Space-Shuttles#204]
I was puting my chickens together with the lead, and i missclicked in a fence, when i tried to remove the lead from the fance, the game crashed, i can't enter in this world anymore ( aroma save lifes ), for some reason i had a hard inventory wipe, but its ok.
The crash report file says is quark related 

Crash report: 
------------------------------------------------------

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2019-06-17 20:38:17 BRT
Description: Ticking entity

java.lang.NullPointerException
    at vazkii.quark.decoration.entity.EntityLeashKnot2TheKnotting.onUpdate(EntityLeashKnot2TheKnotting.java:34)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zbm000(World.java:5118)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: quark:leash_knot (vazkii.quark.decoration.entity.EntityLeashKnot2TheKnotting)
  Entity ID: 552449
  Entity Name: entity.quark:leash_knot.name
  Entity's Exact location: -156.50, 64.38, 167.50
  Entity's Block location: World: (-157,64,167), Chunk: (at 3,4,7 in -10,10; contains blocks -160,0,160 to -145,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Entity's Momentum: 0.00, 0.00, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,ForgeData:{},RelativeAABB:[-0.1875d,0.0d,-0.1875d,0.1875d,0.5d,0.1875d],Attributes:[{Base:20.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.699999988079071d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:16.0d,Name:"generic.followRange"}],Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,DeathTime:0s,ForgeCaps:{"nuclearcraft:capability_entity_rads":{consumed:0b,radiationResistance:0.0d,totalRads:0.0d,radawayBuffer:0.0d,shouldWarn:0b,radiationLevel:0.0d,poisonBuffer:0.0d,radXCooldown:0.0d,radXWoreOff:0b,radawayCooldown:0.0d,radawayBufferSlow:0.0d,radiationImmunityTime:0.0d},"tinkertoolleveling:entityxp":[],"llibrary:extendedentitydatacapability":{"mm:living":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,prevHasAI:0b,frozenYawHead:0.0f,frozenEntityID:-1,frozenLimbSwingAmount:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f},"Ice And Fire - Siren Property Tracker":{CharmedBySiren:0b,SirenID:0},"Ice And Fire - Frozen Property Tracker":{TicksUntilUnfrozen:0,IsFrozen:0b},"Ice And Fire - Stone Property Tracker":{StoneBreakLvl:0,TurnedToStone:0b}},"twilightforest:cap_shield":{permshields:0,tempshields:0},"pneumaticcraft:hacking":{}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,Motion:[0.0d,0.0d,0.0d],Leashed:0b,UUIDLeast:-7962469707180439841L,Health:20.0f,LeftHanded:0b,Air:300s,OnGround:0b,Dimension:0,NoAI:1b,Rotation:[1.40625f,0.0f],UpdateBlocked:0b,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],UUIDMost:5215149114708413751L,Pos:[-156.5d,64.375d,167.5d],Fire:0s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s}

**Comment by Freebi85** [comment]
Hey =)
Updating Quark to latest version should solve the problem if you don't want to wait for the next official pack update. (this weekend)
Please report mod specific problems in the future directly to the appropriate mod githubs.
