### ISSUE TITLE
Refined Storage Filter-Not filtering as it should?  (Mod Filter default?)

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#205]
I have been trying to set up custom filters with my refined storage system, and noticed some strange filtering glitches with Thermal Foundation items.

As far as I can tell, when I add a Thermal Foundation item to the filter, the filter sees only the mod name of the item, not the item itself.  See attached screenshots.

In the example below, I added a Thermal Foundation Lead ingot, and then placed it in the Refined Storage grid.  It filtered to all Thermal Foundation items; not just the Lead ingot.  Note in my screenshot that my Mod option was not checked.

Thanks!
![2019-06-19_22 06 25](https://user-images.githubusercontent.com/10191173/59813580-096d5300-92e0-11e9-9bf1-144baf303633.png)
![2019-06-19_22 06 36](https://user-images.githubusercontent.com/10191173/59813581-096d5300-92e0-11e9-8186-57d8b2bff86a.png)
![2019-06-19_22 06 43](https://user-images.githubusercontent.com/10191173/59813582-096d5300-92e0-11e9-96e5-47817297bdf2.png)

**Comment by Danekjovax** [comment]
I also notice this happening with other mod items as well.  In Tech Reborn, using a sapphire shows also the ruby, peridot, and garnet.  With a circuit plate from Project RedCore, many other ProjectRedCore items are displayed along with the circuit plate.

It's like there's a "semi-mod" filter being used, as items related in the same mod are being displayed, but not specifically the filtered item.

Seems like a glitch, as I believe the RS Filter is supposed to filter to the specific item placed in the filter list (assuming Whitelist and Mod filter is unchecked).

Thanks again!

**Comment by Danekjovax** [comment]
List of problematic mods: Tech Reborn, ProjectRed Core, Thermal Foundation, Mystical Agriculture, NuclearCraft, Actually Additions, Mekanism.

Method to replicate:  Have a Refined storage system with a crafting grid.  Get some items in it (different mods of items).  Have a Refined Storage Filter.  Place an item of a particular mod into the modlist of the filter.  Open Grid GUI and place filter into one of the 4 filter slots (upper right).  If only the item is displayed, then that mod is OK.  If the item AND other items from that same mod are displyed, then that mod is problematic.

Hope this helps.

**Comment by Freebi85** [comment]
That's nothing I could fix. Please report mod specific issues directly to the corresponding mod githubs.
(check first if someone has already opened an issue about this problem because i have noticed that several filter tickets have been opened/closed in RS)

Please report only the following issues on my Issue Tracker. 
- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be rebalanced. 
- Suggestions for missing or additional integrations in machines.
- Any problems with quests (description, spelling mistakes, task not recognized etc.)

**Comment by Danekjovax** [comment]
Will do.  Thanks.

**Comment by Danekjovax** [comment]
RS dev mentioned the following:
"Play around with the damage/NBT options. Many mods register their items with the same name but different metadata or NBT.

There is not really a way to make it work well in 1.12 and the issue will mostly resolve itself in 1.14 so this will probably not get fixed."
https://github.com/raoulvdberge/refinedstorage/issues/2268

Not sure if this is something you could work with, but it seems there's at least something to work with here.  Thanks again.
