### ISSUE TITLE
[5.2] /dank/null GUI/Hotkey Issues

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#206]
I've recently updated to the 5.2 version of the modpack, and noticed the following issues with the /dank/nulls that I have (I have 2x Mk VI):

1) GUI seems to have a synchronization issue (not sure if it's client or server based).  Items aren't all displayed and pulling items from slots will not get the displayed item, or you can pull items from what you think is an empty slot.  No duping is going on as far as I can tell.  Items are supposed to auto-arrange from top-left, but in this case it is not visually happening.

2) Certain places prevent you from accessing the /dank/null GUI (hotkey or crouch/right-click).  It may be related to if you have a block/entity in range of your crosshairs, but not totally sure.

This may be a mod related bug, and if so may need to rollback to previous version until issue is addressed by the mod devs.  Screenshots attached.
![2019-06-22_09 49 08](https://user-images.githubusercontent.com/10191173/59965200-ece83b00-94d8-11e9-8b0b-dabecef1d011.png)
![2019-06-22_09 55 39](https://user-images.githubusercontent.com/10191173/59965202-f07bc200-94d8-11e9-8ca6-6db1ea0eb5a9.png)

**Comment by Danekjovax** [comment]
Seems to help to empty out the dank/null, then fill it to less than 128 items per stack.  Desynching starts when stacks go to 128+.

This has been reported to mod devs  (see above link)

**Comment by Danekjovax** [comment]
Thanks Freebi.  I was suspecting as much.

**Comment by Freebi85** [comment]
for now backportet danknull due to too many bugs.
