### ISSUE TITLE
Proposal for recipe to automate double and triple batteries

### ISSUE THREAD

**Issue by duncancar** [Freebi85/Dungeons-Dragons-Space-Shuttles#207]
Currently it appears that the only way to craft higher tier batteries from actually additions is through the engineer's workshop, a block that is not automatic. I've noticed that there is, however, a recipe for single batteries inside of the carpenter. Thus, I think it would be nice to have a similar recipe along those lines to make it possible to automate these higher tier batteries. Thanks.

**Comment by Freebi85** [comment]
I can do that. No problem :D

**Comment by duncancar** [comment]
Awesome! Thanks :)
