### ISSUE TITLE
Feature/Idea: Endgame "machines"

### ISSUE THREAD

**Issue by leftyde** [Freebi85/Dungeons-Dragons-Space-Shuttles#209]
Hi,

your Pack is really fun to play but I have a suggestions for tinker alloy automation in endgame.

Maybe you will look at this:
 https://minecraft.curseforge.com/projects/modular-machinery?gameCategorySlug=mc-mods&projectID=270790 
For a custom endgame alloy furnace to automate some "alloying" outside of the smeltery? :)

**Comment by Freebi85** [comment]
I  decided I don't want to work with this mod sorry :/
