### ISSUE TITLE
Cant craft lapis lazuli block

### ISSUE THREAD

**Issue by DragonmasterDJ** [Freebi85/Dungeons-Dragons-Space-Shuttles#21]
its in the title  : )

Whenever I try to craft it it fails, even though the recipe is right.

![2018-12-02_18 38 42](https://user-images.githubusercontent.com/29170640/49337084-c4464400-f661-11e8-8db1-6dfb66c0fb87.png)

**Comment by Freebi85** [comment]
oops^^
