### ISSUE TITLE
Thermal Dynamics filters and servos Blacklist / Whitelist not working

### ISSUE THREAD

**Issue by BeardedGrue** [Freebi85/Dungeons-Dragons-Space-Shuttles#210]
The COFH conduit filters/servos Blacklist or Whitelist, usually with over-provided itemduct, will ignore those lists.  I have not seen this to be a problem with fluid ducts.  Storage inventory connected to the servo or duct does not seem to change the problem.

**Comment by Freebi85** [comment]
Hello =)
Sorry but that's nothing I could fix. Please report mod specific issues directly to the corresponding mod githubs. If this count as issue for the devs.
(check first if someone has already opened an issue about this problem)

Please report only the following issues on my Tracker.

Not working / broken recipes
Proposals for new recipes or recipes that still need to be rebalanced.
Suggestions for missing or additional integrations in machines/Void ore miners/etc.
Any problems with quests (description, spelling mistakes, task not recognized etc.)
