### ISSUE TITLE
Mekanism Logistics connectors cause too much load

### ISSUE THREAD

**Issue by BeardedGrue** [Freebi85/Dungeons-Dragons-Space-Shuttles#211]
Mekanism Logistics pipes over-provide to items to the Logistics pipes, either by pulling through Mekanism, or an auto-eject from other mods.  These items build up quickly and cause horrendous lag.  Changing the display options (solid pipes) did not help the issue.  Breaking the pipes of the tree farm in this cause resolved the issue, once the 10k+ of wood despawned  This is on a 9th gen I7, 1.8.201 Java, 12GB allotted memory, single player.  Switching to CoFH itemducts cleared the problem perfectly, but CoFH has its own issues.

**Comment by Freebi85** [comment]
Hello =)
Sorry but that's nothing I could fix. Please report mod specific issues directly to the corresponding mod githubs. If this count as issue for the devs.
(check first if someone has already opened an issue about this problem.

Please report only the following issues on my Tracker.

    Not working / broken recipes
    Proposals for new recipes or recipes that still need to be rebalanced.
    Suggestions for missing or additional integrations in machines/Void ore miners/etc.
    Any problems with quests (description, spelling mistakes, task not recognized etc.)
