### ISSUE TITLE
Void Ore Miner - Bauxite Ore

### ISSUE THREAD

**Issue by 123zane321** [Freebi85/Dungeons-Dragons-Space-Shuttles#213]
Not a bug, but I don't really see why bauxite ore isn't an output for the void ore miner - it's important mid-late game for making titanium, so I don't see why it shouldn't be an output.

Maybe add it to one of the higher tiers of miner? Like, say, tier 3-4?

**Comment by Freebi85** [comment]
A good suggestion. I will add it to the T3+ miners. 👍

**Comment by 123zane321** [comment]
Thanks for the quick response =) the late game titanium struggle is real
