### ISSUE TITLE
Cyclic's Chaos Reaper wrong recipe

### ISSUE THREAD

**Issue by MiagoMeowsome** [Freebi85/Dungeons-Dragons-Space-Shuttles#214]
The Chaos Reaper from Cyclic seems to have two recipes :
One intended ( and one that seems to be the recipe for a mine cart
https://i.imgur.com/GIy4oa3.png

**Comment by Freebi85** [comment]
Oh super weird. Thank you for reporting =)

**Comment by MiagoMeowsome** [comment]
No problem, thanks for your awesome work on the pack !
