### ISSUE TITLE
Issue alloysmelter

### ISSUE THREAD

**Issue by leftyde** [Freebi85/Dungeons-Dragons-Space-Shuttles#215]
Hi,

I found an error in Tech Reborn Alloy Smelter

1 iron ingot + 5 redstone = red alloy ingot
1 iron ingot + 1 redstone = 1 conductive iron ingot

I can't get red alloy ingots working and maybe can you add a recipe for the induction smelter? :I

**Comment by Freebi85** [comment]
conductive iron? We don't have conductive iron in this pack?

**Comment by leftyde** [comment]
Conductive Iron Ingot is from enderio wich is in the pack?

**Comment by Freebi85** [comment]
This has already been sufficiently discussed in discord. You are using a modified version of the pack. You will understand that there is no support for this. Also, the whole game experience is broken without modified Ender Io machines. But you have to decide for yourself.
