### ISSUE TITLE
dyonite recipe in the smelter 

### ISSUE THREAD

**Issue by picklehead8521** [Freebi85/Dungeons-Dragons-Space-Shuttles#218]
Seems a bit weird when going to automate dyonite i noticed the recipe calls for 9 ingots to make 144mb  and 144mb to make 9 ingots dont know if that is on purpose or not. 

On a side not there are a lot of other recipes that  have this if this is a bug or intended let me know and i can send u a list of them. most found in autocrafting  through RS where  sometimes it calls for 64 plates of something even though if u just normally crafted it it would only cost 4 and can easily be worked around if you program the simple recipe in the rs system

**Comment by Freebi85** [comment]
I don't understand what you mean. 144mb dyonite = 1 ingot / 1 dyonite ingot = 144 mb?
And yes the taia alloys requires an insane amount of ingots for the alloy,

**Comment by picklehead8521** [comment]
can i post screenshots on here ?

**Comment by Freebi85** [comment]
yeah feel free

**Comment by picklehead8521** [comment]
https://i.imgur.com/ECnQmrC.png

1 ingot of liquid 144mb  = 9 ingots in the caster

**Comment by picklehead8521** [comment]
https://i.imgur.com/p39p6J6.png

144mb of liquid = 9 ingots  in the caster

**Comment by picklehead8521** [comment]
or recipes like this one  if u shift click it into the pattern grid  it calls for 9 diamonds on each side  but its craftable with 1 diamond in the regular table

https://i.imgur.com/H4ELbtK.png

**Comment by Freebi85** [comment]
Well i don't know why JEI sometimes makes such weird stuff like this^^ Seems to be a visual error. I had this onve wiht coal blocks for some readon but the recipe works still correct. Can't reproduce in singleplayer.

![raw processor](https://user-images.githubusercontent.com/42634622/60395020-61e8ef80-9b2d-11e9-978c-17977a807cb9.jpg)
![dyonite](https://user-images.githubusercontent.com/42634622/60395021-63b2b300-9b2d-11e9-97c1-dad0eb82fd65.jpg)
