### ISSUE TITLE
Infernal Mobs. Unkillable Ender Dragon

### ISSUE THREAD

**Issue by zMultiKiller** [Freebi85/Dungeons-Dragons-Space-Shuttles#219]
So i just tried fighting the ender dragon after gathering the eyes of ender needed.
After breaking the healing crystals.  I was able to damage the Dragon. but it kept healing up to full HP.

 I realized it had potion effects around it and that it healed then it dove the island. 

My best guess is that My Ender Dragon has the 'Life Steal' effect and it constantly heals from hitting the Enderman when it doves the island. 
It might have some other effects as when it dives the island. it seems  to get stuck in an endless loop of hitting enderman, teleporting past them then diving again (while still on the ground) Meaning it never leaves the enderman attacking it and gaining infinite HP. 

I know its not me doing not enough damage. Because end i enter the end for the first 30 Secs i can damage the dragon with arrows, before it dives and gets caught in a loop.

**Comment by Danekjovax** [comment]
You could drop a few mega torches to prevent enderman spawns and see if that helps. ;2)

**Comment by Freebi85** [comment]
probably mutated into an infernal boss.
I can't prevent boss monsters from appearing infernal sadly 
i think if it's to heavy all you can do is reset the END dimension
