### ISSUE TITLE
can´t be crafted

### ISSUE THREAD

**Issue by ferrium42** [Freebi85/Dungeons-Dragons-Space-Shuttles#22]
Boneblock  try crafting table tinker crafting table refined storage and dye cluster and many of the dye recipes don´t work , if you try craft something with a sapling in refined storage - freeze and game must restart

**Comment by Freebi85** [comment]
Ok thank you. I will fix the boneblock and some dye recipes. The bug with Refined Storage Must be reportet to the mod author. There is Nothing i can do.
