### ISSUE TITLE
5.4 crash  just after start   3 reports

### ISSUE THREAD

**Issue by dhdarkelf** [Freebi85/Dungeons-Dragons-Space-Shuttles#221]
updated to 5.4 from 5.3 
its running on a server from "streamline servers"
the cpu is not dropping it's all ways at 100%, then crash minutes after starting can get in but server is very slow

[crash.zip](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/3353273/crash.zip)

**Comment by Freebi85** [comment]
Hello =)
Hi, all 3 reports are a Watchdog Crashes. A Watchdog error means that the server is stuck (lag) doing something. Could be anything also a weak cpu. You can easy disable it. It wont stop your server from having the long tick times that are causing the watchdog to shut down your server but it will stop shutting off so you can figure out whats up with laggoogles for example. (seems to be a drawer or a mekanism machine or both)

Disable Watchdog in the server propreties. Set max-tick-time to -1

I hope I was helpful.
