### ISSUE TITLE
[mod suggestion]: Nature's Compass

### ISSUE THREAD

**Issue by Dryelo** [Freebi85/Dungeons-Dragons-Space-Shuttles#226]
hi there Freebi,

I hope it's okay posting mod suggestions here - I wouldn't know where else you'd want them.

As the title says: would you consider adding Nature's Compass to your modpack?
In case you don't know that mod, the author's description is:
"Nature's Compass is a utility item that allows you to search for a biome's location anywhere in the world and view information about it."

There's only one item in the mod, so customizing the recipe wouldn't take too long.
I doubt that it would have a noticeable impact on progression through the modpack but it would be a great help for adventurers and achievement hunters like me :)

In any case - thanks for a fantastic modpack an keep up your dedication!

-Dryelo

**Comment by Freebi85** [comment]
was added =)
