### ISSUE TITLE
Cant install modpack due to dependency issue.

### ISSUE THREAD

**Issue by Xiaphear** [Freebi85/Dungeons-Dragons-Space-Shuttles#227]
[https://i.imgur.com/0sEmv6E.png](https://i.imgur.com/0sEmv6E.png)

As screenshot from the twitch launcer, with the error massive on display.
I myself have no idea what mod the number stands for. Perhaps you do.

Thought I'd let you know.

**Comment by dierke9** [comment]
Twitch being annoying once again...
If this is an update try updating to a new profile
If this is an install try resarting the twitch launcher and/or your pc
And hope that works...

**Comment by Xiaphear** [comment]
Closing and opening Twitch did the thing. Sorry for wasting a thread on this,  Thank you regardless!

**Comment by dierke9** [comment]
No worries buddy, twitch likes to be annoying sometimes. Just dont forget to close the issue again 😉
