### ISSUE TITLE
crash on startup 

### ISSUE THREAD

**Issue by coleslaw2005** [Freebi85/Dungeons-Dragons-Space-Shuttles#228]
https://paste.dimdev.org/udayegarud.mccrash
something about rich presence
computer is bad and crashed because of a config before, probably problem my end.

**Comment by dierke9** [comment]
Hello there

You can remove the file "discordcraft-1.0.3.jar" from your mod folder, that should make it start up, this is just a clientside mod so will not affect your gameplay.
In the meantime i will be taking alook why this happens as it shouldnt happen.

**Comment by Donut7163** [comment]
dierke9, where is the modfolder so i may do that ?

**Comment by dierke9** [comment]
@Donut7163 go to your instance folder (uf you are using twitch client you can rightclick on the profile and there should be a option to open it in your filesystem) then go to the mods folder

**Comment by Freebi85** [comment]
Since nobody has reported such a client crash since a long time, I close here. I guess it's done with the latest version. Also I can't reproduce it.
