### ISSUE TITLE
The hardened exchanger (thermal version) recipe is broken.

### ISSUE THREAD

**Issue by Sakamoto0110** [Freebi85/Dungeons-Dragons-Space-Shuttles#229]
Screenshoots:
https://imgur.com/a/kr1ijNg

**Comment by Freebi85** [comment]
Thank you for reporting, i will check this =)

**Comment by Freebi85** [comment]
Temporary fix in update 5.5a. Put old exchanger in a crafting grid to refresh the item. After that it should work. In Next bigger update there is a clean solution for that.
