### ISSUE TITLE
Uncraftable tipped arrow from traveling merchant

### ISSUE THREAD

**Issue by arturgaweski** [Freebi85/Dungeons-Dragons-Space-Shuttles#23]
Merchant that visited my base after few trades offered me except diamonds those "Uncraftable tipped arrow" with no effect. From what i've read on wiki it means that status set on arrow is incorrect and this arrow should not be obtainable by any normal way in survival mode.

**Comment by Freebi85** [comment]
In the next update you will have the possibility to create poison and wither arrows with this "Uncraftable tipped arrow"

I certainly add more but these arrows are actually quite rare. Maybe i find even more exciting ways to use them. Who knows^^
