### ISSUE TITLE
Issues with tech reborn cells and Refined Storage

### ISSUE THREAD

**Issue by kevinlusty** [Freebi85/Dungeons-Dragons-Space-Shuttles#233]
If you try to place liquids into Refined Storage using more than one tech reborn cell at a time, only one cell from the pile is put into storage and all the other liquids and cells in the pile are destroyed...

For example, make a stack of cells full of water, left click into the fluid grid with it... only 1 "bucket" of water goes into storage, one empty cell is returned to you, and the other 63 cells full of water are annihilated.

**Comment by Freebi85** [comment]
Hello :)This issue was already reported to refined storage. Still no fix until today. Can’t do much about it sorry. Just wait and hope. Pls check github of the specific mod befor posting mod specific issues.
