### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by SubMachineGuy** [Freebi85/Dungeons-Dragons-Space-Shuttles#234]
Hello. Ever since I installed this modpack I've been getting crashes. Now, the crash report says it's caused by OpenComputers, and removing the .jar file seems to be helpful, because the game would launch, but also a lot of recipes in game stop working (I don't think I can give you precise info on that), and the quest book progress naturally softlocks. 
Link: https://paste.dimdev.org/hiyufurope.mccrash

**Comment by Freebi85** [comment]
Hello =)
For some reason you are using the wrong Forge Version and Optifine. Both is a problem^^
Removing mods will causes just more issues and brake all custom recipes and alot of Quests.

I suggest to reinstall the pack on twitch and try again.

**Comment by cyber01** [comment]
@SubMachineGuy Похоже потерялась или повреждена одна из библиотек forge. Как вариант - можно переустановить Forge или просто подкинуть библиотеку (по идее это config-1.2.1) в libraries\com\typesafe\config\1.2.1\ и должно заработать. Библиотеку можно взять к примеру в серверной части сборки по аналогичному пути

**Comment by SubMachineGuy** [comment]
So, I've installed previous version of Forge and also replaced the config file and I finally got OpenComputers running! Thank you for the advice.
P. S.: I'm still not sure what exactly was the problem, I forgot to check i.e. I've both dropped config file and installed Forge at the same time. Nevertheless, it's up and running, so I think case closed.

**Comment by Freebi85** [comment]
Noice 🙏😌
Glad to hear 😉👍
