### ISSUE TITLE
Another Crash on Startup (Tinker's Construct)

### ISSUE THREAD

**Issue by jerrythemeatball** [Freebi85/Dungeons-Dragons-Space-Shuttles#236]
Crash on startup during the "bake" portion with the suspected culprit being Tinker's Construct. I've downloaded the pack through the Twitch modpack service and attempted to redownload/reinstall it, but got the same error.

**Comment by jerrythemeatball** [comment]
https://paste.dimdev.org/tuholopuwi.mccrash
link for the crash report

**Comment by cyber01** [comment]
Hello, you need to increase memory limit for java. Now is 3228Mb, but minimum for this modpack is 6Gb, recommended - 8gb+

**Comment by Freebi85** [comment]
As Cyber01 already said. Just out of Memory. 

![ram](https://user-images.githubusercontent.com/42634622/61949673-dc315600-afab-11e9-8a9a-15c89b1c1667.png)
