### ISSUE TITLE
Mystic Agriculture Armor not Working with Enchantment Applicator

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#238]
Currently no Mystical Agriculture armor is placeable in the Industrial Foregoing's Enchantment Applicator.  Is there any way to get these to work together?

![2019-07-27_10 01 49](https://user-images.githubusercontent.com/10191173/61995387-e60f9380-b055-11e9-8460-61c6b97266b7.png)

Thanks in advance! ;2)

**Comment by Freebi85** [comment]
For some reason only the Supremium Stuff is not compatible with the Industrial Foregoing enchanter.
Other Mystical armor works. Sadly is the enchantment applicator a non-tweakable machine.
This means i can't change or add recipes to it. I'm afraid you have to use a normal vanilla anvil.

**Comment by Danekjovax** [comment]
Thanks for checking, Freebi. ;2)
