### ISSUE TITLE
Minecraft failed to start!

### ISSUE THREAD

**Issue by ZeroTheNumber0** [Freebi85/Dungeons-Dragons-Space-Shuttles#239]
Hello. Sorry, maybe you have already seen this problem, but I dunno what to do. When it was like 3/7 it gave me that...
![Desktop Screenshot 2019 07 28 - 17 05 15 97](https://user-images.githubusercontent.com/53395892/62004945-98cb1900-b15e-11e9-97ae-1ad3e07ea4ec.png)
I also have a link if you need it. https://paste.dimdev.org/odehifuvus.mccrash 
( sorry for my bad English. I'm from Russia, but I really want to play. Can you help me please? Thank you )

**Comment by Freebi85** [comment]
Hello =)
You are out of Memory^^ Allocate more Ram to the twitch launcher. Follow the instructions in this picture. The JAR Launcher setting ist not neccessarly required =)

![image](https://user-images.githubusercontent.com/42634622/62005527-ddda5580-b134-11e9-8740-b2a9b4f8e904.png)
