### ISSUE TITLE
Cyclic Storage Bag & Autopickup Dupe

### ISSUE THREAD

**Issue by furrious** [Freebi85/Dungeons-Dragons-Space-Shuttles#240]
Turning on "auto-pickup" in the Cyclic Storage bag will pick up items from inside a chest when broken, while the Autopickup mod does the same thing, doubling what was initially put in the chest.

Only tested on IronChest mod chests.

**Comment by Freebi85** [comment]
Because of this and other reasons the Storage Bag is not Enabled in my Pack.  So how do you get to one?

**Comment by furrious** [comment]
Odd. It has a recipe, and it looks default. I guess I should have been suspicious when I saw that, but it was early game before I noticed how thorough the changes were. 

Oh, I think I see what happened. It doesn't show up in JEI if you search for it, but by looking for uses for leather, you can find the recipe that way. I think.

**Comment by Freebi85** [comment]
Ok Alright thank you. i will take a look and maybe ban the item completely. Make sure to empty the bag befor next update =)
