### ISSUE TITLE
Conflicting Allot Kiln recipie for Electrotine/Red Alloy Ingot

### ISSUE THREAD

**Issue by IgnisFlamme** [Freebi85/Dungeons-Dragons-Space-Shuttles#243]
There is a recipie conflict where 3 Pulverized copper and 4 Redstone dust will yield 10 Electrotine. However there is another recipie that produces Red Alloy Ingots with 1 Pulverized Copper and 4 Redstone which prevents me from making Electrotine.

**Comment by Freebi85** [comment]
Hey =)
This was fixed in Modpack Version 5.5a =)
