### ISSUE TITLE
Barrel Coppy Item Bug 

### ISSUE THREAD

**Issue by zenser30** [Freebi85/Dungeons-Dragons-Space-Shuttles#244]
Barrel Coppy Bug 
Barrel Coppy : https://youtu.be/felX9qAwYnI
item Coppy  : https://youtu.be/VbgxC_u-4os

**Comment by zenser30** [comment]
upss

**Comment by zenser30** [comment]
i Thinking (Drop item> in inventory and  DungeonTactics ) 2 mod

**Comment by Freebi85** [comment]
Due to the lag in this viedo i guess it's on a server?^^

**Comment by Freebi85** [comment]
Closed for lack of information. Probably serverside issue.
