### ISSUE TITLE
Keep crashing on startup

### ISSUE THREAD

**Issue by Tgaza** [Freebi85/Dungeons-Dragons-Space-Shuttles#246]
The modpack keeps crashing and saying the reason is unknown
heres the report: https://paste.dimdev.org/ojilepibiv.mccrash

**Comment by cyber01** [comment]
@Tgaza You got java.lang.OutOfMemoryError 
How much RAM do you have on your computer? At the moment, 3GB is allocated for assembly, when the minimum is 6GB, and the recommended 8GB+

How to set RAM in Twitch: https://media.discordapp.net/attachments/547104723665420288/595233251988078624/gcracAAAAASUVORK5CYII.png?width=730&height=481

**Comment by Tgaza** [comment]
ohhh i've got plenty, ill try upping it

**Comment by Tgaza** [comment]
Its working now. Thank you very much
