### ISSUE TITLE
Infinite Treated Wood Plank

### ISSUE THREAD

**Issue by Sluggly** [Freebi85/Dungeons-Dragons-Space-Shuttles#247]
I don't know if this is intended or not but if you put Treated Wood Planks from Immersive Engineering into a Sawmill from Thermal Expansion, you get 4 Treated Wood Slabs. Then you can combine 2 of those slabs to make a Treated Wood Plank again. So you can basically produce Treated Wood Planks out of thin air pretty easily.
![Craft 1](https://user-images.githubusercontent.com/53790466/62501158-c0b71e00-b7e9-11e9-9039-11223c64f962.png)
![Craft 2](https://user-images.githubusercontent.com/53790466/62501159-c0b71e00-b7e9-11e9-888d-ac93bfbea1ec.png)

**Comment by Freebi85** [comment]
I see. Well, Feels bad :D Thank you for reporting. Have to undupe^^
