### ISSUE TITLE
Unable to make green willow sticks

### ISSUE THREAD

**Issue by mystykar** [Freebi85/Dungeons-Dragons-Space-Shuttles#248]
When trying to make the green Willow sticks, they turn into regular sticks.  Trying to use the created regular sticks does not work in the recipe.  Had to go into creative to give myself the sticks in order to finish the Fancy Fences quest.

**Comment by dierke9** [comment]
In the fancy fences quest it should say that you can make the other fences using a Chisel from the Chisel mod. In there you can convert normal fences to the natura ones

**Comment by Freebi85** [comment]
Correct. All Natura Fences and Gates are available via Chisel^^ Like the quest says =)
