### ISSUE TITLE
Opening game V5.5a

### ISSUE THREAD

**Issue by Kozuin** [Freebi85/Dungeons-Dragons-Space-Shuttles#251]
https://gyazo.com/7826a7154e6384fcb69f0f2aa8114a55
https://paste.dimdev.org/juziniwabu.mccrash

**Comment by cyber01** [comment]
Again and again..
You got java.lang.OutOfMemoryError. You should increase memory limit for minecraft.
You have -Xmx4500m (aka 4.5Gb), but minimum for modpack is 6Gb, recommended 8Gb+.

How to increase memory in Twitch
https://cdn.discordapp.com/attachments/547104723665420288/595233251988078624/gcracAAAAASUVORK5CYII.png

**Comment by Kozuin** [comment]
how much ram should i give to the server?

**Comment by cyber01** [comment]
minimum is 8Gb+ , recommended 12Gb+ and pregerated chunks

**Comment by Kozuin** [comment]
ew thats alot of ram, do u know any cheap host that host with high ram cheap?

**Comment by cyber01** [comment]
You need a lot of ram and high frequency cpu
