### ISSUE TITLE
When you look at uses for any item in jei, it shows the mana tesseract as a recipe.

### ISSUE THREAD

**Issue by pandadox** [Freebi85/Dungeons-Dragons-Space-Shuttles#252]
It's just a minor annoyance but it would clean up JEI. It's the mana tesseract from Botanic Additions, thanks

**Comment by Freebi85** [comment]
I know it drives me crazy too. Sadly a Botanic Additions Mechanic i cant remove currently. I'll check with the devs to see if anything can be changed.

**Comment by Freebi85** [comment]
have just seen on their discord it is already known and in processing. I'm closing here because it's already been reported to the devs.
Thanks anyway =)
