### ISSUE TITLE
Various molten metals have no Ingot Former recipe

### ISSUE THREAD

**Issue by balthierace** [Freebi85/Dungeons-Dragons-Space-Shuttles#253]
I have compiled the following list of ingots that can be cast in a Tinkers' Construct Casting Table, but do not have a corresponding ingot recipe in NuclearCraft's Ingot Former.

Tiberium
Aurorium
Prometheum
Duranite
Valyrium
Vibranium
Karmesine
Ovium
Jauxum
Terrax
Palladium
Uru
Osram
Abyssum
Eezo
Triberium
Fractum
Violium
Proxii
Tritonite
Ignitz
Imperomite
Solarium
Nihilite
Adamant
Dyonite
Nucleum
Lumix
Seismum
Astrium
Niob
Yrdeen
Iox
Meteorite
Basalt
Obsidiorite
Dilithium
Sodium
Potassium
Elementium
Demon
Enchanted
Evil Infused
Pink Slime
Refined Obsidian
Glowstone
Base Essence
CuBe
ScAl
BAM
Stellite
Cupronickel
Nimonic
Hastelloy
Nichrome
CuNiFe
Hydronalium
Vanasteel
Tantaloy
NiAl
Inconel
Pewter
Corten Steel
Titanium
Fiery

**Comment by Freebi85** [comment]
Thank you for your efforts to investigate all this! I will add the missing recipes as soon as I have time.
