### ISSUE TITLE
Not loading 

### ISSUE THREAD

**Issue by jtpattie** [Freebi85/Dungeons-Dragons-Space-Shuttles#254]
https://paste.dimdev.org/towemopiqo.mccrash

**Comment by Freebi85** [comment]
Hello =)
You are out of Memory^^ Allocate more Ram to the twitch launcher. Follow the instructions in this picture. The JAR Launcher setting ist not neccessarly required =)

![pic](https://user-images.githubusercontent.com/42634622/62753588-9cb73f00-ba6c-11e9-98a2-0f3bacf098de.png)

**Comment by jtpattie** [comment]
Thanks. So far, so good. Also, thanks for a quick response
