### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by readalot** [Freebi85/Dungeons-Dragons-Space-Shuttles#257]
I keep getting a crash when trying to start this modpack, I have tried lessening ram & giving it more but I'm not very good at figuring this sort of thing out.
https://paste.dimdev.org/bocunizohu.mccrash

**Comment by Freebi85** [comment]
Can't reproduce so far but i don't use multimc. 
Although that's probably not the problem. What kind of keybind option? 
No one has ever reported a keybind crash o_O

**Comment by Freebi85** [comment]
Was this just a random crash or it working now? Was about to render/register a specific block

**Comment by readalot** [comment]
It happens whenever i try to start the modpack

**Comment by Freebi85** [comment]
Did you try to reinstall the pack in a new profile? Maybe somthing went wrong during download on twitch.

**Comment by readalot** [comment]
yep, I have also tried different versions of the mod pack, if the overload mod is not disabled it crashes, I have also uninstalled and reinstalled java to make sure I have the correct version.
lol I tried just playing the mod pack with this mod disabled but half the recipes wouldn't work.

**Comment by Freebi85** [comment]
yeah you can't remove it or it breaks everything. 
Next step ist launch the pack with the JAR launcher option to use latest JAVA on your pc instead the default one from twitch. You can change it here:

![pic](https://user-images.githubusercontent.com/42634622/62837201-33524e80-bc6d-11e9-939e-e5ccd2bb25a4.png)

**Comment by readalot** [comment]
you have my most profuse thanks, that worked ^_^ and it started without any problems.

**Comment by Freebi85** [comment]
Glad to hear it 😉
