### ISSUE TITLE
Roguelike dungeons are completely empty of rooms and chests.

### ISSUE THREAD

**Issue by Lance5057** [Freebi85/Dungeons-Dragons-Space-Shuttles#258]
Roguelike dungeons spawn but there seems to be nothing in them at all, just hallways of stonebrick.

**Comment by Freebi85** [comment]
Yeah sometimes in rare cases it happens sadly. But was already reported to the author here:
https://github.com/Greymerk/minecraft-roguelike/issues/170

Still wait for a fix so i will close here. Can't do much against it myself.
thanks for reporting it anyway =)

**Comment by stormbringerGT** [comment]
I noticed this happens in Dungeons that create close to world spawn, and in modded Biomes (I see the empty dungeons consistently on the Landfill Biome from Dumpster Diving and other Biome O Plenty, consistently in the Marsh biome for example.

**Comment by srwaggon** [comment]
@Freebi85 
I was able to fix this in my fork of Roguelike Dungeons:
https://www.curseforge.com/minecraft/mc-mods/roguelike-dungeons-fnar-edition

**Comment by Freebi85** [comment]
hmm looks good. What will happen to already generated structures or persistent worlds in general?
Also there will be injected with modded loot now?
