### ISSUE TITLE
suggestion clay and questline visible

### ISSUE THREAD

**Issue by ferrium42** [Freebi85/Dungeons-Dragons-Space-Shuttles#26]
I see no later easy clay recipe , i remember in 1.7 it could be crafted with water and earth essence. Or another way ... 
I wish i can see the questline, so i can see which route i have to finish to open the next chapter. 
Cause there are heavy quest not needed to open the next chapters.  And it shows the things you have to do.

**Comment by Freebi85** [comment]
Clay can be produced using the sludge refiner or idnustrial centrifuge. Optionally also via a chemical combiner or bees. This requires a lot of automation and sophisticated processing lines. There is no intention to make it easy.

As far as the visibility of the quests is concerned, i first have to see how it behaves with the activation of further chapters. If everything is visible from the beginning it can be very confusing.

**Comment by Freebi85** [comment]
But I can mark the main quest paths as main so you know where to go.
