### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by jkirkpatrick** [Freebi85/Dungeons-Dragons-Space-Shuttles#260]
The bug seems to occur when changing key option (e.g. 'inventory' key) which forces a crash.

Afterward it keeps the game in a crash loop (which requires a force kill) every time vising the title screen. Modpack requires re-installation to work.

https://paste.dimdev.org/ufugurasip.mccrash

**Comment by Freebi85** [comment]
Can't reproduce so far but i don't use multimc.
Although that's probably not the problem. What kind of keybind option?
No one has ever reported a keybind crash o_O

**Comment by jkirkpatrick** [comment]
Issue exists with 5.5a and 5.6a

Start minecraft, go to config, find inventory key (default = `E`) and replace with tilde `~`. App will crash immediately; in the case of 5.5a the app exits. For 5.6a the VanillaFix puts into infinite crash loop.

**Comment by cyber01** [comment]
Similar issue: https://github.com/Direwolf20-MC/BuildingGadgets/issues/103
Maybe mod/minecraft related bug

**Comment by Freebi85** [comment]
Since nobody has reported such a client crash again in the last few months, I will close here. I guess it's done with the latest version. Also I can't reproduce it.
