### ISSUE TITLE
[Mod Suggestion] Myst aggr insanium essence seed integration

### ISSUE THREAD

**Issue by Kuperus** [Freebi85/Dungeons-Dragons-Space-Shuttles#261]
There is a mod that lets you grow insanium essence seeds and other tier 6 seeds in the garden cloche, it`s called  MystAgrad Cloche Compat. can you add it to the pack? much appreciated!

**Comment by Freebi85** [comment]
I understand that the mod would make this easier, but for the T6 Seeds there are crux for that. That's why I don't want to insert this mod sorry :/

**Comment by Kuperus** [comment]
you would still need the crux for the T6 seeds, but instead of having a lag farm up and running you can have the T6 seeds in a cloche as well. it allows you to put the crux in the cloche as soil iirc.
