### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Donut7163** [Freebi85/Dungeons-Dragons-Space-Shuttles#263]
This happens sometimes when i start the modpack up https://paste.dimdev.org/emoxiwayes.mccrash
I have a pretty good computer so idk why it happens but it just does. Thanks for your assistance

**Comment by Freebi85** [comment]
You run out of memory =) The twitch launcher need more Ram up to 8GB if possible,

![pic](https://user-images.githubusercontent.com/42634622/62837233-96dc7c00-bc6d-11e9-98a1-89914437a266.png)

**Comment by Donut7163** [comment]
Okay thanks mate
