### ISSUE TITLE
[Mod Request] Unlimited Chiselworks (Chisel support for Underground Biomes)

### ISSUE THREAD

**Issue by scribbler957** [Freebi85/Dungeons-Dragons-Space-Shuttles#266]
Unlimited Chiselworks adds Chisel support for a number of mods including Underground Biomes.

(I'd really like to see Direwolf20 building with some color for a change.)

**Comment by Danekjovax** [comment]
I second this motion.

(I doubt DW20 will ever get out of his cobble kick anytime soon, though. >;2)

**Comment by scribbler957** [comment]
@Danekjovax (But **colored** cobble... Usually DW complains about andesite and diorite when he finds them, but he seemed to like Underground Biomes. Maybe just a little contrasting edging...)

**Comment by Kanaminn43** [comment]
I too would love to see Unlimited Chiselworks in this pack! 
Honestly I'm kind of surprised it isn't already.
Not only does it add support for Underground Biomes but so many others, It'd be a great fit!

**Comment by Freebi85** [comment]
Looks like you guys need it so badlyyyyyy ^^ We will see =)
![image](https://user-images.githubusercontent.com/42634622/63158175-f8f40300-c018-11e9-969f-71662cf68e01.png)

**Comment by Freebi85** [comment]
Bad news. This mod causes more problems and crashes than I could solve in the current status. Above all, it forces me to update to a forge version that takes a lot of time to test with the whole pack. I would have to try it on older versions, but for now I have to reject it. Sorry.

**Comment by scribbler957** [comment]
Weird. I've played dozens of hours with UCW 0.2.2 added without a single problem (not counting unlucky oregen, a sea serpents being generated on top of me, and a teleporting flaming juggernaut that throws potions ;) ).

**Comment by Kanaminn43** [comment]
Same as me, an older version of UCW works with the older forge version and hasn't given me any issues. Strange.
