### ISSUE TITLE
Ironwood log -> planks in Sawmill discrepancy

### ISSUE THREAD

**Issue by romiro** [Freebi85/Dungeons-Dragons-Space-Shuttles#267]
Super minor, but noticed it since it's one of my favorite wood to work with.

The recipe in the TE Sawmill for turning logs into planks gives three logs instead of the six that the other logs give. Not sure if it's intended, though it seems like it's not, so here's the issue!

Edit: Same is the case for the other Rustic wood "Olive wood'

**Comment by Freebi85** [comment]
Thx for reporting =)
Will take a look =)

**Comment by Freebi85** [comment]
found the bug :) fixend in next update.
