### ISSUE TITLE
Mining levels (Stone Pick vs Copper), Mining speeds and Hardness. 

### ISSUE THREAD

**Issue by kulflame** [Freebi85/Dungeons-Dragons-Space-Shuttles#268]
When using a stone pickaxe (Iron level) I CAN mine diamond level ores such as Black Granite Bauxite and Black Granite Galena.  

Using a Copper Pickaxe (Iron level) I can not mine these ores.  

Also Copper has the same mining speed as stone.  Not sure if that is intended,

Mining hardness on granite is the same as ores -- not sure if this is intended.

**Comment by Freebi85** [comment]
https://github.com/Aang23/UndergroundBiomesConstructs/issues/62

**Comment by JonathanCSmith** [comment]
See https://github.com/Aang23/UndergroundBiomesConstructs/pull/219 for a possible fix.

**Comment by Freebi85** [comment]
Still not fixed.
Gonna close this since im working on a final release of DD&SS. Maybe I will take a look at it again if it should be fixed in the future.
