### ISSUE TITLE
Multiple Problems Server Crash, Wool Gin and Horses

### ISSUE THREAD

**Issue by mitchngwen** [Freebi85/Dungeons-Dragons-Space-Shuttles#27]
First off very fun mod and a cool idea. We have found some rather irritating issues wich make gameplay not so good:
Wool Gin works to craft sting once then will not craft any more string., so we tried the squeezer but it take about 1 full minute to produce string what a pain.
Horses multiplying like rabbits in real life! This is annoying and causes unnecessary lag
Server keeps crashing and it seems like it's random see attached crash reports.
Also I do not see a way to back up the server.
[crash-2018-12-05_09.37.26-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/2649963/crash-2018-12-05_09.37.26-server.txt)
[crash-2018-12-05_10.59.23-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/2649965/crash-2018-12-05_10.59.23-server.txt)
[crash-2018-12-05_09.30.20-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/2649966/crash-2018-12-05_09.30.20-server.txt)

**Comment by Freebi85** [comment]
Hello mitchngwen. Thanks for reporting!
I will fix the string (wool gin) recipe in the next update.
I will take a look into configs for the horses to prevent this problem.

Regarding crashes, it has to be reported directly to animania. Unfortunately i can't do much about it except deactivate horses or reduce the maximal spawn rate.

**Comment by mitchngwen** [comment]
So the crash is caused from Animania? I can not figure out why the server keeps crashing.

**Comment by Freebi85** [comment]
As far as i can see the animania horses are to blame for the crash. Something is wrong with a certain entity.
Really weird. You're the first to report this.
