### ISSUE TITLE
Unbalanced food

### ISSUE THREAD

**Issue by DivineCrown** [Freebi85/Dungeons-Dragons-Space-Shuttles#271]
So I love using Pam's for food, and the fact that more complex food requires more items. I've come to noticed a pretty unbalanced to the food with the introduction of Can Food from Galaticraft. The recipe comes from both Galaticraft and Extra Planets and uses a Tin Canister.

Take 1 Tin Canister and combine it with any 2 of these items:
Ground Beef - 2 from Raw beef
Potato
Melon
Carrot
Apple
Potato
Melon
Carrot
Apple
Cooked Chicken
Cooked Salmon
Cooked Fish
Cooked Porkchop

I've tested on the canned chicken and apples and found it to be a bit cheaty due to the changes to hunger and saturation given by a lot of Pam's and vanilla recipes, and I'd like to either see that this is disabled or rebalanced.

**Comment by Freebi85** [comment]
Thx for reporting =)
 Rebalancing the canister will solve the problem i guess.
