### ISSUE TITLE
tooltip error on food item Menril Berries

### ISSUE THREAD

**Issue by cparker607** [Freebi85/Dungeons-Dragons-Space-Shuttles#272]
Version 5.6a of modpack
when eaten menril berries grant half a thing of hunger when the tooltip says it does 1 thing of hunger

**Comment by Freebi85** [comment]
Thx for reporting =)
It seem's i cant tweak the "haunch" tooltip for it. I'm sry. And this is not a mod issue bc i nerfed the berries a bit.  we're gonna have to live with this little thing.
