### ISSUE TITLE
Crash on startup, twitch install

### ISSUE THREAD

**Issue by csakzolta** [Freebi85/Dungeons-Dragons-Space-Shuttles#273]
https://paste.dimdev.org/madajaroqu.mccrash

Hi everyone!

First I tried to install the mod with Forge, but its crashed. After I tried it with the twitch installer but it also crashed. Every crach, the reason is different.

**Comment by Freebi85** [comment]
Raise your Ram. Pack requires 8GB.

Check picture in this issue.
https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/263
