### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mort1s1234** [Freebi85/Dungeons-Dragons-Space-Shuttles#274]
Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by mort1s1234** [comment]
Unable to get Addon: Open Modular Passive Defense (254332) - File ID: 2716443

**Comment by Freebi85** [comment]
This is a twitch error and has nothig todo with the pack^^ 
Anyway Restarting the Twitch Launcher solve the issue with missing Addons.
Happens more often the last few days. More and more players switch to multimc bc they wan't to deal anymore with twitch^^
