### ISSUE TITLE
Twilight Forest Portal

### ISSUE THREAD

**Issue by Mattyboy0066** [Freebi85/Dungeons-Dragons-Space-Shuttles#275]
So, I've tried making the twilight forest portal, and I've skipped the quests of the book because there's way too many of them for my liking, and I figured out everything else myself via google. However, there's nothing in the quest book related to creating the twilight forest portal that I can find, and it appears the usual way of 2x2 water surrounded by various plants + throw diamond in doesn't work. I don't see any clear or obvious indication of how to make the portal... yes I used "bq_admin edit" to check every quest to see if there's a twilight portal quest, and no, I did not find one.

**Comment by Freebi85** [comment]
You need a mana diamond from botania to open the portal. White magic tier 1.
