### ISSUE TITLE
[Mod Suggestion] Recurrent Complex

### ISSUE THREAD

**Issue by SextupleTap** [Freebi85/Dungeons-Dragons-Space-Shuttles#276]
I noticed that IvToolkit by "Ivorforce" was lying around as a stray library mod in the pack, IvToolkit only has four dependents (also by Ivorforce), two of which aren't even updated to 1.12.2, the one I'm primarily interested in though that is for 1.12.2 is Recurrent Complex, a stricture generation mod. I suggest the possibility of adding in Recurrent Complex as it seems like it could work very well along side the other structure generation mods you have in the pack, it really is an incredible structure generation mod with a plethora of well made and unique structures built into the mod, it's highly customizable and even able to be placed into "lightweight" mode in the config to register as little as possible whilst still generating structures etc. this is especially useful for if you are still having concerns about performance in the pack. I feel like the structures this mod adds can provide even more vibrant substance to the world :)

**Comment by Freebi85** [comment]
Hello =)
This mod was still there because I test Recurrent Complex again and again because I like it.^^ Unfortunately I have still crashes  and it just doesn't run stable so it never passed my tests.
It's time to get rid of the lib. Thank you for the heads up.
