### ISSUE TITLE
[Mod Suggestion] Building Gadgets

### ISSUE THREAD

**Issue by MacAttack-UK** [Freebi85/Dungeons-Dragons-Space-Shuttles#278]
Please could you add something to help us build awesome things. I've not been able to find a decent wand to help with this. The XU2 one is a little dated now a days an there doesn't seem to be anything else (that can see) to use.

May I suggest Dire's 'Building Gadgets' mod with some config tweaks to the 'Exchanging Gadget' to stop exchanging of ores that cannot be mined normally etc.

I've been adding it to our server with default configs but it would be nice to see it integrated into the quest lines.

**Comment by RandAlThorn** [comment]
i would love to have this as well :)

**Comment by StormyMode** [comment]
That would be pretty awesome! 👍

**Comment by Tntdruid** [comment]
None stop you from download and add it yourself.

**Comment by Freebi85** [comment]
I'm sorry to disappoint you, but I've decided against it.
