### ISSUE TITLE
botania flower pouch

### ISSUE THREAD

**Issue by RandAlThorn** [Freebi85/Dungeons-Dragons-Space-Shuttles#279]
the botania flower pouch is deleting flowers inside of it. Every Time i have tried to use it when i log back into the game every flower is gone :(. Currently running v 5.6a but this happened in v 5.5a as well

**Comment by Freebi85** [comment]
Was reported here.
https://github.com/Vazkii/Botania/issues/2709
Cant do much for you atm.

**Comment by Freebi85** [comment]
Gonna close here. Seems to be a serverside issue. I'ts reported on Botanias Github. Can't do much then wait and hope if there will be a fix at all for 1.12.
