### ISSUE TITLE
extended crafting automation don´t work right

### ISSUE THREAD

**Issue by ferrium42** [Freebi85/Dungeons-Dragons-Space-Shuttles#28]
I'm attempting to automate crafter and I've got the pattern in an interface facing a automation interface and the interface will input all the items into the extended table, but won't export the ingot back into the interface unless I open the tables gui. does anyone know why this is happening or how to fix it?

also es funktioniert bis zu dem punkt wo es das item craften und rausnehmen soll , scheint ein modproblem zu sein - weil den text hab ich aus enigma expert 2 pack issu 

anyone know a fix - i try mechanical user - no work but i see a tutorial and there it´s working fine without external machines to click

**Comment by Freebi85** [comment]
Ich würde wirklich gerne helfen aber ich fürchte das ist ein coding Problem der mod. Ich denke der issue ist bei Refined Avatitia besser aufgehoben. Ich lass es noch ne weile offen falls noch jemand was dazu sagen möchte.

**Comment by ferrium42** [comment]
https://github.com/BlakeBr0/ExtendedCrafting/issues  ist dort als bug gelistet vor 5 tagen also abwarten

listed as bug
