### ISSUE TITLE
Dungeons-Dragons-Space-Shuttle crash

### ISSUE THREAD

**Issue by Lucka1977** [Freebi85/Dungeons-Dragons-Space-Shuttles#283]
![0](https://user-images.githubusercontent.com/54307710/63329733-c7d64400-c332-11e9-987d-522b00d6eb0e.jpg)

![11111 (1)](https://user-images.githubusercontent.com/54307710/63329688-b55c0a80-c332-11e9-8dc8-31622d1bd018.jpg)
![69271550_2269150846748616_3944162626484830208_n (1)](https://user-images.githubusercontent.com/54307710/63329705-bbea8200-c332-11e9-9f21-c349501c8e54.jpg)

Good morning, 
I have a problem with a modpack "Dungeons-Dragons-Space-Shuttle". By installing this modpack it appears this error mentioned on first two pictures (problem description  and report of the problem). After ignore it and trying to install, the installation of this modpack crashes in the installation phase 6/7 (the third photo) .    Other modpacks work as usually, only this one modpack is wrong. 
I would appreciate if you could help me and try to solve this problem. 
Thank you very much for your understanding.
With my best regards
Lucie

**Comment by cyber01** [comment]
1. Try update video drivers, it may cause lags
2. Allocate more memory to java (now 4Gb), but minimum 6Gb, recommended 8gb+

**Comment by Lucka1977** [comment]
Thanks a lot. I would be happy if someone would place a short video on YouTube or send a short video to my email for to know how to do it. I'm not specialized in this.  My email: lucie.sroubkova@gmail.com. Once again thanks a lot.

**Comment by cyber01** [comment]
https://media.discordapp.net/attachments/547104723665420288/595233251988078624/gcracAAAAASUVORK5CYII.png?width=964&height=634

**Comment by Freebi85** [comment]
Thx Cyber <3

**Comment by Agent-jynx** [comment]
I have this issue also, but I don't have a Minecraft tab under settings from twitch. Help please!!!
