### ISSUE TITLE
[Mod Suggestion] End game content mod Warp Drive

### ISSUE THREAD

**Issue by IIUlqII** [Freebi85/Dungeons-Dragons-Space-Shuttles#284]
[Warp Drive](https://www.curseforge.com/minecraft/mc-mods/warpdrive) this mod will expand the final game content in modpack, and will allow to travel in universe with your mothership (base)

**Comment by Freebi85** [comment]
It’s a great mod but pretty early Alpha. And doesn’t fit in current modpack ongoing development. Anyway thx for the heads up, maybe can use this in another project =)
