### ISSUE TITLE
Entangled Chalice have only one channel

### ISSUE THREAD

**Issue by Baitss** [Freebi85/Dungeons-Dragons-Space-Shuttles#285]
![image](https://user-images.githubusercontent.com/37446282/63408683-8f199600-c42a-11e9-9a3a-c638762f6593.png)

![image](https://user-images.githubusercontent.com/37446282/63409785-d56ff480-c42c-11e9-97a3-166bdcdf21bc.png)

Generally, when player craft Entangled Chalice, result must be 2 "blank" channel Entangled Chalice to set new channel automatically. And if player want more same channel Entangled Chalice, he need craft Entangled Chalice with Entangled Chalice which have wanted channel.

![image](https://user-images.githubusercontent.com/37446282/63410128-8e363380-c42d-11e9-8031-4c780630e7f0.png)

But DDSS have only 1 recipe with preset channel(creativeTank0), so all Entangled Chalice are shared, makes chalice have severely limited potential.

**Comment by Freebi85** [comment]
I think i found the problem. The first chalice will be now the original one and not creative0. And the upgrade recipe will be readded as default in next patch.

Thx for Reporting.
