### ISSUE TITLE
Astral Sorcery Treasure Shrines only Mining Stone

### ISSUE THREAD

**Issue by TheSmiffster** [Freebi85/Dungeons-Dragons-Space-Shuttles#286]
Treasure Shrine Config file is fine and has ores configured but only smooth stone is spawning from the center stone block

and is enabled in astralsorcery.cfg

Any suggestion?

using the Dungeons Dragons and Space Shuttles modpack

Astral Sorcery Version: astralsorcery-1.12.2-1.10.19

**Comment by TheSmiffster** [comment]
and if Disabled like others have mentioned, How to enable again?

**Comment by Freebi85** [comment]
This is intentional for balancing reasons and not an issue.
I don't give any information on how to change the pack.
