### ISSUE TITLE
"Quest Database Not Found"

### ISSUE THREAD

**Issue by fiddler44** [Freebi85/Dungeons-Dragons-Space-Shuttles#287]
I opened the game, made a new world, and the quest book was blank. I tried /bq_admin default load, but the game replied "quest database not found." Any Ideas?

**Comment by cyber01** [comment]
You have betterquesting folder in config? and inside it should be a file DefaultQuests.json

**Comment by Freebi85** [comment]
Sounds like it’s missing the entire mod. Reinstall the pack and check if you launch correctly with this twitch launcher. Im main menu you should see 287 mods loaded.

**Comment by Freebi85** [comment]
If this still don't work, pls contact us on our Discord helpdesk because this is not a Mospack Issue.
