### ISSUE TITLE
[Mod Suggestion] MCT Smeltery IO

### ISSUE THREAD

**Issue by tgstyle** [Freebi85/Dungeons-Dragons-Space-Shuttles#288]
Wondering if you would like to add a mod I created that is similar to Tinker I/O but more balanced. It needs Snowballs as a fuel to cast items, and allows you to automate casting.

https://www.curseforge.com/minecraft/mc-mods/mct-smeltery-io

If you have any suggestions let me know.

**Comment by Freebi85** [comment]
I'm glad you proposed this, but I'm afraid I have to decline. Although I like to support modders and mods very much, I don't want to add this at the moment. 
Great work, though!
