### ISSUE TITLE
Unbreakable Block: "Little Online Picture Frame" from "OnlinePictureFrame"

### ISSUE THREAD

**Issue by msoehnchen** [Freebi85/Dungeons-Dragons-Space-Shuttles#289]
I placed some big OnlinePictureFrames in my base, which can be removed with an axe or hatchet  without problems.

I also build a "Little Online Picture Frame", which cant be broken with an axe, nor a pickaxe.
In addition to that, a pickaxe (mine is from tinkers, which has the xp-gain-trait on it) tries to break it, but is not succesful (durability goes down, i got XP for every hit). So this is in fact a XP-Generator as long a i repair my pickaxe.

But, the real problem is of course that i cant break the block.
I was well able to put it in move-mode with an empty hand and a bit of shift (or ctrl)-leftclicking.

Hitting the Block with an Pick, gains XP - Note: No Block name in WAILA while cursor is on the frame
![2019-08-23_09 49 10](https://user-images.githubusercontent.com/5263600/63575862-593ff300-c58b-11e9-81b0-c8d3eb83d7ea.png)

As you can see, i also get a message above the hotbar, which dont make any sense to me:
![2019-08-23_09 41 38](https://user-images.githubusercontent.com/5263600/63575647-dfa80500-c58a-11e9-9d26-38756628968b.png)

**Comment by cyber01** [comment]
Hi, I’ll try to re-enter the game world (if it's a single player game) or restart the server. If this does not help, you can remove it in the creative

**Comment by msoehnchen** [comment]
> Hi, I’ll try to re-enter the game world (if it's a single player game) or restart the server. If this does not help, you can remove it in the creative

Cyber01, i know how to remove that block, but i want to adress this issue :)

BTW: relogging and restarting client doesn't help here.... (Singleplayer)

**Comment by cyber01** [comment]
i think it mod issue, not modpack

**Comment by Freebi85** [comment]
Pls Report this direct to the mod Author on Online Picture Frames/little Tiles. Thank you. 
There is nothing i can do against this.
