### ISSUE TITLE
semi-friendly skeleton (serious AI problems since last update, barely can move)

### ISSUE THREAD

**Issue by arturgaweski** [Freebi85/Dungeons-Dragons-Space-Shuttles#29]
Found a little problem with monsters, not all of them but single special cases like this skeleton on screenshot that is swinging its sword ultra fast while staying in single place and looking at me rotating but  not moving even single block from his place. When i enter inside him he hits me with his swinging sword but still he won't move.
When i hit him he just accept that and stays waiting patiently for his death. I know skeletons have no brain but he is just like "Hello darkness, my old friend", so sad.

![2018-12-08_13 23 01](https://user-images.githubusercontent.com/45362992/49685900-ca6a7380-faec-11e8-8461-973d0ba3b1f1.png)

**Comment by Freebi85** [comment]
Do you still feel that after the last update the mobs are buggy?

**Comment by arturgaweski** [comment]
Not anymore
