### ISSUE TITLE
Broken Recipe Very Heavy Oxygen Tank

### ISSUE THREAD

**Issue by Cormenthor** [Freebi85/Dungeons-Dragons-Space-Shuttles#291]
The recipe for the very heavy oxygen tank calls for galacticraft palladium ingots specifically with no allowance for being able to only produce only tinkers alloy add on palladium ingots rendering the item un-craftable. This was brought to my attention by GaviGuy which prompted me to check it out.

**Comment by GaviGuy** [comment]
Additional note: the extremely heavy oxygen tank calls for zinc ingots from extra planets, which will most likely lead to the same issue.

**Comment by Freebi85** [comment]
Thank you for Reporting this guys!
Fixed in 5.7 =)
