### ISSUE TITLE
Make Bees worth it

### ISSUE THREAD

**Issue by Minecr4ck** [Freebi85/Dungeons-Dragons-Space-Shuttles#293]
Hello! This pack is freakin awesome! As a pack maker and player, I've been really impressed with what you've done here. To get to my point, I've seen too many packs where bees were just thrown in and not tweaked at all. I feel like this pack has a great opportunity to make the worth all the effort of breeding them. 
I was hoping, if you had the time, that you could make Bees output items(rare ones and/or in larger amounts) to a degree that makes them a very valuable path to go down. 
-It seems harder to get metals and mob drops thru Bees, than Mystical Ag. Maybe Bees could output 2 or 3 times as much as 1 Mystical Ag plant?
-How about rare/specialty Bees that give components and/or liquids like Super Glue or Computer parts or that green slime to make the computer parts?

Thanks for all your hard work!

**Comment by Freebi85** [comment]
Thank you im glad you like it =)
A "Bee Boosting" Update is already planned for 5.8 or 6.0. Can't say for sure.
To give players who love bees an alternative to ore processing and maybe more :P

**Comment by Freebi85** [comment]
Since it is quite difficult to adjust the output of the bees I will completely rework the BeeCombs system. So every single comb will be very useful and create new and interesting outputs. This will also boost ore combs to have an alternative to void ore miners or MA.
