### ISSUE TITLE
Dyeing elevator blocks defaults to an unchangeable grey regardless of dye used.

### ISSUE THREAD

**Issue by Jadeon** [Freebi85/Dungeons-Dragons-Space-Shuttles#294]
As the title states if you dye an elevator block it will become an unchangeable grey color regardless of the dye used.  It appears this is because that particular colored block has been oredict'ed to accept any and all colors.

**Comment by Freebi85** [comment]
This was an oredirct problem in previous version. Maybe 5.5 i dont know exactly.
I just colored several elevators on the latest version and it works fine for me in singleplayer. (except purple one. it's broken in 5.7a and get fixed in a later version)
I'd be glad to have confirmation.

**Comment by Jadeon** [comment]
Will look into this soon.

**Comment by Freebi85** [comment]
Everything should now be fixed on 5.7b. Also the purple one.
