### ISSUE TITLE
industial blast furnace fuel numbers 

### ISSUE THREAD

**Issue by weightmaker** [Freebi85/Dungeons-Dragons-Space-Shuttles#296]
i noticed it wasnt 1:1 with coak coke and iron to make steel. I just assumed the numbers were changed and didnt think much of it but after i've made the industrial blast furnace(IBF) i noticed the burn time of Coal Coke. its burn time in the blast furnace is 1200 ticks while being 3200 in other areas. 

i checked with normal coal and that has 2000 ticks worth of fuel in the IBF. this is the best fuel that i have found. 

you can see these numbers by holding shift over the item while inside the blast furnace

i assume this is a bug. it makes coal coke rather useless, atleast until you get a 
arc furnace but i imagine people will go the agriculture way at that stage. 

![2019-08-28_01 55 56](https://user-images.githubusercontent.com/22963021/63816283-de365e00-c937-11e9-8cd7-6eb72397326f.png)
![2019-08-28_01 55 59](https://user-images.githubusercontent.com/22963021/63816287-e0002180-c937-11e9-940f-13a00a87adc6.png)

**Comment by weightmaker** [comment]
version 5.6a*

**Comment by cyber01** [comment]
I think the value of coal is more because it is more difficult to find and mine in the right quantities than the production of coke coal from virtually nothing (wood)

**Comment by weightmaker** [comment]
Im not sure where you got that information. Thats never been the case afaik.
Coal Coke comes from normal coal. Wood(oak logs) turns into charcoal in the Coke oven

**Comment by cyber01** [comment]
hmm, you right, sorry

**Comment by Freebi85** [comment]
I see the problem.

Coal is not equal to Charcola and too op.
Gonna make this equal to charcoal which is 300 ticktime for a piece of coal and 3000 for a block

Thx for reporting =)
