### ISSUE TITLE
(Guest Suggestion) +Guest line for Galacticraft

### ISSUE THREAD

**Issue by gery29** [Freebi85/Dungeons-Dragons-Space-Shuttles#298]
When you arrived at Tier 4. Questline and you crafting the Tier 1 Rocket you finished all of Guest.
After that the modpack Its little boring because you dont need finishing quests. So if you add +quest line where goals would be like go to the venus then you would know craft the tier 5 Rocket.

(You are doing a very good job)

**Comment by Freebi85** [comment]
Hello =) First of all thank you, im glad you like it to this point in tier 4 :P
I'm aware of where the quest line ends^^
I have already confirmed in Discord that I will consider a Tier 5 quest line as soon as I have more time  for it but thank you for the request =)
