### ISSUE TITLE
Engineer's manual not recognized from Akashic Tome

### ISSUE THREAD

**Issue by LuciousLisa** [Freebi85/Dungeons-Dragons-Space-Shuttles#299]
One of the quests requires an Immersive Engineering engineer's manual. I had made this before it was required and had put it in the Akashic Tome. Once removed from the tome, the questbook did not recognize the manual as being present in my inventory. This is likely an incompatibility issue between mods which cannot be resolved by the modpack creator. However, I'm reporting this so the quest may be tweaked if deemed necessary.

**Comment by Freebi85** [comment]
Hello =)
Thank you for reporting this.
I think i can solve this problem 👍
