### ISSUE TITLE
Suggestion: change setting in animania config

### ISSUE THREAD

**Issue by LuciousLisa** [Freebi85/Dungeons-Dragons-Space-Shuttles#300]
**Problem:** I've lost countless crops and even Botania flowers to passive mobs from Animania feeding on them.  

**Solution:** change the following setting to `false` on line 98 of animania.cfg

```Plant blocks removed after animal eats
B:plantsRemovedAfterEating=true

**Comment by Freebi85** [comment]
I'll think about it^^

**Comment by LuciousLisa** [comment]
For context: I was lucky enough to find a mushroom island close to my spawn, so I decided to go live there in peace (I'm not big on the combat aspect of the game), apart from a dragon that chose to set up its territory in the middle of it. I can deal with the dodos (Primitive Mobs) converting my grass back to mycelium (line 102 in `primitivemobs.cfg` btw, I ended up changing it to false for convenience sake) or the hamsters and mooshrooms eating my regular crops, but when they ate several of my hard earned Botania flowers, I got fed up with it and set it to false. There's no way to stop them from spawning when I move far enough away from my garden area and I can't imagine having to deal with the regular fierce combat with the aggressive mobs in this pack as well as fight passive ones to maintain my progress. I figured I'd let you know about this setting, just in case it was unintended or something.

**Comment by Danekjovax** [comment]
I'd say this should stay enabled, and encourage farmers to simply wall or fence off their gardens full pf precious plants to prevent them from being eaten.

With all respect, LuciousLisa, some solutions should be figured out in-game rather than tweaking yet another configuration option.  :2)  That's what makes MC the magic it is! ;2D

**Comment by Freebi85** [comment]
=)
Thanks again for the suggestion but I decided not to change this config. 
Of course you can change this for yourself at any time - that's no problem.
Freebi
