### ISSUE TITLE
Expensive Plates [Quest] and the recipes

### ISSUE THREAD

**Issue by Mini-kun** [Freebi85/Dungeons-Dragons-Space-Shuttles#301]
I like to report that Expensive plates is Broken after update from version 5.6.a to 5.7a Where i have to get Chrome and titanium Plates and even that recipes is not that true one i add 2 of each Item and the Quest screenshot aswell

[the Quest](https://gyazo.com/0369eab9fe27f361219646096544fd1c)
[the Titan Plate](https://gyazo.com/2043d67363d8501c0d6ad8b850a65b06)
[the Chrome Palte](https://gyazo.com/c983fe0a0d0975a202edf0a5cbda4eb7)

**Comment by Freebi85** [comment]
Feels Bad =( Tech Reborn changed item id's *cry*
Gonny fix that. Thanks for Reporting!

**Comment by Mini-kun** [comment]
yw :3

**Comment by JustinSchieck** [comment]
Wondering if there is an ETA for the next update or if this bug blocks the ability to do galacticraft questing. If not, just wondering if it blocks anything major in the pack

**Comment by Mini-kun** [comment]
There is a discord for this modpack and he say it's going to be 2-4 weeks for next update

**Comment by Freebi85** [comment]
Huh? This bug was solved in latest vetsion of the pack. People need to upodate the questbook after every patch to see all changes^^
