### ISSUE TITLE
Industrial blast furnace 

### ISSUE THREAD

**Issue by birdie1117** [Freebi85/Dungeons-Dragons-Space-Shuttles#303]
Loving the mod!! But since this last update, 5.7b) my industrial blast furnace (tech reborn mod), with advanced machine casings, isn’t getting hot enough to make the tungsten ingots it won’t go over 2380. I broke it down and rebuilt it to see if it would work but still nothing..😥 please help.

Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by Freebi85** [comment]
Hello =)
I't dosent work this way anymore. You need to put 4 Kanthal heating coild and 4 nichrome heatoing coil to the core block (right click on it) it's a new TechReborn mechanic since latest update. The advanced machines casings are still required.

**Comment by birdie1117** [comment]
Ok thank you sorry I should have looked at that....
