### ISSUE TITLE
Quartz duplication trick

### ISSUE THREAD

**Issue by Emblin13** [Freebi85/Dungeons-Dragons-Space-Shuttles#306]
Steps:
1: Put quartz block into sawmill, producing 4 quartz slabs
2: Combine the slabs in a crafting table, producing 2 chiselled quartz block
3: Put the 2 chiselled quartz blocks into pulverizer, producing 8 quartz
4: Craft 2 quartz blocks, and repeat the process
5: ???
6: Profit

**Comment by Danekjovax** [comment]
JEI does report the output of Quartz Slabs as 4 from the sawmill.

Perhaps its possible to adjust the output via config files?

Also, may need to verify sawmill's output of other recipes isn't causing similar duplication issues.
