### ISSUE TITLE
refine storage crafting bug

### ISSUE THREAD

**Issue by Darkspyro911** [Freebi85/Dungeons-Dragons-Space-Shuttles#307]
Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK
where the bug channel?
if you try clicking in the rope recpice form jie into refeinestorage crafting gride it will crash the game
and says disconted
https://cdn.discordapp.com/attachments/538523091589005319/617069768318648321/unknown.png

**Comment by Freebi85** [comment]
Yeah that's a known issue with alle sapling recipes in RefinedStorage. Put it manually when craft things with saplings for now =)

**Comment by Darkspyro911** [comment]
Ok thanks ~Darkspyro911


Sent from Mail for Windows 10

**Comment by Freebi85** [comment]
Doesn't look like it'll ever get fixed in 1.12.2. I'll close here.
