### ISSUE TITLE
Silicon Plates quest broken

### ISSUE THREAD

**Issue by iDarper** [Freebi85/Dungeons-Dragons-Space-Shuttles#309]
Pack Version: 5.7a
Server or SSP: Server

Issue: Silicon Plates quest bugged. https://gyazo.com/5ee58ca3610e530d41b9371f7bf9624d (i've completed the quest previously, but the pic is to show the placeholder)

After updating, the silicon plates task has just a placeholder. No recipe, and no visual of the item required to complete the quest. Players who have just gotten to the quest can't proceed to further quests, cuz the quest is blocking progress in it's current state.

**Comment by Freebi85** [comment]
Plese Refresh your quest database after every update.
Either with the command /bq_admin default load
Or press the update button in Tier 0 (Big icon with the book)
