### ISSUE TITLE
traveling merchants spawning deep underground

### ISSUE THREAD

**Issue by arturgaweski** [Freebi85/Dungeons-Dragons-Space-Shuttles#31]
Not sure if this is intended but shouldn't they wander above underground? No nearby entrances that he could got here

![2018-12-08_15 05 51](https://user-images.githubusercontent.com/45362992/49686846-eb39c580-fafa-11e8-8159-1740650078c5.png)

**Comment by Freebi85** [comment]
Traveling merchants spaws always in the vicinity of players regardless of position. Only the appropriate dimension is decisive.
