### ISSUE TITLE
Custom starting gear doesn't seem to be working

### ISSUE THREAD

**Issue by DEAMONKUN** [Freebi85/Dungeons-Dragons-Space-Shuttles#310]
I seen that people has at the start cooper axe quest book and other stuff but the game just gives me books (Without the quest one).
And the game says that Custom Starting Gear hasn't been configured.
I tried to go into mods and found it but it couldn't be configured at all!

**Comment by Freebi85** [comment]
Tested right now in a few new worlds in latest verison seems to work correctly. Asked also in the community. No problems so far. Maybe corrupted configs or somthing. Just try reinstall the pack.

**Comment by DEAMONKUN** [comment]
Thanks will try ^-^

**Comment by DEAMONKUN** [comment]
Sorry for the stupid question but where should i unzip modpack and were should i put config?(First time  
i have unziped modpack in .minecraft and haven't even touched config.) Sorry...

**Comment by Freebi85** [comment]
Unzip? You need just the twitch launcher to run this pack. So you don‘t have to mess with files and stuff :) Join my tech support discord channel so we can talk better about  this and help you ;D

**Comment by DEAMONKUN** [comment]
Oh sorry for the inconvenience...
