### ISSUE TITLE
Magma crucible has become too slow

### ISSUE THREAD

**Issue by cyber01** [Freebi85/Dungeons-Dragons-Space-Shuttles#312]
After updating to 5.7b (before that it was 5.6a and everything was fine on it), the magma crucible (Thermal Expansion) began to work too slowly. For example: melting Andesite (stoneAndesite) takes about 6 minutes and 20 seconds for one block (10% in about 38 seconds). There is a problem in both single player and on the server and appeared after updating to 5.7b.
Changelog also did not find information about changes in speed

**Comment by Freebi85** [comment]
Weird. Will lookt into it.
There was neither a change on my part nor was there an update for Thermal Expansion.

**Comment by dierke9** [comment]
Iirc the smelting of the stone etc is default thermal expansion.
The speed that it smelts is based on the amount of energy that is needed for the operation, a basic crucible smelts at 20rf/tick
Take alook if the amount of needed rf has changed, if ghat is the case then there is your reason for it being slow.

( Smelting stuff like cobble to lava is very stow to stop people using it together with the lava generator to get infinity energy quite easy)

**Comment by cyber01** [comment]
I thought so too and decided to check. In a single game, I connected the magma crucible with the help of the Creative Energy Cube and maximally improved the Magma Crucible itself (to the resonating one), but the speed did not increase much. Accordingly, this is not the problem. Previously, it took several seconds, but not minutes, to melt one cobblestone block.

**Comment by dierke9** [comment]
Did you check the needed rf? It gets displayed in JEI

**Comment by cyber01** [comment]
Checked, if there was not enough energy, then it would empty the internal storage, but this does not happen. It just feels like the speed was reduced by 10 times. And for work by default, only 20rf / t is required, when I generate in 1.5k rf / t

**Comment by dierke9** [comment]
The machines only use a set amount of rf/t (can be seen in the probe thing or in the info tab at the left of the machine) without caring how much comes in. It only cares about the amount og rf in the internal storage.
However if you say it stays full then it should work at full capacity. So the only logical explanation i can see that or they changed something in the machine or the recipe needs more rf now

**Comment by cyber01** [comment]
I just made a system for generating lava from andesite at 5.6a (it went to arsenic for iridium) and it worked pretty quickly, and after updating to 5.7b the speed dropped sharply

**Comment by Freebi85** [comment]
Tbh i have no clue. It seems to works as intended. Maybe slower than usual. Thermal had no update between 5.6 and 5.7. In the ThermalExpansion discord was also confirmed that it is slow even with 4x augments. But I can't say if this is a mod interaction or not.
I'm afraid there's nothing I can fix myseslf.

**Comment by Freebi85** [comment]
Checked all the recipes. The reason why it requires that long is because any kind of Andesite, Diorite, Granite and Obsidian requires 300k RF per stone to smelt. Which is insane. Regular Vanilla smooth Stone or any kind of Netherrack requires only 30-40k and is much faster. This are Thermal Expansion defalut values and i don't want to override it. 

The Lava Fabricator requires 200k RF per tick for 1000mb Lava without any materials. I would go for that or just use netherrack essences to make tons of it and melt them down :P
