### ISSUE TITLE
Bug or No Bug

### ISSUE THREAD

**Issue by Jacoomis** [Freebi85/Dungeons-Dragons-Space-Shuttles#313]
Is the Wrought helm and wrought axe supposed to be breakable or is that a bug?
They are obtained via the wrought boss and are supposed to be unbreakable but less powerful than iron helm and diamond sword.

**Comment by dierke9** [comment]
They are unbreakable with normal usages.
But there is a mob-effect with the infernal mobs mod, called "Rust", that lowers their durability

**Comment by Freebi85** [comment]
This is correct, and that's fine for me =)
Indestructible is always bad^^ Besides, you can easily defeat this mob to get new ones.
