### ISSUE TITLE
[Mod Suggestion] Immersive Petroleum and Immersive Tech

### ISSUE THREAD

**Issue by nodatahere** [Freebi85/Dungeons-Dragons-Space-Shuttles#314]
In many of my modded sessions, I've deeply enjoyed the features provided by the [Immersive Petroleum](https://www.curseforge.com/minecraft/mc-mods/immersive-petroleum) and [Immersive Tech](https://www.curseforge.com/minecraft/mc-mods/immersive-tech) addons for Immersive Engineering. They add things like multiblock oil refineries, steam generators, and the like which integrate in both function and aesthetic with Immersive engineering.

Links in non-markdown format:
https://www.curseforge.com/minecraft/mc-mods/immersive-petroleum
https://www.curseforge.com/minecraft/mc-mods/immersive-tech

**Comment by Freebi85** [comment]
I have no interest in immersivetech I'm sorry. 

Immersive petroleum is interesting, but has not been maintained for over a year. After a few tests I already had a few issues which annoy me and which will probably never be fixed. 

I'm afraid I have to disappoint you.
