### ISSUE TITLE
Failed to Start

### ISSUE THREAD

**Issue by LazyDrew** [Freebi85/Dungeons-Dragons-Space-Shuttles#315]
While trying to start the Modpack I ran into some problems

[https://gyazo.com/b79ef587199028f56c5142b33b14dcda](url)
and this is the 'link' that comes with it
[https://paste.dimdev.org/etoqofirev.mccrash](url)

I saw on another thread that someone had a problem with an added resource, but this doesn't give me a potential cause for the problem.

If anyone could help, it would be much appreciated.

Thank you,
Lazy

**Comment by Freebi85** [comment]
Hi =)
Crash Report Links dosen't work for me. Did you allocated enough RAM to the tiwitch launcher? This Pack requires 8GB.

**Comment by weightmaker** [comment]
from the crash log he only dedicated 3GB and it was a Out Of Memory exception, so yeah thats the cause

**Comment by Freebi85** [comment]
Thank you @weightmaker 
Now it works for me as well for some reason^^
Definitely out of Memory. Raise your Ram in the launcher =)
