### ISSUE TITLE
Mod Suggestion:  Scannable

### ISSUE THREAD

**Issue by weightmaker** [Freebi85/Dungeons-Dragons-Space-Shuttles#316]
the tinker's Alloying Addon Ores takes forever to find when you need a lot of them. 
This mod can be added as a step between normal mining and automated (f.ex. Void ore miner)

**Comment by dierke9** [comment]
Scannable is a great mod. But i feel like it can be a little overpowered sometimes.

**Comment by weightmaker** [comment]
IMO most mods are overpowered in some way. You still have to dig your way around getting all the ores. it just takes away the RNG of "finding" them. anyway; it can be locked by progression however the pack author wants, IE. Desh/solarium/iron/tungsten/etc.

**Comment by dierke9** [comment]
I do agree with that. But there is no "RNG" in the mining in my eyes. It just depends on how you do your mining. The Scannable mod will change the way of mining from search to direct to destination.
But yea, if it gets added the recipe needs to have some higher stuff

**Comment by Freebi85** [comment]
I took a closer look and decided against it. I'm Sorry. :/
