### ISSUE TITLE
shop cool-downs not working properly

### ISSUE THREAD

**Issue by ngdrex** [Freebi85/Dungeons-Dragons-Space-Shuttles#317]
I'm running the latest version of the pack. After buying a reward from the shop the cool-down never actually stops. It instead goes into negative seconds (and only seconds) never allowing me to buy the reward again...

![Screenshot_77](https://user-images.githubusercontent.com/29693433/64192631-21696300-ce49-11e9-802b-334418db5507.png)
![Screenshot_78](https://user-images.githubusercontent.com/29693433/64192632-21696300-ce49-11e9-92bf-dbb630a05ba3.png)
![Screenshot_79](https://user-images.githubusercontent.com/29693433/64192640-24fcea00-ce49-11e9-8e1d-12f9831f9120.png)

**Comment by dierke9** [comment]
This is a problem with the mod itself

https://github.com/Funwayguy/BetterQuesting/issues/619

**Comment by ngdrex** [comment]
ah thank you
