### ISSUE TITLE
Broken Recipes 5.7b

### ISSUE THREAD

**Issue by Renadarain** [Freebi85/Dungeons-Dragons-Space-Shuttles#318]
![error](https://user-images.githubusercontent.com/3536320/64197665-89866c00-ce7e-11e9-95a9-e1afcf9c71e3.PNG)
Version 5.7b
Quite a few of the Tech Reborn plate recipes are broken or not working server side. They work in single player.

Silicon plate - broken
Chrome plate - broken
Titanium plate - 64 diamonds

Also Tinker's Construct - adding copper and silver to the smeltery doesn't mix to make brass.

These are what we've found so far.

Kind regards,
Renada

**Comment by Freebi85** [comment]
Hello =)
If singleplayer works correctly then your serverfiles are broken or your admin removed mods from the serverpack; or the server wasn't updated correctly to latest version 5.7.b

If you need more Server Support pls join our Tech Support Helpdesk in my Discord Server. 
But i would first talk to your admin or reinstall latest pack version if this is your own server.

Discord Server Link: https://discord.gg/eUajYmK

**Comment by Renadarain** [comment]
Thank you, reinstalling fixed the problem. :)
