### ISSUE TITLE
Team Permissions to not apply to doors

### ISSUE THREAD

**Issue by c0nnex** [Freebi85/Dungeons-Dragons-Space-Shuttles#319]
Multiplayer-Server , several Teams
Doors can be opened by anyone, even if the area is claimed and set to Ally Only.

Works fine with other modpacks

**Comment by Freebi85** [comment]
Hi =)
Please  join our discord helpdsek for serverside problems .
There is neither an official server nor are smp problems supported at all. In #server-support-unofficial are many players with a lot of experience in server setups who have been able to help =)

Discord Server Link: https://discord.gg/eUajYmK
