### ISSUE TITLE
Reward bug

### ISSUE THREAD

**Issue by NeverSalty** [Freebi85/Dungeons-Dragons-Space-Shuttles#32]
Hey, I can't claim some quests

Hey, ich kann manche Quests nicht claimen 
![2018-12-08_20 06 08](https://user-images.githubusercontent.com/39171025/49689673-bfcbd080-fb24-11e8-80fa-c8a29ef630c4.png)
![2018-12-08_20 06 12](https://user-images.githubusercontent.com/39171025/49689674-bfcbd080-fb24-11e8-8af0-fea52f153b31.png)

**Comment by NeverSalty** [comment]
Ok vergiss es ich bin unfähig xD

**Comment by Freebi85** [comment]
xD

**Comment by Freebi85** [comment]
Dann schliesse ich mal wieder^^
