### ISSUE TITLE
Linux Server - Server Start Script

### ISSUE THREAD

**Issue by phrostbit** [Freebi85/Dungeons-Dragons-Space-Shuttles#320]
The server files only have a server start script for Windows. Can one for Linux be added as well?

**Comment by cyber01** [comment]
Change .bat to .sh and run :) Scripts same

**Comment by phrostbit** [comment]
Linux doesn't use batch scripting elements like pause

**Comment by cyber01** [comment]
remove pause

**Comment by phrostbit** [comment]
Does the below need to be added?

#!/bin/bash or #!/bin/sh

**Comment by cyber01** [comment]
not necessary. In my start.sh, only the java -XmX and other

**Comment by phrostbit** [comment]
Cool, thanks. Is there a recommended version of Java for this?

**Comment by cyber01** [comment]
I use latest java 8
