### ISSUE TITLE
No wither skeletons spawning after updating to 5.7b

### ISSUE THREAD

**Issue by vaptsiukas** [Freebi85/Dungeons-Dragons-Space-Shuttles#321]
After updating to 5.7b I am unable to find any wither skeletons in the nether fortress. Only those blazing Jugernauts and burning dogs are spawning. Light level is low, no new light sources added. Before update I had plenty of skeletons in the same fortress spawning. Difficulty level - normal.

**Comment by Freebi85** [comment]
Cant't find any issues so far. Asked also 2 players on latest update in the community. Yes they are rare but should be still there. Maybe try with recreating the nether (deleting)

**Comment by vaptsiukas** [comment]
Recreating Nether dimension helped. Thanks!

**Comment by Freebi85** [comment]
Nice!
