### ISSUE TITLE
Mojang screen not loading after update

### ISSUE THREAD

**Issue by jobaq007** [Freebi85/Dungeons-Dragons-Space-Shuttles#322]
Hello
After the update to version 5.7b , i try launching the game the initial screen came up, so i click launch.
After that nothing happened. i tried several times and i was working perfectly fine before. i left it running and came the next day it was finally inside but it is not normal.
i am trying to figure it out what the issue is, i have plenty of RAM  and speed and FPS has been very optimal.
it is currently using forge-14.23.5.2836. i will try reverting to 5.7 but well see

Thank you guys

Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by Freebi85** [comment]
Hello =)
That's currently a twitch problem when updating packs on this launcher.
Try to Re-Install the pack to a new Profile that should fix the Issue. Don't forget to move your saves folder and options.txt to the new instance^^

Pls join our Tech Support Channel in my Discord Server if you need more Help about this =)
Discord Server Link: https://discord.gg/eUajYmK
