### ISSUE TITLE
Galacticraft raw silicon

### ISSUE THREAD

**Issue by Cormenthor** [Freebi85/Dungeons-Dragons-Space-Shuttles#326]
Galacticraft raw silicon, available by default from the asteroids, is required for the solar array wafers with in the same mod. Has this been disabled? I am not having any luck so far finding it in the asteroids.

**Comment by Freebi85** [comment]
Thanks for reporting.
Will look into it. Usually it should be possible with every silicon. Probably a oredict problem.

**Comment by Freebi85** [comment]
Ah i see the problem. Galacticraft Solar Arrays should be all disabled by default in this pack. It still shows up in JEI and have to remove them.
