### ISSUE TITLE
Kitchen Workshop: Hot Dog crafting - using wrong amount of Olive Oil

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#327]
When crafting Hot Dogs from the Kitchen Workbench, the crafting recipe is using 550mb of olive oil, where JEI reports that you only need 250mb.

JEI listing:
![2019-09-09_18 32 15](https://user-images.githubusercontent.com/10191173/64571059-93054d80-d330-11e9-87f2-0107f5df70e6.png)

Olive oil after crafting a hot dog with 1,000 mbs of oil in Workshop:
![2019-09-09_18 32 18](https://user-images.githubusercontent.com/10191173/64571061-9698d480-d330-11e9-8d2c-f2fa76a32b54.png)

**Comment by Freebi85** [comment]
Hi =)
Are you sure you're not confusing the two things? Because according to my script it takes 250mb Cooking Oil or 550mb Olive Oil. 
You have both variants in your screenshots^^
(All recipes that need oil have 2 variants)

**Comment by Danekjovax** [comment]
I see that it's not a good idea to post images when I'm half asleep.  I'll go back and recheck my images and get back with you if I still see the discrepancy.  if not, I'll ask to close ticket.  Sorry for the confusion.

**Comment by Danekjovax** [comment]
Ok, I went back into my test world and confirmed that 550mbs of olive oil is the requirement for this recipe.

Please disregard this ticket.  My apologies.  I'll make sure I'm at least 90% more awake when I post my next one. ;2)
