### ISSUE TITLE
[Mod Suggestion] Donk Storage

### ISSUE THREAD

**Issue by SynexWolf** [Freebi85/Dungeons-Dragons-Space-Shuttles#328]
I believe dank null was removed from the pack due to the mod being removed from curseforge, is it possible to add in the replacement, donk storage? It functions the same as a dank null and would be really useful for a pack like this one.

**Comment by Freebi85** [comment]
Hi =)
Thanks for your suggestion but as soon as danknull is fixed, I will insert it again. This will be ready soon.
