### ISSUE TITLE
Lag on server

### ISSUE THREAD

**Issue by Renadarain** [Freebi85/Dungeons-Dragons-Space-Shuttles#330]
Hello :)

We're experiencing quite a lot of lag on an 8 gig server and wondered if you could suggest any mods that we could remove from the pack without impacting on the questline as we're really enjoying that.

Kind regards,
Renada

**Comment by Freebi85** [comment]
Hello =)

Tbh there is not much you can remove from the pack beside clientside mods like Journeymap or Discordcraft. Most mods are linked to each other and will break the pack when removed im sorry :/
The most important thing besides RAM is the CPU bc it has to handle a lot of entitiys.

I suggest to join our Discord Server (innofficial Server support channel) there are many players with a lot of experience in server setups who have been able to help others :)
