### ISSUE TITLE
infinite grottols with a silk touch tinker pickaxe

### ISSUE THREAD

**Issue by eggyplantsu** [Freebi85/Dungeons-Dragons-Space-Shuttles#334]
Find grottol.
Hit grottol with silky TiCO pickaxe
Obtain two captured grottols.
Those two grottols can be placed down and the process repeats.
Then you can whack the excess grottols with a normal iron or higher pickaxe for diamonds.
Very broken profit.

**Comment by Danekjovax** [comment]
https://github.com/BobMowzie/MowziesMobs/issues/163
