### ISSUE TITLE
Mekanism Restrictive and Diversion Transporter have the same carpenter recipe

### ISSUE THREAD

**Issue by jinks** [Freebi85/Dungeons-Dragons-Space-Shuttles#337]
The two pipes transporter pipes have the exact same recipes in the carpenter, so obviously only one of them can be made.

The EW recipe adds compressed redstone to one of them, I guess the carpenter should do the same?

**Comment by Freebi85** [comment]
Hello =)
Thank you for reporting this! Fixed in next Update.
