### ISSUE TITLE
Tick Profiler not working on DDSS

### ISSUE THREAD

**Issue by 123Kappa** [Freebi85/Dungeons-Dragons-Space-Shuttles#338]
Hello! I installed Tick Profiler to check what's lagging my server and it doesnt work. 
I get empty profile report like this https://imgur.com/a/LVMbeu0

It's probably a mod conflict and I am asking here because maybe this has been reported before.
Or maybe you know which mod could be conflicting.
There are no errors.

I have server for a lot of modpacks and I don't have this issue

**Comment by Freebi85** [comment]
Sorry Serverside Problems are not supported here. 

Join our Discord Helpdesk in the server support area =)

https://discord.gg/eUajYmK
