### ISSUE TITLE
Erebus Dimension freeze 

### ISSUE THREAD

**Issue by ferrium42** [Freebi85/Dungeons-Dragons-Space-Shuttles#34]
It take me a few newstarts to see the dimension and then again nothing.  (twillight works)
another suggestion your modpack miss a backup system - i added for my pack aroma backup
here the crashreport
[crash-2018-12-10_10.15.16-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/2662499/crash-2018-12-10_10.15.16-server.txt)

**Comment by Freebi85** [comment]
Ok seems to be a little more complicated this time. I have reported it directly to Erebus. let's wait and see

**Comment by Freebi85** [comment]
Mod deleted.
