### ISSUE TITLE
Industrial Blast Furnace Quest Recognition Issue

### ISSUE THREAD

**Issue by Chocolate0118** [Freebi85/Dungeons-Dragons-Space-Shuttles#340]
I have the Industrial Blast Furnace in hand, and have tried clicking the Detect/Submit button multiple times, and it is not recognizing it. 

Some points to note are that I crafted the furnace before the quest was available, and used it multiple times while inputting in some speed upgrades. I do not believe this should have effected recognition however?

**Comment by cyber01** [comment]
When you apply improvements to a block, its metadata changes, most likely it happened in your case, and because of this, it does not "see" your furnace

**Comment by Chocolate0118** [comment]
What would you recommend I do? I really don't want to recraft such an expensive and time-consuming recipe. Is there a way to set the metadata changes to default through a recipe or such?

**Comment by cyber01** [comment]
As an option - take it from the creative so that the quest counts. For some machines, putting them in a workbench helps

**Comment by Chocolate0118** [comment]
I have disabled creative in my world as I have no self control and I would cheat if I did. Don't ask. Will try the workbench stuff tomorrow and tell you how it goes, but not sure what you mean. Do you mean a crafting table or a machine?

**Comment by cyber01** [comment]
crafting table. I would advise you to wait for Freebie, maybe this can be changed in the quest book or it will offer a more convenient solution

**Comment by Freebi85** [comment]
Hey =) Yes it's probably a Metdata Issue. Gonna fix this for next update but next update will take a while do to many new things. If you don't want to wait, open to Lan and enable cheats, so you can use cheats in your singleplayer world.

**Comment by Chocolate0118** [comment]
Thanks, did not know about the LAN thing, though I am nervous I will cheat again with this newfound knowledge. I guess it will work as an exercise of self-control. Love your pack, cheers.
