### ISSUE TITLE
crash during startup of the pack

### ISSUE THREAD

**Issue by saberslay** [Freebi85/Dungeons-Dragons-Space-Shuttles#341]
DD&SS version: 5.7b
Forge: 14.23.5.2836
Pressed "play" on Twitch launcher after downloading and got this screen near the end of mod loading 6/7 on the load screen:
![Cap](https://user-images.githubusercontent.com/4098559/65042671-3c5fcb00-d951-11e9-9067-e2071cd96583.PNG)
hear is the crash report 
(Allocated: 4352 MB) https://paste.dimdev.org/saxodigajo.mccrash
(Allocated: 5120 MB) https://paste.dimdev.org/udivigidiq.mccrash

**Comment by cyber01** [comment]
Don`t use issues for crash reports!

You need allocate **minimum** 6gb of RAM

**Comment by saberslay** [comment]
ok will close
