### ISSUE TITLE
Mystical Agriculture Coal does not work in a Blast Furnace

### ISSUE THREAD

**Issue by TheGamingGeneral** [Freebi85/Dungeons-Dragons-Space-Shuttles#342]
Currently trying with inferium coal and it does not work. Is this intended? In my opinion it is solid fuel similar to coal so it should work?

**Comment by Freebi85** [comment]
Well it's a primitive Blast Furnace^^ Not an issue at all. I'll consider integrating inferium coal. maybe :-P

**Comment by Freebi85** [comment]
Okay, you convinced me. At least for inferium. Coal Coke will be still better =)

**Comment by TheGamingGeneral** [comment]
Awesome thanks :)
