### ISSUE TITLE
Astral Sorcery requires you to craft the Luminious Crafting Table in multiplayer.

### ISSUE THREAD

**Issue by Renari** [Freebi85/Dungeons-Dragons-Space-Shuttles#343]
Players will be locked out of crafting items from Astral unless they craft a Luminous Crafting Table, this is pretty annoying since it's unlikely that you are going to need multiple of them.

**Comment by Freebi85** [comment]
Hello =)
This is gated behind a progression system from astral sorcery itself and has nothing to do with my modpack. Every player needs to craft their own table, wand and so on to unlock the stuff in the personal astral tome. Your welcome to make suggestions to the mod author.

**Comment by Renari** [comment]
Thanks, but you could add a note in the book about this and provide a simple recipe to dupe the tables to circumvent this, this issue took us a couple of hours to find out why I could craft all the Astral things but no one else could.
