### ISSUE TITLE
Download Problems

### ISSUE THREAD

**Issue by NesakysiuLT** [Freebi85/Dungeons-Dragons-Space-Shuttles#344]
This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 225635
Object reference not set to an instance of an object.
Failed to get mod loader from manifest!

Got tohouse three everytime i try instal modpack from Twitch

**Comment by TheGamingGeneral** [comment]
Looked up that error and got this: https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/16

Restart the twitch app (if you did not know; click on the little upwards arrow at the bottom right of your screen and click exit twitch to properly restart), and try installing again. To be clear this is a twitch app issue not a DDSS issue.
