### ISSUE TITLE
Ore Dictonary suggestion with Underground Biomes Ores and Silktouch Tools

### ISSUE THREAD

**Issue by Arcanien** [Freebi85/Dungeons-Dragons-Space-Shuttles#345]
So first off, I am LOVING this modpack. So thank you very much for making something that includes a little bit of everything in it that I like. 

So to business. Due to the amount of Modpacks that I've played, I like to try and be as efficient with getting ores of any kind. Since this mod pack requires an extraordinary amount of Coal, I like to Silktouch my Coal Ores so I can put them into the Mechanical Squeezer from _Integrated Dynamics_ to get a guaranteed 6 coal out of the ore, instead of MAYBE 3 or 4 with Fortune 3. Now the problem I'm running into is mining a Coal ore with Silktouch on the tool with the _Underground Biomes_. When I mine a coal ore that isn't stone, I get for an example an "Andesite Coal Ore" instead. Which the Mechanical squeezer will not take. I have to either cheat getting the vanilla coal directly and throw away the "Andesite Coal Ore" as if in exchange. Or I go into the Twilight Forest and have to mine the Coal from there since all the blocks are still stone. 

I have the same issue with Redstone and Lapis ores. I'm mainly pointing out these three Ore's because the Mechanical Squeezer is the most efficient machine to use to get the most out of those three ores. 

For the suggestion is if it is possible to implement the custom ore provided by _Underground Biomes_ to be equivalent to vanilla as an "Ore dictionary" ore. If it is not since I understand ore dictionarying ANYTHING is an absolute pain. Then I thought of another idea of using how you can use a chisel from _Artisan Tools_ to convert custom cobblestones to vanilla cobblestones, but do it with custom ores from _Underground Biomes_.

**Comment by Danekjovax** [comment]
Good point.  If it's possible, please add the UB equivalent of ores in squeezer processing via OreDict.

**Comment by Freebi85** [comment]
Ther ores are already oredicted. This is more a mod incompatibility, or just missing mod interactions problem.
Adding every single siltouched underground biomes ore to additional machines is beyond my possibilities at the moment. If other silktocuhed UB ores work as intended for you, I would write directly to UB devs for additional integrations of the missing ones.

If they for whatever reason don't want to do this, I can do it myself for DD&SS. In the distant future. 👍
