### ISSUE TITLE
Alchemistry Mineral Salt missing ore dict entries

### ISSUE THREAD

**Issue by Dashinator** [Freebi85/Dungeons-Dragons-Space-Shuttles#346]
I recently noticed a slight difference between the different salts in the pack. 
While Mekansim salt has 3: itemSalt, dustSalt and foodSalt. The alchemistry Mineral Salt only has 1: foodSalt. 
This results in that some food can not be made with Mineral Salt. In my case, that was Tater Tots. it only has a recipe that uses itemSalt. Meanwhile other recipes, for example Yorkshire Pudding has 2 different recipes, one that uses foodSalt, and one that uses itemSalt. Which results in one recipe using both Mineral Salt and Mekanism salt. And one recipe using only Mekanism salt. 

some screenshots to clearify my words

![afbeelding](https://user-images.githubusercontent.com/6791637/65165084-5c20ed00-da3e-11e9-9e25-740d03e01301.png)
![afbeelding](https://user-images.githubusercontent.com/6791637/65165117-6a6f0900-da3e-11e9-954d-734fb068e87f.png)

**Comment by Freebi85** [comment]
Thanks for Reporting. Shouldn't be a problem to make both types compatible for everything.

**Comment by Freebi85** [comment]
Alright, i will remove the mineral salt and replace it with mekanism salt. If you have some mineral salt lying around you can easy convert them after the patch by putting it into a crafting grid.
