### ISSUE TITLE
Elemental Tinker attribute not working on Underground biome Gravel types.

### ISSUE THREAD

**Issue by ZeikosZ** [Freebi85/Dungeons-Dragons-Space-Shuttles#347]
The "Elemental" attribute (obtained from using Certus Quartz parts)  from tinkers should break all vertically connected gravity blocks, but this seems to function only on Sand, Red Sand, and Gravel, all the other kinds of Gravel added by Underground biomes aren't affected.

**Comment by Freebi85** [comment]
Hello =)
Thanks for reporting but this is a mod related issue between Tinkers Construct and Underground Biomes. There is nothing i can do against it. And I don't want to keep an issue open that probably never gets fixed because of low prio. Pls report it to the authors^^
