### ISSUE TITLE
Constant random crashing

### ISSUE THREAD

**Issue by ihaxall** [Freebi85/Dungeons-Dragons-Space-Shuttles#350]
Mod pack is constantly crashing at random intervals. I don't seem to be getting any actual crash reports. I can play for 5 hours fine, then crash twice in 30 minutes. Any other logs that I can upload?
i7-8700k 16gb ram 1070TI for computer and I allocated 8gb for Minecraft through twitch launcher.

**Comment by Freebi85** [comment]
Pls join our tech support channel in discord and try to get some reports and logs from your crash and logs folder or at least from your next one. It's pretty impossible to help without further informations.
Discord Server Link: https://discord.gg/eUajYmK
