### ISSUE TITLE
Recipe bugs

### ISSUE THREAD

**Issue by dcoolArne** [Freebi85/Dungeons-Dragons-Space-Shuttles#351]
Empty recipe in Pulverizer, and all ovium smeltery recipes are listed twice.
![2019-09-25_19 16 10](https://user-images.githubusercontent.com/39049038/65624135-84be5f00-dfc9-11e9-9576-6e85036f1773.png)
![2019-09-25_19 17 53](https://user-images.githubusercontent.com/39049038/65624136-84be5f00-dfc9-11e9-9332-1ac5a60ff180.png)

**Comment by Freebi85** [comment]
Thank you for reporting =)
I'm afraid there's nothing I can do about the empty recipes in the pulverizer. 
As for the ovium, I have to check. sometimes it's just a strange JEI bug. if it's duplicated, I can remove it.

**Comment by Danekjovax** [comment]
If you look carefully in image two, the difference is the fuels involved in smelting.  Not a dupe recipe.

**Comment by Freebi85** [comment]
Yesh it looks like it just scroll thorugh the various fuels^^ Thx for the hint. 
And i can't sadly remove tose "empty" recipes from the sawmill im sry.
