### ISSUE TITLE
Zoesteria Biomes Sulfur ore

### ISSUE THREAD

**Issue by Maikar23** [Freebi85/Dungeons-Dragons-Space-Shuttles#353]
The Sulfur Ore from Zoesteria Biomes makes a Zoesteria Biomes sulfur when you break the ore, but when you search sulfur in JEI only the sulfur from Thermal Foundations shows up.

**Comment by Freebi85** [comment]
Hello =)
This is correct because the sulfur ore in JEi was unified. But it dose't matter because you should be able to use the Zoesteria sulfur for everything else as well. Let me know if not^^
I talk to the author, maybe he can make it compatible to unify when other mods installed.
