### ISSUE TITLE
Spinout causing a ticking entity crash

### ISSUE THREAD

**Issue by UltimateN1NJ4** [Freebi85/Dungeons-Dragons-Space-Shuttles#354]
[crash-2019-09-25_20.40.29-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/3658620/crash-2019-09-25_20.40.29-server.txt)
Playing the game as normal, crashed the world. The log suggests it is a spinout causing the problem.
I've had these issues with packs before and the solution is usually to disable the mob but just wanted to check that this is the best way to go about fixing it(i don't want to break any recipes or anything).

**Comment by Freebi85** [comment]
Hello =)
Befor removing somthing; you're plaing on a outdated Java version. The twitch launcher use this old version by default. If you are using tiwtch, you have to switch to "JAR" settings to can use latest java version on your PC. Or you need another launcher like MultiMC. If you need more help with this join our Discord Server in the Tech support area =)
Freebi
