### ISSUE TITLE
Fresh Milk/Bucket of Milk - Possible Infinite milk?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#355]
Freebi,

The new fresh milk-bucket of milk recipe may allow infinite milk, though at a cost of an empty container.  Is this intended?

Screenshots attached.

![2019-09-27_19 11 01](https://user-images.githubusercontent.com/10191173/65807149-15787480-e15b-11e9-8f88-4b7c50721e52.png)
![2019-09-27_19 11 13](https://user-images.githubusercontent.com/10191173/65807151-17423800-e15b-11e9-991b-df102fde0292.png)

**Comment by Freebi85** [comment]
oh 3 milk with pot i see^^
Thank you
