### ISSUE TITLE
Status Effects that Don't Go Away?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#356]
Testing 6.0 and getting this a couple of times:

Had these debuffs hit me mysteriously (was being attacked by a few Animania Chickens during that time), but these debuffs never went away, even after 5-7 minutes after I noticed them.
![2019-09-27_20 19 23](https://user-images.githubusercontent.com/10191173/65809370-c20e2280-e16a-11e9-83a8-3ad7dc6d87f0.png)

This one more recently at least 5 minutes, but not going away either.
![2019-09-27_21 04 47](https://user-images.githubusercontent.com/10191173/65809372-c33f4f80-e16a-11e9-883c-7dcbe458bf0c.png)

In both cases, I was suffering the effects of these debuffs, and simply relogging "fixed" the status effects, but I don't know if they'll come back at random in future sessions.

**Comment by Freebi85** [comment]
Hm tried with differrent effects like poison and slowness and didn't noticed this issue. Maybe caused by large server ticks? Or some weird sponge interactions?

**Comment by merphle** [comment]
I noticed this in 5.7b last night on a multiplayer server. I ended up with Poison I displaying in my ui with 0:00 duration for a long time, but it wasn't actually affecting me in any way. Relogging cleared it.

**Comment by weightmaker** [comment]
first thought was Nuclearcraft Radiation but that seems to be disabled by default in the pack, so unless they enabled that, then thats not the cause

**Comment by cosmosgenius** [comment]
This may be related...i had mowzies mobs mask which gives me speed buff. Once i tried activating DungeonTactics Diamond ring with speed 2. The speed 2 stayed there until even after deactivating ring. The speed 2 buff only went away once i removed the mask.

**Comment by Danekjovax** [comment]
Since I opened this issue, I realized that the server I was playing on is suffering strange lag-related issues that this may be a side-effect of.  So until we address the other lag issues on the server, I'll hold off this issue until then.

Closing for now.
