### ISSUE TITLE
"Framed" Storage drawers void items on breaking

### ISSUE THREAD

**Issue by Maikar23** [Freebi85/Dungeons-Dragons-Space-Shuttles#358]
The update said that drawers don't lose their items when broken now. On testing this when you break one it drops 1 of what ever item was in it and voids the rest. When the drawer is put back down it is empty.

**Comment by Freebi85** [comment]
Hey =)
Testet with vanilla and tinkers axes and with my bare hands. Everything was fine. Maybe some kind of modded items? You have to be more specific with what and which item exactly. and whether singleplayer or server. and to post it also on Storage Drawers Github pls.

**Comment by Maikar23** [comment]
We are using framed storage drawers and on a server.  I was using a tinkers mattok

**Comment by Freebi85** [comment]
Can you post it here so the devs can fix it =)
https://github.com/jaquadro/StorageDrawers/issues

**Comment by LordHellscream** [comment]
i had this happened to me many times. But i was on a single player world so i just went into creative mod and gave the items back since i lost them due to glitches.

**Comment by Freebi85** [comment]
Was fixed. 👍
