### ISSUE TITLE
Torchmaster - Dreadlamp does not hinder Animania horses to spawn

### ISSUE THREAD

**Issue by Kolerath** [Freebi85/Dungeons-Dragons-Space-Shuttles#359]
Hello Freebi,

I noted in version 6.0a that Animania Horses spawns in a slightly high rate on my server and the dreadlamp does not prevent their spawn in this version. 

I've tried placing multiple dreadlamps without any affect other than other passive mobs.

/Kolerath

**Comment by Kolerath** [comment]
Update: They are literally spawning anywhere :)

**Comment by Freebi85** [comment]
That's exactly what animania wanted to do better in the new update lol.... I will see if i can add them manually to the config.

**Comment by Kolerath** [comment]
Hehe thanks, its kinda comical to walk around my base and finding horses left and right in spots I couldn't imagine, and my server keep responding sometimes that raw horses can't be processed in the smeltery due to reasons (Horses spawning inside the smeltery).

Thanks for the quick followup, still loving the pack!

**Comment by Kolerath** [comment]
Just a quick update, seems like I can replicate this on a singleplayer world using a superflat world type that should only be plains and finding the sweetspot for horse spawn, seems like horses only spawns on certain sweetspots in the plains biome after the 6.0 version.

**Comment by Freebi85** [comment]
Sad. Since adding manually entries into configs dosen’t work we shoul move the issue to animania. I think it worked before their update.

**Comment by Kolerath** [comment]
NP, I'll put up a post with the Animania Github and come back with the issue id.

**Comment by Kolerath** [comment]
https://github.com/capnkirok/animaniamod/issues/361
