### ISSUE TITLE
Quest Smeltery #2 is calling for Air and not Grout 

### ISSUE THREAD

**Issue by InitalHero** [Freebi85/Dungeons-Dragons-Space-Shuttles#361]
- Any problems with quests (description, spelling mistakes, task not recognized etc.)

![image](https://user-images.githubusercontent.com/32253760/65821258-d3057500-e1f8-11e9-8b2f-1e78d022d4e7.png)

**Comment by Matikari** [comment]
I too also have this issue.

**Comment by Matikari** [comment]
After enabling my cheats to edit the quest so that I can progress, the following quest also calls for air blocks rather than seared bricks.

**Comment by Freebi85** [comment]
I apologize. there are 2 quests with this bug after latest update for some reason. you can solve it with bq_admin complete 252 and bq_admin complete 253 until next fix.

**Comment by InitalHero** [comment]
No worries, just wanted to make sure you were aware. Thanks for your quick reply

**Comment by Freebi85** [comment]
Solved in 6.1
