### ISSUE TITLE
Tech Reborn Blast Furnace heat info

### ISSUE THREAD

**Issue by weightmaker** [Freebi85/Dungeons-Dragons-Space-Shuttles#362]
> https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/303#issuecomment-526686545

this info should be available atleast in the quests. 

I had this problem where only the top lava source counted as heat so i couldnt get heat high enough for tungstensteel so i started to look for issues explaining this until i found your comment in the closed thread. 
i made the Tech Reborn manual which just leads to the wiki (browser) and even that doesnt have this info.

**Comment by weightmaker** [comment]
this is a link to the Tech Reborn Wiki:

[https://wiki.techreborn.ovh/doku.php?id=blocks:blast_furnace](url)

**Comment by Freebi85** [comment]
Hi =)
i added addiotional quests for this in Version 6.0b =) A Questbook update is required as well.
cheers

**Comment by weightmaker** [comment]
ah i should have looked if there was a newer version to the pack, lol. my bad.
