### ISSUE TITLE
Cryotheum Dust Carpenter recipe 

### ISSUE THREAD

**Issue by weightmaker** [Freebi85/Dungeons-Dragons-Space-Shuttles#363]
current version: 6.0b
since the Chemical Compound is acceptable in the "top" slot or whatever its called, any automated way of inputting the items into the carpenter will place it there and prevent the carpenter from crafting. 
i have tried every side just in case it was sidedness. 

as a fix you could change the recipe so the chem. compound goes in that slot instead. 

![2019-09-29_04 33 35](https://user-images.githubusercontent.com/22963021/65825130-72674e00-e273-11e9-9831-d458e8fdc89e.png)
this is what happens when you try to imput the ingredients from a hopper and/or crafter. 

![2019-09-29_04 35 04](https://user-images.githubusercontent.com/22963021/65825135-93c83a00-e273-11e9-92ce-b5e88954597a.png)
this is the recipe
![2019-09-29_04 41 28](https://user-images.githubusercontent.com/22963021/65825136-99258480-e273-11e9-9828-a02c516f32f5.png)
an example of the other recipes that uses the chemical compound in the slot i mentioned earlier

**Comment by Freebi85** [comment]
Shouldn’t be a problem :)

**Comment by Freebi85** [comment]
Solved in 6.1
