### ISSUE TITLE
Cranberry can't be juiced

### ISSUE THREAD

**Issue by qchronod** [Freebi85/Dungeons-Dragons-Space-Shuttles#365]
I've been filling out all the varieties of materials in the kitchen and discovered that the Fruit Press doesn't output any fluid from cranberries. JEI shows that it should create 8mb per, but pressing 20 of them gave 0 fluid.
All the other fruits in the press work fine, so I'd guess there is probably a typo somewhere.

DDSS v6.0b

**Comment by Freebi85** [comment]
Hello =)
Sadly it's not possible to tweak and change recipes in "Binnis Extra Trees" machines and the Fruit Press is one of them. This has to be done from the mod authors itself. 

Feel free to post on their GitHub =)
https://github.com/ForestryMC/Binnie/issues
