### ISSUE TITLE
Discord Link not working

### ISSUE THREAD

**Issue by calebjway** [Freebi85/Dungeons-Dragons-Space-Shuttles#366]
Your discord link tries to bring me to a channel in a server but as I am not apart of the server it does not take me anywhere. The link should probably be a server invite link that never expires.

On that note could you please post the discord link. I had a question about altering max mobs spawned in but its not really an issue that needs to be developed.

**Comment by Freebi85** [comment]
Hi =)
This is the official Discorf Link
Discord Server Link: https://discord.gg/eUajYmK 
if it dosen't work try this one: https://discord.gg/Hc2hepg
