### ISSUE TITLE
Indistrual Blast Furnace

### ISSUE THREAD

**Issue by mauvim** [Freebi85/Dungeons-Dragons-Space-Shuttles#367]
![image](https://user-images.githubusercontent.com/36859900/65923907-009d1a80-e3c1-11e9-9d56-ef63f6130ded.png)
![image](https://user-images.githubusercontent.com/36859900/65923954-1d395280-e3c1-11e9-9f63-88e66a039a7a.png)

My quest objective to create a Industrial blast furnace dont detect that my furnace is already made. Dont work by clicking in detect/submit neither by changind the furnace to another slot or droping and picking up.

**Comment by Freebi85** [comment]
Hi =)
Update to latest Version of the pack. It was fixed in 6.0b. Of course you need to refresh your quetbook as well.

**Comment by mauvim** [comment]
Ty Freebi, Great mood pack btw!
