### ISSUE TITLE
Inscriber not enabled on newest version (6.0b)

### ISSUE THREAD

**Issue by Debonairesnake6** [Freebi85/Dungeons-Dragons-Space-Shuttles#368]
In the patch notes it is written:
-Enabled AE2 Inscriber to can use Inscriber name Press for recipes with more then >9 items [more uses to come]

However the inscriber is not available in JEI. In the AE2.zs script the line is written:
mods.jei.JEI.removeAndHide(<appliedenergistics2:inscriber>);

But it is never re-enabled later with a custom recipe.

The only changes I have made regarding AE2 in the pack have been disabling channels and the custom controller recipe, however these should not be causing the inscriber to not show up.

**Comment by Freebi85** [comment]
Just startet up my game on latest version. The inscriber is regularly in JEI and craftable ¯\_(ツ)_/¯
-Checked my uploaded files on Curse: Inscriber is not disabled
You have outdated scripts im sry.
