### ISSUE TITLE
Can't turn the quest fhat requires 204 Grout

### ISSUE THREAD

**Issue by JordanGalbas** [Freebi85/Dungeons-Dragons-Space-Shuttles#369]
![2019-10-01_21 22 54](https://user-images.githubusercontent.com/38844879/66011581-addf6380-e491-11e9-8994-40f52242cd91.png)

I do have all 204 grout

**Comment by Freebi85** [comment]
Was fixed in 6.1
Pls use the searchbar befor posting issues^^
https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/361
