### ISSUE TITLE
Smeltery #2 Quest not working

### ISSUE THREAD

**Issue by mebert02** [Freebi85/Dungeons-Dragons-Space-Shuttles#372]
Version 6.1.
In the Ores, Alloys & Smeltery [Tier 1] quest line. The Smeltery #2 quest has a requirement of 204 Air. The text says it needs 204 Grout but it is not detecting it in the inventory.
![Capture](https://user-images.githubusercontent.com/12300647/66090823-a3cd6b80-e54a-11e9-88f9-088f1ab4b6b0.PNG)

**Comment by Freebi85** [comment]
Hi =) was fixed in 6.1 Refresh your questbook with bq_admin default load if you dont have an update button on the top right corner when opening the questbook. Pls search next time for solved or similiar issues befor posting something.
