### ISSUE TITLE
Artisan's Tables don't give items back for vanilla crafting recipes

### ISSUE THREAD

**Issue by Spikey5** [Freebi85/Dungeons-Dragons-Space-Shuttles#373]
When crafting a vanilla crafting (3x3 crafting table) recipe on an Artisan's table such as the Blacksmiths or Kitchen workshop, items such as buckets and items with durability (such as Artisan's Tools) are consumed.

Tested with: 
Empty Cell recipe on Blacksmiths Workshop, Hammer was consumed instead of damaged.
Dough recipe using water bucket in Kitchen Workshop, Buckets were consumed instead of emptied.

I couldn't see any other issues for this so I hope this isn't a duplicate, let me know if you need more details/testing.

Thanks for a well made pack!

**Comment by Freebi85** [comment]
Thank's for Reporting. Can reproduce it. Will be fixed in next patch. Until then better craft 3x3 recipes which requires artisan tools into vanilla table :P
