### ISSUE TITLE
Certus Quartz to Charged Certus conversion

### ISSUE THREAD

**Issue by TechnicPotato** [Freebi85/Dungeons-Dragons-Space-Shuttles#376]
This can be done via the Oredictionificator (Mekanism), and can convert any oreDict: oreCertusQuartz to Charged Certus Quartz Ore.
Unsure if intended, was suggested by the pack Discord to report.

**Comment by Freebi85** [comment]
Thank you for the heads up. It was not intended. Gonna change it <3

**Comment by Danekjovax** [comment]
Not sure if this is related but you can convert charged Certus Quartz to regular certus quartz inadvertently with the Oredictionificator.  oredict entry for charged certus quartz is both oreCertusQuartz and oreChargedCertusQuartz.  When you enter the former oredict entry then pump certus quartz of either type through it, it will "uncharge" the charged certus quartz back to the regular variety.

Screenshots provided.
![2020-02-05_20 47 06](https://user-images.githubusercontent.com/10191173/73992793-35485200-491e-11ea-99e7-b5708402f657.png)
![2020-02-06_20 08 28](https://user-images.githubusercontent.com/10191173/73992795-38434280-491e-11ea-9760-fb57c338e088.png)
![2020-02-06_20 10 55](https://user-images.githubusercontent.com/10191173/73992798-3a0d0600-491e-11ea-8ce4-7b87f6da27c2.png)
![2020-02-06_20 11 05](https://user-images.githubusercontent.com/10191173/73992802-3bd6c980-491e-11ea-91f9-7954bd566893.png)
