### ISSUE TITLE
Issues with Rock Crystals

### ISSUE THREAD

**Issue by trustinlies** [Freebi85/Dungeons-Dragons-Space-Shuttles#377]
Rock Crystal Ore from Astral Sorcery is not spawning. The Underground Biomes versions are, but those do not drop Rock Crystals. This essentially locks out a significant portion of the pack. The only way we have found to obtain rock crystals is through the void ore miner. If this is intentional, it is what it is. However with quests to make the Resonating wand to find Rock Crystal Ore, it doesn't seem like this is intended.

**Comment by Freebi85** [comment]
Hi =)There were some issues since latest update. But im gonna remove it compelely from the overworld. It can be crafted in the luminious crafting table and obtained with void ore miners in upcoming patch 6.2 in a few hours^^

**Comment by trustinlies** [comment]
Awesome, thanks for the update
