### ISSUE TITLE
Smeltery #2

### ISSUE THREAD

**Issue by Przyhol** [Freebi85/Dungeons-Dragons-Space-Shuttles#379]
There is a problem in questline ores, alloys & smeltery in quest Smeltery #2 
Instead of grout in the quest is standing Air and i cannot finish the quest 

![Smeltery #2](https://user-images.githubusercontent.com/56178257/66245374-b93ec300-e70d-11e9-902f-716c18d30c70.jpg)

**Comment by Freebi85** [comment]
Was fixed in version 6.1. We are already on 6.2 Updating the questbook is required as well.
/bq_admin default load
