### ISSUE TITLE
Tier 5 Ore Miner doable before going to Space

### ISSUE THREAD

**Issue by Minecr4ck** [Freebi85/Dungeons-Dragons-Space-Shuttles#381]
Hello. 
With the RFTools Builder quarry, I am able to get about 20-25 vibranium ore over the course of 1000 chunks. (512x512).  Not sure if this is intended, but, because of this, I am able to make Tier 5 Void Ore Miner before going to space. That tier gives Mars regolith. 
So, unless this doesn't bother you(though it does feel slightly cheaty/unbalanced to me), one suggestion might be to make "space parts"(Mars regolith, etc..) be apart of the recipe for the higher tier void ore miners.  

Thanks for your hard work!

**Comment by Freebi85** [comment]
Vibranium is also in the overworld not only on mars. Just very rare without a quarry and this is intended and also on the quest description. Anyway you cant make ingots or blocks without regolite stone before. Vibranium cant be brocessed without this. At least in newer versions^^
