### ISSUE TITLE
Cannot Craft Anything in Luminous Crafting Table

### ISSUE THREAD

**Issue by Kaktus021** [Freebi85/Dungeons-Dragons-Space-Shuttles#382]
Playing on a server, updated to 6.2 from 6.1

I've crafted the Luminous Crafting Table and have the quest to craft Rock Crystal. When I put the items in the table and right click with the Resonating Wand nothing happens.

The table has full light and the item does not appear on the right side of the crafting table like it should if it can be crafted.

**Comment by Freebi85** [comment]
Make sure you crafted the Luminous Crafting Table and the resonating wand yourself. Astral Sorcery is gated behind personal progression. 
Pls join our help desk channel in our discord server for more infos. 
Discord Server Link: https://discord.gg/eUajYmK
