### ISSUE TITLE
Battery not crafting [Not working / broken recipes] 

### ISSUE THREAD

**Issue by InitalHero** [Freebi85/Dungeons-Dragons-Space-Shuttles#383]
- Not working / broken recipes 

![image](https://user-images.githubusercontent.com/32253760/66259394-2d14b600-e776-11e9-821f-c4b45ea56cdb.png)

JEI says the below

![image](https://user-images.githubusercontent.com/32253760/66259421-736a1500-e776-11e9-947b-722f7fdc8dc6.png)

The Battery Recipe doesn't seem to be working. I have 4k Silicon in the Engineer's Workshop. This very well could be user error.

**Comment by Freebi85** [comment]
Oh no you forgot to cook the infused silicon :D

**Comment by InitalHero** [comment]
You are absolutely correct, thank you for your help!
