### ISSUE TITLE
Cannot craft Signalum Exchanger

### ISSUE THREAD

**Issue by pkoos** [Freebi85/Dungeons-Dragons-Space-Shuttles#385]
When attempting to craft the signalum exchanger it will not craft.

Attempted fixes: 

- crafting both through JEI and also placing each individual item.
- breaking the Elite crafting table and moving it
- logging out and back in and attempting to craft again.
- restarting computer
- creating a test world and crafting again.
- shift clicking into my inventory will add the exchanger into my inventory. When I click the exchanger in any way, it disappears, and all items appear back in the crafting grid.

When I try to craft, it either doesn't show up as a valid recipe, or when it does show up it immediately bounces all the items back into the crafting grid.
![signalumexchanger1](https://user-images.githubusercontent.com/7260843/66279395-06ce4380-e866-11e9-8d93-dc86d042ba54.PNG)

**Comment by Freebi85** [comment]
Feels Bad :( But i know how to solve it^^
