### ISSUE TITLE
Silk Touch Ores (Underground Biomes) and Machines

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#386]
UB Ores seem to be OreDict'ed with the vanilla (stone) equivalents for mining, but when processing them in machines (Mechanical Squeezer, Enrichment Chamber, etc) they aren't accepted at all.

See screenshots below:
(Coal processing is listed at bottom)
![2019-10-06_23 49 15](https://user-images.githubusercontent.com/10191173/66284350-55df9d00-e895-11e9-804c-6b9bf8ea7dd2.png)

(Chalk Coal Ore isn't accepted for processing)
![2019-10-06_23 49 23](https://user-images.githubusercontent.com/10191173/66284352-57a96080-e895-11e9-9e10-0da95bc3804b.png)

**Comment by Freebi85** [comment]
Hello =)
Read my answer here =)

https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/345
