### ISSUE TITLE
Exchanger - Exchanging Magma Slimy Grass gives only Purple Slimy Grass instead

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#387]
I'm using a diamond exchanger in the Nether, and decided to exchange a few Magma Slime Grass blocks.  When I finished with the exchange, looking in my inventory, I apparently received the wrong slime grass blocks; purple slimy grass!

Please advise.  Screenshots attached.  Thanks!
![2019-10-06_14 41 47](https://user-images.githubusercontent.com/10191173/66284488-0b125500-e896-11e9-841f-f3f2f3591f9e.png)
![2019-10-06_14 41 50](https://user-images.githubusercontent.com/10191173/66284498-106f9f80-e896-11e9-8d6b-4d4b0b931c25.png)

**Comment by Freebi85** [comment]
Opened here:
https://github.com/JackyyTV/Exchangers/issues/60

**Comment by Danekjovax** [comment]
Ok I’ll add to that ticket.  Sorry for the confusion. 😝

**Comment by Freebi85** [comment]
I'm shutting down here for inactivity. I don't think that's gonna be resolved anytime soon.
