### ISSUE TITLE
Nether Portal Glitch?

### ISSUE THREAD

**Issue by PotatoGodz** [Freebi85/Dungeons-Dragons-Space-Shuttles#388]
After I opened a nether portal for the first time some magma slimes came out, which was fine since i had doors in front of it, but after awhile i started getting hit randomly by invisible magma slimes and if I use the axe from the Axe Of a thousand metals I can hit something that constantly spawns small magma slimes that never stop. Just to clarify i'm playing on a server

**Comment by Freebi85** [comment]
Hello =)
Can be an invisible infernal mob. 
Pls join our Helpdesk in our Discord Server for Server Side issues. This can be better discussed there. Of course it can also have something to do with the server itself.
