### ISSUE TITLE
Quest can't be made

### ISSUE THREAD

**Issue by VBenedekN** [Freebi85/Dungeons-Dragons-Space-Shuttles#389]
I've encountered a bug in the questbook. At the Tinker's construct chapter the "Smeltery #2" and the "Smeltery #3" cant' be made. It says it needs 204 air blocks. I could fix it with the command /bq_admin complete 252/253 <username>, but I don't think that is can be done by normal players.
<img width="2492" alt="Képernyőfotó 2019-10-08 - 18 40 50" src="https://user-images.githubusercontent.com/44666856/66415148-35c9ee00-e9fb-11e9-9e31-be057d431971.png">
<img width="2495" alt="Képernyőfotó 2019-10-08 - 18 40 46" src="https://user-images.githubusercontent.com/44666856/66415163-41b5b000-e9fb-11e9-9ced-645cbda662c2.png">

**Comment by Freebi85** [comment]
Was fixed in version 6.1. We are already on 6.2 Update the pack and or the questbook as well^^
/bq_admin default load
