### ISSUE TITLE
a few quest bug tier 2 questline

### ISSUE THREAD

**Issue by ferrium42** [Freebi85/Dungeons-Dragons-Space-Shuttles#39]
not detected: 663 Electrolytic separator, 666 gas Burning generator, 667 Purification chamber
Potion Shelf Quest suggestion build a potion shelf, Questname resourcefull furnace used twice, data Storage cell move recipe to normal crafting 

Ich muss das mal kurz loswerden. Ist dir klar wieviel Arbeit dieses craften macht, das ist schlimmer als mit einer chest und einem Tinkertable. Nicht davon zu sprechen dies je zu automatisieren. Wieviele Einheiten soll man da hinbauen. zb der master assembler speichert kein rezept. X- machinen nötig. Oder dieser andere Mod da seh ich auch nix automatisierbar. Also wenn du echt materialintensiv und hardcore gehen willst sollten alle rezepte automatisierbar sein zumindest  kabel und verbrauchsmaterialien. es ist echt was neues dein Modpack und es gefällt mir auch weil es auch Kampfmöglichkeiten und erkundung ermöglicht. Aber teilweise seh ich es auch kritisch, zb die lootbags machen soviel cheatbar da wüsste ich gar nicht wo ich anfangen soll und wie einfach ist es da ein system hinzubauen. Auch wenn du Storage drawers offensichtlich nicht magst oder sehr sehr schwierig machst. Oder du rennst rum und lootest die vielen evil altare und drachenchest ... was zumindest begrenzt wäre. Ja ich weiß auch wie schwierig es ist mit diesen op mods je eine balance zu finden. Ist wie gesagt nicht das erste pack das ich spiele.

**Comment by ferrium42** [comment]
es jedem recht zu machen ist eine kunst die keiner kann - es ist vlt nicht erkennbar wie stark du noch an dem Modpack arbeitest wenn man es herunterlädt :) dann hätte ich vermutlich die finger erst mal davon gelassen (normalerweise geht da auch kein youtuber ran an solche packs) - ansonsten spiele ich schon sehr viel , so ein paar stunden und da kann man schon was erreichen - ja vlt frustriert das ein oder andere , zumindest wenn das spiel crasht und man dauerlädt was bei mir fast 15 min dauert - mach dir keinen Kopf ich helfe oder nerve ^^ wo ich kann - und patchen tust du verdammt schnell

**Comment by Freebi85** [comment]
Ich konnte jetzt kabel und schlatkreise in den carpenter integrieren. Dieses gerät lässt rezepte speichern und automatisiert laufen. Ausserdem hat es storage und fluid slots. Für mich top zum programmieren und die für user etwas angenehmer um damit zu arbeiten. am besten du machst dir schon ein paar bevor im nächsten patch stahl dafür gebautcht wird^^
