### ISSUE TITLE
Osgloglas brown magic to OP for early/mid game

### ISSUE THREAD

**Issue by Vendet29** [Freebi85/Dungeons-Dragons-Space-Shuttles#390]
Osgloglas has 2 traits global travel and brown magic wich is:
-  mobile 
-  has no penalty
- instantly use teleport(safe teleportation )
- can be used to teleport from other dimensions
Considering that it has other trait and its best mid-level metal for tools and weapons,
brown magic should be dealted from osgloglas so it has only global travel, or balanced maybe tool durability penalty.

**Comment by Freebi85** [comment]
Sounds reasonable. I will check that and remove it if necessary. But this has no effect on tools and weapons that have already been crafted.

**Comment by Vendet29** [comment]
It makes other teleportation methods that needs some setup pointless because you can make stone tools with osgloglas binding(1 ingot) and have easy teleportation system
