### ISSUE TITLE
Most liquids can be duplicated with /dank/null due to "listAllMilk" oredict entry

### ISSUE THREAD

**Issue by griseouslight** [Freebi85/Dungeons-Dragons-Space-Shuttles#391]
Most buckets of fluid have a "listAllMilk" oredict entry:
![image](https://user-images.githubusercontent.com/9774133/66496234-9e12e100-ea88-11e9-85e0-cddf58312d2a.png)

This means you can place any of these in the /dank/null/, enable OreDict mode, and duplicate it with any item with the tag, including the Fresh Milk and Soy Milk items.

**Comment by Freebi85** [comment]
Hm LoL that's weird. But i think i can fix this.
