### ISSUE TITLE
Animania animals spawn at 0x 0y 0z with Zoesteria installed

### ISSUE THREAD

**Issue by katubug** [Freebi85/Dungeons-Dragons-Space-Shuttles#392]
So this is a weird one. A couple of people in the Animania discord were reporting issues with Animania animals not seeming to spawn. After some testing, it was discovered that they *were* spawning, but for some reason always at 0x 0y 0z, and then suffocating or falling out of the world.

I do not play DDSS but I figured I'd do some testing to see what could be causing the issue. I made a fresh install with just Animania/CraftStudioAPI and Zoesteria. I was able to replicate the issue a few times, but not every time. I was not able to replicate the issue with only Animania/CraftStudioAPI and Traverse. Additionally, I tried another entity-spawning mod (ZAWA) with Zoesteria, and could not replicate the issue, even when using the same seeds the issue occurred in previously. So, my theory is that there's some miscommunication between Zoesteria and Animania regarding how spawning should work.

**Mods and versions**: 
animania-1.12.2-1.7.2
CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
Zoesteria Public Alpha 1.4.10
When using Traverse: Traverse v1.6.0 build69 for 1.12.2
When using ZAWA: zawa-1.12.2-1.7.0.

I tested on forge 2836 and 2838 just in case that was the issue, but saw no difference between them.

Replicated:
- Seed -1994555203772886380
- Spawned in Bush Biome

Replicated:
- 4819391118352641278
- Spawned in Plains Biome

Issue at the Animania github: https://github.com/capnkirok/animaniamod/issues/367

**Comment by Freebi85** [comment]
Temporarly fixed with a donwgrade of animana for DD&SS. i won't update the mod for now until it's fixed.
