### ISSUE TITLE
Inventory bug

### ISSUE THREAD

**Issue by wickedwzrd** [Freebi85/Dungeons-Dragons-Space-Shuttles#393]
Not sure what mod could be causing this issue but I will occasionally have some items from my inventory tossed into my crafting grid and armor slots. I attached a screenshot of the issue.
![Minecraft 1 12 2 27_09_19 01_04_39](https://user-images.githubusercontent.com/9831909/66522559-b6502380-eabb-11e9-96f1-d9036cdd8cac.png)

**Comment by Freebi85** [comment]
Hi =)
I tested a lot of different things and stuff. Also with similar items like yours in the inventory and can't still reproduce it. Check if this happens again in version 6.3 and under what circumstances.

**Comment by RevenForevermore** [comment]
I have the same type of thing going on now except it's everything in my hotbar and inventory slots. The armor slots aren't affected and it seems to happen when I press sneak while hovering over an item. It stops happening when I reload the save but idk what starts it. This isn't the same issue but I haven't seen anything similar while searching the webs for help.
