### ISSUE TITLE
Hook disappears when opening tomb

### ISSUE THREAD

**Issue by Serkette** [Freebi85/Dungeons-Dragons-Space-Shuttles#395]
Forge: 14.23.5.2836
DD&SS Version 6.2
Released 04. Oct. 2019
289 Mods Loaded

When retrieving inventory from a grave while having a wooden hook equipped to the first bobble slot, an iron hook that should have been returned to me, it was equipped upon death, was missing. The wooden hook was still equipped.
[debug.log](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/3711771/debug.log)
[latest.log](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/3711772/latest.log)

**Comment by Freebi85** [comment]
Please follow the template and report mod's own issues directly to their authors. Corails Tombstone.
