### ISSUE TITLE
Crash upon trying to make Iron Plates inside Blacksmith WorkShop

### ISSUE THREAD

**Issue by bunnyman14** [Freebi85/Dungeons-Dragons-Space-Shuttles#396]
**Issue**
Attempting to craft Iron plates (the same way you would in a normal crafting table) results in the game crashing to the title screen. I did this 3 times to be sure. I have not modified the modpack in any way (yet).

**Modpack Version**
6.2

**Possible fix**
Prevent the Workshop from allowing Plates to be crafted within it, or properly implement the recipe into the Workshop.
[crash-2019-10-10_21.41.03-client.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/3715274/crash-2019-10-10_21.41.03-client.txt)
let's hope that txt can open. If not, I'll put it in a pastebin.

**Comment by Freebi85** [comment]
I am in contact with the mod author. Let's see what we can do here.

**Comment by Freebi85** [comment]
https://github.com/codetaylor/artisan-worktables/issues/197

**Comment by bunnyman14** [comment]
Thank you!
