### ISSUE TITLE
CoFH Core Multishot enchants not working on livingwood/crystal bow 

### ISSUE THREAD

**Issue by OverlordKyo** [Freebi85/Dungeons-Dragons-Space-Shuttles#397]
As stated in the title multishot does not work on Botania bows. Is this just an incompatibility between the two mods or can they be made to work together?

**Comment by Freebi85** [comment]
Hey :)
I guess incompatibility between the two mods. Sadly nothing i could change myself. I suggest to open a ticket into botania tracker. But there's no guarantee that the devs might add it.
