### ISSUE TITLE
More sealable blocks for space station

### ISSUE THREAD

**Issue by cosmosgenius** [Freebi85/Dungeons-Dragons-Space-Shuttles#398]
Currently the only available clear block for space station are vacuum block from galacticraft and normal glass/glass pane. Vacuum block don't seal when used as roof and normal glass just looks Horrible. Can mana glass or alf glass be added to sealable id in galacticraft or maybe chiselled version of glass?

**Comment by Freebi85** [comment]
Hello :) 
Sure, it’s a good idea. I will add a few glass types to it!

**Comment by cosmosgenius** [comment]
Thx!!!
