### ISSUE TITLE
Inserting more than one Blood Cell in Blood Infuser couse Cells disappear.

### ISSUE THREAD

**Issue by mcwnuq** [Freebi85/Dungeons-Dragons-Space-Shuttles#399]
Upon inserting more than one Blood Cell in Blood Infuser couse other Cells and blood disappear.
![image](https://user-images.githubusercontent.com/11915730/66708272-31c90380-ed4e-11e9-8a6b-745569ecec74.png)
![image](https://user-images.githubusercontent.com/11915730/66708273-3beb0200-ed4e-11e9-9e45-edf2c37df987.png)
![image](https://user-images.githubusercontent.com/11915730/66708276-473e2d80-ed4e-11e9-9d80-fb316e23dd35.png)
![image](https://user-images.githubusercontent.com/11915730/66708279-4c02e180-ed4e-11e9-97ac-6051e1a1c779.png)

**Comment by Freebi85** [comment]
Hey =)
Thank you for reporting. Can you put the issue to Evilcraft as well? I can't fix this myself sorry.

**Comment by mcwnuq** [comment]
Fixed, check referenced issue.
