### ISSUE TITLE
Cant find recipe to make stone button

### ISSUE THREAD

**Issue by billyty08** [Freebi85/Dungeons-Dragons-Space-Shuttles#4]
Just updated to newest version and I'm not sure if it was there before but currently I can't find a recipe in jei to craft stone button needed for the clay juicer. If there is a recipe for it it would be greatly appreciated if you would point it out in quest or other or if it is in a different workstation

**Comment by Freebi85** [comment]
Until now, I didn't realize this mistake. Thank you. Will be fixed as soon as possible.
