### ISSUE TITLE
Pack Description Inconsistency 

### ISSUE THREAD

**Issue by drhaber** [Freebi85/Dungeons-Dragons-Space-Shuttles#400]
Pack Description still mentions the inclusion of Streams

> My Modpack uses Traverse & Zoesteria Biomes along with streams to create a beautiful terrain in the overworld!

Update notes 6.0 mentions the removal of this mod

> Included in Version 6.0a+6.0b:
> ...
> -Removed Streams mod because incompatible with spongeforge. Streams in persistend worlds are now just empty. I apologize

**Comment by Freebi85** [comment]
Thank you for the heads up :D
Fixed^^
