### ISSUE TITLE
Laser Lasso duplication

### ISSUE THREAD

**Issue by grugasaurus** [Freebi85/Dungeons-Dragons-Space-Shuttles#401]
Currently, if you offhand a plustic laser (mine is refined glowstone medium, manyullen battery, alumite handle (linked to a chest), netherrack pipe piece) and right click a friendly mob such as a chicken usig the golden lasso, you will both activate the laser killing the friendly mob (producing drops) and activate the lasso, filling it with an undamaged mob upon which you can repeat this process for infinite speedy animania drops.

**Comment by Freebi85** [comment]
Solved.
