### ISSUE TITLE
[ModSuggestion] PackagedAuto

### ISSUE THREAD

**Issue by ruifung** [Freebi85/Dungeons-Dragons-Space-Shuttles#402]
Might I suggest having the PackagedAuto mod be added to make it slightly easier for AE2 to deal with crafting receipes with > 9 types of items. Right now, RS is clearly superior in the autocrafting department with the Refined Avarita addon. This should make it *slightly* easier for AE to interoperate with RS for handling the larger receipes.

The PackagedAuto mod is basically an addon to AE to allow for bundling and unbundling of multiple items into a single item for the purposes of AE2 autocrafting.

https://www.curseforge.com/minecraft/mc-mods/packagedauto/files/2806611

**Comment by Danekjovax** [comment]
I know I look at this a couple weeks ago, but for some reason couldn't get the items in my JEI.  I probably did something wrong, and I'm not terribly experienced with this advanced level of auto-crafting, so I'll recuse myself from any further judgement on this mod add-on.

Ruifung, you're more than welcome to make a test build of DDSS with this mod added to it and test it yourself, and report your findings in here.  Thanks.

**Comment by ruifung** [comment]
Aye, I'll give it a try when I have time.

**Comment by ruifung** [comment]
It shows up in my JEI just fine. It's basically a handy glue mod to allow AE to delegate autocrafting of higher tier items to RE. I would *really* love to see this in the pack, as then it would bring AE to just being slightly inferior to RS for this level of autocrafting.

**Comment by Freebi85** [comment]
Im not against this. But of course this stuff will be gated behind planet progression like Refined Avaritia which is the counterpart fot Autocrafting in RS.

**Comment by ruifung** [comment]
Tentatively, this thing packages items into bundles, so it has uses other then large advanced crafting, i believe it doesn't actually handle the crafting itself (unlike the RS patterns which work in an RS crafter), you still need the automation interface for this I believe.

**Comment by Freebi85** [comment]
Added in 6.5
