### ISSUE TITLE
[Mod Request] Super Sound Muffler

### ISSUE THREAD

**Issue by Renari** [Freebi85/Dungeons-Dragons-Space-Shuttles#403]
This is just a really nice quality of life mod, with Animania farms and breeding dragons the sounds can get pretty overwhelming, this leads me to just mute the game for long periods of time. We do already have sound mufflers but the Extra Utilities sound mufflers are basically all or nothing, so I've just been muting my game instead to get a similar effect.

[https://www.curseforge.com/minecraft/mc-mods/super-sound-muffler](https://www.curseforge.com/minecraft/mc-mods/super-sound-muffler)

**Comment by Freebi85** [comment]
Did you already testet this on your client?

**Comment by Renari** [comment]
I did not my group was playing on a server so it wasn't something easy to add when everyone is installing from the twitch client.

**Comment by Freebi85** [comment]
Well we testet a bit around with this mod. All the animania mobs and other ones like primitive mobs dosen't seems to work properly. So it's not useful at all IMO i'm sorry :(
