### ISSUE TITLE
Technical Issue - Crashing on Loading Screen

### ISSUE THREAD

**Issue by kitten2021** [Freebi85/Dungeons-Dragons-Space-Shuttles#404]
Upon launching the D&D mod through Twitch's launcher, the game loads only so far and then crashes. However, I keep a close watchful eye on it, and I don't ever see it exceeding the allowable memory, but this is what it continues to crash for according to the crash report (linked below).

"com.google.common.util.concurrent.ExecutionError: java.lang.OutOfMemoryError: GC overhead limit exceeded"
and...
"Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded"

If someone that knows more about coding and such than I do, can you please look at this report and tell me what else could possibly be going on? Does anyone know how to allocate more memory utilizing the Twitch launcher to MC so as to help prevent it from crashing? Is there a limitation on the amount of memory that Twitch allows to be used? I honestly don't know. I've provided a snippet of what my computers shows as far as the memory within it... maybe it will help?

Crash Report: https://paste.dimdev.org/numufaqaji.mccrash
![ComputersMemory](https://user-images.githubusercontent.com/56518417/66720720-66bc7100-edb5-11e9-9561-1aaa8ecfb21e.PNG)

**Comment by cyber01** [comment]
You need to increase memory for java in launcher settings. 

Dont use issues for crashes, its not modpack problem

**Comment by Freebi85** [comment]
Hi =) 
Follow the instructions here. 
https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/263
