### ISSUE TITLE
Iron ore can’t see it

### ISSUE THREAD

**Issue by SupaMkNasty** [Freebi85/Dungeons-Dragons-Space-Shuttles#406]
i love the pack but just wondering if this is a issue, while mining I can’t not see iron ore I hover my cursor over certain blocks and it will say red granite iron ore I was like wow I can’t actually see the iron but ever other ore I can any help would be appreciated thank!!!

**Comment by Freebi85** [comment]
Hi =)
I guess it's just hard to spot because of underground biomes. There's not much you can do except install texture pack or ask the UndergroundBiomes author if he can make it more visible^^

**Comment by SupaMkNasty** [comment]
Do you have a texture pack that would go good with your pack??? Suggestions please lol!!!

**Comment by Freebi85** [comment]
There is one!!!! Omegalul^^
Check this out =)
https://www.curseforge.com/minecraft/texture-packs/official-dd-ss-64x64-texturepack

**Comment by SupaMkNasty** [comment]
Thank you!!! Keep up the awesome work!!!!
