### ISSUE TITLE
Cake duplication with Chest Transporter mod

### ISSUE THREAD

**Issue by blackRaTTeN** [Freebi85/Dungeons-Dragons-Space-Shuttles#407]
Using any chest transporter on an uneaten cake drops a duplicate and creates an item drop ghost that cannot be picked up, it also counts as an entity (they interact with vacuum hoppers and similar blocks, but are not picked up by them).

**Comment by Freebi85** [comment]
Thank you for reporting. Can you pls open this issue to chest transporters as well? That’s nothing i could fix myself.
