### ISSUE TITLE
MIilk disapire after milking

### ISSUE THREAD

**Issue by Vendet29** [Freebi85/Dungeons-Dragons-Space-Shuttles#408]
Milk disappear from inventory  or when placed in world.
It happens when i try to left click milk container in inventory it changes back to empty container , when placed it in the world or machine it  disappear. 
- milk spawned with JEI works normally.
- containers that i check:  cell, bucket, pipette, wooden tank from fluid tanks
- tested on milking fresian cows 
- i have last update 6.3, before it works without problems

**Comment by Freebi85** [comment]
Animania was downgraded because it have other severe bugs. That's probably why. And i can't update until all the involved mod authors fix their bugs betweens Zoesteria and Animania. This can take a while.
So i have to close for now.
