### ISSUE TITLE
Lava Cell Deletion with Magma Anvil

### ISSUE THREAD

**Issue by bunnyman14** [Freebi85/Dungeons-Dragons-Space-Shuttles#409]
**Bug Description:** Using a Lava Cell from Tech Reborn on a full Magma Anvil from Cyclic (or one that's above 9,001mb of lava) consumes the Lava Cell _without giving back an empty cell_ and does NOT fill the Magma Anvil either. Likely a bug on Cyclic's part! I'll post this there as well!

**What is expected to happen:** Lava Cell is not consumed NOR anvil filled, in other words nothing should happen at all.

Currently fixed this by cheating the lost cells back but not everyone feels okay with doing that.

**Comment by bunnyman14** [comment]
https://github.com/Lothrazar/Cyclic/issues/1249

So apparently it's not happening when I pull items out and THEN do it with a single cell. It's likely the fact that either A: the item in the Anvil is causing an issue or B: rapidly clicking bypasses a check to see if the tank is too full

**Comment by Freebi85** [comment]
Thx for reporting it to Cyclic. I can't do much there. Wait and hope.

**Comment by Freebi85** [comment]
Gonna close this since im working on a final release of DD&SS. Maybe I will take a look at it again if it should be fixed in the future.
