### ISSUE TITLE
Pam`s "Pavlova" recipe result is not eatable 

### ISSUE THREAD

**Issue by Ruthgar** [Freebi85/Dungeons-Dragons-Space-Shuttles#410]
Made a pie and cannot eat it.

**Comment by Danekjovax** [comment]
Confirmed.  It's placed like a regular cake and it's eaten after placed.  It doesn't count as being eaten when done like that.  So either that mechanic needs to be fixed where it's recognized or Pavlova needs to be removed from the eaten list.

![2019-10-15_19 00 21](https://user-images.githubusercontent.com/10191173/66876041-5a374480-ef7e-11e9-816b-925914033873.png)
![2019-10-15_19 02 26](https://user-images.githubusercontent.com/10191173/66876044-5c010800-ef7e-11e9-82c1-5ccbbec3b6ed.png)

**Comment by Freebi85** [comment]
so it can be eaten and give hunches but it dosent count for the additional hearts?

**Comment by Danekjovax** [comment]
It's eaten like a vanilla cake.  It has to be placed to be eaten.  It gives a heart for each "slice" eaten like a vanilla cake.  I'm not sure how the code recognizes what's eaten when using this method of eating.

**Comment by Freebi85** [comment]
Yeah somthing broken there. Too much weirdness^^ Gonna remove the cake and the entry from the Food Book.

**Comment by Danekjovax** [comment]
In retrospect, the cake functions like it should, but isn't interacting properly with the Spice of Life "Food Knowledge" mechanic.  There may be more foods like this, and I'll report them as I come across them.  Thanks!

**Comment by Danekjovax** [comment]
I'll add that there are a couple other cakes in Pam's - Cheesecake and Pumpkin Cheesecake - that are similar to Pavlova that must be placed to eat, but these DO work for counting as an eaten food for the Food Book.  Perhaps comparing any config data between these cakes and pavlova may reveal the glitch with Pavlova.  Hope this helps!
