### ISSUE TITLE
Crash when adding ProjectE

### ISSUE THREAD

**Issue by Machiavelli1990** [Freebi85/Dungeons-Dragons-Space-Shuttles#411]
Hey. I'd like to add ProjectE to this Pack, but whenever I add it, It causes an issue with ProjectE itself or Nuclearcraft having an issue. Not sure how to fix and if this is the right Github to post it to.

Pastebin: https://pastebin.com/5NtxtRpJ

Any help would be appreciated :)

**Comment by dierke9** [comment]
Hello

We do not give support to modified packs. You better post the issues on the issuetrackers of the mod that you are trying to add.

**Comment by Machiavelli1990** [comment]
So I'd post this on Nuclearcraft or on ProjectE issue tracker?

**Comment by Machiavelli1990** [comment]
Alright, will do that :) Thank you!
