### ISSUE TITLE
Tome of Lightning not working

### ISSUE THREAD

**Issue by Alcan4** [Freebi85/Dungeons-Dragons-Space-Shuttles#412]
Found this Tome of Lightning
https://snipboard.io/gzqEwo.jpg
![image](https://user-images.githubusercontent.com/4534085/66940281-f88ddd80-f044-11e9-9dc5-00d69087dcb8.png)
in a chest in this tower:
![image](https://user-images.githubusercontent.com/4534085/66940259-ef047580-f044-11e9-88ac-46518fbc8835.png)

Inside the book is only "BEHOLD THE STORM!" and if you click it all these errors appear:
![image](https://user-images.githubusercontent.com/4534085/66940243-e7dd6780-f044-11e9-845c-bb7d1e2ae054.png)
but nothing else. Not sure what it's supposed to do or what mod its from though.

**Comment by Freebi85** [comment]
Hi =)
Well must be somthing from the Ruins mod if you found this book there. I can't do much sorry. I suggest reporting this to the Ruins Mod Author.
