### ISSUE TITLE
[Mod Suggestion] Please consider adding the CleanView mod, and finally get rid of the annoying potion swirlies in your face!

### ISSUE THREAD

**Issue by OmaiGrundles** [Freebi85/Dungeons-Dragons-Space-Shuttles#414]
There is a mod called CleanView, and all it does is remove potion particles around your character. It doesn't affect mobs or anything else, just the particles around your player character.

I can't be the only one who gets incredibly annoyed by the 'potion swirlies' being in your face, right? 

It also has a hotkey to re-enable the horrible swirlies so everybody wins!

**Comment by Danekjovax** [comment]
A link to the mod page would help.  Got one?

**Comment by OmaiGrundles** [comment]
https://www.curseforge.com/minecraft/mc-mods/cleanview

But i just tried out the mod and it doesn't seem to be working.... I'm so dissapointed right now.

**Comment by Danekjovax** [comment]
Well, if you can't get the mod to work with your test DDSS build, then you may consider dropping this ticket, as it's not wanting to work with this modpack.  Sorry for your troubles.  Perhaps looking into another mod will help?

**Comment by OmaiGrundles** [comment]
Yeah ill reopen this if i can get it to work, though seriously if somebody could get this to work i would be so happy lol.

**Comment by OmaiGrundles** [comment]
I have figured out how to get the CleanView mod to work in this pack.

You need to set line 142 of RandomPatches's config to false. this would disable the feature described as "Fixes MC-10369 (server-side particle spawning not creating particles for clients) and MC-93826 (breeding hearts only showing once instead of all of the time an animal can breed)."

I have let the author of CleanView know of this, but I think it is likely RP's issue.

As for if swapping in one feature(removing the horrible in your face particles) for another(having more hearts when bred and such) is worth it, that would be up to you people. But for me, I finally can use potions without ripping my hair out. :)

**Comment by TheRealHypo** [comment]
I might also recommend Optifine: Then under Options -> Video -> Animations you can disable Potion Particles explicitly.

**Comment by Freebi85** [comment]
Since this can be solved with Optifine I don't think that additional mods and configurations are necessary.
