### ISSUE TITLE
Akutuq recipe - not finding in JEI, though listed in Food Book?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#415]
Seems that at least one recipe showing up in the Food Almanac isn't being listed in JEI.  Akutuq is one of them.  If I locate more, I'll be sure mention them in an addendum.

Screenshot included.  Thanks!
![2019-10-12_21 14 16](https://user-images.githubusercontent.com/10191173/67059313-7c6bc680-f126-11e9-985e-7ed2b4990e5e.png)

**Comment by Freebi85** [comment]
It's possible that you will find more foods that was removed but still in the food book. If so open a new issue for it. Then we can collect all the food book "bugs" there.

**Comment by Danekjovax** [comment]
I'll do that.  I have another 900 foods to go, so there's bound to be 1 or two more like that.  We'll see. The grind is real! ;2D
