### ISSUE TITLE
Some Pam's Food - Multiple Recipe Listings?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#416]
I'm seeing double or even triple for these recipes.  What's up?

Roast Chicken
![2019-10-12_21 44 47](https://user-images.githubusercontent.com/10191173/67059351-acb36500-f126-11e9-82ac-403842d9013a.png)

Spicy Mustard Pork
![2019-10-10_06 39 12](https://user-images.githubusercontent.com/10191173/67059595-b25d7a80-f127-11e9-8fc6-7db64aa4ec60.png)
![2019-10-10_06 39 14](https://user-images.githubusercontent.com/10191173/67059597-b38ea780-f127-11e9-82d0-bac50b9229ae.png)

I'll add more here as I run across any others.  Thanks.

**Comment by Freebi85** [comment]
Because there are multiple ways to craft them if you check carefully the ingredients^^
Anyway, one day it will change to the workshop with different stuff. So pla don’t report pams default recipes for now :)

**Comment by Danekjovax** [comment]
Hmm, I only saw the same items, but I'll check them again next time I'm browsing these recipes.  And yes, I'll stop with these types of tickets.  Sorry for any trouble.  :2}
