### ISSUE TITLE
[Mod Suggestion] Just Enough Throwing in Fluids 

### ISSUE THREAD

**Issue by drhaber** [Freebi85/Dungeons-Dragons-Space-Shuttles#419]
At present I have this running on my instance as its client side. However as there are multiple recipes that involve throwing items into fluids I thought I would suggest it to be added to the pack proper.  
[https://www.curseforge.com/minecraft/mc-mods/jetif](https://www.curseforge.com/minecraft/mc-mods/jetif)

**Comment by Freebi85** [comment]
Sorry to disappoint you. I'm not interested in this mod :/
