### ISSUE TITLE
Suggestion: Just Enough Resources

### ISSUE THREAD

**Issue by DrDarkfire** [Freebi85/Dungeons-Dragons-Space-Shuttles#42]
I'm curious, was Just Enough Resources purposely left out? It has a lot of useful JEI functions including ore y levels and mob drops.

**Comment by Freebi85** [comment]
Thanks for your suggestion :) This has already been discussed in discord. Sorry JER is sadly not compatible with Underground Biom Ores. =(
Come to discord and join the best ncommunity there is to get all news :D
 https://discord.gg/eUajYmK
