### ISSUE TITLE
Game crash due to husk

### ISSUE THREAD

**Issue by Silivek** [Freebi85/Dungeons-Dragons-Space-Shuttles#420]
My game crashed when loading NBT data on a husk, and I don't know how to fix it.
Crash Report:
[https://paste.dimdev.org/hanoyepapo.mccrash](url)

**Comment by Freebi85** [comment]
I don't see exactly whats causing this. Anyway i would recommend to use latest Java version instead of the outdated one from the twitch launcher. [switch to JAR settings] If it happens again join our Tech-Support in my discord Server for more help =)
