### ISSUE TITLE
Grave not appearing after death

### ISSUE THREAD

**Issue by Hide-Stampede** [Freebi85/Dungeons-Dragons-Space-Shuttles#421]
I had found an above ground dragon dungeon and i had gone to find the dragon and died got a grave key to retain my lost items upon arrival i had found the highlighted hitbox to say my grave was there however there wasnt a tombstone to click onto i tried using the key as i have had prior instances where the grave wouldnt render in but still been able to get my things back but this time i didnt i looked around to see if the grave had spawned somewhere the hitbow wasnt  showing it fully but i dug around and i couldnt find that either so ive currently got a world where i have lost all my things with no way of retaining them back

**Comment by Freebi85** [comment]
Oof thats sad man :( There is not much i can do for you. I suggest to report it to Corails Tombstone devs with some logs and files to help them fixing it for futher similiar situations/problems!
There is also openblocks command to get your stuff back if it was stored correctly with ob_inventory
