### ISSUE TITLE
Underground Biomes ore dictionary bug

### ISSUE THREAD

**Issue by Zander81** [Freebi85/Dungeons-Dragons-Space-Shuttles#425]
underground biomes blocks are not working in recipes or chisel??

**Comment by Freebi85** [comment]
All Stone types are oredicted to vanilla smooth and cobblestone and can be used in every recipe which requires stone usually. For Example: Stone pickaxe. You have to check first, some stone types are automatically mined as smooth stone. Of course this dosen't work for cobble recipes.
 They don't have chisel integration at all. You can only chisel them to vanilla stone with an artisan chisel.
