### ISSUE TITLE
Wild Hunt Quests not Refreshing

### ISSUE THREAD

**Issue by CygnusInfinity** [Freebi85/Dungeons-Dragons-Space-Shuttles#426]
The Wild Hunt section of quests aren't reopening when the quest cooldowns hit zero, in fact they're ticking to a negative cooldown number ranging from -02 seconds to nearly a minute and staying there.

My guess is it's probably something to do with skipping the tick where it hits 0 and not having a catch to refresh if the cooldown is negative?

![DDSSQuestIssue](https://user-images.githubusercontent.com/38057434/67425910-cc66e500-f58d-11e9-8e9f-7b2ec740ec91.png)

UPDATE: The numbers also keep changing when I reopen the quest book, never hitting a minute or more.

**Comment by CygnusInfinity** [comment]
Major update: All cooldown quests just turned to complete at once? I haven't even fulfilled several of them. It may have been at the end of the last quest's cooldown?

**Comment by Freebi85** [comment]
Hey =)
Currently you have to wait until longest cooldown is gone to refresh all the other ones. Is a know Issue in better questing. Should be fixed with the next pack update. Until then you have to wait for the longest CD or clear them all yourself in Edit mode^^

**Comment by CygnusInfinity** [comment]
Thanks for the info, sorry if it was something you already knew about. I tried to find another post on the same topic before posting.
