### ISSUE TITLE
primed pendant is unbalanced with instant potions.

### ISSUE THREAD

**Issue by danielrab** [Freebi85/Dungeons-Dragons-Space-Shuttles#427]
problem:
primed pendant from Evilcraft gives you an effect repeatedly even if it is an instant effect.
for example: potion of instant healing makes you almost invincible by healing you every tick.

possible way to fix:
the config of Evilcraft contains field "S:primed_pendant.potionMultipliers".
adding a potion there with a multiplier less than one blacklists the potion.

**Comment by Freebi85** [comment]
Thx will look into it.

**Comment by Freebi85** [comment]
I will significantly increase blood consumption fot this item to balance them. And if necessary also blacklists potions  effects if it is still too strong.
