### ISSUE TITLE
Celery Soup is Uncraftable

### ISSUE THREAD

**Issue by bunnyman14** [Freebi85/Dungeons-Dragons-Space-Shuttles#430]
As shown in the images provided, Garden Soup takes priority over Celery Soup, making the latter impossible to craft. Using JEI to automatically place the ingredients does not help.
Temporary fix is to cheat the celery soup in.
**Expectation**
![2019-10-25_19 13 05](https://user-images.githubusercontent.com/7276888/67609688-f0782100-f75b-11e9-95a8-f47c81572734.png)
**Reality**
![2019-10-25_19 13 10](https://user-images.githubusercontent.com/7276888/67609689-f0782100-f75b-11e9-8149-cee40dd2b4c3.png)

**Comment by bunnyman14** [comment]
![2019-10-25_22 21 32](https://user-images.githubusercontent.com/7276888/67612960-cfbcc500-f775-11e9-81c5-c03fe3920f61.png)
Asparagus Soup counts too!

**Comment by Danekjovax** [comment]
I was getting to it eventually, but it's nice to know I'm not the only one finding food issues. Thanks for reporting this! :2D
