### ISSUE TITLE
Salt Block (Mekanism) - Process in more than just an Enrichment Chamber?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#432]
Is it possible to allow Mekanism's Salt Block to be processed in more machines than just the Enrichment Chamber?  It would be intuitive to think it could be put into any grinder/pulveriser/squeezer/etc, but JEI isn't showing these process paths, and you can't place the block in any of the mentioned machines.

Thanks!

![2019-10-24_06 37 10](https://user-images.githubusercontent.com/10191173/67613914-72c70c00-f781-11e9-8a84-ed1f3baf68d0.png)

**Comment by Freebi85** [comment]
Why not. Pulverizer, Grinder, Cruser and so on^^

**Comment by Danekjovax** [comment]
You 'da man!
