### ISSUE TITLE
Glass of Milk - More crafting Options?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#434]
Currently, crafting a glass of milk requires manual crafting with a bucket and a few glass bottles.  Please make it also possible to fill milk bottles with the Fluid Transposer.  Thanks!
![2019-10-24_19 26 09](https://user-images.githubusercontent.com/10191173/67614012-0ea54780-f783-11e9-9fa6-a92cfe1aafa4.png)

![2019-10-24_19 26 01](https://user-images.githubusercontent.com/10191173/67614000-f1707900-f782-11e9-8536-da8d82d918b5.png)

**Comment by Freebi85** [comment]
Hmm... Why not. And Fluid Infuser as well :D

**Comment by Danekjovax** [comment]
Freebi, it's always a pleasure working with you! ;2)
