### ISSUE TITLE
Exchanger & Soulstone = Cobbled Soulstone?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#435]
By its nature, an exchanger swaps blocks, so how is it that using the exchanger on Soulstone results in cobbled Soulstone?  Seems like an error in the block swap table.  Using a regular Silk Touch pickaxe yields Soulstone as expected.

Please fix this mechanic so Soulstone can be directly harvested by exchangers.  Thanks!
![2019-10-24_22 45 08](https://user-images.githubusercontent.com/10191173/67614040-98551500-f783-11e9-9172-9b22e285ecda.png)
![2019-10-24_22 45 15](https://user-images.githubusercontent.com/10191173/67614041-9a1ed880-f783-11e9-86f9-8824f278d8db.png)

**Comment by Freebi85** [comment]
Pls report to the mod Author. Don't wanna keep open issues that I can't fix myself and may never get fixed.

**Comment by Danekjovax** [comment]
Understandable.  I'll forward this to the mod author.  Thanks.

**Comment by Danekjovax** [comment]
https://github.com/JackyyTV/Exchangers/issues/61#issuecomment-546600028

**Comment by Danekjovax** [comment]
Found this:
In my client, "Exchangers.cfg": Line 580-581:
# If true, enables Silk Touch (gets the blocks itself rather than drops) in all Exchangers
B:doExchangersSilkTouch=**true**

**Comment by Freebi85** [comment]
i don't see how this can fix your problem? If silk touch is on then you should be able to silktouch blocks, If not then it's an issue rigth?^^ I don't gonna change the configs.

**Comment by Danekjovax** [comment]
My Exchanger still doesn't pick up Soul Stone as Stone, but as cobbled, so the implied "Silk Touch" is not a thing.

Next time I'm on I'll try it with a Silk Touch enchantment and see if that'll work.  If that does the trick, we'll have to just use ST enchantment.  It's just not intuitive, given the name of these devices.

**Comment by Danekjovax** [comment]
I tried it last night with an exchanger with ST on it, and still only got cobblestone.
