### ISSUE TITLE
Natura Wood Bowls (Ghost/Fuse/Dark/Blood) not craftable?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#436]
Trying to craft any of the Natura bowls per JEI only results in the vanilla bowl.  Foods requiring these bowls (Glowshroom stew) are not craftable and therefore not accessible as they require these bowls to be made.

Please allow these bowls to be made.  Thanks!
![2019-10-25_22 56 30](https://user-images.githubusercontent.com/10191173/67614066-11ed0300-f784-11e9-85b0-60da64748531.png)
![2019-10-25_22 56 02](https://user-images.githubusercontent.com/10191173/67614068-15808a00-f784-11e9-9a20-eee4dfc231ce.png)
![2019-10-25_22 56 35](https://user-images.githubusercontent.com/10191173/67614072-23cea600-f784-11e9-8044-4938b14c28fc.png)
![2019-10-25_22 56 50](https://user-images.githubusercontent.com/10191173/67614073-27fac380-f784-11e9-87c5-e83e7b1fa58f.png)

**Comment by Freebi85** [comment]
Oh haha yes. Will add a chisel recipe for bowls lol :D 
It's a bit "special" because of my wood nerf system like the natura fences so gonna add it via chisel for now :P

**Comment by Danekjovax** [comment]
Um, ok. ;2)  I'll take your word for it. >;2)
