### ISSUE TITLE
[Mod Suggestion] AE2 Stuff

### ISSUE THREAD

**Issue by fajeczek00** [Freebi85/Dungeons-Dragons-Space-Shuttles#438]
AE2 Stuff has beta for 1.12.2
It does add items for better AE2 management.
The best item from this mod IMO is network visualizer which draws x-ray of network bound to it with channels amount and p2p channels.
It is very useful 
https://www.curseforge.com/minecraft/mc-mods/ae2-stuff

**Comment by Freebi85** [comment]
It's interesting but the last update was in 2017. I don't think I want to risk it I'm sorry.
