### ISSUE TITLE
[Suggestion] Add FastWorkbench

### ISSUE THREAD

**Issue by primetoxinz** [Freebi85/Dungeons-Dragons-Space-Shuttles#44]
Due to the extreme amount of recipes in this pack, the vanilla crafting registry is very large and given how it is implemented in vanilla it must loop the entire registry every time it makes an item. For shift-clicking an entire stack, that means it does about a couple million unnecessary look ups and thus causes the server to hang. 

If you added [Fast Workbench](https://minecraft.curseforge.com/projects/fastworkbench) it mitigates this lag significantly by caching recipe results. It would be a great improvement to the experience of this pack.

Thanks for your work.

**Comment by Freebi85** [comment]
Thanks i will consider this in my next update =)
