### ISSUE TITLE
Mystical Ag: Infusion Crystal - Using them Ignores Unbreaking Enchantment

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#440]
I recently enchanted my Infusion Crystal with Unbreaking III with the hopes it would help make it more durable during use.

Well, after converting thousands upon thousands of Inferium essence with it, I have great confidence to report that all Unbreaking enchantments used on these crystals are being ignored.  See the screenshots below.  In this example, I placed enough essence for 60 conversions, and observing the durability before/after, you'll see the durability was used each and every operation.

![2019-10-26_07 57 31](https://user-images.githubusercontent.com/10191173/67628968-1f1df680-f845-11e9-9f70-ee10dec729db.png)
![2019-10-26_07 57 50](https://user-images.githubusercontent.com/10191173/67628973-2cd37c00-f845-11e9-8719-e2864fc8b532.png)

So, either it wasn't intended for Unbreaking to be allowed on this item, or the code for it is broken.

Freebi, let me know if this is a mod-related issue, and I'll move this to the appropriate mod's GitHub.  Thanks.

**Comment by Freebi85** [comment]
Can't sadly add/remove enchantments or interact with them in any way on items. Thanks^^

**Comment by Danekjovax** [comment]
https://github.com/BlakeBr0/MysticalAgriculture/issues/235
