### ISSUE TITLE
Forge Multipart: Nor Gate - Sometimes not rendering (ghost entity).

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#441]
Not sure if this is a mod-specific issue, but I'll post it here first to get things rolling.

The NOR gate from Forge Multipart CBE fails to render on-screen much of the time, and when it is "invisible", it will act like a ghost block (like it was mined but server-side has the block as unmined), and make it hard to walk over/around.  Notably, the hotbox for the gate is also non-existant, and onlt breaking the underlying block will it "pop" and go into your inventory.  Replacing the gate will allow it to render as normal, but something as yet undetermined causes it to stop rendering.

Screenshots attached.  Thanks!

Before...
![2019-10-26_23 16 24](https://user-images.githubusercontent.com/10191173/67629090-9ce30180-f847-11e9-9e16-7bf2074c7af1.png)

After breaking underlying block and replacing it...
![2019-10-26_23 17 03](https://user-images.githubusercontent.com/10191173/67629091-9f455b80-f847-11e9-8f19-88d980a0cde4.png)

**Comment by Freebi85** [comment]
FYI i can only interact with recipes around any crafting tables, artisan tables, most machines as well as quests and configs. 
Everything else should be reported to their mod author or my github gets bloated with stuff i can't fix myself.

**Comment by Danekjovax** [comment]
Thanks Freebi.  I'll take note.  I apologize for any bloating of the issues list.

https://github.com/TheCBProject/ForgeMultipart/issues/69
