### ISSUE TITLE
Actually Additions - Using Coffee Cup with Unbreaking Enchantment ignores Enchantment

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#442]
Similar to https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/440, the Coffee cup with Unbreaking Enchantment will ignore any durability bonus when used.

Either Unbreaking isn't intended to be placed on the item, or Unbreaking code is broken for it.
![2019-10-26_23 28 07](https://user-images.githubusercontent.com/10191173/67629175-0283bd80-f849-11e9-80a9-244526d60807.png)

**Comment by Freebi85** [comment]
Pls Report always mod related problems to their Author. Can't add/remove enchantments or interact with them in any way. Thanks^^
