### ISSUE TITLE
Natura-Potash Apple Cannot be Eaten?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#443]
The Potash Apple from Natura, though listed as an edible food (albeit a poisonous one), will not be eaten.  Please look into this, or let me know to forward this ticket to the appropriate mod's GitHub. Thanks!
![2019-10-26_23 35 58](https://user-images.githubusercontent.com/10191173/67629309-2eec0980-f84a-11e9-82da-58b0956bb61b.png)
![2019-10-26_23 36 01](https://user-images.githubusercontent.com/10191173/67629310-301d3680-f84a-11e9-877a-3e34e79b8b45.png)

**Comment by Freebi85** [comment]
Only thing i can do is blacklist for the book. If you want a "fix" you should report it to their author. If this is an issue at all. Let me know.

**Comment by Danekjovax** [comment]
I think it's a problem when any item doesn't do what it "advertises".  But since it's a mod issue, I'll move the issue there.  Thanks!

**Comment by Freebi85** [comment]
Thank you. Will update once it's fixed from the devs.
