### ISSUE TITLE
Server crash.

### ISSUE THREAD

**Issue by yellowBanano** [Freebi85/Dungeons-Dragons-Space-Shuttles#445]
Greetings, 

I downloaded DD&SS with intention to play in multiplayer. For the first time I created world locally. Opened in local network. Invite my neighbors. Then I had to transfer server to 24/7 mode and switched local environment to dedicated server. When I uploaded map and started server everything was fine. My friend that haven't played earlier logged in with ease. When I attempted to login, server crashed. I don't know the reasons. Could you give me a hint about it?

Here is crash report:
https://gist.github.com/yellowBanano/4c2929a78a3fca809dedae8e7bd92bb9

**Comment by Freebi85** [comment]
Pls join our discord server "Tech Support" for Serverside Problems. I don't troubleshoot them here at all like my template descriptions says :)
Anyway for some weird reason you are not recognized as online.

Discord Server Link: https://discord.gg/eUajYmK
