### ISSUE TITLE
Eucalypt's fences

### ISSUE THREAD

**Issue by HeliopoliSS** [Freebi85/Dungeons-Dragons-Space-Shuttles#446]
Hello!
I found that you are not able to craft eucalyptus fences because they require eucalyptus sticks and they are unobtainable. Same with eucalyptus workbench and possible some others recipes.

**Comment by Freebi85** [comment]
The only way to craft them is a chisel. Put any kind of vanilla fence in a chisel to convert them^^
If you read the Quest in Tier 0 "fancy fences" you will find some explanations.
