### ISSUE TITLE
Food Issues (Compiled)

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#447]
EDIT:  This is a compiled list of current (and ~~resolved~~) food-related issues, to keep clutter in the food issues list to a minimum.  If you observe any food issues not already listed below, please add them as a comment to the end of the thread;  I'll add them to a list I have here if it fits in one of them.  Thanks!

**Comment by Danekjovax** [comment]
I wonder if all the cakes listed twice in the Food Book will have this problem?

Carrot Cake, Cherry Cheesecake, Chocolate Sprinkles Cake, Holiday Cake, Lamington, Red Velvet Cake, <more TBD>

**Comment by Freebi85** [comment]
i don't know honestly. Only thing i can do is blacklist all the food which is not recognized by SOL book.

**Comment by Freebi85** [comment]
i suggest to put all the things you find out in here. Will let open the issue for a while so you don't have to open new ones for food stuff 💃

**Comment by Danekjovax** [comment]
I'll do that, Freebi.  Thanks. ;2)

**Comment by Danekjovax** [comment]
Later today, I'll investigate the Duplicate items in the Food Book list and see if its an indicator of the problem we've seen with Pavlova and Pineapple UpsideDown Cake.

**Comment by Danekjovax** [comment]
Concerning the Cakes issue: https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues/67

**Comment by Danekjovax** [comment]
Foods to take out of the Food Book or fix recipes so they're craftable:
Akutuq, Apple Cider, Apple Snow

<More to be listed here as I find them>

**Comment by Danekjovax** [comment]
The following seeds should be enabled to allow for foods/recipes requiring them:

Giga Pickle (1 vegetable, 1 recipe)

**Comment by Danekjovax** [comment]
Alternate Recipes:

Tunafish Sandwich - Substitute Sweet Pickle in place of Giga Pickle.

**Comment by Danekjovax** [comment]
Culinary Generator will not accept Beechnuts, though JEI lists it as a possible use.
![2019-11-09_07 27 15](https://user-images.githubusercontent.com/10191173/68528585-b6ae2b00-02c2-11ea-8256-4d2dc154a321.png)

**Comment by Freebi85** [comment]
after a detailed investigation, I unfortunately found out that it is not possible to interact with this machine. And since EU2 is discontinued in 1.12... :/ you know.

**Comment by Danekjovax** [comment]
Ok, I'll keep that in mind.  I'll still leave the list there for future reference, but I'll add your note.

**Comment by Danekjovax** [comment]
Foods not showing in the Food Book:
Biscuits of Totality

**Comment by GearsOfClockwork** [comment]
The chicken dinner from the copper hammer quest doesn't show up in JEI and has no recipe.

**Comment by noodlenoggin34** [comment]
As I recall, I got the new food bonus multiple times for humanoid flesh from evilcraft because they can have different nbt data. I would use it to kill myself when I was low and too lazy to regen, but I got 4 or five different new food bonuses from deferent stacks of humanoid flesh.

**Comment by Danekjovax** [comment]
> As I recall, I got the new food bonus multiple times for humanoid flesh from evilcraft because they can have different nbt data. I would use it to kill myself when I was low and too lazy to regen, but I got 4 or five different new food bonuses from deferent stacks of humanoid flesh.

I'll check it out and see if I can repeat the issue.  Thanks for the heads up.

**Comment by GearsOfClockwork** [comment]
Cooked kebab doesn't have a recipe.

**Comment by Danekjovax** [comment]
> Cooked kebab doesn't have a recipe.
> 
> Edit: Nevermind, you have to use the furniture mod grill to cook it. That wasn't clear from JEI.

Hmm, not sure if JEI can see MrCrayfish's machines... Freebi?

**Comment by GearsOfClockwork** [comment]
> 
> 
> > Cooked kebab doesn't have a recipe.
> > Edit: Nevermind, you have to use the furniture mod grill to cook it. That wasn't clear from JEI.
> 
> Hmm, not sure if JEI can see MrCrayfish's machines... Freebi?

The mod does include a recipe book with the missing recipes. You get it by buying it from the computer. If JEI's not possible to fix, you can have people do that instead.

**Comment by Freebi85** [comment]
Yeah crayfish has a few "special* mechanics. Thanks for the heads up.

**Comment by Danekjovax** [comment]
Ultimate Stew does not recognize Zoestria Biomes' equivalents for ingredients.  So far I've seen it with Peach, but it could also be happening with any of its fruits.  Please allow them to be included.  Thanks!

**Comment by Freebi85** [comment]
Gonna close this since im working on a final release of DD&SS. Most of this issues are solved,
