### ISSUE TITLE
Osgloglas material lost the 'Global Traveler' trait

### ISSUE THREAD

**Issue by azmicomico** [Freebi85/Dungeons-Dragons-Space-Shuttles#448]
The latest changelog (6.3) mentions the removal of the 'Brown Magic' trait from Osgloglas, when making tinkers' tools.

I didn't see a mention to 'Global Traveler' also being removed, so maybe it wasn't intentional?

Can you confirm that I can "fix" it, by editing 'tweakersconstruct.cfg' and changing the line `osgloglas:all:sassy` to what it was before?

EDIT: Changing the config file mentioned above does restore the trait to osgloglas. Unfortunately, it doesn't give the trait back to your already made tools. Goodbye Heroic level Lasergun...

**Comment by Freebi85** [comment]
Sorry it was intended, forgot to mention in the changelog. There are still plenty of materials for Global Traveler like Alumite :)
