### ISSUE TITLE
Binnie's Drinks- All count as a single food?  Causing Problems with SoL/Food Book!

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#449]
When you have JEI extended overlay on and view a Binnie's drink, you see this:
![2019-10-28_21 45 13-sm](https://user-images.githubusercontent.com/10191173/67732516-01ca6300-f9d2-11e9-8f6d-8e3dc8a014ef.png)

And, Interestingly enough, when you craft even one of the drinks and drink it for the first time, SoL will count you drinking ALL of the drinks!
![2019-10-28_21 45 11-sm](https://user-images.githubusercontent.com/10191173/67732632-6980ae00-f9d2-11e9-82bb-73084cef3295.png)
![2019-10-28_21 45 12-sm](https://user-images.githubusercontent.com/10191173/67732633-6ab1db00-f9d2-11e9-99fd-30481816d2c2.png)
![2019-10-28_21 45 13-sm2](https://user-images.githubusercontent.com/10191173/67732639-6c7b9e80-f9d2-11e9-9433-eee6b1204cd7.png)
![2019-10-28_21 45 16-sm](https://user-images.githubusercontent.com/10191173/67732643-6f768f00-f9d2-11e9-8503-0baa6343134d.png)

However, it will only count as ONE of the foods you have eaten in the Food Journal - this causes a Desynch of the values of what you've eaten and the Foods you've Tasted:
![2019-10-28_21 44 45-sm](https://user-images.githubusercontent.com/10191173/67732712-9e8d0080-f9d2-11e9-8ec5-c1e8b2bf25a2.png)
![2019-10-28_21 44 52-sm](https://user-images.githubusercontent.com/10191173/67732718-a3ea4b00-f9d2-11e9-837a-55fefd1f0a1c.png)

I'm sure that the large reason for the difference in counts is the number of the Binnie's drinks (92 minus the one that counted minus something else?)

Not really sure what needs to be done to fix these problems (I think they're somewhat related but separate as well), but it will only cause confusion in the long run for those who want to pursue foods in DDSS.

Thanks for your time. ;2)

**Comment by Freebi85** [comment]
It looks like SOL have a problem with Oredictionary entries. If so then a lot of other things are affected by this as well. Example: Butter and Cocoa Butter. Sounds like somthing to report to their author^^

**Comment by Danekjovax** [comment]
Will do.  Thanks.

**Comment by Freebi85** [comment]
I mean SOL Carrot Edition^^

**Comment by Danekjovax** [comment]
https://github.com/ForestryMC/Binnie/issues/613

**Comment by Freebi85** [comment]
I'm going to close here. After following the conversation, the issue can only be fixed by binnis. They don't seem to be active at the moment. But I will continue to follow the issue.
