### ISSUE TITLE
Food Book - Foods Not Craftable/JEI Searchable (Compiled List)

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#450]
The following is the current list of Foods found in the Food Book that are listed as a food to eat, but not (currently) craftable and/or JEI searchable:

Akutuq (mentioned in https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/415)
Apple Cider (Pam's HarvestCraft)
Apple Snow (Pam's HarvestCraft)
Apple of Lofty Stature (Cyclic)
Arrowroot (Pam's HarvestCraft) (seed not enabled?)

Either find a way in the configs to enable the seed/crafting recipe, or disable it from showing up in the Food Book and removing it from the food list.

**Comment by Danekjovax** [comment]
One problem source is for the Pam's HarvestCraft seeds that have been disabled from spawning in "harvestcraft.cfg", line 307:
`seeds {
    B:agaveseeddropfromgrass=false
    B:amaranthseeddropfromgrass=false
    B:arrowrootseeddropfromgrass=false
    B:cassavaseeddropfromgrass=false
    B:chickpeaseeddropfromgrass=false
    B:elderberryseeddropfromgrass=false
    B:flaxseeddropfromgrass=false
    B:greengrapeseeddropfromgrass=false
    B:huckleberryseeddropfromgrass=false
    B:jicamaseeddropfromgrass=false
    B:juteseeddropfromgrass=false
    B:kaleseeddropfromgrass=false
    B:kenafseeddropfromgrass=false
    B:kohlrabiseeddropfromgrass=false
    B:lentilseeddropfromgrass=false
    B:milletseeddropfromgrass=false
    B:mulberryseeddropfromgrass=false
    B:quinoaseeddropfromgrass=false
    B:sisalseeddropfromgrass=false
    B:taronutseeddropfromgrass=false`

Enabling these will also enable many foods needing these ingredients.

**Comment by Danekjovax** [comment]
The file "solcarrot.cfg" can be used to blacklist foods, it appears.

Line 15 is where they are added.  Currently nothing is there.  

I would assume these are OreDict item names (which can be searched for in the "allitems.txt" (in C:\Users\<profile>\Documents\Curse\Instances\Dungeons, Dragons and Space Shuttles\config\multimob\modInformation).

**Comment by Freebi85** [comment]
We already talked about this. You are just going to duplicate issues. I already said im gonna enable the seeds again and blacklist all the things which arent craftable. And yes many things are removed because they are pointless^^ So it's intended not to be craftable. pls merge ALL food issues into https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/447
Thank you to keep clean my Github 💃

**Comment by Danekjovax** [comment]
Oops!  Sorry.  I'll keep future posts in there.  Any suggestions on what I should rename that issue?
