### ISSUE TITLE
Crafted Rock Crystal Ore not completing quest #218

### ISSUE THREAD

**Issue by Alcan4** [Freebi85/Dungeons-Dragons-Space-Shuttles#451]
You can't click on the ore picture in the questbook to see the recipe,
nor does it accept the ore you craft via the Luminous Crafting Table.

It seems to have the right item IDs

**Comment by Freebi85** [comment]
It's a block breaking task. Put it down and break the block :)

**Comment by Alcan4** [comment]
sorry im dumb
