### ISSUE TITLE
Tinkers Construct ( Modpack V 6.3 )

### ISSUE THREAD

**Issue by HelixRanmaru** [Freebi85/Dungeons-Dragons-Space-Shuttles#452]
Good afternoon,

It appears that the trait for Paper in Tinkers Construct might be off by a little bit unless the "Writable" trait is no longer a part of this pack. 

![2019-10-29_09 01 28](https://user-images.githubusercontent.com/57140181/67769395-c9a33e80-fa2a-11e9-8f31-0d6b3657c849.png)
![2019-10-29_09 01 30](https://user-images.githubusercontent.com/57140181/67769396-c9a33e80-fa2a-11e9-8f95-301f61ea0599.png)

**Comment by Freebi85** [comment]
Hello =)
This is correct, it was removed from paper and replaced with a bunch of other traits^^
