### ISSUE TITLE
Old lumium amount still given as reward

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#453]
In quest number 697, 1000mb of lumium is given in a cell. Since the update to 144mb increments, perhaps the reward could be changed to a wood tank with 1008mb in it.

**Comment by Freebi85** [comment]
Hey =)
I understand your point but no sorry. There are many more reward cells with liquid metals and I don't necessarily see it as a problem^^
