### ISSUE TITLE
Content Tweaker fluids don't have localized names

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#456]
Really minor issue, but I noticed in TOP that superglue looks like this in an Engineer's Workshop.  I assume the other CT fluids have the same problem.
![image](https://user-images.githubusercontent.com/3029695/67906504-8b556e80-fb53-11e9-8950-c62714973ee9.png)

Edit: Confirmed, same for `fluid.shibu`

**Comment by Freebi85** [comment]
I localized the name for Jei and the fluid containers. I can't localize it for TOP. Probably not compatible between artisan, contenttweaker and TOP. Can't do much there sry. If you still wish a fix contact the mod author pls :)
