### ISSUE TITLE
Quark's bookshelves are not compatible with Chisel

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#457]
Not knowing they had a different crafting recipe using stairs instead of planks, you can't chisel a Quark bookshelf into a Chisel variant or vice-versa.

**Comment by Danekjovax** [comment]
Have you tried looking at Quark's or Chisel's respective GitHubs to see if these issues have been mentioned there?

Interesting idea you have here, but I'm not sure if this is the best place to report this type of an issue, as it seems to relate to game mechanics more than an issue with a recipe or modifying one.

**Comment by DarkYuan** [comment]
Yeah, that makes sense. It's probably not best to make changes here.
