### ISSUE TITLE
Primitive mobs' mobs do not spawn unless it's a blood moon.

### ISSUE THREAD

**Issue by DannyDan4** [Freebi85/Dungeons-Dragons-Space-Shuttles#458]
In my playthrough of the pack, I've noticed that the only time a majority of the primitive mobs spawn (an exception being the brain slime) is during blood moons. I cannot get the primitive mobs to naturally spawn otherwise.

**Comment by drhaber** [comment]
I have the same issue, I am playing on a server

**Comment by DannyDan4** [comment]
I think this may actually have to do with spongeforge, rather than the modpack itself, so if you think it's justified to close, go right ahead.

**Comment by Freebi85** [comment]
Ah sorry i don't support serverside problems here. Use my discord Server for that. And yes it's sadly i known issue with spongeforge but there are a few people with a workaround in my discord if i remember correctly.
