### ISSUE TITLE
[QoL Suggestion]  Silicon Compound work reduction

### ISSUE THREAD

**Issue by Sartugha** [Freebi85/Dungeons-Dragons-Space-Shuttles#459]
The three Silicon compounds (Red, Glowing, and Electrotine) all have multi-step processes to them.  Perhaps add these recipes to the induction smelter and other Alloy furnaces to reduce the "Craft then Cook" process?  A Mystical Agriculture recipe would be pretty neat, too, but I'm not going to push my luck.

**Comment by Danekjovax** [comment]
Sounds good to me.  I'll second this. ;2)

**Comment by Freebi85** [comment]
Im ok with a Induction Smelter / Alloy Smelter recipe =)
