### ISSUE TITLE
Entangled chalice always produces frequency 0

### ISSUE THREAD

**Issue by DannyDan4** [Freebi85/Dungeons-Dragons-Space-Shuttles#460]
When I try to use entangled chalices, I always end up with a group ID 0, meaning that only one entangled chalice can be used per world. This is especially bad on servers where other players could then take your liquid you're trying to pump or provide.

**Comment by Freebi85** [comment]
Hmm In what version did you notice that? the chalice recipe is default since a few versions to avoid such problems.

**Comment by Freebi85** [comment]
?

**Comment by DannyDan4** [comment]
I apologize for the delay. the replication of chalices is fine, the issue is when I make the chalices in the 5x5 crafting table, it always outputs frequency 0. This was done in the latest version.
