### ISSUE TITLE
crash on loading saves, backups and created new world

### ISSUE THREAD

**Issue by Vendet29** [Freebi85/Dungeons-Dragons-Space-Shuttles#461]
My game saves start crashing i have only my main and test world.  I tried my backups saves and they crash to, so i make new clean DDSS install and I was abel to create new world and it loads normal, but when i copy my save/backups to saves folder they crash and that new created world that works before, crashed to. 
New World pastebin after copying old saves - https://paste.dimdev.org/kucenivapi.mccrash
Old save pastebin - https://paste.dimdev.org/ucusedavob.mccrash

**Comment by Freebi85** [comment]
Hey =)
For some reason you are not recognized as "online" and your loaded chunks keep crashing the game.
Maybe somthing with the new Java update i don't know. However; try to update FTB Lib and Utils manually, maybe this fix the problem. Gonna update anyway in next patch.
Pls use our tech support in our discord Server for further crashes 💃 
cheers
