### ISSUE TITLE
[Mod Suggestion] MCMultipart for Mekanism cable covering. 

### ISSUE THREAD

**Issue by Arcanien** [Freebi85/Dungeons-Dragons-Space-Shuttles#463]
For the use of power transfer I really like using Mekanism's Universal cables since it automatically transfers between most power types. However I have found it frustrating that I can't cover up the cables. Looking up online I have discovered that Mekaniasm has the capability of having covers with their cables through the Mod [_MCMulitpart._](https://www.curseforge.com/minecraft/mc-mods/mcmultipart) I had went to the Mekanism discord and found this out since I only found controversy on whether it worked or not online. I have personally downloaded that mod into the modpack and was able to use Chisel & Bits to cover my Mekanism cables. Unfortunately it looks like Little Tiles doesn't work even though I like that mod more. I know for the meantime I'll just use it in my modpack, but there were some others that didn't think there was any way to cover their Mekanism cables within the DD&SS discord. Wasn't sure if you knew about this either or if there was specific reason you didn't include it.

**Comment by Freebi85** [comment]
Hello :)
I'm very sorry but the modpack is in a pre-final status where I will not add any more mods now.
