### ISSUE TITLE
Sticks in TechReborn Grinder yields Bonemeal

### ISSUE THREAD

**Issue by Seizewell** [Freebi85/Dungeons-Dragons-Space-Shuttles#464]
Title says it all: putting a Stick in the TechReborn Grinder gives 6 Bonemeal. I don't think that's intended. 
![2019-11-03_19 58 26](https://user-images.githubusercontent.com/44748801/68090468-5f4c2d00-fe74-11e9-85d0-2b641d8de8fd.png)

**Comment by Freebi85** [comment]
Öhm Kappa :D 
Thanks ill take a look ^^

**Comment by Danekjovax** [comment]
Confirmed. 
![2019-11-04_23 14 26](https://user-images.githubusercontent.com/10191173/68178165-e246b380-ff58-11e9-8f01-b2c80990974c.png)
![2019-11-04_23 14 35](https://user-images.githubusercontent.com/10191173/68178166-e4a90d80-ff58-11e9-9179-7cf70af9a9bd.png)
