### ISSUE TITLE
EU2 Creative Builder's Wand?

### ISSUE THREAD

**Issue by sixtysixone** [Freebi85/Dungeons-Dragons-Space-Shuttles#465]
Hi - Is ExtraUtils2's "Creative Builder's Wand" intended to be ... well, creative? It doesn't duplicate blocks, and just acts like a larger version of the normal Builder's Wand.

Playing on a server, only extra mods are for profiling lag (laggoggles, tickprofiler, etc).

Craft Creative Builder's Wand after spending days hunting down ancient dusts and crafting majestic ingots.

Expected: R-click on block. Get dupe of block (and nearby of same block).
Actual: Nothing happens unless block is in inventory. Places just like normal builder's wand.

 Thanks!

**Comment by Freebi85** [comment]
Hello 🙂
That would actually have been the purpose of this item. Thanks for reporting. Since I can't fix it myself and the EU2 mod was abandoned  I will probably remove the item completely and look for an alternative. If i find something useful you can convert your useless wand to the new item :)

**Comment by sixtysixone** [comment]
Excellent, thank you!

**Comment by sixtysixone** [comment]
Sounds good! I'll just refund myself the ingredients to creative builder's wand and work towards that when it's updated. Thank you for this! (On top of the heaps of thanks for such an awesome pack).

**Comment by Freebi85** [comment]
Your most welcome! But maybe you don't like me so much anymore after the new draconic duper recipe lol :D

**Comment by sixtysixone** [comment]
Why, is it going to be too easy? :manicgrin:
