### ISSUE TITLE
Chemical Reactor- Corn to Carrot??

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#466]
Not sure if this is your doing, Freebi, but I saw this recipe:

![ChemReactor-CorntoCarrot](https://user-images.githubusercontent.com/10191173/68180139-87b15580-ff60-11e9-9450-d8176c51c46b.png)

Shouldn't the corn instead be a carrot?

**Comment by Freebi85** [comment]
Probably because TechReborn use Oredict entries like allveggis to make this golden carrot^^ No Big deal for me. Thanks anyway 💃
