### ISSUE TITLE
Resonant Fluxducts still require 1000mb of Lumium instead of 1008.

### ISSUE THREAD

**Issue by Sartugha** [Freebi85/Dungeons-Dragons-Space-Shuttles#468]
Title says it all, Resonant fluxducts require 1000mbs of Lumium instead of 1008. 

![2019-11-05_11 39 24](https://user-images.githubusercontent.com/57288542/68231580-f1f9e280-ffc0-11e9-8b8c-c65e63ac32d0.png)

**Comment by Freebi85** [comment]
Feelsbad :D
