### ISSUE TITLE
Pulverizer Recipes for Underground Biomes

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#469]
Need a way to process UB cobble into (UB?) gravel and for UB gravel into sand

**Comment by Freebi85** [comment]
Hey =)
I agree with UB Cobble to Gravel and maybe UB gravel to sand but i don't gonna convert every single gravel type as well^^

**Comment by DarkYuan** [comment]
Well as long as the compressed gravel uncompressing recipe still doesn't need a chisel, that's fine
