### ISSUE TITLE
Blood Moon Crash

### ISSUE THREAD

**Issue by DragonTamr34** [Freebi85/Dungeons-Dragons-Space-Shuttles#47]
Since the most recent update, every blood moon has crashed my game. This is the crashlog:
https://pastebin.com/Wqa5B9S4

**Comment by Freebi85** [comment]
Thanks for your report. I will forward it to the developers of bloodmoon. I hope they can find a solution for this problem.

**Comment by DragonTamr34** [comment]
The game lags and uses a ton of memory, then crashes. It could be the number of mobs and mob types spawned during the blood moon. Using only the Bloodmoon mod there are no crashes.

**Comment by Freebi85** [comment]
I have created several blood moons in different worlds for testing and cannot confirm this. Nevertheless I forwarded yours to find the error. I can't fix chrashes without knowing exactly what caused it in the coding. Therefore I have to wait for the developers. If they take care of it...... :/

**Comment by antiqque** [comment]
I disabled blood moons but i still get the crash, this is the crash log:
https://pastebin.com/t5Xq1tj1

Yes, i have a couple of extra mods but they don't affect mobs in any way and i was getting the crashes before i added them too.

The only fix that works is spamming "/kill @e" commands in the console while logging in ( if i do it only before it still crashes when i spawn ) so i deducted it's something that happens only when users are present in the world.

**Comment by Freebi85** [comment]
Oh cool I will include and observe that in the next update. I leave the issue a bit open.  You can contact me if something changes or stays stable. thanks for this info
