### ISSUE TITLE
Idea for converting cobble

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#470]
Maybe the enrichment chamber could turn UB cobble and gravel into their vanilla counterparts, since the artisan's chisel appears to be the only way even late-game.

**Comment by Freebi85** [comment]
Sounds good to me. Probably not anymore for upcoming patch but why not.

Hint: Remeber there is also the Igneus Extruder to create some UB Stone variants.
