### ISSUE TITLE
crash after clicking on a Relic Trader

### ISSUE THREAD

**Issue by FreeYourMind1** [Freebi85/Dungeons-Dragons-Space-Shuttles#471]
**issue**
i found a house with 2 villagers in it, one is a fletcher and the other one is a Relic Trader and after clicking on the relick trader the game crashes.

**Modpack Version**
6.3

https://paste.dimdev.org/ujifarikon.mccrash

**Comment by Freebi85** [comment]
Thanks for reporting. From which mod is the relic trader; immersive?^^ Pls report the crash to the author, i can't fix such a crash myself :/

**Comment by FreeYourMind1** [comment]
i have no idea from which mod the villager is. it must be one of the mods that adds buildings to the world.
