### ISSUE TITLE
rolling machine and other ways to dupe iron and gold

### ISSUE THREAD

**Issue by danielrab** [Freebi85/Dungeons-Dragons-Space-Shuttles#472]
1) the big one: the rolling machine can easily dupe iron by crafting minecarts, hoppers, ect. and gold by crafting powered rails. you can get more iron/gold back using smeltery.
2) crafting golden rails and then smelting it in the smeltery converts 2 iron, 17 redstone, a stick and 4 gold into 8 gold.
3) crafting a copper chest, upgrading it to iron and smelting it in the smeltery converts 14 copper, 4 glass and 8 planks and 4 iron into 8 iron

**Comment by Freebi85** [comment]
thanks for reporting, will look into it :)
