### ISSUE TITLE
Corail Tombstone is totally unbalanced

### ISSUE THREAD

**Issue by danielrab** [Freebi85/Dungeons-Dragons-Space-Shuttles#474]
in Corail Tombstone, there's a thing called "knowledge of death". it allows you to
1) teleport back to your place of death
2) find structures and teleport to them, including end cities, giving you an early end acces
3) be invincible for 90 seconds after death, allowing for fast LP generation

probably there's more.

i am not sure if it can be balanced without a replacement mod.

**Comment by Freebi85** [comment]
I am aware of the potential of this mod but there are no plans to replace it in 1.12. The recent Halloween event unlocked all the perks temporarily.
