### ISSUE TITLE
stones from underground biomes drop redstone, lapis and gold nuggets

### ISSUE THREAD

**Issue by danielrab** [Freebi85/Dungeons-Dragons-Space-Shuttles#475]
stones from underground biomes drop redstone, and gold nuggets.
block placers + block breakers + furnaces + stone from underground biomes = infinite gold, redstone or lapis, depending on the type of stone and altitude.

**Comment by Freebi85** [comment]
I can't interact with Underground Biomes extra drops. Pls report to the mod Author.

**Comment by drhaber** [comment]
Do you have fortune on your pick? I noticed these drops only began when I enchanted my pickaxe
