### ISSUE TITLE
Ingot Former has two recipes that use Molten Milk Chocolate, only one is accessible.

### ISSUE THREAD

**Issue by Jemmysponz** [Freebi85/Dungeons-Dragons-Space-Shuttles#476]
There are two recipes that the NuclearCraft Ingot Former uses milk chocolate for, one using 144 mb of Molten Milk Chocolate and one using 1000 mb of Molten Milk Chocolate, and only the former recipe is used by the Ingot Former.

**Comment by Freebi85** [comment]
Ah hank you! The galacticraft chocholat bar should only be made by galacticraft machines and pixie dust^^ It's a different ingredient from the chocolat milk.
