### ISSUE TITLE
Hovering Hourglass recipe needs 3000 mB Lumium to craft instead of 3024

### ISSUE THREAD

**Issue by merphle** [Freebi85/Dungeons-Dragons-Space-Shuttles#477]
DDSS version 6.3.

The recipe for Botania's Hovering Hourglass in the Mage's Workshop requires 3000 mB Molten Lumium, which is an awkward amount.

**Comment by merphle** [comment]
Also all 25 of the Molten Lumium-based recipes in the Engineer's Workshop require multiples of 1000 mB. Most of the Carpenter recipes are multiples of 1000 mB, but some are multiples of 144 mB.

**Comment by Sartugha** [comment]
Seconded.  Most all of these recipes are the thermal duct items such as:
Resonant Fluxduct
Signalum-Plated Fluxduct
Signalum-Plated Itemduct
Signalum-Plated Itemduct (Opaque)
Quintuple Battery
Quadruple Battery
Impulse Itemduct
Impulse Itemduct (Opaque)
Signalum Plated Impulse Itemduct
Signalum Plated Impulse Itemduct (Opaque)
Super Laminar Fluiduct (Opaque)
Super Laminar Fluiduct
Vacuum versions
Dense Versions
Hovering Hourglass

The amounts are not set for even ingot amounts for the normal recipes or the boosting mixture recipes.
