### ISSUE TITLE
Mod Suggestions (Laser Creeper Robo Dino Riders From Space/Trumpet Skeleton)

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#479]
Freebi,

Please consider adding these two small mods:

Laser Creeper Robo Dino Riders From Space (https://www.curseforge.com/minecraft/mc-mods/laser-creeper-robot-dino-riders-from-space/files/2568686)
Trumpet Skeletons (https://www.curseforge.com/minecraft/mc-mods/doot/files/2549462)

Why?  Because we need more space stuff, and LCRDRFS fits that bill in such a fun and challenging way!  Also because who doesn't love/hate a skeleton chasing you at night blasting his trumpet!?

**Comment by Seizewell** [comment]
Yes please :D

**Comment by Danekjovax** [comment]
Also, there are random "invasion" events that trigger with the Laser Creeper mod.  It would be a nice touch to have them trigger starting the time a player achieves completion of Tier 3 or 4 Main Quest, so it's not too much of a burden to be ransacked by laser toting creepers riding mecha T-REXX 1000's!

**Comment by Freebi85** [comment]
Hmm, i am really the last one who wants to disappoint you but even more mobs is not good for this pack. Forge Servers have already to "fight" with ticking errors^^

**Comment by Danekjovax** [comment]
If I can make a case where adding one or both is minimal extra footprint for a server, would you be more willing?

**Comment by Freebi85** [comment]
Sorry I don't want to add any more mods that add additional animals or mobs atm :(
