### ISSUE TITLE
Sandy-Coal Compound

### ISSUE THREAD

**Issue by Enomin** [Freebi85/Dungeons-Dragons-Space-Shuttles#48]
First off thanks for all the great work.
and a merry Christmas.

i have a tiny problem in the new update.
25-12-2018
Quest item sandy coal compound not being "detected"
Quest is not completing.

26-12-2018
Quest Floral Powders crafting the Floral Cyan Powder  is not being detected
Quest is not completing

Both of these quests are crafting Tasks so perhaps the problem is there.
I am playing on a server in a team and in a party.

**Comment by Freebi85** [comment]
Thank you so much! Glad you like it. I will adjust the tasks so that the items are recognized. sorry for the circumstances.
