### ISSUE TITLE
Crystal Cluster

### ISSUE THREAD

**Issue by Palbosa** [Freebi85/Dungeons-Dragons-Space-Shuttles#480]
I almost completed my book quest.

To be able to finish all the book, I stumble across a quest asking me to make a Blood Magic Crystal Cluster.

That item doesn't appear in JEI and doesn't seem to have a crafting recipe.

Any way to solve this ?

**Comment by Freebi85** [comment]
Hi =)
Yes it's broken since latest bloodmagic update. It's fixed in upcoming patch this weekend :)
