### ISSUE TITLE
Add a pair of shapeless recipes to "toggle" between Tinker's Construct Expander Horizontal and Vertical

### ISSUE THREAD

**Issue by merphle** [Freebi85/Dungeons-Dragons-Space-Shuttles#481]
The Expander Horizontal and Expander Vertical are the same recipe, just rotated 90 degrees (horizontal vs vertical - clever :) ). Please create a shapeless recipe that accepts a Horizontal as input and outputs a Vertical, and vice-versa.

A niche situation, sure, but nice if someone (like me) goofed and made the wrong one.

**Comment by Freebi85** [comment]
Hello =)
Well JEI is pretty clear how to craft which one tbh so i don't see necessarly an issue there BUT i will chage the required plates to make it more clear. Shapeless recipes in 5x5 crafting is gonna mess things up^^

**Comment by merphle** [comment]
I was thinking more that the two existing shaped 5x5 recipes are perfect and could be left as-is. Adding two more recipes (shaped or unshaped) to convert between the two outputs is what I'm talking about. 

My particular situation is that I made one Expander Horizontal, applied it to my hammer, liked the result and wanted to put a second (or more) Expander Horizontal on my hammer, only to realize that max is one. So letting me convert it to a Vertical would be a nice nod towards letting me recoup my costs. Like I said, probably a niche situation, but I bet I'm not the only one.

Something like this (bear with me, my first time writing MC script):

# Expander Horizontal -> Vertical
recipes.addShapeless(<tconstruct:materials:13>, [<tconstruct:materials:12>]);
# Expander Vertical -> Horizontal
recipes.addShapeless(<tconstruct:materials:12>, [<tconstruct:materials:13>]);

Thanks for all your hard work on the pack btw. My friends and I hare having a great time. :)

**Comment by Freebi85** [comment]
Oh lol that’s not a problem, I'm sorry I misunderstood you.
