### ISSUE TITLE
Suggested additional automation for Project Red coils

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#483]
Similar to how basic and advanced coils from AA are made in the rolling machine, could i suggest a recipe for making the copper, iron, and gold coils from PR in the rolling machine like: `M, M, R = C x3`, where M = the block of metal (copper, iron, or gold), R = a block of redstone, and C is the appropriate coil. Maybe x4 as an output to give the recipe a slight buff. Or maybe `M, r, r, r, r = C x2` with dust would be better.

**Comment by Freebi85** [comment]
Sounds good^^I'll edit a possible recipe.
