### ISSUE TITLE
Recipe Suggestion: The Rotary Condensentrator/Supercooler Liquid Gases

### ISSUE THREAD

**Issue by drhaber** [Freebi85/Dungeons-Dragons-Space-Shuttles#484]
The Rotary Condensentrator from Mekanism and/or the Supercooler from NuclearCraft should also support the liquid Gases from Galacticraft Planets and Extra planets.

Additionally at first glance some liquids and gases, such as liquid nitrogen ~~or Oxygen (gas)~~ are not transformable using the Liquid Dictionary converter.

**Comment by Freebi85** [comment]
The Rotary Condensentrator from Mekanism dosen't support changes for External mods afaik.

Which gases exactly are you missing to be "cooled" from the nuclearcraft machine?^^

**Comment by drhaber** [comment]
Liquid Argon is the only one actually... I noticed, assuming fluid dictionary consolidation, all the others can be made using Mekanism NuclearCraft or Rockhouding chemistry.

As far as I can tell some of the Galacticraft Planets and Extra planets fluids have no converting recipes:
Liquid Glowstone -Extra Planets (could be converted to molten glowstone) 
Liquid Nitrogen -Extra Planets 
Liquid Methane -Extra Planets -no none use (perhaps the Expansion Chamber from Rockhouding chemistry to convert to Methane Gas) 

Liquid Methane - Galacticraft Planets -no none use (perhaps the Expansion Chamber from Rockhouding chemistry to convert to Methane Gas) 

Liquid Nitrogen - Galacticraft Planets (this one can currently be converted using the Supercooler from NuclearCraft which seems incorrect)

**Comment by Freebi85** [comment]
Gonna Close this for now since im working on a final update for DD&SS to end the project. Don't have the time for this implementations and changes.
Maybe I will take a look at it again in the future when i came back to the project.
