### ISSUE TITLE
Lootbags give out Ice & Fire silver ingots instead of unified Thermal ones

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#486]
Self explanatory

**Comment by binh3012** [comment]
Yes. Me too.

**Comment by newt111** [comment]
On 6.5, and Ice and Fire silver nuggets are still loot bag rewards
![2019-11-25_23 24 41](https://user-images.githubusercontent.com/6668735/69601972-8f9e6b80-0fdb-11ea-91dc-a7294032ddf3.png)

**Comment by Freebi85** [comment]
Hm feelsbad. thanks for he heads up. But the nuggets should at least be crafted to a regular thermal ingot. Still gonna change asap.
