### ISSUE TITLE
There are no quests labeled as Main Quests in Tier 0

### ISSUE THREAD

**Issue by merphle** [Freebi85/Dungeons-Dragons-Space-Shuttles#487]
DDSS version 6.3

None of the quests in the "Tier 0" section are labeled as main quests. If this is a conscious decision by the pack owners, then disregard this. Otherwise, I would suggest that all of the quests leading to six of the eight end goals on the right (everything except Kitchen & Protectors) should be flagged as Main Quest.

I have a few new people who joined my server. They're working their way through Tier 0 now, and it's frustrating me that I can't just tell them to follow the quests that have the fancy border, like I know I'll be able to do once they hit the other quest pages. :)

**Comment by Freebi85** [comment]
Hello =)
There are no "mainquests" in Tier 0 because you can see everything... and you can just follow you favorit path.^^ So there is no reason to make exclusive mainpaths to all the specific chapters for me sorry^^

**Comment by merphle** [comment]
Totally fair point, and no need to apologize. :)
