### ISSUE TITLE
CTM breaking whenever you're running a resource pack

### ISSUE THREAD

**Issue by DannyDan4** [Freebi85/Dungeons-Dragons-Space-Shuttles#488]
When running a 64x resourcepack, be it pureBDcraft or the freebi's mix pack that comes with the modpack, CTM stops functioning properly. This is demonstrated with pureBDcraft, but tested with both in my base, screenshots attached.
![2019-11-09_23 16 52](https://user-images.githubusercontent.com/27591249/68539440-c163d100-0351-11ea-9a30-2c4915d9283f.png)
![2019-11-09_23 23 39](https://user-images.githubusercontent.com/27591249/68539441-c163d100-0351-11ea-80b8-24e209d52b16.png)

**Comment by DannyDan4** [comment]
However, this is not an issue with CTM itself, as I tried downgrading CTM, with no change. I also tried installing optifine to see if that changed anything, with no difference.

**Comment by Freebi85** [comment]
I apologize but i have no clue how 64 resourcepacks can interact with this. It seems the resourcepack dosen’t matter. I can’t help you there for such an issue. I suggest to report it to the author so they can investigate some interactions.

**Comment by DannyDan4** [comment]
Could you reopen this? In doing some experimentation, it appears downgrading chisel to what was in 6.3 is all that is needed to fix the issue.

**Comment by Freebi85** [comment]
Should be solved with latest Resourcepack release V. 1.3^^
https://www.curseforge.com/minecraft/texture-packs/official-dd-ss-64x64-texturepack/files
