### ISSUE TITLE
Invalid dimension Moon Crash 

### ISSUE THREAD

**Issue by Trunks19814** [Freebi85/Dungeons-Dragons-Space-Shuttles#49]
Hi 
ich habe heute das modpack Geupdatet und nun stürzt bei mir das Spiel. Egal ob neue Welt oder das Save Game.

https://pastebin.com/pHVcFPqJ

**Comment by Freebi85** [comment]
Entferne Optifine, diese mod wird fast nirgends mehr für einen sicheren Ablauf unterstützt da sie nicht immer mit forge mods kompatibel ist. Besonders nach Updates kann das ne Weile dauern bis wieder eine funktionierende Version kommt.

**Comment by Freebi85** [comment]
Es hat sich rausgestellt das das spiel crasht wenn die Sprache auf Deutsch eingestellt ist. Setzt man sie wieder auf englisch sollte es wieder laufen. Ich werde bis zum nächsten patch entweder weider die alte Version einfügen oder warten bis Galacticraft die Fehler behoben hat.

**Comment by Trunks19814** [comment]
thx werde es mal probieren .

Das modpack macht richtig spaß. hab heute das erste mal nen drachen gefunden und mich dazu mal informiert. da hast du dir aber richtig mühe gegeben. :+1:

**Comment by Freebi85** [comment]
Danke freu mich das es dir gefällt :D

**Comment by Trunks19814** [comment]
Eine kleine Rückmeldung und zwar läuft es jetzt mit der neuen Version, konnte mein spielstand auch übernehmen. Einfach das game auf Englisch stellen und anschließend ein Backup datei vom letzten Speicher punkt aufspielen und nun läuft es . :+1:
