### ISSUE TITLE
Mod Suggestion: Immersive Cables

### ISSUE THREAD

**Issue by drhaber** [Freebi85/Dungeons-Dragons-Space-Shuttles#490]
[This mod](https://www.curseforge.com/minecraft/mc-mods/immersive-cables) adds Immersive engineering themed cables for [Refined Storage](https://media.forgecdn.net/attachments/221/676/2017-12-22_23.png) and [Applied Energetics 2](https://media.forgecdn.net/attachments/221/674/2017-12-22_23.png). I think it would be a great Aesthetic addition.

**Comment by Freebi85** [comment]
Well maybe it's not bad^^ But it hasn't been serviced for over a year and I have too many mods that are causing me more and more problems due to lack of maintenance. I'm sorry, :(
