### ISSUE TITLE
smeltery #2 quest

### ISSUE THREAD

**Issue by dayneschicktanz** [Freebi85/Dungeons-Dragons-Space-Shuttles#491]
so I updated my game to the newest version but can't update quest book, says I don't have permission to use this command. cant turn in the grout. how do I fix this????

**Comment by Freebi85** [comment]
If you are playing singleplayer -> Open your game to lan when ingame and allow cheats. Then you can enter the command. If you are on a server then this has to be made from your server admin in the server console :)
