### ISSUE TITLE
Texture Pack (Suggestion): Add to Twitch Launcher

### ISSUE THREAD

**Issue by noodlenoggin34** [Freebi85/Dungeons-Dragons-Space-Shuttles#492]
Resource packs can be attached to the pack in the Twitch launcher, which would make it a lot easier for people using it to use the new texture pack. 

If there is an issue with adding too much to the file size, then you could load a single default resolution instead of all of them.

**Comment by JFMillerUSA** [comment]
[[128x - 32x] Dungeons, Dragons and Space Shuttles [MC1.12]](https://bdcraft.net/community/releases-for-packs-f10/dungeons-dragons-and-space-shuttles-t7206.html)

**Comment by Freebi85** [comment]
There is an extra curse project just for the texturepack which is linked everywhere^^ Discord and Curse mainpage. The official comes with a resolution of 64x64. No other resolutions available.
