### ISSUE TITLE
New Electrotine Seed Recipes

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#493]
Now that the electrotine essence only makes dust without iron, maybe the seed recipe should use a custom electrotine dust block, similar to redstone made from just dust instead of the alloy.

**Comment by Freebi85** [comment]
The Essence makes both, you can just use iron ingots (or iron essence) to make Electrotin ingots instead of only the dust so there is no reason to simplify the recipe for me. Thanks anyway for your Feedback, i apprecieate it :)
