### ISSUE TITLE
EvilCraft Broom is using 10x as much blood in pack version 6.4 vs earlier versions

### ISSUE THREAD

**Issue by merphle** [Freebi85/Dungeons-Dragons-Space-Shuttles#495]
DDSS6.1/config/evilcraft.cfg:    I:broom.bloodUsage=1
DDSS6.3/config/evilcraft.cfg:    I:broom.bloodUsage=1
DDSS6.4/config/evilcraft.cfg:    I:broom.bloodUsage=10

**Comment by Freebi85** [comment]
Hello =) This is intended since it's usable pretty early. Just missed to write it into Patchnotes. Thanks for the heads up :)
