### ISSUE TITLE
DynamicSurroundings causes crash during startup when enabled.

### ISSUE THREAD

**Issue by TheWyzer** [Freebi85/Dungeons-Dragons-Space-Shuttles#496]
Under 6.3 I was using the DynamicSurroundings-1.12.2-3.5.4.3.jar.  When transferring to 6.4a/b it causes the game to crash during mod loading (launch).

Can provide logs if needed.

**Comment by Freebi85** [comment]
Heyho. i didn't testet DynamiS. anymore since its disabled by default. Probably also outdated. Did you testet to update just DS itself?

**Comment by TheWyzer** [comment]
No, I will give that a shot and thanks for the reply.  Will update, for knowledge base.

**Comment by TheWyzer** [comment]
Current Dynamic Surroundings (1.12.2-3.6.0.2) is only compatible with Animania 1.7.2 or higher.

So RIP Dynamic Surroundings for now I guess.

**Comment by Rdf** [comment]
I am using DynamicSurroundings 3.5.4.3/OreLib 3.5.2.3 (not sure if this is correct, but works)

**Comment by Freebi85** [comment]
I don't know if it's possible to use¨this orelib version in most recent update. But if it works why not :)
