### ISSUE TITLE
Fix for Freebi's Resource Pack and Chisel

### ISSUE THREAD

**Issue by Hachuurui** [Freebi85/Dungeons-Dragons-Space-Shuttles#497]
I made a correction to the Freebi's Resource pack for DDSS to fix the chisel graphics issue. I checked other mods and didn't see any other texture connection issues.

Here is a link to the modified version for you to review.

https://drive.google.com/file/d/1NgqkXcWiivAGWR0cHBEE5OAN66PmydPc/view?usp=sharing

Soon as you have it let me know on here so I can remove it from my drive XD

**Comment by Freebi85** [comment]
You sir are amazing! 😉 give me a bit time to include it in latest resourcepack version. Gonna close here when im done. ♥️

**Comment by Hachuurui** [comment]
Hehe no worries, and I apologize in advanced if I missed anything, but I think I got all of them :p

**Comment by Freebi85** [comment]
So i checked and uploaded the new files to curse. Thx again for the work! If i mss something i let you know :P
