### ISSUE TITLE
No Way To Get Terrax

### ISSUE THREAD

**Issue by intoxicatedpenguin** [Freebi85/Dungeons-Dragons-Space-Shuttles#498]
I'm looking at the Orechid recipe but there is no way to obtain terrax to make a terrax block it looks like, unless JEI doesn't show a recipe for it. I don't see anywhere online referencing the alloy or material or whatever.

**Comment by intoxicatedpenguin** [comment]
nvm im stupid

**Comment by Freebi85** [comment]
lul :D
