### ISSUE TITLE
Broken Advancement and Title

### ISSUE THREAD

**Issue by 0Samuro0** [Freebi85/Dungeons-Dragons-Space-Shuttles#500]
After eating standard ration, got this message "0samuro0 just gained the achievement advancements.dungeoneering.born_survivor.title!
advancements.dungeoneering.born_survivor.description"

![image](https://user-images.githubusercontent.com/40067707/69130677-f8f51a80-0ac1-11ea-83bf-46d2d81dba0b.png)

**Comment by dierke9** [comment]
This is not a pack problem but a mod problem. Their language files are not correctly set up.

Please report this to the mod author of whatever mod the rations are

**Comment by 0Samuro0** [comment]
ok, thx
