### ISSUE TITLE
Opening modpack error

### ISSUE THREAD

**Issue by sulit04** [Freebi85/Dungeons-Dragons-Space-Shuttles#503]
Hello! I was attempting to open the pack for the first time, but this error popped up:

![image](https://user-images.githubusercontent.com/58111380/69479699-4fb66900-0dce-11ea-9125-48cdefbecab3.png)

I am unsure how to fix it because it says the mod causing the error is unknown.
Can anyone help me out?

**Comment by Freebi85** [comment]
Raise your Ram in the twitch launcher to 8GB. (i hope you have more then 8GB in your system?) Or you can't launch the pack^^ Join our disord server so we can help you better if you have more trouble.
Cheers
