### ISSUE TITLE
Nether Mobs

### ISSUE THREAD

**Issue by JFMillerUSA** [Freebi85/Dungeons-Dragons-Space-Shuttles#504]
Not much of an issue for some but the mobs in the nether seem to be OP a little bit. Can't even mine anything, get killed right after going through portal. Unless I'm missing something.

**Comment by Freebi85** [comment]
Hi^^
Well the Nether is no joke in this pack :P But there are a lot of tricks you have to use to survive like shields and ranged weapeons. Certain tinkersconstruct shields are particularly well suited for this. Join our discord channel. There are so many tips that players can give you to make your life easier :D
