### ISSUE TITLE
Won't launch, downloaded with twitch launcher

### ISSUE THREAD

**Issue by matthewpugs** [Freebi85/Dungeons-Dragons-Space-Shuttles#506]
Failed to download file, the file contents differ from what was expected.
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Filename on disk: jna-4.4.0.jar
Path: C:\Users\Matthew\Twitch\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Exists: File

**Comment by Freebi85** [comment]
Sorry but that's a twitch related issue. You can join our discord server for some tipps and tricks by players or switch to the MultiMC launcher which seems to run much better and almost no issues^^
