### ISSUE TITLE
Bibliocraft breaks JEI search nearby inventories

### ISSUE THREAD

**Issue by Bang257** [Freebi85/Dungeons-Dragons-Space-Shuttles#507]
## Modpack Version: 
6.5

## Bug Report:
Having Bibliocraft Typesetting table or Printing Press placed on the ground breaks the JEI "search nearby inventories" capability (T key by default). This prevents searching nearby inventories unless breaking and picking the two Bibliocraft machines back up.

## Expected Behavior/Suggestions:
Having the bibliocraft machines placed should not prevent "search nearby inventories" from functioning

## Is It Repeatable? Steps to Reproduce: 
1. Place Typesetting Table or Printing Press
2. Have a chest full of items nearby
3. Search for an item in one of the chests by hovering over one you have or one from JEI and pressing T.
4. Expected result is to show particles on the chest containing the items, actual result is nothing happens

## Link to Log or Crash File Paste**: 
https://pastebin.com/LxhiTyNU

## Mod/s Affected: 
Bibliocraft 2.4.5
JEI 4.15.0.292

**Comment by Freebi85** [comment]
Hello =) This is a mod related issue and i can't do much against this. Pls Report such issues to the Authors. 
The issue between Bibliocraft and Extra Utilitis, not JEI. Anyway both mods are discontinued so i don't think this will ever be fixed for Minecraft 1.12.2.

Edit: Was already reported but, as expected, no answer. So im gonna close sorry.
https://github.com/Nuchaz/BiblioCraft/issues/671
