### ISSUE TITLE
Upper Tier RebornStorage Recipes Don't Have an Increased Yield From Boosting Mixture

### ISSUE THREAD

**Issue by PatrickZergRush** [Freebi85/Dungeons-Dragons-Space-Shuttles#508]
Most of the storage disks don't produce 2 when using a boosting mixture. 
Thanks!

Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by Freebi85** [comment]
Hello =) 
The Boosting Mixture Basically increases the speed of each recipe so that all of them can be produced almost instantly. And as described in the tooltip, it only increases the output of some recipes but not all.
Some higher tiers are excluded. Same for AE2/RS
