### ISSUE TITLE
Players unable to update modpack to 6.5 due to mod missing or no longer available.

### ISSUE THREAD

**Issue by Hachuurui** [Freebi85/Dungeons-Dragons-Space-Shuttles#509]
This is probably an issue with twitch but so you're aware, players on my server are getting the following error when trying to update the modpack.

This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 246761

**Comment by Freebi85** [comment]
Check this link pls =)
https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/506

**Comment by Hachuurui** [comment]
Yeah I basically had them use multimc :p Seems all modpacks are having the issue atm.
