### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by CaptianBoo** [Freebi85/Dungeons-Dragons-Space-Shuttles#510]
> Unable to get Addon: Dungeons, Dragons and Space Shuttles (301717) - File ID: 2831468

Sometimes it wouldn't even try, others it would just quit for no reason. I tried around 20 times and only got to downloading about half the files before it quit twice.

**Comment by CaptianBoo** [comment]
Tried again, got about half the files before quitting

> This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 297039

**Comment by Freebi85** [comment]
You can't download packs at all today. Twitch is compeltely broken for every Pack.
You can keep trying, wait for tomorrow or just switch to the multimc launcher. 
If you need some help for this pls join our discord Server.
