### ISSUE TITLE
Spelling Mistakes

### ISSUE THREAD

**Issue by PatrickZergRush** [Freebi85/Dungeons-Dragons-Space-Shuttles#512]
I am going through Tier 3 having a blast (hehe). I noticed a few typos in the quests and I figured,, while I am on a github spree, I should mention these as well. I apologize in advance if these are fixed in 6.4, as I haven't been able to update from 6.3 yet. Thanks for putting together this fun modpack! 

Chemical Reactor : says quantitis. Should say quantities. 
Industiral Electrolyzer! : Title should say Industrial
Elite Control Circuit : Says Expansive but I think it means to say expensive.
Boron - Aresenic Mix #step7 : quest title might have meant to say Boron - Arsenide
Thermoconducting Alloy : Says thermoCUNducting and Arsenid(e) 
Chrushed Arsenic : Title says Chrushed. Description text says Smerltery
Copper Selenoid: Says Selenoid instead of Solenoid in the title
Boron Element : says ignots

Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by Freebi85** [comment]
Sad and nice at the same time :D 
If you find more, put it all here.

**Comment by Danekjovax** [comment]
Thanks, Patrick!  I'll help by placing my edits here too, Freebi. ;2)

**Comment by PatrickZergRush** [comment]
Crystaltin ingots! : I believe it should say Crystaltin in both the description and task title

**Comment by hunter-anderson** [comment]
In Ores, Alloys, and Smeltery T2 the Nucleum Pickaxe Head quest says it requires "1x Nucelum Pickaxe  Head"

**Comment by Grumpledorf** [comment]
Is this still a good place to post typos?
There's a misplaced comma in "reacto,r" in Reactor Casings T3 Main

**Comment by chfishy** [comment]
In the Crossbow quest(). "Your crossbow is useless whitout bolts..." Whitout should be changed to "Without" Version 6.5
