### ISSUE TITLE
Satchel automatic pickup

### ISSUE THREAD

**Issue by JFMillerUSA** [Freebi85/Dungeons-Dragons-Space-Shuttles#514]
Mod v6.5

Thermal Expansions Satchel(Basic) and (Hardened) will not automatically pickup items, messed with filters no go.

**Comment by Freebi85** [comment]
I need to check myself because I've never heard of it before.
But if so i can't fix mod related Issues myself anyway. Report this to the Mod Author pls :)

**Comment by JFMillerUSA** [comment]
Figured it out from Thermals site. Use V key to toggle activation of auto pickup. Need to have that in the Satchels info tab.

**Comment by Freebi85** [comment]
Well autopickup was removed due to lots of bugs since version 6.x
So you are reporting about outdated versions^^
