### ISSUE TITLE
Early game infinite flight bug?

### ISSUE THREAD

**Issue by severi167** [Freebi85/Dungeons-Dragons-Space-Shuttles#515]
In the pack you can achieve infinite flight once u unlock the glider. If you find boots with the multijump enchantment and have them equipped with the glider, that allows you to jump mid air infinitly since the multijumps jump counter resets after a set amount of time instead of when you hit the ground. Meaning you can glide with the glider and keep jumping to gain more air than you lose resulting in infinite flight with no rf cost or anything, found this out in the pack with my friend and we were in mid tier 1 of main questline with infinite flight cause of this. I dont know if this was intended or not but it seems really out of place to be able to infinitly fly at that stage of the game when we cant even make the tier 1 jetpack yet. This style of flight makes the jetpacks in the future kind of obsolete in the pack

**Comment by Freebi85** [comment]
Earlygame flight is not an issue at all. You have first to find those boots/enchants and make steel for the glider. (or explore a lot) Just consider you lucky.
BUT there are already earlier ways to get to fly. You only need rabbit feets and a hyppogriph or a evilcraft broom.
But the "comfortable-creative" flight is still gated behind late tier jetpacks, supremium armor, flying squid etc.
