### ISSUE TITLE
[Suggestion] Tool Head Upgrade

### ISSUE THREAD

**Issue by JFMillerUSA** [Freebi85/Dungeons-Dragons-Space-Shuttles#516]
Would it be possible to bring back upgrading the tool head on the Tool Forge, except using Flint use an Ender Pearl with a Sharpening Kit.

TIA

**Comment by binh3012** [comment]
I think that is a Tinker config and Freebi can't change that.

**Comment by Freebi85** [comment]
Not sure if that was ever possible but in this pack you can only use sharpening kits to repair the tools and I want to leave it at that :P 💃
