### ISSUE TITLE
Astral Sorcery Altar not allowing tier 2 recipes on multiplayer server

### ISSUE THREAD

**Issue by BackToTheBas1cs** [Freebi85/Dungeons-Dragons-Space-Shuttles#517]
It was suggested in the discord I post here no tier 2 recipes are working in the Astral Sorcery Altar attached are an image of my altar, the recipe in the altar with light bar filled and pictures of my astral tome showing what i have an havent completed for AS progress purposes. The Tool in the image is the linking tool for AS however the same issue appeared for the telescope which i eventually just cheated in. All quests in the white magic quest chain to this point are completed 
![Altar](https://user-images.githubusercontent.com/39974516/69737288-26fdde80-1102-11ea-8f5d-6ac3cc35597f.png)
![AS1](https://user-images.githubusercontent.com/39974516/69737289-26fdde80-1102-11ea-97e5-8367c2be4247.png)
![AS2](https://user-images.githubusercontent.com/39974516/69737290-26fdde80-1102-11ea-804c-4a94f57aa1e9.png)
![AS3](https://user-images.githubusercontent.com/39974516/69737291-26fdde80-1102-11ea-8d8b-27005c3e1494.png)
![AS4](https://user-images.githubusercontent.com/39974516/69737292-26fdde80-1102-11ea-92e1-1a53e9a1046c.png)
![wand](https://user-images.githubusercontent.com/39974516/69737293-27967500-1102-11ea-80ee-210cada0e865.png)

Edit Added Lens recipe in altar to show tier 1 recipes work
![pane](https://user-images.githubusercontent.com/39974516/69737842-16019d00-1103-11ea-9153-35d6e2c740c7.png)

**Comment by Freebi85** [comment]
I don't handle mulitplayer issues at all here like my template says =)  pls use our discord Server for the unofficial server support.

**Comment by BackToTheBas1cs** [comment]
the unofficial server support everyone suggested posted here as none of us can figure it out w
