### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by abdullah3nzy** [Freebi85/Dungeons-Dragons-Space-Shuttles#519]
i want to play DDSS for the first time and it show me this error :
Failed to download file, the file contents differ from what was expected.
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Filename on disk: jna-4.4.0.jar
Path: C:\Users\User\Twitch\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Exists: File 
please help me
![5526](https://user-images.githubusercontent.com/58284053/69779794-46584280-11ba-11ea-98ed-8c4d6ac59221.png)
![5526](https://user-images.githubusercontent.com/58284053/69779801-49ebc980-11ba-11ea-8881-d519c4931fcf.png)

**Comment by Freebi85** [comment]
This is a twitch related issue and not a modpack problem so worng place here^^ But we have a solution for this pinned in our tech support channel in the dd&ss discord. Take a look there to solve it :)
cheers

**Comment by abdullah3nzy** [comment]
i just re download minecraft , twitch , the modpack and it works thank you :)
