### ISSUE TITLE
[Mod Suggestion] Realistic mods

### ISSUE THREAD

**Issue by geryyyyyyyyyyy** [Freebi85/Dungeons-Dragons-Space-Shuttles#522]
Hello!

There is three mod, which can be make your pack more better.
The Minecolonies or TekTopia
The Dynamic Surroundings.
The Tough as Nails, Tough expansion. The problem with Tough as Nails is will be no longer updated, but besides, no problem. 

And i almost forget the ItemPhysic mod.

**Comment by Freebi85** [comment]
Hello =)
Thanks for your suggestions but right now I don't want to insert any of these mods sorry. Dynamic Surrounding is already in the pack but it is disabled by default because it sometimes causes problems.
