### ISSUE TITLE
DungeonTactics Rings

### ISSUE THREAD

**Issue by JFMillerUSA** [Freebi85/Dungeons-Dragons-Space-Shuttles#524]
Is there a reason why hunger goes down so fast wearing any enchanted rings from DungeonTactics. Is it conflicting with another mod or something?

**Comment by Freebi85** [comment]
Hey :)
No that’s sadly how dungeon tactics rings work nc they can be very powerful  :/ can’t change that system. You need probably mid to lategame stuff like saturation modules or auto feeders to can keep up with this

**Comment by JFMillerUSA** [comment]
You could change in .minecraft\config\dungeontactics.cfg file

    # Hunger cost value for Trinket Speed Effect. [range: 0.0 ~ 100.0, default: 0.1]
    S:"1-Trinket Speed Boost"=0.0

    # Hunger cost value for Trinket Jump Effect. [range: 0.0 ~ 100.0, default: 0.1]
    S:"2-Trinket Jump Boost"=0.0

    # Hunger cost value for Trinket Mining Haste Effect. [range: 0.0 ~ 100.0, default: 0.1]
    S:"3-Trinket Minging Haste"=0.0

    # Hunger cost value for Trinket Gills Effect. [range: 0.0 ~ 100.0, default: 0.2]
    S:"4-Trinket Water Breathing"=0.0

    # Hunger cost value for Trinket Night Vision Effect. [range: 0.0 ~ 100.0, default: 0.2]
    S:"5-Trinket Night Vision"=0.0

    # Hunger cost value for Trinket Fire Resistance Effect. [range: 0.0 ~ 100.0, default: 0.3]
    S:"6-Trinket Fire Resistance"=0.0

    # Hunger cost value for Trinket Stone Skin Effect. [range: 0.0 ~ 100.0, default: 0.3]
    S:"7-Trinket Resistance"=0.0

    # Hunger cost value for Trinket Strength Effect. [range: 0.0 ~ 100.0, default: 0.4]
    S:"8-Trinket Strength"=0.0

    # Hunger cost value for Trinket Invisibilty Effect. [range: 0.0 ~ 100.0, default: 0.4]
    S:"9-Trinket Invisibility"=0.0

**Comment by Freebi85** [comment]
of course not to 0.0.....

**Comment by Peavii** [comment]
Can the values in the config be set to even smaller numbers such as: 0.01 & 0.001 (and does it use #E-# (scientific notation) format?)? Would be nice if that isn't the case...
If not I'd rather have certain powers set to 0.0 & the better ones @0.1-0.2 in my modpack considering filling up hunger is already a bastard...
