### ISSUE TITLE
Suggestion for Nether Ores

### ISSUE THREAD

**Issue by VikingKaare** [Freebi85/Dungeons-Dragons-Space-Shuttles#525]
Can the modpack author make a recipe for turning nether ores into vanilla ores (found in overworld). Reason being that I can't process nether ores in my mekanism setup. Just like you would turn the blocks from Underground Biomes mod into their vanilla counterparts (stone, cobblestone etc.)
This is by using the chisel from artisan worktables mod ^^

**Comment by Freebi85** [comment]
what kind of nether ores do you mean exactly?^^ most of them seems to have regular mekanism integration.

**Comment by Freebi85** [comment]
?
