### ISSUE TITLE
Alternative recipes to rolling machine

### ISSUE THREAD

**Issue by ray73864** [Freebi85/Dungeons-Dragons-Space-Shuttles#527]
Would love for alternative recipes for things that are currently only craftable in the TechReborn rolling machine (and possibly other TechReborn machines?)

The TechReborn machines are badly designed, they tend to be TPS killers on a server (at least on ours which has good RAM, CPU and storage with only 2 players on it).

I don't mind paying a little extra on a recipe to be able to auto-craft it without having to use a TechReborn machine, it can even be an ingredient that you can't deal with early-game (Not ancient dust or mystical ingots though, those are already way too rare, i've only found a couple on the server and am barely mid-game).

**Comment by Freebi85** [comment]
I'm not sure if I have another machine that can do the same thing without installing additional mods, which is not the goal. I have to take a look.

**Comment by Freebi85** [comment]
The next update offers a new and outstanding opportunity for your crafting requests in "early" lategame.
