### ISSUE TITLE
[Mod Suggestion] Better Builder Wands / Building Gadgets

### ISSUE THREAD

**Issue by ben-mkiv** [Freebi85/Dungeons-Dragons-Space-Shuttles#530]
Hey, currently it looks like the only Building Tool is the ExtraUtils2 Builders Wand which is limited to 9 Blocks, so i would suggest to add one or both of the following mods:

https://www.curseforge.com/minecraft/mc-mods/better-builders-wands

https://www.curseforge.com/minecraft/mc-mods/building-gadgets

**Comment by 41k0n** [comment]
This is a great suggestion! Building Gadgets is a beautiful mod for builders. Very recommended!

**Comment by Freebi85** [comment]
I confirm for patch 7.0 better builders wand.
Building gadgets I have already rejected in another request sorry.
