### ISSUE TITLE
Underground Biomes recipes from essence

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#532]
I know you can get the stones from the Igneous Extruder, and so technically you can get the cobble that way too, but there's currently no way to make the gravels or sands, should someone want to build with them. I made some recipes using the Mystical Agriculture essences, and while I was at it, made some for the stones too anyway.

https://pastebin.com/Nyi2ACJ6

**Comment by Freebi85** [comment]
Sounds good :D Will give it a shot :)

**Comment by Freebi85** [comment]
Well for some reason i can't get the code to work. i already cleaned up a few issues but still. Don't have the time to mess with it or to integrate alls th UB things manually atm. I'm gonna push that back in the priority list for now. 🤕

**Comment by Freebi85** [comment]
I'm sorry. I'm not gonna deal with this any further for now.
