### ISSUE TITLE
High server thread time on events

### ISSUE THREAD

**Issue by Eyries01** [Freebi85/Dungeons-Dragons-Space-Shuttles#533]
I used LagGoggles to diagnose why every new world runs roughly about 30ms tick time, which is abnormally high for a new world. It looks like it has something to do with Forge or SpongeForge or mods that is on top of the list in the event subscriber. I attached a screenshot of LagGoggles profiling result. I am not using dedicated server, this was from a single player world. Please investigate, thank you.
![2019-12-07_02 59 41](https://user-images.githubusercontent.com/51029874/70371193-34ebf600-189e-11ea-9a87-66e56f5ee300.png)

**Comment by Freebi85** [comment]
Pls use our Techsupport in my discord Server for TPS/FPS issues.  There are already innumerable tips and tricks how to increase gameperformance-results considerably if it does not run optimally as for the others. It's not my job to figure out what needs to be improved on your system to make it run more smoothly. no offense :)
