### ISSUE TITLE
New Recipe: Magic Powder!

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#535]
Freebie,

There is no current recipe for crafting Magic Powder (DungeonTactics), and it has several crafting recipes that require it and it is a consumable for all the DungeonTactics spell scrolls (when stored in a Magic Pouch).  The costs of the spells and the rarity of the powder make practical use of the scrolls all but useless except in mid-late game when easily killing source mobs (Witch/Evoker) with other means becomes possible - then these scrolls are made a moot point by then,

Solution: make a relatively accessible crafting recipe to yield a modest amount of this powder, and also offer a more advance recipes which would yield 2x-4x the amount.

Proposed recipes: 

Tier I
1x Evil Dust, 1x Luminessence, 1x Magic Compound, 1x Compost OR 1x Bone Meal
Yield: 4x Magic Powder.

Tier II
1x Evil Dust, 1x Luminessence, 1x Magic Compound, 1x Pulverized Mana Infused Metal
Yield: 8x Magic Powder.

Tier III
1x Dark Magic Dust, 1x White Magic Dust, 1x Magic Compound, 1x Pulverized Mana Infused Metal
Yield: 16x Magic Powder.

Make magic great again!  Thank you! ;2)

**Comment by Danekjovax** [comment]
Thanks!

**Comment by Freebi85** [comment]
probably not exactly what you wrote down, but it'll be craftable :D

**Comment by Danekjovax** [comment]
Still, it's amazing that you're putting something like this into the modpack.  Thanks again!
