### ISSUE TITLE
Conflicting Recipe: Yellow Gift Ribbon

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#536]
It's currently impossible to craft the Steve's Carts seasonal item "Yellow Gift Ribbon" which is 8 string surrounding a yellow dye. That recipe currently crafts "Tape Measure Reel" from Bibliocraft.

**Comment by Freebi85** [comment]
Thank you! You can use the Forestry worktable to switch between crafting results until next patch.
