### ISSUE TITLE
game wont lauch like it should

### ISSUE THREAD

**Issue by MCbuilder1230** [Freebi85/Dungeons-Dragons-Space-Shuttles#537]
game will not finish launching it gives me this https://paste.dimdev.org/boyehibawu.mccrash

**Comment by Freebi85** [comment]
You're out of memory. Raise your ram in the twitch launcher to 8GB if possible. Join our Discord Server for more help =)
Cheers

**Comment by MCbuilder1230** [comment]
I so for got that I just built a new PC and I totally for got to do that lolSent from Yahoo Mail on Android 
 
  On Tue, Dec 10, 2019 at 12:48 AM, Freebi85<notifications@github.com> wrote:   
You're out of memory. Raise your ram in the twitch launcher to 8GB if possible. Join our Discord Server for more help =)
Cheers
