### ISSUE TITLE
NuclearCraft Voltaic Pile storage size error

### ISSUE THREAD

**Issue by GMous** [Freebi85/Dungeons-Dragons-Space-Shuttles#538]
NuclearCraft Voltaic Pile's energy storage has tiers: Basic, Advanced, DU and Elite.
They have storage size (from config): 
Basic: 1 600 000
Advanced: 64 000 000
DU: 25 600 000
Elite: 102 400 000

According to the recipe Advanced needed to create 3 Basic, DU - 3 Advanced, Elite - 3 DU.
As seen, DU and Elite has too low storage sizes.
Most likely the DU and Elite must have ten times larger storage size.

**Comment by Freebi85** [comment]
Energy storage from Nuclearcraft was never intended to be enabled in the pack and gets removed in next patch. Was already reported, also because as you can see, the recipe is default^^

**Comment by GMous** [comment]
Oh, this is sad news.
What is the reason? These storages look pretty good. Even the default recipes are not simple, but you can still complicate them for high tiers.

**Comment by Freebi85** [comment]
I feel there are enough batteris ingame already, but protip: You can enchant ThermalExpansion batteryCubes/Flux Capacitors with holding I, II or III so they can hold much more energy then defaul!  :D
