### ISSUE TITLE
Twilight Forest Equipment recipe re-balancing.

### ISSUE THREAD

**Issue by Sartugha** [Freebi85/Dungeons-Dragons-Space-Shuttles#539]
At current time, the recipes for any equipment from the Twilight Forest are so expensive that only someone interested in completion of the advancement table would ever make any of them.  While it's understandable that something that starts enchanted should be costly, every piece of armor or equipment requiring a Majestic Ingot seems a little to pricey.  Especially when the enchants on the items are only midlevel at best.

Perhaps a modification to the recipe would be a good idea.  Instead of the Majestic Ingot, change the item to either a mana infused ingot, or a block of mana infused metal.  This way, the enchanted item is still a little pricey, it requires an item only found in the Twilight Forest, and is still not easy for a new player to get ahold of.

**Comment by Freebi85** [comment]
I think I replace the majestic ingots with one or two nuggets. so you only need 1 ingot for the whole armor.
