### ISSUE TITLE
Inconsistent quest types

### ISSUE THREAD

**Issue by antiqque** [Freebi85/Dungeons-Dragons-Space-Shuttles#54]
Hello,

Because of the frequent updates and quest book resets i had to redo alot of quests multiple times and i noticed that some of them are not set to the same type as their similar neighbouring quests ( crafting instead of retrieval ).
Examples:
- On the Mystical Agriculture [Tier 1] page quest 391 ( Packed Ice! ) is set as a crafting task even though quests 388 ( Cactus ) and 394 ( Rotten Flesh ) are set as retrieval tasks.
- On the Mystical Agriculture [Tier 1] page quest 421 ( Mystical Flowers ) is set as a crafting task even though quests 409, 412, 415 and 418 are set as retrieval tasks.

I'm fairly sure there are more, i could compile a complete list if it helps.
This only bothers me because i am trying to set up chests with the items needed to quickly redo the quests every time the quest book will reset ( i am expecting this to happen quite often ) but i cannot complete some of them in this fashion because they are crafting tasks.

**Comment by Freebi85** [comment]
try to use next time the command bq_admin default load manually whitout den questbook button. Aus irgend einem grund passieren oft fehler in welten die schon etwas ätler sind mit dem updaten durch diesen button. 
As for the crafting taskt, I should have replaced most of them by now. I don't like crafting tasks myself. But it can of course always be that I missed something somewhere at 1100 quests^^ if you notice something you can report it. I will adjust the listed ones.

**Comment by Freebi85** [comment]
Otherwise just get the quest progress from the backup folder and then update it manually, not with the book. Aroma saves every 45 minutes
