### ISSUE TITLE
Flim Flam enchant

### ISSUE THREAD

**Issue by geryyyyyyyyyyy** [Freebi85/Dungeons-Dragons-Space-Shuttles#540]
What is this enchant doing?

**Comment by Freebi85** [comment]
The Flim Flam Enchantment is an enchantment added by OpenBlocks. This enchantment is applied to any armor piece up to level IV. It will bring bad luck to other players while the enchanted armor is equipped.

a bunch of effects from bad luck
Add Bane of Arthropods on random items.
Spawn Charged Creepers (with 0 blast radius).
Cause negative potion effects such as Blindness and Nausea. It can also give Jump Boost and Speed. These effects have extremely short duration, but very high potency (around level 50).
Encase the attacker in Dirt when they put down Torches.
Shuffle their inventory.
Make about 30% mobs in a 20x20x20 centered around the attacker invisible.
Cause them to drop their items.
Add some random lore to their items' tooltips.
