### ISSUE TITLE
Recipe suggestions: Terrax (among others)

### ISSUE THREAD

**Issue by ray73864** [Freebi85/Dungeons-Dragons-Space-Shuttles#541]
Currently one has to go to stupid lengths to automate terrax with the smeltery, for some reason RefinedStorage has issues with fully automating it.

Terrax could be automated with NuclearCraft, except NuclearCraft can only mix 2 fluids not 3.

What I propose is a new recipe with a 50% loss of fluid.

A dummy fluid that combines 2 of the other fluids for making Terrax, such as Jauxum + Karmesine.

Then, the dummy fluid plus the other fluid (in this case Ovium) could be put into the NuclearCraft liquid mixer.

The result of this would be a 50% loss of fluid, so where as the smeltery turns all 3 ingots into 2 terrax ingots, the NuclearCraft method would result in only 1 terrax ingot, but, it would be 100% automated.

There are other ones where there are more than 2 fluids required for alloying that could get similar treatments, but it would be nice to not require the smeltery.

**Comment by Freebi85** [comment]
There is something secret in planning for this project ;-) You'll see.

**Comment by ray73864** [comment]
OMG, You have me intrigued now :D
