### ISSUE TITLE
Rockhounding and techreborn's chrome dust are not uniform

### ISSUE THREAD

**Issue by luoxingzlx** [Freebi85/Dungeons-Dragons-Space-Shuttles#543]
The two types of chromium dust's oredict are dustChromium and dustChrome, so the chromium dust of Rockhounding can‘t be used.

**Comment by Freebi85** [comment]
it's intended that you can only get chrome through the industrial furnace/Mystical agriculture. Consider the chrom(ium) as another product for the decoblocks of Rockhound itself.

**Comment by Danekjovax** [comment]
I think this needs to be revisited and allowed to interchange between Tech Reborn and Rockhounding versions of the dust by simply crafting them into one another.  Screenshots below show where it is too easy to convert Tech reborn dust/ingots into Rockhounding dust but not the other way around.  These are identical materials as implied by other recipes/processes, so they should be equivalently handled and oredicted to reflect as such.

![2020-03-26_20 07 42](https://user-images.githubusercontent.com/10191173/77708332-29802000-6f9e-11ea-86d5-976b7d6e7968.png)
![2020-03-26_20 07 57](https://user-images.githubusercontent.com/10191173/77708337-2b49e380-6f9e-11ea-88da-ebc218b76ec2.png)
![2020-03-26_20 08 07](https://user-images.githubusercontent.com/10191173/77708339-2d13a700-6f9e-11ea-8355-797024e58047.png)
![2020-03-26_20 09 36](https://user-images.githubusercontent.com/10191173/77708343-2edd6a80-6f9e-11ea-80ba-7a5be6433d01.png)
