### ISSUE TITLE
Fluix Dust doesn't have all the options Quartz Dust does

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#545]
For parity's sake, one should be able to make Fluix Dust in the Actually Additions Crusher, Immersive Engineering Crusher, and Tech Reborn Grinder.

**Comment by DarkYuan** [comment]
Also a mortar recipe for all three (certus, nether, and fluix) would be great

**Comment by Freebi85** [comment]
You really wants me to work hard :D
It's okay^^ done^^
