### ISSUE TITLE
Constant Crashing Before, During, and after Loading

### ISSUE THREAD

**Issue by Wolvesbane** [Freebi85/Dungeons-Dragons-Space-Shuttles#546]
I'm getting constant crashing when trying to play this modpack, all at different times. Some crashes happen instantly when hitting play, some will happen while it is on the last phase of loading mods,sometimes the screen will just go completely black the moment the loading screen updates, some will happen when trying to load into a server, and some will happen just after playing for a few hours.

So far I've tried restarting my PC when these happen, I've re-installed this modpack fresh multiple times, I've tried using the files in the vanilla minecraft launcher, I've raised the amount of RAM multiple times, and it's now sitting at 12GB, Java has been updated, and nothing has fixed my issue.

[latest.log](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/3963610/latest.log)
[2019-12-14-1.log.gz](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/3963611/2019-12-14-1.log.gz)
[2019-12-14-2.log.gz](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/3963612/2019-12-14-2.log.gz)

Here are the latest, and past two logs.

**Comment by Freebi85** [comment]
Hey =)
Pls join our discord server for technical support #singleplayer-support channel and provide some chrash-logs as well. This Github is for ingame related issues like recipes or quests. Thank you :)
Discord Server Link: https://discord.gg/eUajYmK

**Comment by Wolvesbane** [comment]
Honestly no help.
