### ISSUE TITLE
Tier 5 Thermal Padding ungated

### ISSUE THREAD

**Issue by PatrickZergRush** [Freebi85/Dungeons-Dragons-Space-Shuttles#547]
Tier 5 thermal padding is immediately available. I have tons of magnesium from my void miner t4. There is no actual gating towards jumping straight to tier 5 thermal padding. Tier 3 is gated behind desh at least. 

Also, my t4 void miner is giving me lots of pluto zinc ore. Kinda seems weird getting zinc ore before I have even been to the moon.

Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by Freebi85** [comment]
Thank for the heads up!
