### ISSUE TITLE
Magma/Diamond Anvil will not repair Supremium Armor

### ISSUE THREAD

**Issue by Slyklaw** [Freebi85/Dungeons-Dragons-Space-Shuttles#550]
While you can place the armor in the anvil, the item goes immediately to the output slot without any repair.

**Comment by Freebi85** [comment]
Yes everything from mystical agriculture can’t be repaired in cyclic anvils this is correct. You have to find other ways like blood chest :)

**Comment by Slyklaw** [comment]
Are you saying this limitation is by design and not a bug? Because they work in other packs.
