### ISSUE TITLE
Glitch putting two Wood Tanks that each hold 4000mb into a coke oven with more in it fills both.

### ISSUE THREAD

**Issue by icyhero** [Freebi85/Dungeons-Dragons-Space-Shuttles#553]
I put one Coal block into my coke oven which gave me 5000mb of creosote oil and when I shift clicked in two wood tanks I had 8000mb filling two full Wood Tanks in the output.

**Comment by Freebi85** [comment]
Hi :) That's unfortunately not something I could fix myself. Report it to the mod author of Large Fluid Tanks.
Thank you.
