### ISSUE TITLE
Suggestion: Don't generators mandatory quests

### ISSUE THREAD

**Issue by TDSSS** [Freebi85/Dungeons-Dragons-Space-Shuttles#554]
Right now, the T1 main quest requires you to make several different kinds of generators to progress, see picture.
![Capture](https://user-images.githubusercontent.com/32099540/70962929-27492400-2087-11ea-8aa8-d49190c3e7f5.PNG)

To even get to that point, you had to have gotten solar panels. And both the oil generator and steam dynamo generate RF, so you could power the machines from one mod with generators from another, or just run everything off of solar panels. There's even another quest for Immersive Engineering powergen if you want to go for that.

In my opinion, it doesn't make much sense to require one of each kind of generator before proceeding with the other machines. Why do I need a steam dynamo before I should make sawblades or motors, what can a steam dynamo do that a solar panel or oil generator can't? I suggest making the generator questlines sidequests so people can chose their preferred method of power generation and do not have to craft machines they have no use for just to unlock other quests that might be relevant to them..

**Comment by Freebi85** [comment]
Hello =)
Thanks for your feedback.
The questbook is designed in this way that it guides you through many possibilities and mods with many step by step instructions as described at the beginning of the book. It has already been revised and shortened several times.  It will not be further shortened for the time being.

**Comment by TDSSS** [comment]
I don't quite see the point of guiding you through 5 different ways of making RF, but fair enough.
