### ISSUE TITLE
Fluix, quartz and nether quartz dupe

### ISSUE THREAD

**Issue by danielrab** [Freebi85/Dungeons-Dragons-Space-Shuttles#555]
In AE2 you can turn fluix, quartz and nether quartz into double amount their pure versions.
You shouldn't be able to turn pure versions back into normal.
But you can by putting them into the compacter to turn into plates and then putting the plates into the induction smelter with sand to turn them into normal versions.

**Comment by gwyngerlits** [comment]
You can also put nether quartz blocks into a sawmill for 4 slabs. 4 Slabs crafts into 2 chiseled nether quartz, which you can immediately chisel back into 2 nether quartz blocks.
