### ISSUE TITLE
Storage Drawers Creative Storage vs Creative Vending upgrade

### ISSUE THREAD

**Issue by therodet** [Freebi85/Dungeons-Dragons-Space-Shuttles#557]
Is the recipe for the currently applied to the Creative Storage upgrade possibly intended for the creative Vending upgrade? Given that the storage upgrade is akin to the Black Hole storage from Industrial Foregoing, the recipe seems terribly expensive by comparison, and more in line with other creative supply items.

**Comment by Freebi85** [comment]
Thank you for the heads up! <3
