### ISSUE TITLE
Pack not working on my creeperhost server. 

### ISSUE THREAD

**Issue by theguy01205** [Freebi85/Dungeons-Dragons-Space-Shuttles#56]
I just installed this pack this morning on my creeperhost server. Installation was successful on server side and twitch launcher with correct versions. 3.4a However when trying to connect to the server from client the loading screen comes up for about 60 seconds and then says "disconnected" I have worked with CreeperHost all day today trying to fix this and they cannot come up with a solution. They say its a connectivity problem and the server or something on my end is timing out? This error comes up in server console when this happens.

[Error] [FML]: NetworkDispatcher exceptionio.netty.handler.timeout.ReadTimeoutException: null.
06:38:05 [Info] [NetHandlerPlayServer]: MaximusCorey lost connection: Timed out.
06:38:05 [Info] [DedicatedServer]: MaximusCorey left the game

All other instances running other packs are working fine and I am not have connectivity issues with my home network so I am at a loss of how to get this to run on my server. I installed RandomPatches on the server side to try and correct this to no avail.  Any help would be greatly appreciated! Thanks!

**Comment by Freebi85** [comment]
Hello =) This is sadly a very inconsistent issue. Try to repair minecraft via twitch app. Most of the time it works again after this action. If this does not help, open random patches configs and search this lines:

**Comment by theguy01205** [comment]
Thanks a bunch for the quick response! I will give this a try as soon as I get back to my pc this evening! Thanks again!

**Comment by theguy01205** [comment]
Unfortunately I did the repair on my profile in the twitch launcher and modified the RandomPatches config as you suggested but I am still getting the same timeout problem and cannot connect. Any other suggestions on how to resolve this? Thanks!

**Comment by theguy01205** [comment]
UPDATE: I went back into the RandomPatch config on the server side. For some reasons the modifications didnt save. I changed the two lines you suggested again and after two login attempts I was finally able to join and am now in game!!! Thanks a bunch for the help I am so excited to play this pack!! THANK YOU!

**Comment by Freebi85** [comment]
glad to hear that! hopefully your enjoy the pack! =) Will close here.
