### ISSUE TITLE
[Suggestion] Add OpenComputers Tinkers Driver

### ISSUE THREAD

**Issue by ben-mkiv** [Freebi85/Dungeons-Dragons-Space-Shuttles#560]
please add this mod, so that the Smeltery can be at least be automated with OpenComputers

https://www.curseforge.com/minecraft/mc-mods/opencomputers-drivers-for-tinkers-construct

The mod doesnt add any new items/blocks. It just adds support for the Tinkers Smeltery/Furnace/Tank to the OpenComputers Adapter

**Comment by Freebi85** [comment]
Sorry to disappoint you. I'm not interested in this mod.

#donthatemepls D:
