### ISSUE TITLE
[ModSuggestion] PackagedExCrafting in addition to PackagedAuto

### ISSUE THREAD

**Issue by GMous** [Freebi85/Dungeons-Dragons-Space-Shuttles#561]
For a well-working autocraft cycle (just like with Refined Avaritia for RS) this addition is needed for AE and PackagedAuto.
It adds tables that can automatically create items by recipes from Unpackager.
It is very necessary for automation Extended Crafting's crafting tables with AE.

Link: https://www.curseforge.com/minecraft/mc-mods/packagedexcrafting

**Comment by GMous** [comment]
Since there is practically no documentation for these mods, a more detailed explanation may be required.

At the moment, for automation using AE and PackagedAuto, you need to create 3 machines (two of which require ME channel to work) for each recipe: a Packager, an Unpackager and an Automation Interface. It's annoying.

At the same time, a similar solution for RS and Refined Avaritia allows you to create an unlimited number of recipes with the one Extreme Pattern Encoder simply by encoding the desired patterns and use usual Crafter from RS. Which is great :)

PackagedExCrafting is an addition to PackagedAuto from its developer which allows you to relatively balance the ways of automation AE and RS.
With this extension you can create one Packager and an Unpackager for every 20 recipes. And you will also need to create special automation tables of each type: 5х5, 9х9, etc.

**Comment by Freebi85** [comment]
Very well explained, thank you. I will take a closer look at this for upcoming patch 7.0.

**Comment by Freebi85** [comment]
Confirmed,
