### ISSUE TITLE
Refined Avaritia pattern display issues

### ISSUE THREAD

**Issue by ray73864** [Freebi85/Dungeons-Dragons-Space-Shuttles#562]
A lot of the Refined Avaritia patterns have no images when they are inside of a Refined Storage crafter or Reborn Storage Multi-Block Crafter, or when you hold down shift while looking at an inventory.

https://puu.sh/ERYsA/3b5b091a60.png

Row 2 Columns 1 to 5 have the following patterns:

Stone Tank, Copper Tank, Tin Tank, Iron Tank, Bronze Tank

Row 3 Column 2 is a Carpenter pattern
Row 4 Column 9 is a Basic Energy Cube pattern

Modpack v6.5

**Comment by Danekjovax** [comment]
This may likely be an issue with the mod itself, unless you know these renderings work in other modpacks.  If that's the case, you'll have to put in the issue with the mod dev, and not here.

**Comment by Freebi85** [comment]
Yes agree with danek. This is nothing that can be fixed on my end sadly. You have to put it to refined storage but im not sure if 1.12 bugs will still be fixed.
