### ISSUE TITLE
Thermal Foundation oil cannot be used for oil quest even though it and GC oil have identical functions

### ISSUE THREAD

**Issue by Landmaster** [Freebi85/Dungeons-Dragons-Space-Shuttles#563]
Title. I'm referring to the quest (in main questline 2) where one needs to fill a wooden tank with oil.

**Comment by Freebi85** [comment]
Well of course not^^ The quest literally asks you to search for a Galacticraft oil reservoir, found in desert and ocean biomes.

**Comment by Landmaster** [comment]
@Freebi85 Did you read the title? The point I was trying to make is that if TF and GC oil functions **exactly the same**, there is **zero** point in making the player look for one specific type of oil, other than to artificially create tedium.
