### ISSUE TITLE
Proposal for an addition to the quest book, Blacksmith's Workshop Quest: Squeezing Gas. Maybe add the following line as we get the how do I get methane in a cell question a lot and this would help in answering it more concisely.     "Note; the squeezer does not have a built in tank you need to place one beside it"

### ISSUE THREAD

**Issue by Cormenthor** [Freebi85/Dungeons-Dragons-Space-Shuttles#564]
Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by Cormenthor** [comment]
This line would help in guiding people more quickly to resolving this question that we probably hear about 40 times a day now.
"Note; the squeezer does not have a built in tank you need to place one beside it"
Thanks for your time as always Freebi

**Comment by Freebi85** [comment]
Agree with you :)
