### ISSUE TITLE
Extraplanets Heavy Oxygen Tank not counted for quest 1216

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#567]
Accidentally made a blue tank for the quest and it only accepts the default red one from Galacticraft. Maybe putting them into an oredict entry would let you make any of them.

**Comment by Danekjovax** [comment]
Perhaps adding a crafting recipe to allow all colored tanks revert back to the default "red" tank would be possible?

**Comment by DarkYuan** [comment]
That. plus being able to dye them from any color instead of making them with colored wool

**Comment by Freebi85** [comment]
Oredicted 💃
