### ISSUE TITLE
Game keeps crashing during Bloodmoon

### ISSUE THREAD

**Issue by Dakotaraptor** [Freebi85/Dungeons-Dragons-Space-Shuttles#57]
Not sure what exactly is going wrong, but I keep getting this crash 
https://pastebin.com/HQCGEpgd

Is there any chance you could rebalance or remove blood moons too? I can't go five feet without dying, so I just keep respawning and dying over and over again.

**Comment by Freebi85** [comment]
Hello =) It's not Bloodmoon's fault, it's RoughMobs'. Bloodmoon only increases the chance that a faulty mob can spawn. This problem is known and will be fixed in the next update. If you want to fix this for yourself, you only need to update Roughmobs to the latest version.

**Comment by Dakotaraptor** [comment]
Oh sweet, thanks for the quick response!
