### ISSUE TITLE
Elven Gateway Core can burn!

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#570]
Pretty close call happened near my botania setup, where the endoflames are near the portal! Since the pack makes it more expensive to make, I'd consider it more of a pack issue than a botania issue

**Comment by Freebi85** [comment]
Hmm? ![image](https://user-images.githubusercontent.com/42634622/71408303-feec9700-263d-11ea-932a-61fab3951dde.png)

How am I supposed to change that? I can change the block hardness or the mining level but nothing with fireproof as far as I know. I'm open to suggestions, maybe I'm wrong. But the recipe doesn't change.

**Comment by DarkYuan** [comment]
`furnace.setFuel(IIngredient input, int burnTime);`
Setting the `burnTime` to 0 will stop the input from being a fuel item.

**Comment by Freebi85** [comment]
I thought flammable so that it could catch fire if there was lava or fire nearby -.-^^ kappa

**Comment by DarkYuan** [comment]
Oh I see the confusion. I never mentioned that I was breaking it to move it and it fell near the endoflames
