### ISSUE TITLE
Not working / broken recipes

### ISSUE THREAD

**Issue by Moonz3r** [Freebi85/Dungeons-Dragons-Space-Shuttles#571]
Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by Moonz3r** [comment]
Version 6.5
The recipe states: "In the Alloy Smelter you put in (1) Shibuichi Ingot + (2) Triberium Ingot = 3 Aluminum Ingots", but you can't put anything in the right slot of the alloy smelter.  Another recipe states you can submit the same recipe in the Alloy Kiln, but it does not smelt anything at all.

**Comment by Freebi85** [comment]
Works fine for me. Are you sure to use TRIberium ingots and nod TIberium?^^ Because you can only put ingots which are acceptet as recipe in the Techreborn alloy smelter.
