### ISSUE TITLE
Mobs stealing items from players

### ISSUE THREAD

**Issue by concision** [Freebi85/Dungeons-Dragons-Space-Shuttles#572]
## Problem
Several players on a server I host have been reporting a mobs stealing items directly out of their inventory and running off. Oftentimes, these mobs despawn before the player realizes they were missing an item. 

The known mobs that exhibit this behaviour are skeletons and zombies.

This has been invalidating several hours of players works'. This mechanic seems unintentional, due to the amount of configuration modifications that were bundled in this modpack:

- **roughmobs.cfg** (Rough Mobs):
  ```bash
  # Chance (1 in X) that an enderman steals the targets held or equipped item to drop it on the ground
  # Set to 0 to disable this feature [range: 0 ~ 32767, default: 3]
  I:endermanStealItemChance=0
  ```
  
- **ice_and_fire.cfg** (Ice And Fire):
  ```bash
  # True if pixies are allowed to steal from players [default: true]
  B:"Pixies Steal Items"=false
  ```
- **astralsorcery.cfg** (Astral Sorcery):
  ```bash
  key_disarm {
    # Defines the chance (in percent) per hit to make the attacked entity drop its armor. [range: 0.0 ~ 1.0, default: 0.05]
    S:DropChance=0.00
  }
  ```	

Note the different configured value compared to the commented default value.

### Special AI
After searching for quite some time, I discovered that the [Special AI](https://www.curseforge.com/minecraft/mc-mods/special-ai) mod adds a thief AI goal - notably to the same mobs reported to exhibit this behaviour.

There are configuration options to disable particular AI goals.

```bash
##########################################################################################################
# elite_ai
#--------------------------------------------------------------------------------------------------------#
# Options to control the types of elite AI and their weighted chances of occurring.
##########################################################################################################

elite_ai {
    # List of mobs that can gain special AI patterns and their chances to gain those patterns.
    # You can specify multiple chances for each entity - each chance will be rolled and multiple AIs can stack.
    # Note that the entity must have task-based AI enabled.
    #    >> Entity_Array:[ Value={ entity_id <extra_data>, ~entity_id <extra_data> }, Default={ minecraft:zombie 0.05 0.05, minecraft:skeleton 0.2 0.05, minecraft:zombie_pigman 0.1 0.05 0.02 } ]
    S:_mob_list <
        minecraft:zombie 0.05 0.05
        minecraft:skeleton 0.2 0.05
        minecraft:zombie_pigman 0.1 0.05 0.02
     >
	 
	... TRUNCATED ...
	
    # Weight for the thief ai pattern to be chosen.
    #    >> Integer:[ Range={ 0, 2147483647 }, Default=1 ]
    I:ai_thief=1
	
	... TRUNCATED ...
	
}
```

### Open Blocks
The [OpenBlocks](https://www.curseforge.com/minecraft/mc-mods/openblocks) mod seems to have a mechanic to drop player items as well, with an enchantment called "[Flim Flam](https://ftb.gamepedia.com/Flim_Flam)"

I do not think that these mobs have enchanted gear, but I am noting it as well.

<hr>

Note: I have alraedy disabled this in my configuration, but thought that it might be useful to report it here, as it seems it might be unintended.

Thanks for your hard work.

**Comment by Freebi85** [comment]
Thank you for the feedback but a bunch of this settings are already disabled by default in my pack like ice&fire pixies. They don't steal at all. However i don't think i will disable all of them and make an easy mode, but i will look into it.

**Comment by concision** [comment]
I have ***not*** modified the first three configurations. Those are the _default_ configuration values for _this_ modpack, indicating that it seems the trend for this modpack is "mobs should _not_ steal".

However, the the configuration file "Special AI" (`Special_AI.cfg`) has an entry that allows mobs to steal. This particular feature is quite buggy and error prone (players are unable to get their rare items back). I note that this seems unintended and should be properly reviewed.

**Comment by Dinomoh109** [comment]
There are always a new update and they keep making it worse. Now you must have MOB Rank to change lobbies. So Greedy
