### ISSUE TITLE
[Suggestion] Compressed Plate Recipes for the TR Compressor/TE Compactor

### ISSUE THREAD

**Issue by ben-mkiv** [Freebi85/Dungeons-Dragons-Space-Shuttles#573]
Currently for compressed Plates we have to use the TR Rolling Machine which can only be automated if you have one Machine for each Recipe, or the Galacticraft Electric Compressor which is really slow.

So i would suggest to add recipes for the TR Compressor/TE Compactor which takes 4 plates as input and gives 1 compressed plate as output. (Bronze, Steel, Tin, Aluminum, ...)

**Comment by Freebi85** [comment]
there are already other plans for this^^ 

https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/527
