### ISSUE TITLE
Suggestion: Way to turn liquid plastic into IF plastic

### ISSUE THREAD

**Issue by TDSSS** [Freebi85/Dungeons-Dragons-Space-Shuttles#574]
There's three kinds of plastic in the pack, Industrial Foregoing Plastic, Nuclearcraft Bioplastic and Pneumaticraft Plastic. You can melt IF Plastic and NC plastic into liquid plastic, but liquid plastic can only be turned into Pneumaticraft Plastic. it would be nice (and make sense, IMO) if there was a way/recipe to turn liquid plastic back into the other kinds of plastics or otherwise convert between them.

**Comment by ben-mkiv** [comment]
maybe the nuclearcraft ingot former could be used for that task
