### ISSUE TITLE
character starts spinning out of control when moving

### ISSUE THREAD

**Issue by playerchili** [Freebi85/Dungeons-Dragons-Space-Shuttles#575]
When i open the game and a new world everything loads fine, but once i start to move my screen goes like white. i figured the camera view goes into the players character as when i try to look around i can see the red from my skins hat. once i stop moving it takes a few seconds before it comes back to normal.

When i got my inventory to open my players arms were spinning around fast and other animals and mobs around me also had this effect where their arms and legs would be spinning around as they move... eventually killing them.

Not sure what is causing this as the it worked fine the first time i booted the game but everytime after this keeps happening

**Comment by Freebi85** [comment]
Hello =)
I can't reproduce this i'm sorry. The only player where this happened had optifinie installed and changed several settings. Unfortunately I can't help you there :/ If it happens again please contact the technical support in our discord server. There we can try to find a solution together with other players. Provided that the pack has not been altered.

Cheers
