### ISSUE TITLE
Certus quartz tools - special ineffective against non vanilla gravel

### ISSUE THREAD

**Issue by Aduis1210** [Freebi85/Dungeons-Dragons-Space-Shuttles#576]
Normal Gravel multi breaks due to the effect elemental.

Non Vanilla Gravel from underground biomes doesnt multi break when using shovel with elemental perk.

**Comment by Freebi85** [comment]
Hello :)

Yes this was reported already but there is nothing i can do against it. This is a mod incompatibility and should be reported directly to the author of Underground Biomes and/or Tinkers Consctruct. But im not sure if this will gonna be fixed for 1.12 anymore tbh.

Cheers
