### ISSUE TITLE
Paxels missing

### ISSUE THREAD

**Issue by Reygok** [Freebi85/Dungeons-Dragons-Space-Shuttles#577]
Hi, I don't know if this is intentional, but JEI only contains the Osmium and Inferium-like Paxels. However, one quest gives you a Lapis lazuli Paxel as a reward. By default, Mekanism has many other Paxels built in.

**Comment by Freebi85** [comment]
Thank you for reporting. Shouldnt have paxels at all due to the AIOT's. Will remove the one and rework this reward^^
