### ISSUE TITLE
seed drop??

### ISSUE THREAD

**Issue by Strovo** [Freebi85/Dungeons-Dragons-Space-Shuttles#578]
Hi Freebi85, 

in Mystical Agriculture the seeds that are inside the red box, I only made one, let them harvest all night with the farmer of Actually Addictions, and apparently I duplicate them

![Screenshot_24](https://user-images.githubusercontent.com/5396543/71585016-7c575200-2aeb-11ea-8645-87925c67c55b.jpg)

That happens on my server, I was testing all night in single player, and nothing happened.

I did the test with everything exactly as I have it on my server, now my question where I can check this on the server, so that it doesn't happen again.

And sorry if I didn't have to report this

**Comment by Freebi85** [comment]
Yeah after a few tests i don't noticed this problem as well in singleplayer. Mabye your sever configs are messed up. Try to exchange your Mystical Agriculture configs with the original ones. If this doesen't work then it's some kind of serverside issue wit the AA Farmer maybe. I don't know much about server stuff so there is no official support for Multiplayer sorry^^ You can always try in our Discord Server in the unofficial tech support if it's still happening.
