### ISSUE TITLE
Suggestion: Astral Sorcery Perks over 30

### ISSUE THREAD

**Issue by Brillik** [Freebi85/Dungeons-Dragons-Space-Shuttles#579]
Hey, I had a suggestion, as I was digging through config files I found a line in AstralSorcery.cfg  about 1/3 of the way down the file stating:
level {
# Sets the max level for the perk tree levels. [range: 1 ~ 100, default: 30]
I:levelCap=30

I think it'd be a lot of fun to have more perks to play around with than just the 30, and I would love to see this set to 100 and be able to have all of my favorite perks.
My reasons why this should be:
1. It seems to be very rare for packs to change this setting even though it is given by the author a much wider possible range, and DD&SS would have another audience to attract Astral sorcery lovers with the possibility of 100 perks.
2. After level 17, the rate of perk xp gained is so slow that it'd be a pretty huge accomplishment just to get to level 100, making all those +perk experience nodes worth taking.
3. If you wanted to gate things like using the vicio mantle for creative flight perk you could adjust the mantle recipe.
4. Most of the perks aren't that game-changing or breaking, in general adding better QoL.
5. Chain Lightning + Vampire + Bleed, and then add chain mining, tons of extra life, defense, plant growth, bigger stomach, and I'll be awesome! Oh wait, I can already get all of those things in game via blood magic and tech mods. But I like Astral sorcery better!

I'm sure the list can go on, so I'll end it here. Thanks for your time and for making such an awesome challenging pack.

**Comment by Freebi85** [comment]
First of all thanks for the praise :)
Then it still seems to me a bit overkill combined with the other magic mods together :0

I think about it.

**Comment by Danekjovax** [comment]
Maybe if it's possible, could extra levels be gained through some "Expensive, but doable" spell/ritual/process?

Just wondering.

**Comment by Freebi85** [comment]
Sorry to disappoint you. I've checked it and for now I think the system is fine as it is.
#donthatemepls 

Sorry @Danekjovax  for such changes one would have to add some new code to the mod. I am not authorized to do that. D:
