### ISSUE TITLE
Exchanger mining level

### ISSUE THREAD

**Issue by Sartugha** [Freebi85/Dungeons-Dragons-Space-Shuttles#580]
The Obsidian Exchanger, the second to last one of the Durability exchangers, has the same mining level as the previous exchanger.  This is despite it requiring a Dyonite block to craft the exchanger itself.  The end result is that there is no reason to craft the Obsidian level other than higher durability until you have the materials to get to the last exchanger.  The RF based exchangers do not have this issue as there are three fewer levels of exchanger in the process.

Possible solution:
Allow the Obsidian exchanger to have Duranite level mining to match the material used in its crafting.

![emerald](https://user-images.githubusercontent.com/57288542/71648083-4cfc3d00-2cc5-11ea-94ac-b52ba7300b4d.JPG)
![obsidian](https://user-images.githubusercontent.com/57288542/71648090-5ab1c280-2cc5-11ea-9fc5-467a2469f985.JPG)

**Comment by Freebi85** [comment]
thank you :)

**Comment by CloudyDash** [comment]
The Signalum exchanger has the same issue: Costs a dyonite block to craft, yet is only Cobalt mining level.

**Comment by Freebi85** [comment]
Thank you for the heads up :) *fixed indev
