### ISSUE TITLE
Hook picked up from a grave gets deleted if there is a hook in baubles already

### ISSUE THREAD

**Issue by JurasTW** [Freebi85/Dungeons-Dragons-Space-Shuttles#581]
**Reproduction:**
Have a hook in bauble slot,
Die,
Put a new hook in bauble slot,
Recover gravestone

New hook is there while old is gone completely.

As only one hook can be in baubles, it seems that the game just deletes the one that tries to occupy that space. I guess old hook tries to force out the new hook but the new hook voids that action. 

Don't know if that bauble lockout is on a mod level or modpack level. Solution would probably be to replace the lockout with a priority instead or exempt hooks from going back to bauble slot when a grave is opened 

But great pack overall, long and lots of fun. The lootbags could be more generous though, Legendary bag having just some alchemistry stuff is kinda disappointing.

**Comment by Freebi85** [comment]
Hello :) first of all im glad you’re enjoying the pack! 🙏👍

Sadly this sounds like a incompatibility issue between corails tombstone, hooks and/or baubles. I can’t do much there myself. Best thing is to report it to corails or all 3 of them if it’s not already. But keep in mind some mods stopped support for 1.12.

Cheers!
