### ISSUE TITLE
[Suggestion] Wool cloth recipe for the carpenter

### ISSUE THREAD

**Issue by GMous** [Freebi85/Dungeons-Dragons-Space-Shuttles#582]
Currently for wool cloth only one recipe with Artisan's needle. Which is losing durability on craft.
Such items are poorly suited for automatic crafting in both RS and AE systems as spent on 1 craft regardless of durability.
Wool cloth used in the Extra Planets Filter which is used in the Tank Valve and other recipes.

So i would suggest to add recipes for the Carpenter (or another machine) the same as for the String Mesh.

**Comment by Freebi85** [comment]
Even better. Sawmill :0
