### ISSUE TITLE
Tinkers Scythe and Cyclic Scythe not working

### ISSUE THREAD

**Issue by Reygok** [Freebi85/Dungeons-Dragons-Space-Shuttles#583]
Hi, both the Tinkers Scythe and the Cyclic Scythes don't work: right clicking a crop only harvests and replants the clicked one, and not several in an AoE. I guess this is a conflict with whatever mod adds this functionality for empty-handed right-clicking. Maybe tool functionalities need to be prioritized?
Thanks in advance!

**Comment by Freebi85** [comment]
Hey :)
This is a mod interaction which i can't fix myself. However, should be fixed for cyclic in next update but for tinkers you should probably open an extra ticket to their github. 👍 

Cheers :D

**Comment by Reygok** [comment]
Okay thanks, I' ll contact them! Which mod is it that adds the right click harvest function? Is it Gentle harvest?

**Comment by Freebi85** [comment]
This is usually from pams harvestcraft afaik :)
