### ISSUE TITLE
Shutting Down internal server

### ISSUE THREAD

**Issue by Konkordzik12** [Freebi85/Dungeons-Dragons-Space-Shuttles#584]
so my game sometimes just closes down saying Shutting down internal server and also it freezer every 5 mins, especially when loading in the world plz help

**Comment by dierke9** [comment]
Usually that means that an error has occured in your singleplayer world. Please send your latest.log over if it happens again so we can take alook at it

**Comment by Freebi85** [comment]
closed because no further information. Pls use our tech support channel in my discord server for more help :)
 Discord Server Link: https://discord.gg/eUajYmK
Cheers
