### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by cryevee** [Freebi85/Dungeons-Dragons-Space-Shuttles#585]
[crash-2020-01-06_22.05.15-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/4032126/crash-2020-01-06_22.05.15-server.txt)

This happens anytime I try to host a server.

**Comment by Freebi85** [comment]
Hey :)
You have to change max tick time to -1 in server propreties^^
But pls like my templale says, no serverside issues and crashes in github. I don't support servers at all here. Use our tech support in discord for next time :)

Cheers.
