### ISSUE TITLE
Game keeps crashing. I coppied the code from the crash. can anyone help. Im going to copy and paste the link with the crash report.

### ISSUE THREAD

**Issue by zoe8ad** [Freebi85/Dungeons-Dragons-Space-Shuttles#586]
https://paste.dimdev.org/buteroviqe.mccrash

**Comment by Freebi85** [comment]
Hello :)
You run an outdated pack and/or forge version it seems. Update to latest version and try again, pls use our tech support channel in my discord if you still have problems bc it's easier to troubleshoot :)

Discord Server Link: https://discord.gg/eUajYmK

Cheers.
