### ISSUE TITLE
Better Questing Party Quests Not Syncing

### ISSUE THREAD

**Issue by devleesch001** [Freebi85/Dungeons-Dragons-Space-Shuttles#589]
Problems with quests : I joined friends on a server, I joined the group of quest but the quest which we were previously validating by my friends were not for me

**Comment by Freebi85** [comment]
Yeah there is a known issue about the entire sync system in better questing. There is not much i can do until the mod is fixed properly. Pls don't report Server issues in this Github like the template says.

You can find more infos about that in the tech support channel in my discord server. #known issues.

**Comment by devleesch001** [comment]
OK thanks and sorry
