### ISSUE TITLE
Server Crashing from soundreloader

### ISSUE THREAD

**Issue by Punkenstein** [Freebi85/Dungeons-Dragons-Space-Shuttles#59]
here is crash log
[crash-2019-01-16_14.48.56-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/2764429/crash-2019-01-16_14.48.56-server.txt)

**Comment by dierke9** [comment]
Soundreloader is a clientside only mod and should not be present in server files.

**Comment by Freebi85** [comment]
Use the correct serverfiles for your server or delete mod from the server. https://minecraft.curseforge.com/projects/dungeons-dragons-and-space-shuttles/files/2660595

**Comment by OldManCraft** [comment]
I have an Idea that forge provides, Easy config change to make your mod disable if on server.
