### ISSUE TITLE
[Question/Suggestion] Getting Gaia stuff

### ISSUE THREAD

**Issue by GMous** [Freebi85/Dungeons-Dragons-Space-Shuttles#591]
In many recipes of the Draconic evolution requires a Gaiasteel ingots, which are made from a Gaia Spirit. Which can only be obtained by killing the boss. So you have to kill this boss many times for crafting. 
Was it intended that way, or is there a reason to improve and create another way to get these ingots, or Gaia spirit? I assumed that it would take 2-3 times to kill the boss, and then there would be some other way to get resources.
Thanks in advance

**Comment by Freebi85** [comment]
There will be a more efficient recipe in 7.0 in the new multiblock machine^^
