### ISSUE TITLE
[Suggestion] Alternative for End Game Carpenter. 

### ISSUE THREAD

**Issue by Arcanien** [Freebi85/Dungeons-Dragons-Space-Shuttles#593]
Had thought about it as a very end game alternative of having the Sequential Fabricator from Thermal Expansion being used much like the carpenter is. If the augment "Fluidic Fabrication" is added to the machine, it gives the machine a tank. So in turn you can have an alternative for being able to craft items faster than the carpenter without having to use the boost. Or even even maybe include that the boost is available with the Fabricator. I figured that it would be VERY end game and for balance would have to make the fabricator and the augment much more expensive if wanting to make it as fast or faster than the carpenter with a boost in the recipe. I don't know though how difficult that would be to implement this.

**Comment by Arcanien** [comment]
The only issue I could see with this is the "extra slot" that the carpenter provides as a container for all the crafted items to be into for the end resulted item.

**Comment by Freebi85** [comment]
Hello =)
Well im' sorry but this is just an automated craftingtable and not meant as machine for custom recipes. It uses the pool of the vanilla table and don't have crafttweaker support to add custom stuff. 
I am also about to do a prefinal update and will not make such changes to the game anymore^^
