### ISSUE TITLE
[Suggestion] Draconic Evolution and its Information Tablet going to be removed in next update. 

### ISSUE THREAD

**Issue by Arcanien** [Freebi85/Dungeons-Dragons-Space-Shuttles#594]
I wasn't sure if it was brought to your attention, but the author of DE is going to remove the information tablet and have the mod completely integrated into another mod called "Project Intelligence." Now I have already added as a custom mod to the pack for this reason. But you may want to include that mod to be included in the pack. Since basically the DE "manual" is going to be completely integrated into another mod.

**Comment by Freebi85** [comment]
Hey =) Thank you for the heads up^^ 
Yes, I'm aware of that. As soon as this update comes i will switch to the new mod but i'm waiting for it now for 7 months and slowly i doubt that another DraconicEvolution update for 1.12 will come because they work on 1.14 afaik. 
But we will see :)
Cheers
