### ISSUE TITLE
Duping issue between the Carpenter and the Automation Interface from Extended Crafting

### ISSUE THREAD

**Issue by Arcanien** [Freebi85/Dungeons-Dragons-Space-Shuttles#595]
I was able to reproduce this 100% every time I tried it. 

After you setup the recipe to be inserted onto a crafting table from an Automation Interface. Put a Carpenter next to the Interface. Have all the items that are needed to make the recipe within the carpenter. Point the side that the Interface is pulling from at the Carpenter. The Interface will start pulling the items, but instead of the items being pulled out of the Carpenter, they are duplicated. I realized this was happening after I looked in my RS storage and found that I had 4k crystaltine ingots when I shouldn't of had any. And when I realized what was happening... I had about 7k RS Crafters since I had setup the Crafters first.

**Comment by Freebi85** [comment]
Hey :)
Im afraid i can't help you there. This is a mod issue and/or interaction and has to be reported to the author. Can't fix such a dupes myself. Also make sure you can reproduce this in singleplayer. No one ever said something about that.  
However as far as I know RS is no longer maintained on version 1.12 so I don't know if this can ever be fixed.

**Comment by Arcanien** [comment]
Actually it didn't have anything to do with RS. It was just between the Forestry's Carpenter and Extended Crafting's Automation Interface. So I guess I'll let them know. Thanks for the info.
