### ISSUE TITLE
Questbook: one problem with quest + enhancement

### ISSUE THREAD

**Issue by DragonmasterDJ** [Freebi85/Dungeons-Dragons-Space-Shuttles#6]
Hey there! I'm sorry for another post, but I am looking to help out since I love the pack so much! (I am DragonmasterDJ420 who replied on your curse site btw!)

The one small problem I see with one of the quests is the one for finding nether quartz. The quest is named Peridot! Where it should be named Quartz! ^^

Also, for a enhancement. I see that the quest cover is the default image given by the mod. I was wondering if maybe you'd like a artwork that I can make for the new image in front of the quest book menu? just in case here are two examples of my previous artworks!
https://www.deviantart.com/magicfur/art/D-D-DUEL-772269533 (example 1)
https://www.deviantart.com/magicfur/art/By-the-crystal-lake-side-772266535 (example 2)

**Comment by Freebi85** [comment]
Thanks for Reporting =) It will be fixed in next update.

For example, if you want to draw a picture, you need to use a dragon, a spaceshuttle and maybe a dungeon in the background^^ I'm open to it but I'm not promising anything^^

**Comment by Freebi85** [comment]
Huhu Dragonmaster. I close this Issue. You can contact me here regarding your image: freebi85@gmail.com
