### ISSUE TITLE
Single player game crashes (v 6.5)

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#600]
https://pastebin.com/QvHqys8q 

Game suddenly crashed, happened twice today. Attached is error log

**Comment by Freebi85** [comment]
EXCEPTION_ACCESS_VIOLATION is usually a sign of a broken ram sitck or a stick that is not sitting properly in its slot. This is at least one of the more common causes I know of.
But it does't necessarily have anything to do specifically with the modpack.

If you need more help I recommend to visit the dd&ss dicord server. 
Someone may be able to tell you more than I can on this particular case.
