### ISSUE TITLE
Aluminum bees not breedable

### ISSUE THREAD

**Issue by Entbark** [Freebi85/Dungeons-Dragons-Space-Shuttles#601]
Aluminum bees are not breedable in this pack. They require a block of aluminium (note the spelling) as the block beneath the apiary, but all we can get in this modpack are blocks of aluminum (note the spelling). I've gone through many soul frames to test this.

**Comment by Freebi85** [comment]
Hello =)
I didn't change anything in the breeding system. All breeds are by default. Recheck with rupdate 7.0 because there was a Magibee update. If it's still not working report it to the author because i cant fix this myself like just an item recipe :/
