### ISSUE TITLE
After upgrading to V 7.0 Don't see my moon and mars celestial gateways in my main gateway.

### ISSUE THREAD

**Issue by TerraCerrantic** [Freebi85/Dungeons-Dragons-Space-Shuttles#602]
Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by Freebi85** [comment]
There was no update from Astral sorcery. No clue waht't happen. Singlerplayer? Try to relink your gateways.

**Comment by TerraCerrantic** [comment]
I picked up my home gateway, and put it back down. Now the 2 other gateways' stars appear, but not named. Maybe if I pick them up and put them down it their names will show.
