### ISSUE TITLE
After upgrading to V7.0 sometimes can't see a mystical agriculture seed I just planted.

### ISSUE THREAD

**Issue by TerraCerrantic** [Freebi85/Dungeons-Dragons-Space-Shuttles#603]
However, Oneprobe shows it to be present, and growing.

**Comment by Freebi85** [comment]
i can still see all my crops. Tried to break and replace them? It is also possible that the id's have corrupted themselves but then you would have to see several strange blocks in your world.

**Comment by Freebi85** [comment]
Any news on this? Still couldn't confirm. Nor have I received any other messages about it.

**Comment by Slyklaw** [comment]
I've seen it occur, both with mystical crops and other mod blocks. If you look closely, you can see the black outline of the block. No known repro steps, yet.

**Comment by TerraCerrantic** [comment]
That part of my base was experiencing a lot of lag, client lag I think, so I moved my mystag setup down one floor.  It probably had not much to do with mystag itself.  Now I no longer see this problem, nor do I see that kind of lag anymore.
