### ISSUE TITLE
Request: New patch release of 6.x which only adds SimplyBackpacks

### ISSUE THREAD

**Issue by merphle** [Freebi85/Dungeons-Dragons-Space-Shuttles#604]
To ease server transition of users from v0idBackpack to SimplyBackpack, can we get a new patch release of 6.5 which does literally nothing but add SimplyBackpack? I could run that server for a week, let people migrate over from one backpack to the other, then upgrade to 7.0 cleanly.

Thanks!

**Comment by Freebi85** [comment]
Hello :)
I understand the problem but it all happened very fast for me too. I don't have the time for an extra update to 6.5 but you can either give the players time or tell them to install the mod. Then you have standard recipes for a fair exchange.
Sorry bud :/
