### ISSUE TITLE
7.0 Avaritia extreme pattern invisible in inventory when set to carpenter

### ISSUE THREAD

**Issue by arborelliott** [Freebi85/Dungeons-Dragons-Space-Shuttles#605]
When the pattern is made to be a carpenter, the pattern becomes invisible. holding shift does make it appear

**Comment by arborelliott** [comment]
![image](https://user-images.githubusercontent.com/60042521/72667744-2ccebc80-39ed-11ea-9108-56097fab92a9.png)

**Comment by Freebi85** [comment]
Hey :) 
It seems to be the case for all forestry machines. 
Sorry can't do much there. Pls Report to Refined Avaritia and Forestry. some renedering issue which i can't fix myself sry :/
