### ISSUE TITLE
Unable to progress past "Easy Blocks, Easy life" Tier 2 main quest line

### ISSUE THREAD

**Issue by Vapetank** [Freebi85/Dungeons-Dragons-Space-Shuttles#607]
Advanced crafting table does not recognise the recipie for the factorizer in 7.0

![2020-01-19_02 38 46](https://user-images.githubusercontent.com/60052897/72673626-3b58ba80-3a65-11ea-98c8-810cdd1d87c3.png) Shows Recipie

![2020-01-19_02 38 38](https://user-images.githubusercontent.com/60052897/72673636-588d8900-3a65-11ea-9c58-b8ba5f4fc5d0.png)Shows items moved to Advanced crafting table.

All server/ client files are current. tested in single player with same effect. 

reports from other players in server shows the recipie with pistons/sticky pistons in the vacant slots as seen in the above screenshots, but they are unable to retrive the factorizer from the table.

not quite sure what to do (apart from spawning one in to progress)

any help would be greatly apprecieated

thanks

**Comment by Freebi85** [comment]
Hi :) was fixed in 7.0a
Just update server and client. Cheers
