### ISSUE TITLE
Solar Dust (Venus) - Give it a use or remove from worldgen?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#608]
I'm getting Solar Dust from mining in Venus, and JEI lists its only use as an ingredient for making Solar Array Wafers with GC's Circuit Fabricator, but the use for this Wafer isn't listed.

Was it disabled on purpose or was it a mess-up with GC recipies?

In either case, the dust needs a valid use or be removed from worldgen, I think.  Thanks again!

:2)

![2020-01-18_23 37 29](https://user-images.githubusercontent.com/10191173/72675029-9f22b980-3a4c-11ea-9c95-6d67b026aebc.png)

**Comment by Freebi85** [comment]
do you happen to know where that dropped from? o_O

**Comment by Danekjovax** [comment]
It was mined up by the mining bees I've been using to mine on Venus.  Not sure which block they mined to get it, so I'll do a little mining and see if I can reproduce the material.

**Comment by Freebi85** [comment]
merged to https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/733
