### ISSUE TITLE
Broken Quest olive tree quest

### ISSUE THREAD

**Issue by Punkenstein** [Freebi85/Dungeons-Dragons-Space-Shuttles#61]
![2019-01-16_08 58 14](https://user-images.githubusercontent.com/37779138/51257357-0bb43580-196d-11e9-97a9-8fa42f4a5622.png)

**Comment by Freebi85** [comment]
You have removed Dynamic Trees. This is a item quest relatet to this. Removing quests breaks quest progression and sometimes recipes. Readd Dymani Trees and if you dont like them just disable it in the configs. You can craft the required seedling in a different way.

**Comment by OldManCraft** [comment]
All the DT mods create server problems. They always have.

**Comment by Freebi85** [comment]
you asked me and I answered you. You can disable Dynamic trees in the configs as already mentioned.

**Comment by OldManCraft** [comment]
No that’s fine, this community will choose a different pack as this one has to many issues.

That’s for your reply
