### ISSUE TITLE
Wrong Obsidian ratios in Adv Alloy Smelter

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#610]
I think the recipe for Fractum in the new multiblock alloyer is meant to be 3 Triberium, _**1** Obsidian_, 1 Abyssum, and the recipe for Obsidiorite should be 2 Meteorite (or 1 cobble) and _**1** Obsidian_, because a block of Obsidian gives 2 ingots worth of molten material. The ratios for Seismum and Alumite are correct though.

**Comment by Freebi85** [comment]
ok 😢
