### ISSUE TITLE
Erro version server. 7.0b for Dungeons-Dragons-Space-Shuttles

### ISSUE THREAD

**Issue by duirron** [Freebi85/Dungeons-Dragons-Space-Shuttles#611]
[crash-2020-01-21_01.16.36-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/4091281/crash-2020-01-21_01.16.36-server.txt)
[crash-2020-01-21_02.48.14-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/4091282/crash-2020-01-21_02.48.14-server.txt)

One occurred when a blood moon started and another when he was exploring the map.

**Comment by Freebi85** [comment]
Hi :)
Set your max tick time to -1 in the server proprieties to avoid this crash. Pls don's use Github for Server Crashes and Issues like my tempalte says... :) If you need more help check tech support channel in discord.
Cheers 😃

**Comment by duirron** [comment]
Where do I get this option? Can you be more detailed? 
Okay, where do I put bugs?
