### ISSUE TITLE
"Unbalanced" Glass Bottle recipe still available

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#612]
The Binnie Core recipe for Empty Bottles is still available and can be crafted into vanilla ones

**Comment by Freebi85** [comment]
Thank you :)

**Comment by LordHellscream** [comment]
Probably also make recipes that uses bottled liquid to refund empty bottles like they do for buckets since bottles are more expensive now?
