### ISSUE TITLE
Reinforced backpack recipe

### ISSUE THREAD

**Issue by zzumche** [Freebi85/Dungeons-Dragons-Space-Shuttles#615]
Reinforced backpack is out, but the quest book is still requiring me to make one (Tier 1 main questline).
How to... avoid that problem?

**Comment by Freebi85** [comment]
You (or your server admin) have to update the questbook as well after every update^^

Use the command /bq_admin default load
If you don't have permissions in singleplayer open a world to LAN and allow cheats on.

Cheers
