### ISSUE TITLE
Does redstone not work in this pack?

### ISSUE THREAD

**Issue by Frogliza** [Freebi85/Dungeons-Dragons-Space-Shuttles#616]
I have noticed that blocks that normally can connect to redstone like the fluid placer and collector don't connect. Is there something wrong or is this a mechanic of the pack?

**Comment by Freebi85** [comment]
Hello :) 
No, nothing has been changed in the Redstone mechanics or in the interaction with machines of other mods. 
If the device does not accept redstone then it is either wanted by the mod-maker or it is a bug that needs to be reported to them :) Make sure it's not an smp issue before.
Cheers
