### ISSUE TITLE
QoL suggestion: recycle lower tier storage disk into their storage parts

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#617]
It would be great if an recipe can be added to convert a refined storage disk back into the storage part. (at the cost of losing the casing)
Normally its not as much an issue as I can grind for 1 64k disk. But because its gated it forces us to make multiple 16k disks. Yes you can make another disk drive but its messy.
The benefit of this is that it can encourage people to start with using lower tier storage like 4k and they wont be totally useless once you can upgrade.
You will still need to create new higher tier disk first anyway to transfer the items over before recycling i think it make sense.
Thank you for your consideration.

**Comment by tkoopman** [comment]
You can just shift-right click the empty storage disk to get both storage part and housing back. This is standard RS feature.

**Comment by LordHellscream** [comment]
@tkoopman : i just found out watching direwolf's video,  hehe. Will lose
