### ISSUE TITLE
Blood magic progression pacing

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#621]
First of all I want to say I really really enjoyed this pack, some says its super grindy, yes it is grindy but I feel its right amount of grind that make it feel every achievement is truly worth it.
I am at late Tier 2 stage with good progression on ore alloying and mystical agriculture. I feel the amount of mining was intense at early stage but its slowly getting better as I progress and built up my material farms, getting access to better tools and such. 

But blood magic, oh, that's another thing. I feel like getting to tier 3 blood magic (to make blood infused irons) is really out-of-pace with the rest of the pack and being extremely tedious and repetitive. (I know blood magic is a grindy-mod by its nature, but its likely enough so in its vanilla form without making it 10x more grindy)

Problems with blood magic:
- no viable substitute from stand on a regen flower and stab myself slowly (I can use mixer and evilcraft blood to convert into life essense yes, but without displacement runes, 20mb/t transfer speed so slow its negligible)
- "difficulty" at focus on repetition -- for most other progress I feel like it encourage balance between each of the quest lines. But for blood magic its pure repetition.
For example setting up auto mana farm making it much much easier to make manasteel for various recipe. Progressing in tech make it cheaper to manufacture components for all other quest lines.
Having good resource farm making it much more quickly to setup refined storage or progress other resource-intensive tracks. Progress into ore alloy opens gate to many more powerful recipes. and a healthy dosage of exploration and mining trip is sprinkled in between making the whole experience fun and challenging. The blood magic progress have none of that, 

Suggestion:
Perhaps instead of requiring infusing a gazillion slates to make rune even in the earliest stages. Offer alternative routes. Perhaps alternative recipes that require you to progress sufficiently in other tracks or exploring certain dungeons etc. Giving out displacement runes as reward for certain quests so evilcraft and other blood source can be viable alternative etc.

**Comment by Freebi85** [comment]
Hello :)
DD&SS is in a pre-final release so I can focus on new projects. I don't know if I will make any major content changes in dd&ss. I will leave the ticket open and think about it.

**Comment by CalligoMiles** [comment]
This. I made it into T5, and the T3 Altar is still the only grind I truly despised.

**Comment by Freebi85** [comment]
Graveyard soil + blood arsenal glass shards with a zombie on top and you have an endless source of LP^^ Everything else is just automation. Ingeus Extruder for compressed Stone and so on.

In ddss you are often faced with the challenge of finding new ways to reduce the grind.
Example: opencomputers setup with a transposer adjacent to the blood altar, with input and output chests on two other sides and a custom program to infuse whatever is dropped in the input and move it to the output when it's done.

**Comment by LordHellscream** [comment]
@Freebi85 i think you are missing the point. In later stage its not an issue. But to reach tier 3 which you are fairly early in the game its a super tedious process. 
The graveyard soil requires diamond level promise accepter. which requires reinforced slate among other things. 
Input/output can be managed by liquid monitor, but then self-sacrifice still needed to get through tier 3.

**Comment by Freebi85** [comment]
@LordHellscream That's not entirely correct. You can reach t2 altar without to self sacrifice one single time. Everything you need are some evilcraft trees, arboreal extractors and alchemical imbuer and you can convert as many evilcraft blood to LP as you want. (Or rottenflesh into tinkers blood and then to lp) But this is probably more suited for a discord conversation then github.
