### ISSUE TITLE
 Quest broken: Advanced Backpack

### ISSUE THREAD

**Issue by Takerulol** [Freebi85/Dungeons-Dragons-Space-Shuttles#622]
Hello there,

the quest "Advanced Backpack" in Tier 2 Main Questline is now broken in the current version of the modpack (7.0b). The quest is still linked to the old V0id's backpack and therefore the following quest is not reachable. It should be changed to a Simply Backpacks item id. Since I haven't played further than this point, I don't know if there are any more quests of this type, so please check that as well.

Best regards,
Takeru

**Comment by Freebi85** [comment]
Hello =)

Check pls https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/615
