### ISSUE TITLE
I can't craft wood planks

### ISSUE THREAD

**Issue by raymanfanguy** [Freebi85/Dungeons-Dragons-Space-Shuttles#623]
i'm having an issue where i can't craft wood planks from vanilla logs as well as modded logs... i grabbed about 18 oak logs i tried putting them in my character's crafting grid and nothing i didn't get 2 planks per log like i was suppose to instead i was left with an empty output slot with nothing in it even though i had followed the recipe accordingly unless the recipe has changed since the last time i played i am at a loss

**Comment by Freebi85** [comment]
Sounds like your file scripts are corrupted for some reason. Assuming you’re in ssp. Try to reinstall the pack, don’t remove or add anything because this breaks all recipes and try again. If it’s still not working join my discord in tech support and we will see what’s going on there 😃👌
