### ISSUE TITLE
Suggestion: Improve selling of farm food to villagers

### ISSUE THREAD

**Issue by TDSSS** [Freebi85/Dungeons-Dragons-Space-Shuttles#626]
I realize this is going to be a pretty out there suggestion, but trying to sell certain farmable foods to farmers is pretty damn painful. Assuming you want to sell soybeans or something, you need to click through like 200 trades until you reach soybeans, then repeat that for every other farmer, etc.

I figured you could make this a great deal easier by doing the following:
1. Add some new item called 'bundle of food' or something that's created by taking 9 wheat/soybeans/etc (basically whatever the farmer buys in terms of food plants)
2. Replace the 200 trades of the farmer villager with a single one where he buys bundles of food.

**Comment by Freebi85** [comment]
I can’t interact with villager trading tables. 

There are mods that allow a very limited integration but they are partly outdated and I will not use them. You need to send your request to pams harvestcraft so they can implement this in the main game and improve the trading tables.

**Comment by Semi0ne** [comment]
@TDSSS 
I don't know if it's a feature, bug or some other mod has changed farmer behavior, but in my game you can throw any of the trade items in the first trade (wheat iirc) and the farmer will buy it. I found that out by accident, a very happy and fortuitous accident, after having spent plenty of time like you clicking through all the trades. I suggest you give it a try.
