### ISSUE TITLE
Moving Syngas into the Assembler

### ISSUE THREAD

**Issue by CalligoMiles** [Freebi85/Dungeons-Dragons-Space-Shuttles#627]
So I've set up a full Rockhounding line after the recent update, but now I'm stumped at the last step. How do I move Syngas into the Assembler? I can't find a single duct/pipe/tube that's compatible with Rockhounding vessels/gas pipelines, and those vessels themselves aren't compatible with anything but their own pipelines either. I can't even do it manually because you can't use cells or buckets on them.

**Comment by Freebi85** [comment]
Hey there 😋
To extract fluids/gases from the rockhounding system you have to pump it in a Rockhound „transposer“ from the transposer you can use regular pipes like fluiducts to export it into other tanks/machines. 
Pls use my discord server for further questions 🙃
