### ISSUE TITLE
Underground Biomes ores can't go through Mekanism ore-processing

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#628]
For example, Marble Lead Ore can't be put into a Purifier, Crusher, Enrichment Chamber, etc. Found this out when attempting to process a silk-touched charged certus quartz ore in the enrichment chamber for 4 crystals, but only "stone" certus quartz ore was allowed.

**Comment by Freebi85** [comment]
Hey :)
Silk touched underground biome ores have no mod compatibility at all. It’s not worth it to use silktouch. And i don’t gonna mess with it in this pack anymore sorry. You can use the ore dictionary converter to make it viable.

Cheers

**Comment by DarkYuan** [comment]
Oof. As long as there's a way then, didn't think about the ore dict converter.

**Comment by Danekjovax** [comment]
Using the Oredictionificator helps a lot for silk touched ores, but...
