### ISSUE TITLE
[v3.5c] Waterfall audio clipping

### ISSUE THREAD

**Issue by Gamertech** [Freebi85/Dungeons-Dragons-Space-Shuttles#63]
Version: 3.5c

Some sources of water falling such as the Astral Sorcery fountains create glitched overlapping audio. Would be something to do with Dynamic Surroundings. There's an issue here: https://github.com/OreCruncher/DynamicSurroundings/issues/437

It doesn't occur with the latest beta branch 3.5.4.2, but switching would require you to redo any customisations to the config, as well as add OreLib and their new HUD add-on mod to keep light levels/chunk borders.

All 3 mods come out lighter resource-wise than just the 3.4 branch of DS though, so that's a bonus.

**Comment by Freebi85** [comment]
Thanks for the tip! I'll take a look. That with the lightlevel is no problem because I already have more overlays inside (F7)
