### ISSUE TITLE
Tooltip needed for Mekanism Factories

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#635]
A similar tooltip as for upgrading backpacks, because the mek machines like Purifier being crafted into Basic Purifying Factory will lose all contents and upgrades. That, or I think it's possible to incorporate the NBT of the crafting item into the result somehow.

**Comment by Freebi85** [comment]
Dosen’t work well and affects too many machine due to similar item tags.
