### ISSUE TITLE
Argon and Xenon duplication using Alchemical Imbuer

### ISSUE THREAD

**Issue by CloudyDash** [Freebi85/Dungeons-Dragons-Space-Shuttles#636]
Using the Alchemical Imbuer in combination with Alchemistry's Atomizer allows you to duplicate Argon and Xenon.
 1 Xe/Ar Element + Sodium Hydroxide in Alchemical Imbuer = 100mB Xenon/Argon
1000mB Xenon/Argon in Atomizer = 16 Xe/Ar
Leading to a 600mB higher yield of Xenon and Argon than is put in. 

I found this while looking for alternative ways to produce Dark and White magic essence, so please let me know if this is an intended feature ^^

**Comment by Freebi85** [comment]
:0
