### ISSUE TITLE
Satchel auto-pick destroys Tinkers tools

### ISSUE THREAD

**Issue by Nagapito** [Freebi85/Dungeons-Dragons-Space-Shuttles#64]
If you have the satchel with auto-pick enabled and you drop a tinker tool, you will only get a stick instead of the tool....

Reproduce:
Enable satchel auto-pick.
Drop tinker tool with Q.

**Comment by Freebi85** [comment]
Do you remember what kind of tool that was and what kind of material? Because if I test it with different tools it doesn't happen. Maybe it was a certain material that doesn't fit.

**Comment by Nagapito** [comment]
Confirmed...It was realistic item drops.
Maybe a new conflict with Tweaker Constructs...  Found this: https://github.com/Funwayguy/RealisticItemDrops/issues/18

**Comment by Freebi85** [comment]
Since I don't use this mod in my pack I don't see why I should change anything about it. But as you can read in the other thread you only need to disable one config in tweakers construct then there should be no more problems =)

**Comment by Nagapito** [comment]
Ohh, I wasnt asking for a change. 
I was just updating you on the issue and what could be the cause, in case you wanted to know, since Realistic Drops and Tinkers are used successfully in other packs
