### ISSUE TITLE
Adding Advanced Alloy to the Advanced Alloy Smelter

### ISSUE THREAD

**Issue by DarkYuan** [Freebi85/Dungeons-Dragons-Space-Shuttles#640]
That could be another ingot that the multiblock does at an increased yield, the ones made from 3 tin, 3 bronze, and 3x material

**Comment by DarkYuan** [comment]
Just wondering, did you make it so that it combines straight into the advanced alloy and not just the mixed metal ingot?

**Comment by Freebi85** [comment]
Straight into advanced alloy^^

**Comment by DarkYuan** [comment]
Thanks!
