### ISSUE TITLE
Request: an easy path 'downgrading' from liquid argon to argon gas

### ISSUE THREAD

**Issue by Azutte** [Freebi85/Dungeons-Dragons-Space-Shuttles#643]
Yes, I see that they're wildly different, I just happen to have been given some liquid argon cells earlygame and find myself needing the cells? Also it's interesting that I can't click liquid argon into seared tanks, but I can into wood tanks (but I can't iron bucket it back out of the tank?).

**Comment by Freebi85** [comment]
I'm sorry, there are no plans to convert these two liquids and/or gases to each other.

Also i cannot change how a fluid or gas behaves in tanks or other containers. You must suggest this to the author of the respective mod.
