### ISSUE TITLE
Upgraded Reservoir with a holding enchant gets downgraded to Reservoir (basic) at some point during gameplay.

### ISSUE THREAD

**Issue by JurasTW** [Freebi85/Dungeons-Dragons-Space-Shuttles#644]
A weird one. I have used Reservoirs a lot in the past so not sure if this is a mod issue. May be a conflict or a save corrupt.

Steps to recreate:
craft hardened (or above) reservoir
enchant for holding (any level)
use normally to transfer huge amounts of liquids around

happened to me 3 times across multiple versions. I had 2 enchanted hardened reservoirs. one turned into a basic one, keeping the enchants. then the other as well. I lost one to the backpack update and crafted a new one, upgraded it till reinforced and enchanted to holding 4. used to transfer water and liquid starlight. and again it turned to a basic reservoir while keeping the enchant. i believe the holding enchant is critical for recreating the issue.

I was unable to pinpoint the exact moment when this happens, but the last instance did happen within an hour of creating the item and 1 save-load.
Did not find this issue mentioned in discord>singleplayer support

**Comment by Freebi85** [comment]
That's indeed a weird one. And annoying! I couldn't reproduce this on the quick, but I believe you.

Unfortunately, there's not much I can do about interactions with enchantments. But you have already listed a lot of detailed steps. I suggest you post that on Thermal Expansion and see what the devs have to say about it. After all, holding is their own enchantment.

Sorry I can't be of more help 😞
