### ISSUE TITLE
Storage Drawers Tiered Upgrades

### ISSUE THREAD

**Issue by Reygok** [Freebi85/Dungeons-Dragons-Space-Shuttles#645]
Hi, I think it would be nice to be able to use previous tier storage drawer upgrades in the next tier. Replacing the Storage Module in the middle each time. Otherwise you can trash all your upgrades each time you move up a tier, feels kinda wasted...

**Comment by Freebi85** [comment]
Since I already had several surveys on various tiering systems I know that this is mostly not welcome for most people. But I can consider recycling the worse upgrades to get templates and stuff back.
