### ISSUE TITLE
Charge Certus Quartz and Oredictionificator

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#648]
(Related to #376)

Not sure if this is related but I found two issues with how Charged Certus Quartz interacts (or not) with the Oredictionificator:

1) You can convert charged Certus Quartz to regular certus quartz inadvertently with the Oredictionificator.  oredict entry for charged certus quartz is both oreCertusQuartz and oreChargedCertusQuartz.  When you enter the former oredict entry then pump certus quartz of either type through it, it will "uncharge" the charged certus quartz back to the regular variety.

2) Charged Certus Quartz will not convert to the "regular" Charged Certus Quartz using this device.

Screenshots provided.
![2020-02-06_20 08 28](https://user-images.githubusercontent.com/10191173/73992795-38434280-491e-11ea-9760-fb57c338e088.png)
![2020-02-06_20 10 55](https://user-images.githubusercontent.com/10191173/73992798-3a0d0600-491e-11ea-8ce4-7b87f6da27c2.png)
![2020-02-06_20 11 05](https://user-images.githubusercontent.com/10191173/73992802-3bd6c980-491e-11ea-91f9-7954bd566893.png)
![2020-02-06_20 26 18](https://user-images.githubusercontent.com/10191173/73994250-e51fbe80-4922-11ea-805d-f70e7a75adf3.png)

**Comment by Freebi85** [comment]
Yeah i removed this intentionally to not let people easy convert to charged certus quartz 😃 

Nevertheless there is the possibility to do the opposite if you have too much "charged quartz" for whatever reason. I consider this a small QOL feature, 

I think it's a nice little feature. Let me know what you think about it.

**Comment by Danekjovax** [comment]
Well, the problem is it will only work for regular certus, and "uncharge" charged certus.  No other way.  I think it would be fine to leave uncharged as uncharged and charged as charged.  So no, I don't like the QoL.  I'd like to preserve the charge state and just convert out of the UB stone type with this device.

If it's because of the dual oredict definitions of the charged version, then I'll raise a ticket with the mod owner.

**Comment by Freebi85** [comment]
Oh well should be easy to remove the oredict entry from the charged stones^^
