### ISSUE TITLE
Some Draconic Evolution items will not go into Simply Backpacks?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#649]
I discovered that Pickaxes and Staves of Power from Draconic Evolution cannot not be placed inside a Simply backpack, although other DE items go in without any problem.

Is this intended?  See screenshot:
![2020-02-06_21 01 34](https://user-images.githubusercontent.com/10191173/73994546-e3a2c600-4923-11ea-817f-e59fff8c3a54.png)

**Comment by Freebi85** [comment]
Interesting, no i don't think this is intentional. 
But only the maker himself can answer this question. Since this is a mod issue, I recommend to open a new ticket here:

https://github.com/Flanks255/simplybackpacks/issues
