### ISSUE TITLE
Request: path to "upgrade" Mystical Aggraditions Dragon Scale, which currently drops, into Quark Dragon Scale, which doesn't

### ISSUE THREAD

**Issue by Azutte** [Freebi85/Dungeons-Dragons-Space-Shuttles#657]
If not outright switch out the items, or put them in an oredict entry so the recipe works. 

Maybe (at most) Runic Altar recipe surrounding the MA one with Ice and Fire dragon scales? Throw the MA one into elf portal? Shear the dragon? Blood infuse the MA one? Dunk it in boosting mixture? Surround it in Magic Powder?

The Fire Axe, Kikoku, and Compound Bow require a comical amount of elytra and I've been chastised in the past for personally skyrocketing the file size of the End on a server looking for them. Enabling the already progressively harder dragon fight to put out an elytra (directly or indirectly, depending on drop or recipe) would in itself be a cost higher than simply going out and finding another one, except in terms of the most crucial resource: hard drive space.

**Comment by Freebi85** [comment]
When an Ender Dragon is killed, one Dragon Scale will be dropped but this will ONLY happen on summoned dragons by use of an End Crystal on each side of the dragon nest. 

You won't get one from the naturally spawned dragon or from some other mod rituals to resurrect the dragon.

I'm sorry but I won't put in an alternative.
