### ISSUE TITLE
Exploring the world when kaput

### ISSUE THREAD

**Issue by cederjack** [Freebi85/Dungeons-Dragons-Space-Shuttles#658]
I was exploring in a private multiplayer server with forge essentials added and the server crashed. Was in a forest biome loading new chunks.

[crash-2020-02-09_18.59.24-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/4177714/crash-2020-02-09_18.59.24-server.txt)

**Comment by Freebi85** [comment]
Pls move to our tech support channel in the discord for help. There is no support for serverside issues like the template says in this github.
