### ISSUE TITLE
Yrdeen alloy ratio

### ISSUE THREAD

**Issue by Landmaster** [Freebi85/Dungeons-Dragons-Space-Shuttles#659]
Right now, Yrdeen has a janky alloy ratio requiring concrete as a multiple of 144mb, despite the fact the fact that concrete is made in batches of 500mb. Adamant's alloy ratio was fixed in 7.0b, but Yrdeen's hasn't yet. In addition, molten Osram, a necessary component for Yrdeen, can't be made in the Melter.

Also, is Yrdeen planned to be creatable in the Advanced Alloy Smelter multiblock? Just wondering.

**Comment by Freebi85** [comment]
This alloy is already under revision and will have better ratios and possibly other components in the next patch. It is certain that liquid concrete from a mixer is still needed. 
There is also a recipe planned for the advanced alloy smeltery.

**Comment by Landmaster** [comment]
`It is certain that liquid concrete from a mixer is still needed`

Just wondering, does that apply to the Advanced Alloy smelter recipe as well, or does it apply just to the ordinary smetery recipe?

**Comment by Freebi85** [comment]
(∩ ͡° ͜ʖ ͡°)⊃━☆ﾟ✧ It's magic
