### ISSUE TITLE
Localization of quests

### ISSUE THREAD

**Issue by cyber01** [Freebi85/Dungeons-Dragons-Space-Shuttles#66]
Hello, what about localization of quests to other languages? If you believe the WIKI(https://github.com/Funwayguy/BetterQuesting/wiki/Localisation)  mod BetterQuesting, then this is done with the help of resource packs, and therefore with the assembly should be supplied with the files of localization (volunteers will help with this).
I think this will increase the number of modpak players. Not everyone is comfortable (or not everyone knows well) English.

For my part, I am ready to help with the localization of quests in Russian (ru_RU)

Nickname on MinecraftCurse - cyber01

**Comment by Freebi85** [comment]
Hello =)
Yes I am definitely interested! I would like to translate the book into German as well. But I have to honestly say I don't quite understand how it works. I read the wiki and did some tests but it didn't work. I am grateful for any help. Maybe I see on the basis of an example how I have to do this exactly.

**Comment by cyber01** [comment]
Honestly - I did not try to build in the localization of the BetterQuesting, I will test it by the end of the day today.

**Comment by cyber01** [comment]
I did it, but the truth is that you have to rework the whole DefaultQuests.json.

This can be either a resource pack

Resource pack example: 
[test.zip](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/2788917/test.zip)



How to do:
Open DefaultQuests.json in a text editor, find the variables line"name:8": "Welcome!", and replace with "name:8": "ddss.0.10.name" the variable name can be anything, I chose this format:
ddss.0.10.name where, ddss is the name of the assembly, 0.10 is the ID of the quest ("0:10" in the top of each quest), and then the field name.

Then we enter a variable with the same name in the lang file and assign a value. An example of a lang file in a resource pack, and in ru_ru.lang it looks like this: 
ddss.0.10.name=Добро пожаловать! 

Добро пожаловать - russian welcome

In game (with enabled test resource pack): [Screenshot](https://puu.sh/CBelW.png)

The developer BetterQuesting wrote that you can put Lang files in the resource directory, but it did not work for me. (i tried many variants)

**Comment by Freebi85** [comment]
Thank you! It's easy with that. So I just need to translate and rename the file in my example to de_ and put into the folder.

**Comment by Freebi85** [comment]
yes I don't want to change anything on the main file.

**Comment by cyber01** [comment]
I'm not against

**Comment by cyber01** [comment]
Work is being done in repository https://github.com/cyber01/ddss_locale/

**Comment by cyber01** [comment]
All done, repo https://github.com/cyber01/ddss_locale
