### ISSUE TITLE
Fruit Press Liquids Not Same As JEI Quantity

### ISSUE THREAD

**Issue by everseeking** [Freebi85/Dungeons-Dragons-Space-Shuttles#661]
**Modpack Version**: 7.1a
**Machine**: Binnie's Extra Trees Fruit Press
**Issue**: Either JEI is showing incorrect fluid quantity output or the fruit press is not producing the amount it should.

JEI shows a tomato producing 100mb of tomato juice, but it is creating 96mb.

JEI shows an apple producing 200mb of apple juice, but it is creating 192mb.

I've only tested those two so far but others may be incorrect as well.

**Comment by Freebi85** [comment]
Hello :)
Thank you for reporting but i can't change anything there. You need to report this to the mod author since I cannot change all the recipes in binnis machines. (Sadly no creafttweaker integration)
maybe the loss is intentional by the developer.

Cheers

**Comment by everseeking** [comment]
Ok, thanks for the info!

It appears the issue has been fixed but your modpack is a handful of versions behind, just FYI (probably using an older version for compat/stability reasons).

**Comment by Freebi85** [comment]
Ah yes i have some random crashes with latest binnis version 😢But this is already reported so hopefully there is soon a fix.
