### ISSUE TITLE
[Oversight] Kanthal heating coil quests appear twice

### ISSUE THREAD

**Issue by Landmaster** [Freebi85/Dungeons-Dragons-Space-Shuttles#664]
In the questing book, it asks to craft a set of 4 kanthal heating coils twice, once in MQ3 and the other in MQ4. However, there's no point in crafting two sets, since the blast furnace only accepts one set of 4; the other set has to be nichrome. This could be fixed by making the MQ4 quest only ask for nichrome.

**Comment by Freebi85** [comment]
oopsi thank you :)
