### ISSUE TITLE
Cinnebar ores don't give cinnebar

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#667]
It's strange that cinnebar, a fairly rare ores in the nether doesn't actually make cinnebar. Nothing is gated by cinnebar as far as I can tell there are other way to create them. 
Maybe an oversight?

**Comment by Freebi85** [comment]
Cinnebar Ore is from Tech Reborn and completely different to Thermal Expansion cinnabar. Usually used only in the Techreborn grinder iirc.
However, will check tonight if there are legit uses for it, if not it gets removed.
I don't gonna unify it to TE cinnabar which is obtained completely different
