### ISSUE TITLE
Immersive engineering Sheetmetal Chutes bugged

### ISSUE THREAD

**Issue by billhenson404** [Freebi85/Dungeons-Dragons-Space-Shuttles#668]
The immersive engineering Chutes are invisible to other players and upon breaking them they turn into a non textured conveyor belt with a odd name
![unknown2](https://user-images.githubusercontent.com/60955062/74303291-53032600-4d27-11ea-9e27-1391da07cf91.png)
![unknown3](https://user-images.githubusercontent.com/60955062/74303297-58f90700-4d27-11ea-8b4f-9238b6bb727c.png)
![unknown](https://user-images.githubusercontent.com/60955062/74303300-5b5b6100-4d27-11ea-9b02-d650bd1782a5.png)

**Comment by Freebi85** [comment]
Hello :)
Unfortunately this is not something I can fix myself. (Rendering issue?)
Only recipes or quests. Please report this to the mod author if this is the case with Default textures.
