### ISSUE TITLE
tech reborn grinder recipes missing for several things 

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#669]
Don't wanna open a hundred bugs for these missing recipes, so here is a list:
Tech reborn grinder recipes missing:
1. Sulfur
2. Blizz Powder
3. Blitz Poweder
4. Basalz Powder
5. Sugar (from sugar cane)

6. Black quartz ore is crushed to dust directly in the grinder instead of to black quartz like other crushers (pulverizer, AA crusher, immersive engineering crusher etc)

7. Tech reborn refined iron ingots cannot be made in tech reborn alloy smelter

8. Tungsten dust cannot be made from crushing tungsten ores in tech reborn grinder (while every other crusher machines can)

**Comment by Freebi85** [comment]
Dont get me wrong but i don't gonna add all missing recipes from Thermal Expansion just because of bad mod interaction/integration. i do my best but i'm im pre final release so dont expect too much.

**Comment by LordHellscream** [comment]
no problem! thanks for the great work! are you making another modpack?
can't wait.

**Comment by Freebi85** [comment]
Yes, I'm planning something. I'm afraid I can't tell you too much about it yet^^

**Comment by LordHellscream** [comment]
List updated.

**Comment by LordHellscream** [comment]
list updated.

**Comment by LordHellscream** [comment]
list updated.

**Comment by Freebi85** [comment]
I think i added now the most important things 👍
