### ISSUE TITLE
Infinity Capacitor is way too expensive

### ISSUE THREAD

**Issue by DennisCorvers** [Freebi85/Dungeons-Dragons-Space-Shuttles#670]
The infinity capacitor is much more expensive than a creative energy cube. The capacitor is only used for storing energy while the cube can generate an infinite amount of energy.

There is currently no sense in crafting the capacitor as it is more expensive and inferior to the energy cube. The capacitor recipe should become much cheaper and be moved from end-game to late game.

**Comment by Freebi85** [comment]
The Capacitor will be removed in next patch as mentioned in Discord.
