### ISSUE TITLE
Some creative items should be disabled

### ISSUE THREAD

**Issue by DennisCorvers** [Freebi85/Dungeons-Dragons-Space-Shuttles#671]
Any and all creative items that allow players to obtain infinite x items should be disabled. As making just one of these essentially allows the player to make infinite more in no time.

**Comment by Freebi85** [comment]
Hi :)
I Disagree.
This requires an insane amount of work and progression through the whole pack and most of the mods. Until then you usualy don't worry about that anymore.
If people share this stuff in multiplayer for others it's not my fault. Pack is designed for singleplayer experience.
Cheers

**Comment by DennisCorvers** [comment]
This requires an insane amount of work and progression through the whole pack and most of the mods.
Yes, and once you've crafted a single creative vending upgrade, you can use that to get infinitely more materials. You only ever need to craft/grind one of these items, and everything else can be disregarded.

I AM talking about single player. Items like these completely destroy off any further gameplay or need to make anything.
