### ISSUE TITLE
No Jauxum in TF

### ISSUE THREAD

**Issue by CalligoMiles** [Freebi85/Dungeons-Dragons-Space-Shuttles#673]
JEI says Jauxum generates in the Twilight Forest.

Four hours of going at every granite pocket I could find with a prospector and hammers says there's none whatsoever, especially since I started finding it regularly again once I went back to the Overworld.

**Comment by Freebi85** [comment]
Oh weird. It's actually only in Deep Dark and Overworld. Is a JEI display error. I'll see if I can get it out of there.
