### ISSUE TITLE
Discord ban not expiring

### ISSUE THREAD

**Issue by CalligoMiles** [Freebi85/Dungeons-Dragons-Space-Shuttles#674]
Sorry to bother you about this here, but I currently have no way of reaching anyone on the server.

I got banned for a week for using one naughty word too many. That was almost two weeks ago, and I still can't rejoin. Help pls?

(Calligo#3498)

**Comment by Freebi85** [comment]
This is indeed a whole new way of communicating this lol. Try again, should work now. And keep it clean ya^^
