### ISSUE TITLE
Unnecessary Oxygen Collector quest

### ISSUE THREAD

**Issue by Landmaster** [Freebi85/Dungeons-Dragons-Space-Shuttles#675]
In MQ4, there is a quest asking for a Galacticraft Oxygen Collector in order to obtain the oxygen needed to survive in space. However, the Oxygen Collector is completely unnecessary since Mekanism oxygen (which is made with an Electrolytic Separator from MQ2) can be used in place of Galacticraft oxygen.

**Comment by Freebi85** [comment]
Unnecessary is exaggerated. It is no different than using a pulverizer instead of the grinder beside efficency. The best I can do is move it to a sidequest. Will see

**Comment by Landmaster** [comment]
`Unnecessary is exaggerated. It is no different than using a pulverizer instead of the grinder beside efficiency.`

This is a flawed analogy. With the pulverizer vs grinder, the Tech Reborn grinder is obviously faster than a Pulverizer with upgrades of similar cost, but the Pulveriser is available far earlier on in the game and does not require steel. On the other hand, a Galacticraft oxygen setup, even though it is far more late-game than the Mekanism setup, produces much less oxygen per tick (9.3 vs 256 mb/t at max upgrades) and requires a continuous input of energy (unlike Mekanism, which can produce for free with a gas-burning generator). This difference is even more pronounced when you consider that you already have the infrastructure for Mekanism oxygen well before MQ4 (mainly for 3x ore processing), meaning that you really only have to expend speed upgrades in practice.

**Comment by Freebi85** [comment]
I was thinking about making it an optional quest so you can still use the mekanism setup IF you still have one at this point.  So you can just choose to go ahead or not.

And btw Suggestions and comments are always welcome. But when I say no there is no reason for a "downvote". Although I have brought a constructive solution to implement it as an optional quest which is a very good solution. I do this voluntarily in my spare time.  Whatever I decide, you will have to live with it.

**Comment by Landmaster** [comment]
Let me make it clear that the downvote was not because of you moving it to a sidequest or doing whatever you decide, which I have zero problems with. The reason why I downvoted was because you claimed that it was "no different than using a pulverizer instead of the grinder beside efficiency," which is a misleading comparison.

**Comment by LordHellscream** [comment]
@Landmaster : completely off-topics but Freebi85 is one of the nicest mod creator out there. With so many douchbags out there he's a rare one and should be respected. Downvoting him while he clearly already agreed to look into the issue is really uncalled for. Remember he is spending his own time to providing free entertainment to so many of us, we should be more appreciative. Just my 2 cents

**Comment by Landmaster** [comment]
I apologize if my wording might seem like I'm trying to put him down, which I absolutely do not intend to. It's just that as a mod author myself of one of the mods in the pack I get frustrated at times when something seems off in a pack or the like. As much as I like a lot of the aspects of this pack (the selections of mods being a strong point for the most part), there's a few things that irk me at times about this pack that make it fall just short of me really claiming that this pack is the best of 1.12 TBH

**Comment by Freebi85** [comment]
Thanks for praise and criticism but continuing this discussion in github makes no sense. If there is anything else to talk about contact me in Discord. You can always write to me privately. DM messages are not blocked.

In conclusion:
This is my first modpack ever and I didn't expect so many people to try it anyway. I try my best. BUT like in every modpack there are people who love it and people who hate it. And like in every modpack you have the choice to play it or not. My visions and imaginations do not always mean that they correspond to those of other people. And that is fine. 
For example, I don't agree that you can shoot through walls with laserguns from plustic, I asked for a config and it was rejected. It's okay, I live with it :)

**Comment by Landmaster** [comment]
Thanks. PlusTiC was also my first mod
