### ISSUE TITLE
"Zombie Chunk" not craftable.

### ISSUE THREAD

**Issue by Hexxonite** [Freebi85/Dungeons-Dragons-Space-Shuttles#676]
The receipe for "Zombie Chunk" says it can be dropped but it's also craftable and has a recipe..

![image](https://user-images.githubusercontent.com/5312542/74464336-a6928280-4e93-11ea-9ac9-f933f00d94ca.png)

However the recipe requires "Tier 1 Mob Chunk" as ingredient, which itself is the result of smelting the "Zombie Chunk" in an oven... This doesn't sem to make sense?

![image](https://user-images.githubusercontent.com/5312542/74464362-af835400-4e93-11ea-82d6-5c679b21a338.png)

Also I have killed about 100 zombies already and even though the drop-chance should be 30% I didn't get a single one? Are there maybe some special circumstances for that?

Thanks in advance ^^

**Comment by Freebi85** [comment]
Hello :)

You need a soulium dagger in order to can obtain mob chunks. 
It becomes craftables after you found Tier 1 Mob chunk which can be crafted to Zombie chunks :)
