### ISSUE TITLE
Electrotine ores cannot be broken into electrotine with Refined Storage Destructor (non-silktouch)

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#677]
Electrotine ores (obtained through void ore miners) cannot be broken into electrotine when mined with the refined storage destructor. even though regular pickaxe can. 
When the ore is destructed, its mined the ore (as silk-touched), which basically mean it does nothing.

**Comment by Freebi85** [comment]
Unfortunately I cannot change how the destructor affects individual ores. You will have to report this to the mod author and process the ore in another way until this is fixed. However, it is possible that mod support has been discontinued for 1.12 :(
