### ISSUE TITLE
Request: Gas tanks (from mekanism) should have alternative recipes in carpenter/rolling machine/assemblers etc

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#678]
Currently mekanism gas tanks all have to be made in blacksmith workshop. I don't mind that except the gas tanks are used in many recipes. I feel like it's ok to have large crafting table for machines etc, but items that are used as sub-components should have alternative recipes to minimize unneeded tediousness in later stage of the game when you need to scale up the production.
I think rolling machine would make the most sense for it. but carpenter, master assemblers would also work.

Thanks for your consideration.

**Comment by Freebi85** [comment]
Oo in which pack version are you playing on? Gas tanks was added to the master assembler 2k20 😄

**Comment by LordHellscream** [comment]
oh you are right! i missed it. must because im not that far in the pack yet. But some intermediate option would be awesome, right now its basically stone age -> futuristic age with nothing in between. But again, its entirely up to you. Not gonna force it. Just suggestion :)

**Comment by Freebi85** [comment]
Haha :D yeah let me see what i can do with rolling machine.
