### ISSUE TITLE
OpenModularPassiveDefense

### ISSUE THREAD

**Issue by Binomialgeoduck** [Freebi85/Dungeons-Dragons-Space-Shuttles#68]
Whenever you touch a fence for this mod, you crash with an error relating to this mod and Galacticraft Core. Not sure how many people have had this issue but my room mate and I can not play anymore because of it

**Comment by Freebi85** [comment]
Hello=)
Thx for reporting. Update manually OpenModularPassiveDefense  to latest alpha build should solve the problem. I will include this in my next update.

Freebi

**Comment by Binomialgeoduck** [comment]
Thank you so much for a fast response. We are loving this pack and really
didnt like the idea of having to stop playing. That you for helping us fix
this
