### ISSUE TITLE
Material Absorber ( Not working / broken recipes )

### ISSUE THREAD

**Issue by RomixERR** [Freebi85/Dungeons-Dragons-Space-Shuttles#680]
There is no (but it used to be) recipe for an "Material Absorber" from "RfTools Dimensions". Is it disabled in config?

<img width="699" alt="2020-02-15_13 34 30" src="https://user-images.githubusercontent.com/13717583/74585634-0dc94780-4ff8-11ea-8574-40faa357f9bc.png">

**Comment by Freebi85** [comment]
It's diabeld in this pack, you have to play without it^^ Same with liquid absorber.
And there is no config for it.
