### ISSUE TITLE
The Neutron fluid. (Suggestions for missing or additional integrations in machines)

### ISSUE THREAD

**Issue by RomixERR** [Freebi85/Dungeons-Dragons-Space-Shuttles#681]
I suggest a recipe for Fluid Infuser:
"Neutron Fluid" from NuclearCraft (1000mb)     +     "Pile of iridium dust" from Tech Reborn     - >     to "Pile of Neutrons" from Avatria.

<My playlist (RUS) Dungeon dragons and space shuttles    [https://www.youtube.com/watch?v=iioI01AfJN8&list=PLDvAF6sC3pZ2zH7ZdLJffNAYY_MHzAP5S](url)    >

**Comment by Freebi85** [comment]
Thank you for playing my pack :)

Sorry neturonium have only 2 specific ways to be generated atm and i will stick with it for now.
