### ISSUE TITLE
Suggestion: Neutronium singularity

### ISSUE THREAD

**Issue by mgla** [Freebi85/Dungeons-Dragons-Space-Shuttles#683]
Hi,

I noticed that neutronium quickly has no uses once fully automated. Might I suggest a neutronium singularity to get rid of excess neutronium (and bragging rights?). Or maybe thats better as a Avaritia suggestion?

**Comment by Freebi85** [comment]
Well i aready added a bunch of more uses for next update but still not that much. 
I didn't want to turn this into an important resource that is constantly needed or I would have to change and adapt the lategame again. It would be good to also nudge Avaritia for more ideas.
Maybe I can integrate it in my next pack a bit better :)

**Comment by Freebi85** [comment]
Just to be clear, i don't gonna add a neutronium singularity on my end^^

**Comment by Danekjovax** [comment]
Placing a neutronium singularity in the world destroys the chunk it's placed in and crashes the server, due to the space/time rift caused. >;2)
