### ISSUE TITLE
I can't craft in my celestial altar!

### ISSUE THREAD

**Issue by akika47** [Freebi85/Dungeons-Dragons-Space-Shuttles#684]
Its suddenly happened a week ago. There is no problem with the structure or the starlight levels. The crafting recipe can't be wrong because i copied it from JEI. Here is the photo: 
![image](https://user-images.githubusercontent.com/61090999/74592747-d02ee380-5024-11ea-85b8-4e811836d941.png)

Edit: I can't use my attunement altar too(i only can't attune myself, i can attune rock crytals). Its didn't give me perk. And in my Astral Tome the attunement chapter didn't come up. Pictures: 
![image](https://user-images.githubusercontent.com/61090999/74592789-15531580-5025-11ea-8f13-7f4154cd7d5e.png)
![image](https://user-images.githubusercontent.com/61090999/74592830-5ea36500-5025-11ea-99af-dd9ad142d415.png)

**Comment by Freebi85** [comment]
Seems your personal progression in astral sorcery is gone for some reason. Is this in singleplayer or multiplayer? Did you tried to unlock your knowledge with the creative item? Otherwise no idea sorry.
The astral sorcery github can probably be more helpful the me.

**Comment by akika47** [comment]
> Seems your personal progression in astral sorcery is gone for some reason. Is this in singleplayer or multiplayer? Did you tried to unlock your knowledge with the creative item? Otherwise no idea sorry.
> The astral sorcery github can probably be more helpful then me.

Oh i didnt tried it with the creative item but now i tried and its fixed so thank you Freebi!

**Comment by Freebi85** [comment]
Noice :D

**Comment by akika47** [comment]
> Noice :D

Btw its unlocked everything so i need to remember what i crafted and what the item unlocked for me. :D
