### ISSUE TITLE
The lasers are missing in empowerer

### ISSUE THREAD

**Issue by akika47** [Freebi85/Dungeons-Dragons-Space-Shuttles#686]
Here is the photo: 
![image](https://user-images.githubusercontent.com/61090999/74594611-b7302d80-5038-11ea-8f37-bdb4acd8d401.png)
Edit: And sometimes its overwrite the texture of the items like this: 
![image](https://user-images.githubusercontent.com/61090999/74594685-7ab10180-5039-11ea-81a8-d539b1bac3c7.png)

**Comment by Freebi85** [comment]
Not sure if this is an issue at all with the empowerer. However, I will try something there if i can change that 😃  
But pls report only issues around recipes and/or quests in my tracker and mod issues to their authors^^
You can always DM me in Discord if you're not sure about something.

**Comment by akika47** [comment]
> Not sure if this is an issue at all with the empowerer. However, I will try something there if i can change that 
> But pls report only issues around recipes and/or quests in my tracker and mod issues to their authors^^
> You can always DM me in Discord if you're not sure about something.

Okay!

**Comment by Freebi85** [comment]
maybe i found a solution :0

**Comment by Freebi85** [comment]
(∩ ͡° ͜ʖ ͡°)⊃━☆ﾟ✧ It's magic
