### ISSUE TITLE
Divinity Reagent recipe appears to be broken/non functional

### ISSUE THREAD

**Issue by Yiluxius** [Freebi85/Dungeons-Dragons-Space-Shuttles#687]
Despite having all the materials in the forge plus enough will in the tartaric gem, the crafting doesn't seem to work.
https://cdn.discordapp.com/attachments/523043263553208330/678414913026261015/unknown.png
https://cdn.discordapp.com/attachments/523043263553208330/678415191746019347/unknown.png

**Comment by Freebi85** [comment]
This default blood Magic recipe seems broken either way. I need to completely rework it i guess.
