### ISSUE TITLE
New Server Crashing

### ISSUE THREAD

**Issue by vitrop** [Freebi85/Dungeons-Dragons-Space-Shuttles#688]
[crash-2020-02-15_21.33.05-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/4209391/crash-2020-02-15_21.33.05-server.txt) 
I created a new server for me and my friends hosted through HostHavoc. I followed the steps they provided to install the modpack and It will not stop crashing. This is the crash report I have went through several forums but have found nothing to help.

**Comment by Freebi85** [comment]
Pls read first the template when open issues. Mo server support at all in github. Pls join server tech support channel in Discord 😉
