### ISSUE TITLE
openj9

### ISSUE THREAD

**Issue by thehackedone** [Freebi85/Dungeons-Dragons-Space-Shuttles#689]
I know it probably isn't supported, but does anyone use openj9 to run their server? I switched to it after reading about how much "better" it is less memory and faster blah blah, but I am lagging now on a fresh server. Any suggestions possibly for JVM arguments?

Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by Freebi85** [comment]
This question is better suited for tech support discord then my github sry. No server support at all hete.
