### ISSUE TITLE
No recipe for Arc Furnace Electrodes

### ISSUE THREAD

**Issue by wideblaze** [Freebi85/Dungeons-Dragons-Space-Shuttles#69]
Light Engineering Block Quest requires Arc Furnace Electrodes -- no recipie for electrode blueprint.

Only other method I can find is use Metal Press which requires Heavy Engineering Block (seems out of order) -- which in turn requires osram (no idea how to find that)

**Comment by Freebi85** [comment]
Thank you for bringing this to my attention. I will include the blueprint recipe in the next patch and provide better possibilities for coak dust. You can find Osram in the Nether on the surfaces of lava lakes.
