### ISSUE TITLE
[Mod Suggestion] More space content

### ISSUE THREAD

**Issue by geryyyyyyyyyyy** [Freebi85/Dungeons-Dragons-Space-Shuttles#690]
Hello!
I think to enjoy more the space travelling, need some update.
I have 3 mod which can do your modpack more enjoyable :
-Galacticraft add-on
-Galaxy Space
-Hwyla

**Comment by Freebi85** [comment]
Hi :)
Sry i'm in a pre final release and don't gonna add more mods to the pack for now. Also Galaxy space have some issues with extra planets.
Also we have The One Probe so there is no need for hwyla^^
