### ISSUE TITLE
Suggestion: Make Enderium Element to Ingot recipe cheaper 

### ISSUE THREAD

**Issue by CloudyDash** [Freebi85/Dungeons-Dragons-Space-Shuttles#691]
Currently when processing Majestic Dust to Majestic ingots, a large amount of Enderium Element is generated as a byproduct. To turn these into ingots is fairly expensive, and not worth it at all, since enderium is easy to make with the smeltery/advanced alloy smeltery.
Perhaps the Chemical Compound in the recipe could be removed, and the amount of sodium hydroxide needed reduced?

**Comment by Freebi85** [comment]
I'm afraid I don't agree with that. Enderium needs platinum. Even though it's easy in the new furnace, it's still rare.
Triberium is easier to find/make than platinum even if it is a PITA.
However, Sodium hydroxide can be reduced.
