### ISSUE TITLE
Suggestion: enable recipe for Thermoconducting alloy in other alloy machines?

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#693]
The nuclearcraft alloy furnace is not hard to make, and the thermoconducting alloy is gated by the boron arsenic. It's quite strange we will have to make this redundant alloy furnace from nuclearcraft just to make this particular alloy.
In the tier 3 quest line, it's not even a required quest. Oversight?

**Comment by Freebi85** [comment]
Well it's just a side quest. May useful may not, everyone has to decide for themselves. I'm not going to remove side quests. Also because removing quests brings problems with new ones in developement^^
