### ISSUE TITLE
Wraughtnaut can have Regen effect

### ISSUE THREAD

**Issue by Yiluxius** [Freebi85/Dungeons-Dragons-Space-Shuttles#696]
The Ferrous Wroughtnaut from Mowzies mobs can apparently have the "Regen" effect, essentially making it unkillable, since you can only damage it every few animations.

**Comment by Freebi85** [comment]
I'm sorry but i can't just remove the regen effect from specific mobs and i don't want to remove it completely. i also don't want to remove the possibility that they can be infernal. 
I would say leave that one and search for to the next one. There are more than enough^^
