### ISSUE TITLE
Main Quests are incorrectly marked as Side Quests

### ISSUE THREAD

**Issue by WaitingIdly** [Freebi85/Dungeons-Dragons-Space-Shuttles#697]
Reporting:
- Any problems with quests (description, spelling mistakes, task not recognized etc.)

I didn't do enough looking around yesterday, when I posted the prior request, which only contained the "Black Magic [Tier 2]" first quest. Here is what I've noticed since then:

A number of quests (5 of them) are marked as a side quest incorrectly. They are all the first quest of a chapter. 

- The first quest in "Tier 1 - Main Questline" has its first quest, "Engineers Workshop" (#327), incorrectly marked as a "side quest"
- The first quest in "Ores, Alloys & Smeltery [T1]" has its first quest, "Tinker Time #1" (#243), incorrectly marked as a "side quest"
- The first quest in "Ores, Alloys & Smeltery [T2]" has its first quest, "Tool Forge" (#703), incorrectly marked as a "side quest"
- The first quest in "Mystical Agriculture [Tier 1]" has its first quest, "More Infernium" (#273), incorrectly marked as a "side quest"
- The first quest in "Black Magic [Tier 1]" has its first quest, "Getting Started with Black Magic" (#488), incorrectly marked as a "side quest"

Suggestion: Make the boss mob kills in chapter "Wild Hunt" marked as important quests.
They are: "#848", "#849", "#850", "#878", "#1261", "#997", "#856", and "#857", named "Wroughtnaut Hunter", "Barako the Sun Chief!", "Frost Maw Hunter", "Naga Hunter!", "Alpha Yeti Hunter!", "Ur-Ghast Hunter!", "Enderdragon Hunter!" and "Witherboss Hunter!"

In addition, "Wroughtnaut Hunter" (#848) and "Frost Maw Hunter" (#850) are both missing exclamation points, unlike the rest of the boss hunter quests.

**Comment by Freebi85** [comment]
Thx for the heads up but i only mark mainquests to know how to follow which path if one is required. Everything else is fine for me.

**Comment by Freebi85** [comment]
Not an issue at all to mark the very first quest of a chapter as main quest because you have no other chance to progress without but i will at least change them^^
