### ISSUE TITLE
Auxiliary sieve doesn't appear to improve centrifugal separator secondary output

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#699]
Not sure if bug or intended, but with 3 of these sieves upgrade, im still getting roughly 4-5 evil powder out of each stack of dark magic dust. Bug? or intended.

**Comment by Freebi85** [comment]
This is correct, apparently all custom recipes in Thermal Expansion machines are not affected by the sieve upgrades. 

Edit: After some research in the crafttweaker discord... seems thermal doesn't support custom recipes that can be modified with augments in general. So 7% is the default value.
