### ISSUE TITLE
cant craft vacuumulator

### ISSUE THREAD

**Issue by DragonmasterDJ** [Freebi85/Dungeons-Dragons-Space-Shuttles#7]
When trying to craft a vacuumulator device from thermal expansion, it will not show up, even though the recipe is exactly the same. When trying to make other devices.  like the item allocator, it works.

recipe:
![sqqqssqsqsqsq](https://user-images.githubusercontent.com/29170640/48976791-ba609600-f0e1-11e8-80d2-bcd5d00ee77c.PNG)

me trying to craft it: 
![2018-11-25_18 35 36](https://user-images.githubusercontent.com/29170640/48976798-d5cba100-f0e1-11e8-9ed1-fa77bc9d70b3.png)

me trying other device recipes:
![2018-11-25_18 38 56](https://user-images.githubusercontent.com/29170640/48976802-dfed9f80-f0e1-11e8-920b-dd07aee14483.png)

**Comment by Freebi85** [comment]
Thanky you for Reporting =) 
I finally found the reason. Fixed in next Update.
