### ISSUE TITLE
Quantum compressor not accepting items

### ISSUE THREAD

**Issue by ahall4454** [Freebi85/Dungeons-Dragons-Space-Shuttles#700]
My quantum compressor is fully powered, has ultimate catalyst, but when trying to put items in they just sit there in the input slot and never move into the buffer, so cannot make singularities at all.

**Comment by Freebi85** [comment]
Yeah it's a weird issue sometimes with this specific machine. You have to break it, move it in another chunk nad place it back. that should work. Don't know why it sometimes does this^^

**Comment by ahall4454** [comment]
Uh oh! Thanks for the advice! Do I need to leave it in the other chunk?

**Comment by Freebi85** [comment]
No you can put it back after that^^

**Comment by ahall4454** [comment]
Awesome, thanks!

**Comment by Maarten-V1** [comment]
doesn't work for me 
skyfactory 4

**Comment by MyNameIsTrez** [comment]
Works for me!

**Comment by MyNameIsTrez** [comment]
The issue seems to only occur when I tried shift-clicking in the Ultimate Catalyst before I put any ingots in and I hadn't placed the Quantum Compressor in a different chunk first (note that shift-clicking it is useless anyways, cause it always goes into the wrong slot when you do that).

**Comment by Bigdeath** [comment]
So the thing with the junks is nonsense. Put the Quantum compressor down, turn on the power, put the Catalyst in the first slot PER MOUSE, then a stack Iron, cookie, whatever in the second slot PER MOUSE. Everything else can be done with a shift click. Or export from an ME system etc. 10k items (iron, cookies...) must be inserted for each singularity.
