### ISSUE TITLE
Please add replacement recipes for AA batteries

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#701]
Sorry if this issue is similar to the one already opened. But I feel this is a more specific request so maybe ok to open a new ticket. 
Due to the problems with autocrafting recipes that takes AA battery, is it possible to add custom items that can be converted from and to AA batteries that can be used in crafting ?
Been playing this pack for months this is one of the most painful thing I've experience. especially since AA batteries themselves are nested recipes and they are required for  many many many other things that are also nested,  Which amplifies the issue 1000 folds.

**Comment by Freebi85** [comment]
Good news.

- In next update you can stack all AA batteries up to 64 [as long they have same energy ammount or empty]
- Crafting/upgrade system completely overhauled to prevent some nbt issues in the carpenter

**Comment by LordHellscream** [comment]
Yay! Christmas!

**Comment by binh3012** [comment]
Does the next update come out soon?
