### ISSUE TITLE
sawmill thermal one 

### ISSUE THREAD

**Issue by grills68** [Freebi85/Dungeons-Dragons-Space-Shuttles#702]
hello 
the sawmill from thermal give sawdust but not any planks i try it with many different tree log no one give planks i use last version 
after a few time worked but make one stack with nothing 
the star of the first was bugged and now the second one work great sorry

**Comment by Freebi85** [comment]
I tried with vanilla, natura and forestry logs and works fine in latest version 7.1a.
But when it's already solved then it's fine^^
