### ISSUE TITLE
Please readd Energy Bees 

### ISSUE THREAD

**Issue by debadoo1** [Freebi85/Dungeons-Dragons-Space-Shuttles#703]
Please readd the Energy Bess been working towards them for weeks. For those of use who arent tach savvy in energy its the only way to go,. Please reconsider Thanks deb

**Comment by Freebi85** [comment]
Sry it's disabled bc its literally broken with all the amount of energy it produces, No chance to reenable it. There are PLENTY of ways to produce energy. Following the questbook will give you more then enough hints and possibilities to do so^^
