### ISSUE TITLE
Ring of Aesir Not Craftable?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#707]
- Not working / broken recipes 

The recipe for crafting the Ring of Aesir (Botania) is not working.  I have the requisite items (the rings of Thor, Odin, & Loki) but will not craft regardless of which crafting GUI I use.

Please fix?  Thanks! :2D

![2020-02-22_14 21 10](https://user-images.githubusercontent.com/10191173/75097947-94dd6900-557e-11ea-9aee-43237459e61d.png)

**Comment by Freebi85** [comment]
This item was removed in Botania version R1.10 346.
Sorry it's gone
