### ISSUE TITLE
I am getting this weird error where I can't get any of the tinkers construct smeltery controllers to work when I click on them. It says "Error: topaddons:tconstruct. How can I fix this?

### ISSUE THREAD

**Issue by theowspang** [Freebi85/Dungeons-Dragons-Space-Shuttles#708]
I am getting this weird error where I can't get any of the tinkers to construct smeltery controllers to work when I click on them. It says "Error: topaddons:tconstruct."
<img width="1920" alt="2020-02-22 (25)" src="https://user-images.githubusercontent.com/61368565/75102730-c7ef1f00-55b5-11ea-941c-d0c71cc851a4.png">

<img width="1920" alt="2020-02-22 (25)" src="https://user-images.githubusercontent.com/61368565/75102707-9f672500-55b5-11ea-87ac-00852647172b.png">

**Comment by Freebi85** [comment]
Don’t know tbh.  seems to be a common issue in multiplayer. Nothing to worry about. If you want some help there you have to ask in the correct github of the mod author „the one probe „
Cheers
