### ISSUE TITLE
Unbreaking can be added to Infusion Crystal but doesn't have an effect.

### ISSUE THREAD

**Issue by Dystilled** [Freebi85/Dungeons-Dragons-Space-Shuttles#709]
Enchanted an infusion crystal with Unbreaking 3, should on average cause the item to last 4x longer. 

First stack of essences crafted actually cost 66 durability somehow. 
Every other craft cost 64 durability per stack. 

0% unbreaking procs and actually cost more than normal on one craft.

**Comment by Freebi85** [comment]
Hey :) Can’t fix myself that’s a modside issue. Was reportet to the author bit he won’t gix this anymore for 1.12. pls use searchbar next time :)
