### ISSUE TITLE
Quest book - Ores, Alloys & Smeltery Tier1 - Mooore Redstone, Thaumcraft rewards

### ISSUE THREAD

**Issue by Vulrik** [Freebi85/Dungeons-Dragons-Space-Shuttles#71]
[Version 4.1] 
In the Ores, Alloys & Smeltery Tier1 reward section the reward of the quest Mooore Redstone is from Thaumcraft. I think this should be replaced with something else.
![redstone](https://user-images.githubusercontent.com/7890888/51805373-b2051280-226c-11e9-9f42-3d7930e2fa06.PNG)

**Comment by Freebi85** [comment]
Thx! =) This is already fixed in the upcoming update (available in about 1 hour)
