### ISSUE TITLE
ore dictionary of molten Beryllium?

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#710]
Molten Beryllium from Nuclearcraft cannot be used in recipes such as iridium neutron reflector. Either of them are hard to make. But i thought since they are really the same thing they should be substitute of each other in recipes to simplify autocrafting

**Comment by Freebi85** [comment]
fluids can't be oredicted. I can just add a fill recipe for the other beryllium.

**Comment by Freebi85** [comment]
I don't know why but for some reason it doesen't work with this fluid. I'm sorry :/
