### ISSUE TITLE
make energy cubes stackable for autocraft?

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#711]
Energy cubes are also a pain for autocraft with similar issues like the AA batteries. 
- Not recognized during crafting even when completely newly created ones 
- not stackable making it a nightmare to autocraft.

Since you need to do a heck lot of nesting crafting for energy matrix this amplifies the pain.

**Comment by Freebi85** [comment]
Sorry only thing i will change there is stacking size.
