### ISSUE TITLE
Nest (Animalia) not craftable

### ISSUE THREAD

**Issue by Sidetrack15** [Freebi85/Dungeons-Dragons-Space-Shuttles#712]
The nest from Animalia IS in JEI and when items are placed in the crafting grid it looks like it should craft but when you click to remove the finished item it does not craft.  Shift clicking does nothing either.  I'm assuming this is a bug but perhaps there is an alternative breeding path for chickens that I just missed.  Thanks for the help, loving the pack!
![image](https://user-images.githubusercontent.com/29827337/75118202-016f6b00-5646-11ea-80bd-55bcfa48b9d4.png)

**Comment by Freebi85** [comment]
I could craft it whitout problems in Singleplayer. Pls check again and make sure you are using the correct ingredients.

**Comment by Sidetrack15** [comment]
Yes, it's multiplayer.  I found I could just cheat the items in and they work fine so I'll just do that for my friends too.  Weird how things work in one game type and not the other.  Thanks!
