### ISSUE TITLE
Smeltery Controller add-on

### ISSUE THREAD

**Issue by carlosvega97** [Freebi85/Dungeons-Dragons-Space-Shuttles#714]
We started this modpack a few weeks ago, once we got all the material to build the smeltery and we contruct everything the smelty controller start this error. I tried to delete that add-on but didnt work.
![Minecraft](https://user-images.githubusercontent.com/25154449/75119290-b2dfc200-5681-11ea-9d01-ef06621a735a.jpeg)

**Comment by Freebi85** [comment]
Check https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/708 pls
