### ISSUE TITLE
Liquid Duplication bug

### ISSUE THREAD

**Issue by enigma0Z** [Freebi85/Dungeons-Dragons-Space-Shuttles#715]
When switching a Thermal Expansion reservoir to refill equipment (shift, r-click) and holding a stack of Tech Reborn cells, all cells are filled, but only one bucket is consumed from the reservoir.

1. Have a TE Reservoir
2. Have a stack or TR cells
3. Switch reservoir into filling equipment mode (shift right-click)
4. Hold the stack of cells

Expected: the number of cells filled is dependent on the volume of the liquid in the reservoir
Actual: All cells are filled, consuming one bucket from reservoir

Dungeons, Dragons, and Space Shuttles 7.1a (latest)

**Logs**
https://pastebin.com/kwdeaJAw

**Additional context**
I have raised a bug with Tech Reborn here: https://github.com/TechReborn/TechReborn/issues/2051
I tried to also raise a bug with Team CoFH but I can't find their issue tracker.

Most likely this is _not_ a bug with the mod pack, but I figured I'd at least put the report here as well.

**Comment by Freebi85** [comment]
Thank you for the heads up! But gonna close here. Can’t do much myself except ban the reservoirs and I’m not sure if there will be ever a fix for 1.12 anymore since they moved on.
