### ISSUE TITLE
Pressure chamber glass too cheap

### ISSUE THREAD

**Issue by siber-cat1** [Freebi85/Dungeons-Dragons-Space-Shuttles#717]
Feels like a missed recipe, but I believe the default recipe for Pressure Chamber Glass from PC:R is enabled, making the building of a pressure chamber fairly cheap, since edges and corners can also be glass. There's both a Chamber wall + glass makes one, and eight compressed iron and one glass makes 16 pressure chamber glass.

**Comment by Danekjovax** [comment]
I can only imagine Freeb's "Balanced" this one faster than you could hit the "Comment" button. >;2)
