### ISSUE TITLE
Allow crafting larger item inupts for Modular Machinery machines

### ISSUE THREAD

**Issue by AdityaGupta1** [Freebi85/Dungeons-Dragons-Space-Shuttles#718]
For large autocrafts, 9 slots (the only available input size at the moment) easily gets clogged up, and that means I have to manually rearrange materials so the crafting can continue. Allowing crafting bigger item inputs (up to 32 slots with the ludicrous input) would really help with this problem.

**Comment by Freebi85** [comment]
Sure, why not^^
