### ISSUE TITLE
Recipe to create carpenter should require  9 types of items or less

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#721]
Currently carpenter requires 10 types of items, making it not possible to encode fully into a crafting pattern for autocrafting until extreme pattern encoder is available (i assume).
Consider this a early-mid game item, this does not make sense. 
Should reduce the recipe to 9 types of items so it can be encoded properly. 

Thanks!

**Comment by CloudyDash** [comment]
Carpenters are fully automatable from start to finish without the use of Packaged Auto or Refined Avaritia. You simply just need to have the AE/RS system keep the automation interface stocked with one of the items (eg: keep a servo in the input) and don't include that as part of the recipe!

**Comment by LordHellscream** [comment]
@CloudyDash  thats what I been doing, leaving 1 item out. But it's very hacky. There is no reason to have more than 9 items in the recipe it doesn't increase the difficulty.

**Comment by Freebi85** [comment]
There are no changes planned. Sorry

**Comment by LordHellscream** [comment]
ok :)
