### ISSUE TITLE
giant sequoia sapling recipe doesn't exist

### ISSUE THREAD

**Issue by Azutte** [Freebi85/Dungeons-Dragons-Space-Shuttles#722]
clicking on it reveals a gendustry recipe but unless I'm way off the mark, I'm pretty sure you need an actual source of giant sequoia genes as material for that template in the recipe

**Comment by Freebi85** [comment]
I can' change or fix breeding issues and i don't want to add a custom recipe for something in there which should work by default. Pls contact the mod author to fix the breeding chain :)
Cheers
