### ISSUE TITLE
bound pickaxe. player soul got to weak

### ISSUE THREAD

**Issue by andie0200** [Freebi85/Dungeons-Dragons-Space-Shuttles#725]
when useing the special action of the bound pickaxe from blood Magic (the excavation) I randomly die with the msg " players soul got to weak". this is normal when you don't have lp. but with even when I'm fully charged up on lp it happents (This is the first modpack I play were this happends)

**Comment by Freebi85** [comment]
HI :)
And You're the first player it's ever happened to. Are you sure about your network?
However can't help you much there. We are on latest Blodmagic Version, check their githubs and report it to the author if it happens again and no ticket has been opened there.
Cheers
