### ISSUE TITLE
Electroblob's Wizardry

### ISSUE THREAD

**Issue by CaldwellYSR** [Freebi85/Dungeons-Dragons-Space-Shuttles#726]
I want to add this mod but I don't want to break all the quests and modifications. I'm not sure if that's a valid concern but I wanted to check.

**Comment by Freebi85** [comment]
Well as always at your own risk. The chance to break things in this pack is very high due to the massive amounts of tweaks. I don't know. Do not know the mod and have never tested it.
Cheers
