### ISSUE TITLE
Uranus White Gems/Wafers - No Uses?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#727]
Hi, Freebi!

Please look into the uses you've set up with the Red/White/Blue Gems and their respective Wafers, and see why there's no uses for the white gems, other than making White Gem Wafers which have no apparent use in JEI.

It looks like it could be used for some advanced oxygen collectors or fuel loaders/etc, similar to the uses of the Red/Blue gems.  
![2020-02-27_18 50 42](https://user-images.githubusercontent.com/10191173/75497820-723ebc00-5993-11ea-9abc-ec0caf2f7ccb.png)

Thanks!

**Comment by Freebi85** [comment]
There are many more wafers from Extra planets which are not used at all by default in the mod itself. I don't have uses for this as well atm. I'll see if I can get this out of JEI.

**Comment by Danekjovax** [comment]
That's fine.

If you could incorporate the gem for some late-game recipes, that would at least help bring some utility to the material, but failing that, the 20k white gem ore I mined up can be utilized for decor blocks. ;2)

**Comment by Freebi85** [comment]
:D ok let me see

**Comment by Freebi85** [comment]
Merged to https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/733
