### ISSUE TITLE
NuclearCraft methanol does not work in a Rockhounding transposer

### ISSUE THREAD

**Issue by Landmaster** [Freebi85/Dungeons-Dragons-Space-Shuttles#728]
This prevents methanol made by the Nuclearcraft method from being inputted into the reforming reactor to make acrylic acid, even though JEI says Nuclearcraft methanol should be usable.

EDIT: Methanol is not the only missing fluid from the transposer recipes. Hydrogen gas is also missing.

EDIT 2: Even when I manually add a Methanol transposer recipe via CraftTweaker, it still cannot be put in the Reforming Reactor since it is considered a liquid, not a gas, in the Rockhounding system.

**Comment by Freebi85** [comment]
I added only the most important ones to the transposer which are important for the use of the modpack. But I will add more and more on request - no problem. So i can do this with Hydrogen.

But if Rockhound is not compatible with the fluid of another mod, then I cannot change that. You have to pass this on to the author.

**Comment by Landmaster** [comment]
`You have to pass this on to the author.`

https://github.com/GlobbyPotato/Rockhounding_Chemistry/issues/116

**Comment by Freebi85** [comment]
Gonna close this since im working on a final release of DD&SS. Maybe I will take a look at it again if it should be fixed in the future.
