### ISSUE TITLE
Artisan Worktable automation?

### ISSUE THREAD

**Issue by ThomasKidder** [Freebi85/Dungeons-Dragons-Space-Shuttles#730]
Not sure if this is intentional, but it would be really nice if there was some way to automate artisan worktables.. I see that there is a 'blank design pattern' and 'designer's workshop' but they don't have recipes so I'm guessing they are disabled.

**Comment by Freebi85** [comment]
Hello :)
Artisan Tables is not my mod, i just made the modpack. You have to ask this in the github of Artisan Tables and Workshops. Currently it's not possible to automate it.
