### ISSUE TITLE
Likely known: Graphite bug

### ISSUE THREAD

**Issue by thehackedone** [Freebi85/Dungeons-Dragons-Space-Shuttles#732]
The Smeltery from tinkers when turning coal into blocks from it, its suppose to turn to graphite not sure if thats intended but it turns to coal instead.

Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by Freebi85** [comment]
Ah yes you shouldn't be able to cast graphite blocks or ingots because graphite dust is made differently. I need to remove the graphite ingots as well. Liquifacted Cola is just coal in the future^^
