### ISSUE TITLE
Items With No Use

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#733]
Hi, Freebi!

(Edit) I'm making this a Compiled list, as I've found several things with this "problem".

These items/materials seem to have no obvious use in JEI.  It's sad to see something in the game not get given any uses (like Uranus White Gems), and it can cause some frustration with players as they realize the time/effort they've put into collecting the material not have any craftable use (other than be used for decoration).  

If there is a mod-specific use for them that JEI isn't listing for whatever reason, then let me know and I'll make note and strike it from this list.

But at least here's some other options for you to consider adding into an existing recipe or use for new ones!  Adding these items to recipes, I believe, would give players more options to explore in making and crafting, thereby making this modpack even more awesome!

Thanks! :2D

**Current List (as of Feb 29, 2020):**

- Anglesite Ore (Extreme Reactors) - (gem)
- Benitoite Ore (Extreme Reactors) - (gem)
- Yellow Garnet (Tech Reborn) - Dust/Plate
- Uranus White Gem Ore - Gem #727 
- Venus Dust #608

**Comment by Danekjovax** [comment]
#727 #

**Comment by Freebi85** [comment]
Dont think i gonna add any uses for one of this items anymore. Still gonna let issue open just in case I start working on these items again.

**Comment by Danekjovax** [comment]
Thanks, Freebs. ;2)

**Comment by Freebi85** [comment]
Gonna close this since im working on a final release of DD&SS. Some things are implemented others not. For now, I'm leaving some of this items as it is.
