### ISSUE TITLE
Grape and Agave Seeds

### ISSUE THREAD

**Issue by AJFelidae** [Freebi85/Dungeons-Dragons-Space-Shuttles#735]
Hey,
I heard grape and agave seeds are drop disabled, and I can't find a sifter recipe, but grapes are required for a quest in Kitchen Workshop - could you please change this?

Thanks!

**Comment by Freebi85** [comment]
Hi :) 
You are right it's disabled for some reason. I missed it sry. 
But Agave Seeds have a Sifter Recipe.

Cheers
