### ISSUE TITLE
Error trying to make recepys to craft according to quest book

### ISSUE THREAD

**Issue by tomtenberge** [Freebi85/Dungeons-Dragons-Space-Shuttles#739]
Please report the following issues on this Github Issue Tracker:

so far i have found the following recipes not working:
2 tiny charcoal into a charcoal
charcoal pile
wooden spike

**Comment by Freebi85** [comment]
Do you changed something in the pack? Those are all custom recipes and it looks like your pack is broken. Reinstall without altering the pack. If you still have issues you can contact us in discord. The recipes are working fine. Just tested
