### ISSUE TITLE
Congealed Blood Boots, "easy"

### ISSUE THREAD

**Issue by bludde** [Freebi85/Dungeons-Dragons-Space-Shuttles#74]
All slimeboots have a modified recipe except blood version, and blood slime can be found on slime islands i nether and made from smeltery:)

![boots](https://user-images.githubusercontent.com/1352518/52179735-2e07d900-27de-11e9-8ea2-5fd2cc6df4b5.PNG)

Version 4.3

**Comment by Freebi85** [comment]
Hello =)
Thanks, I missed that! Incoming next update.
