### ISSUE TITLE
Newest update broke crafting of coloured clear glass

### ISSUE THREAD

**Issue by semkreuze** [Freebi85/Dungeons-Dragons-Space-Shuttles#740]
Since version 7.2a (or 7.2) it is no longer possible to create Tinkers Construct coloured clear glass, as it will default to regular Minecraft coloured glass. Recipe still shows it should be possible.

Kind regards,
Sem Kreuze

**Comment by Freebi85** [comment]
oopsi, yep because i oredicted the glass.
Gonna add chisel recipe for all tinker glasses because i'm lazy :P
