### ISSUE TITLE
Stacking AA battery dupe item/rf

### ISSUE THREAD

**Issue by siber-cat1** [Freebi85/Dungeons-Dragons-Space-Shuttles#742]
As of update 7.2a, the stacking AA batteries don't behave as a stack of individual batteries.

Charging a stack of 4x Double Batteries only consumes 350 kRF, and then the individual batteries can be unstacked and discharged separately for a net gain in RF.

Additionally, when charging a stack of 4x Double batteries in AA's Energizer, it will output four batteries, and decrement the stack in the input by one. Removing the output stacks repeatedly will leave you with 10x batteries (4+3+2+1).

Not sure if AA needs to fix this bug, or the pack shouldn't enable stacking of batteries.

**Comment by Freebi85** [comment]
OOf yes can reproduce, And in certain machines they gets completely voided! Hotfix inc.
