### ISSUE TITLE
Integrated Dynamics Energy Batteries are losing their charge between saves 

### ISSUE THREAD

**Issue by md5i** [Freebi85/Dungeons-Dragons-Space-Shuttles#745]
7.2a

Integrated Dynamics Energy Batteries in one's inventory lose power between saves.  Issue is in ID mod, reported at https://github.com/CyclopsMC/IntegratedDynamics/issues/823.

**Comment by md5i** [comment]
Mod author recently fixed this.

**Comment by Freebi85** [comment]
Thank you for the heads up. Including in next update

**Comment by md5i** [comment]
I should note that, although fixed in the sources, I don’t believe a release has been made including the fix yet.
