### ISSUE TITLE
laggoggles not working correctly after 7.2a/7.2b update

### ISSUE THREAD

**Issue by druidbruce** [Freebi85/Dungeons-Dragons-Space-Shuttles#747]
![laggoggles](https://user-images.githubusercontent.com/61846869/76016590-b6c1de80-5ee2-11ea-9075-7621d5072265.png)
Usually in the single entities section, there should be a bunch of entities detected and shown, but for now it is definitely not showing all the entities.
laggoggles version: LagGoggles-FORGE-1.12.2-4.3-HOTFIX
DDSS version 7.2b

**Comment by druidbruce** [comment]
as a reference, sampler is working fine after the update.

**Comment by Freebi85** [comment]
Sry i don’t use this mod by default in my pack and never testet any version of it since there is no official server support. I can’t say which one you can use or not or what’s the issue. The community on the Discord Server would be more helpful then me there I’m sorry.
