### ISSUE TITLE
Integrated dynamics energy battery crafting recipe for Refined storage

### ISSUE THREAD

**Issue by druidbruce** [Freebi85/Dungeons-Dragons-Space-Shuttles#748]
When trying to make a processing pattern for the energy battery in refined storage, even if I manually change the resulting output to an already hand crafted energy battery (no automatic charging device on the player), the RS system still will not recognize the pattern and the actual crafted battery as the same item. 
Similarly, if the battery is used as an ingredient for some other crafting recipe, whether if I simply shift+click the recipe directly from JEI or manually click in the crafted item, the recipe cannot be completed.
Case 1:
simply shift+click recipe(that includes the energy battery) from JEI
RS will recognize that the battery needs to be crafted, and request the battery, however, when the crafting is complete for the battery, it goes back to the system as a different item, therefore RS is stuck in the stage of waiting for the battery to be completed.

Case 2:
manually click in the crafted battery
Even if RS has the crafted battery in its storage, it will not recognize it as part of the recipe, and simply say item is missing.

I am not sure whether this is an RS issue, or an ID issue or the modpack issue, so I'm reporting it here.

**Comment by druidbruce** [comment]
Interesting thing to notice:
After RS finishes crafting the energy batteries, as stated above it is considered a different item from the original recipe. Taking out those energy batteries and putting them back into RS changes nothing, RS still considers them the same.
However, if I take put those energy batteries into the Epic Backpack from Simply Backpacks, and then put them back into RS, then they are now considered the same thing as the encoded pattern result.

**Comment by Freebi85** [comment]
Well autocrafting with some batteries van always make problems due to nbt data of the batteries. Some mods works better other don’t completely.

However i can’t fix processing crafts myself. 
Which recipe exactly are you trying to autocraft?

**Comment by druidbruce** [comment]
energy interface from integrated tunnels, which requires energy battery from integrated dynamics.

**Comment by Freebi85** [comment]
Ah i see. Well that's a default recipe from Integrated Dynamics. Looks like the mods don't work well together. Can't help you there.

Pls Report to the mod Authors.

**Comment by Freebi85** [comment]
Let me try something, maybe i found a workaround without the devs having to change anything.
