### ISSUE TITLE
Pink Slime Liquid, No recipe Available

### ISSUE THREAD

**Issue by thehackedone** [Freebi85/Dungeons-Dragons-Space-Shuttles#749]
The liquid and tools are in but there isn't a way to "melt it down" in order to apply it to better tools.

Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by Freebi85** [comment]
Pink Slime is not meant to be melted in the smeltery. You need the Part Builder and the patterns :)
