### ISSUE TITLE
Replace Chestnut w/ Almond in MQ1?

### ISSUE THREAD

**Issue by Landmaster** [Freebi85/Dungeons-Dragons-Space-Shuttles#750]
Almond makes the same amount of Seed Oil and also has the benefit of being usable for making milk, unlike Chestnut IIRC.

**Comment by Freebi85** [comment]
? Squeezing Chestnuts (or any kind of "nuts") is efficient yes. It's just an example in the quest which tells you mainly to use or interact with the questbook shop. Dont't gonna change something there.

**Comment by Landmaster** [comment]
It's still worth mentioning Almonds though IMO, even if in a minor sidequest, since it is an alternative way to make milk if the player does not want to go through the hassle of transporting and breeding animals.
