### ISSUE TITLE
[Recipe brocken] Dragon Egg Energy Siphon & Storage Tablet

### ISSUE THREAD

**Issue by pfeiferocks** [Freebi85/Dungeons-Dragons-Space-Shuttles#751]
The recipes checks for nbt data on the battery's
If the battery has been crafted without charging and discharging it or when it has been toggled 
you can't craft them.

Fix: 
Remove .withTag({Energy: 0}) at line 389 on TechReborn.zs
Remove .withTag({Energy: 0}) at line 517 on RFTools.zs

**Comment by Freebi85** [comment]
Pls update to latest Version. Both are fixed and reworked already.
And always write your Pack Version when opening tickets. (or update before :) Thanks.
