### ISSUE TITLE
Unify arsenic dust to fluid values

### ISSUE THREAD

**Issue by siber-cat1** [Freebi85/Dungeons-Dragons-Space-Shuttles#753]
Just noticed that Rockhounding chemistry treats 144 mb of arsenic as one ingot/dust worth, while NuclearCraft treats it as 666 mb. This causes a potential loop for duplicating the resource instead of producing it.

I'm unsure which value would be easier to settle on, as every recipe it's used in would need to agree on a value, otherwise players would be left with a few mb left, and ratios would be very large.

**Comment by Freebi85** [comment]
Thank you,. It should be 666mb.
