### ISSUE TITLE
Chiselable Charcoal Block not craftable?

### ISSUE THREAD

**Issue by FalloutBe** [Freebi85/Dungeons-Dragons-Space-Shuttles#754]
Hello,

There are charcoal blocks from different mods. These are chiselable:
- Thermal foundation
- Forestry

These are not:
- Mekanism
- Actually additions
- Rockhounding mod - Chemistry

Now, it seems like crafting the block from charcoal pieces, always gives you the Mekanism charcoal block, which cannot be chiseled.
So is there a way to obtain the charcoal block from either Thermal Foundation or Forestry?

**Comment by Freebi85** [comment]
Probably not atm but you can try with the Oredictionary Converter (machine)
I cann add the mekaism block to the charcoal chisel package in next update.

**Comment by Freebi85** [comment]
Are you on latest pack version?

All Charcoal blocks including Mekanism, Acutally Additions, Thermal Foundation and Forestry are in the chisel package on latest version.

**Comment by FalloutBe** [comment]
I supposed we were on the latest version because we started really recently, but we are on version 7.1a and you already made 7.32b

I'm so sorry to waste your time :/
Thanks for your reply anyways!
