### ISSUE TITLE
oredict request: pam's honey -> sugar in vanilla, rustic, and botania potions

### ISSUE THREAD

**Issue by Azutte** [Freebi85/Dungeons-Dragons-Space-Shuttles#755]
(it's already in $listAllSugar for foods that'll take that)

- potion of swiftness
- fermented spider eyes
- brew of fleetfeet
- brew of adrenaline
- brew of overload
- elixir of speed

**Comment by Freebi85** [comment]
Hi :) Yes honey and sugar Should be already oredicted :)

But i'm sorry; i don't gonna oredict potions. Something always goes wrong or behaves strangely for certain recipes.
