### ISSUE TITLE
[JEI] Recipe broken: Sticks

### ISSUE THREAD

**Issue by blizzard4591** [Freebi85/Dungeons-Dragons-Space-Shuttles#756]
Dear all,

the recipe for sticks is broken: 
<pre>
P P -
- - -
- - -
</pre>, where P is a wood plank, should yield 2 sticks (recipe is shown in JEI), but instead yields a wooden pressure plate.
The other recipe with the saw works, but for automation in AE or RefinedStorage, this recipe is much nicer.

**Comment by Freebi85** [comment]
for sticks you only have to use the planks vertically and not horizontally. (also for processing patterns) 
But I will change the pressure plate recipe so there is no mess.
