### ISSUE TITLE
Graphite Block bug for Nuclearcraft questing.

### ISSUE THREAD

**Issue by RapidfireCRH** [Freebi85/Dungeons-Dragons-Space-Shuttles#757]
Nuclearcraft has a graphite block requirement however does not have a recipe. extreme reactors has a similar block and both blocks work for nuclearcraft but the questbook only accepts the nuclearcraft graphite block option. Had to spawn it in manually for a user. This is at the bottom of the tier 4 recipe chain.

**Comment by Freebi85** [comment]
In latest Version the book accepts all kinds of graphite blocks. Version 7.2b
If you're already on that version update the questbook with /bq_admin default load
You should be able to make the Estreme Reactors Graphite block with graphite ingots.
