### ISSUE TITLE
ddss 7.2 industrial blast furnace wont register 2 lava blocks

### ISSUE THREAD

**Issue by DoozerSg1** [Freebi85/Dungeons-Dragons-Space-Shuttles#758]
hi this issue seems to have popped up again, after building the tech reborn industrial blast furnace we have been trying to get it to heat for chrome smelting, however, it only registers the top lava block in the furnance, i have tried as many different ways, moving structure, trying other hot items. moveing the lava.

Feedback on this issue would be great and i have been on your wiki. and i searched this section first.
![image](https://user-images.githubusercontent.com/62196829/76695853-18daca80-66bf-11ea-8c56-6132b430db70.png)
![image](https://user-images.githubusercontent.com/62196829/76695865-3871f300-66bf-11ea-8d1a-73282f76225b.png)

**Comment by Freebi85** [comment]
Tech Reborn changed the heat mechanic for the Industrial Blast Furnace without proper documentation. You will find Quests abount it in Tier 3 amnd 4 Main questline.
To reach more then 1700 Heat with medium casings you have to right click with 4 Kanthal Heating Coils on the Industrial Blast Furnace Core Block.
To reach the maximum amount of heat with advanced casings you have to right click with 4 Nichrome Heating Coils on the Industrial Blast Furnace Core Block.

The Lava inside isn't requred at all but should work when putting 2 buckets inside.

Cheers

**Comment by DoozerSg1** [comment]
it doesnt work when putting 2 buckets in it only registers one and its the top bucket that only registers. sorry i didnt clarify that, but thank you for your help good sir
