### ISSUE TITLE
I'm getting this error and I don't know how to fix it.

### ISSUE THREAD

**Issue by JokerVagus** [Freebi85/Dungeons-Dragons-Space-Shuttles#760]
![Capture](https://user-images.githubusercontent.com/62265899/76802152-1652a080-67a5-11ea-934d-9c9bebade62f.PNG)

**Comment by Yiluxius** [comment]
@JokerVagus This is not the right place for this. Head over to the discord into the #single-player-support channel and provide your crashlog there.
