### ISSUE TITLE
Flügel Tiara got too hard of a nerf.

### ISSUE THREAD

**Issue by Yiluxius** [Freebi85/Dungeons-Dragons-Space-Shuttles#761]
Noticed that the flügel tiara now needs a redstone singularity, which I find a bit unfair when compared to other sorts of flight in terms of progression. Without the eye of the flügel it isn't even permanent flight, as it needs to recharge, which requires gaia 2 progression already. 
Most people usually wouldn't have an incentive of setting up a proper mana generation and delivery (via mana mirror or something else) which some of the botania gear would change.
Now with one of the alternatives being pushed into the same oblivion as the angel ring, the only real option would be supremium armor or maybe the astral mantle with the perk, which are both considerably cheaper than the progression required for the quantum compressor... (also brooms still exist, which basically cost nothing when compared to these)
And I wouldn't think that remotely comfortable flight should be gated as far back as the IBF, with the nano beacon flight modifier now being gated even further back, behind a VOM tier 4.

**Comment by Freebi85** [comment]
I'll have a look at it but even if the singularity goes away it won't be much cheaper. After all it is creative flight for low mana cost. Angel ring needs for example GP. Supremium a long chain of crafting and stuff.

Basically there are much cheaper and earlier ways to fly like ice&fire mounts, Brooms, Hang glider + jump boost, just not very comfortable solutions.

**Comment by Danekjovax** [comment]
I just wish the Tiara had more "Fly Time".  Is that configurable?
