### ISSUE TITLE
Melon to slice conflicting recipe

### ISSUE THREAD

**Issue by Yiluxius** [Freebi85/Dungeons-Dragons-Space-Shuttles#763]
Crafting a melon into slices has two different recipes. One is added by dungeontactics only yielding 5 and one by cyclic yielding 9. 
![javaw_ypDD45IOE8](https://user-images.githubusercontent.com/12602100/76888561-694f5500-6884-11ea-9cd7-f6ae66878553.png)

**Comment by Freebi85** [comment]
Oh lol ey o_O
