### ISSUE TITLE
Molten Lumium missing texture

### ISSUE THREAD

**Issue by Mist3rEvil** [Freebi85/Dungeons-Dragons-Space-Shuttles#764]
Molten Lumium placed in world has no texture

**Comment by Freebi85** [comment]
? With a specific resourcepack or by default? However, i can’t fix broken textures except from my own custom items.

**Comment by Mist3rEvil** [comment]
default textures

ok sad one

**Comment by Freebi85** [comment]
Well, i would say report it to thermal expansion but they closed their github for 1.12. I’m sorry 😐
