### ISSUE TITLE
[Suggestion] Use Crafting Core and Pedestals from Extended Crafting as an Upgrade to Empowerer

### ISSUE THREAD

**Issue by hyracinth** [Freebi85/Dungeons-Dragons-Space-Shuttles#767]
Currently, I do not believe that the Crafting Core / Pedestals from Extended Crafting is being utilized.
Perhaps they can be put in as an upgrade for the Empowerer setup?
I'm finding the Empowerer to be quite slow, especially when you kick off a job that requires hundreds of empowered diamatines. 
Thanks for reading!

**Comment by Danekjovax** [comment]
If the mod has code (preferably already in a .cfg) to support that feature, then this would be possible.

**Comment by Freebi85** [comment]
Hey :)
Gonna close this since im working on a final release of DD&SS. Maybe I will take a look at it again if i should come back to this in the future.
