### ISSUE TITLE
MIssing crafting recipe

### ISSUE THREAD

**Issue by Mist3rEvil** [Freebi85/Dungeons-Dragons-Space-Shuttles#768]
The Solar Panel of Infinity requires a Acces Card tier 5, which is get by compacting NASA workbench schematic - Tier 5 rocket. This Item has no crafting recipe ( ID #10893/0)

**Comment by Freebi85** [comment]
Rocket Schematics need to be found in dungeons on the respective planet. (planet progression)
Then you have to process it in a compactor or pressurizer.
![2020-03-20_18 42 57](https://user-images.githubusercontent.com/42634622/77191251-f25fc980-6ada-11ea-9ab0-ab8c6941ed11.png)
