### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by Howaitooni** [Freebi85/Dungeons-Dragons-Space-Shuttles#769]
![Annotation 2020-03-21 214121](https://user-images.githubusercontent.com/62466738/77225566-23fe9080-6bc0-11ea-9a98-9398ee53e5ca.png)

I copied the mod folder straight from the mod folder in the server. My friend however is able to connect to the server

**Comment by Freebi85** [comment]
Sorry no server support here like the template says. Pls move over to tech support channel in our discord server.
However if other people can connect you probably should reinstall your client.
Cheers
