### ISSUE TITLE
Ammo for open turrets

### ISSUE THREAD

**Issue by bludde** [Freebi85/Dungeons-Dragons-Space-Shuttles#77]
The quest for the Disposable item turret have the wrong ammo in the quest text.
![bild](https://user-images.githubusercontent.com/1352518/52223542-23b11200-28a6-11e9-971a-7044c721ad84.png)
![bild](https://user-images.githubusercontent.com/1352518/52223563-2dd31080-28a6-11e9-90a2-96aea553b51d.png)

V4.3

**Comment by bludde** [comment]
Quest #979

**Comment by Freebi85** [comment]
Thank you for reporting this =) Fixed in next update.
