### ISSUE TITLE
Dilithium Ore doesn't drop items if it's a Underground Biomes variant

### ISSUE THREAD

**Issue by duck-mon** [Freebi85/Dungeons-Dragons-Space-Shuttles#772]
Regular Tinkers Alloying Addon version is mine-able while other variants is not. Tested multiple times with a Supremium Pickaxe. Regular Ore drops the crystals while the variant does not.
![image](https://user-images.githubusercontent.com/46102557/77269982-ca51a100-6c67-11ea-9097-65c91330d093.png)
![image](https://user-images.githubusercontent.com/46102557/77270004-d89fbd00-6c67-11ea-9c8e-e963badd40e9.png)

**Comment by Freebi85** [comment]
Underground Biomes change block hardness and sometimes also the mining level. It's how the mod works afaik :/
You need sometimes mining level cobalt for some of the changed ores. The normal ones are still lvl  iron. That's why it dropps nothing.

**Comment by duck-mon** [comment]
The pick in hand is higher than cobalt. The cobalt pick itself doesn't work.

**Comment by Freebi85** [comment]
Ok i would also try with another pick with lvl cobalt or higher. never tired with a supremium pick.

However, if so then it's a mod issue and should be reportet to the author. But i'm not sure if underground biomes or mystical agriculture 1.12 are still maintained at all.
