### ISSUE TITLE
Joining error

### ISSUE THREAD

**Issue by gery29** [Freebi85/Dungeons-Dragons-Space-Shuttles#773]
When i start my world and after its loaded it crashing.
https://paste.dimdev.org/ohikotoheh.mccrash

**Comment by Freebi85** [comment]
looks like a corrupted chunk for some reason (Oil Generator Block from Actually additions)
Try to load a backup from the backup folder. 
If you need some more help join the thech support channel in our Discord Server.

Cheers 😃
