### ISSUE TITLE
Access Cards on Tech Reborn Compressor

### ISSUE THREAD

**Issue by siber-cat1** [Freebi85/Dungeons-Dragons-Space-Shuttles#775]
Access cards can be made in the Thermal and NuclearCraft plate-makers, but not in Tech Reborn's. I had to dig out my old Compactor to keep progressing. Please add recipes for all access cards for the Compressor.

**Comment by Freebi85** [comment]
Well i did already but for some reason the cards recipe won't work with tech reborn compressor  😭 
apparently  i doesen't recognize custom materials so I had to remove it again.

:(
