### ISSUE TITLE
Tier 4 Questline: Path to Yrdeen is weird

### ISSUE THREAD

**Issue by Mist3rEvil** [Freebi85/Dungeons-Dragons-Space-Shuttles#776]
Since it is needed to build the advanced smelting Factory in Main Questline Tier 3 is makes no sense that the quests in main questline tier 4 wants you to use the fluids in a Tinkers smelery to get Yrdeen ingots

**Comment by Freebi85** [comment]
This is correct but the quest only shows the basic steps with a very small amount of required material. It is not wrong to know this. Also in the Yrdeen quest there is a hint that you can make this alloy with solid materials. Not an issue at all for now.

Thanks for the tip anyway. When I have more time I will see what kind of rework I can do.
