### ISSUE TITLE
AIOTs not respecting harvest levels

### ISSUE THREAD

**Issue by JonathanCSmith** [Freebi85/Dungeons-Dragons-Space-Shuttles#777]
Stone AIOT can harvest diamond tier materials (rubies etc). I haven't tested the extent of this issue but noticed that my copper pick cannot but my AIOT can. I am unsure if this is the same issue as #268?

**Comment by Freebi85** [comment]
Yes this has to fo with Underground Biomes and their stone hardness/mining lvl system.
But thanks for the heads up :)
https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/268

**Comment by JonathanCSmith** [comment]
Just to comment - I really don't think this is the same bug. If I attempt to mine a level 4 hardness underground biomes ore with a copper pick axe it will not mine (which would mean that the previous bug is fixed). The issue I am having is with AIOT tools specifically. To me, this seems to be an issue with Actually Additions which is hardcoding its 'canHarvest' check and not using 'getHarvestLevel' from blocks.

**Comment by Freebi85** [comment]
I see. If so then the ticket is now in the right place (AA github) 
Thanks for your cooperation. 
👌

**Comment by JonathanCSmith** [comment]
Whew - Okay this bug is extremely sporadic. Certain tools can and cannot mine their appropriate materials. It doesn't seem to be consistent in anyway. I will try and dig into the issue a bit more, but just so  I have a complete understanding - do any of the other mods in the pack edit tool levels at all?
