### ISSUE TITLE
[Suggestion] Allow Different Colored Oxygen Tanks for Crafting

### ISSUE THREAD

**Issue by hyracinth** [Freebi85/Dungeons-Dragons-Space-Shuttles#778]
The recipe for the "Very Heavy Oxygen Tanks" from Extra Planets only accepts the red "Heavy Oxygen Tanks" from Galacticraft. 
Would it be possible to allow the various colored tanks (from Extra Planets) to be used in crafting? 
The recipes for the "Heavy Oxygen Tanks" only differ in the colored wools.

**Comment by Danekjovax** [comment]
I agree that some crafting recipe could be made to cycle or re-dye the tanks to different colors.  Make it so! ;2)
