### ISSUE TITLE
Revisiting Chrome/Chromium (necro #543)

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#779]
I''m asking you to revisit #543 as there's too many processes and other ways to convert out of Tech Reborn chrome and make Rockhounding Chromium, but not the other way around, wasting a lot of useful material in the process.

Make Chromium and Chrome equivalent in that they can interchange between one another in a crafting table (dust/ingot), or oredict them into one item.

They're the same material, and there's no real reason to handle them differently.

If you do insist on keeping them as separate materials, then please remove the conversion recipes that convert out of Tech Reborn chrome and properly segregate the materials completely (albeit a counter-intuitive thing).

Thanks for your time, Freebi!

![2020-03-26_20 07 42](https://user-images.githubusercontent.com/10191173/77708590-dbb7e780-6f9e-11ea-9d76-a800cc722ae2.png)
![2020-03-26_20 07 57](https://user-images.githubusercontent.com/10191173/77708594-dce91480-6f9e-11ea-87e9-45f4cd01f6f3.png)
![2020-03-26_20 08 07](https://user-images.githubusercontent.com/10191173/77708604-e2def580-6f9e-11ea-8e87-368b164d20a8.png)
![2020-03-26_20 09 36](https://user-images.githubusercontent.com/10191173/77708611-e83c4000-6f9e-11ea-807f-937438d5798e.png)

**Comment by Freebi85** [comment]
Sorry no this is a balance breaker, Chromium is used mainly for rockhound alloys or for some decorative blocks and pretty easy obtaniable. At least in the DD&SS Universum.

A complete rework and merge of the two would cost far too much effort. I can't spend that much time on ddss anymore.

But you're right, it shouldn't come from the techreborn machines. I will remove it.

**Comment by Danekjovax** [comment]
At least change the chrome in the electrolyzer be TE and not Rockhounding.  I wasted thousands of sapphire to realize this.  Thanks.
