### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bg2304** [Freebi85/Dungeons-Dragons-Space-Shuttles#780]
![Screenshot (1)](https://user-images.githubusercontent.com/62762902/77780060-b507b880-7053-11ea-92a1-b34cb71d6a86.png)
I tried replacing more version of this mod but it does'nt work at all, how i can fix that

**Comment by Freebi85** [comment]
you probably didn't allocated enough ram into your launcher. Raise your ram up to 8GB and don't remove mods. This just breaks the pack.

Join our discord server for more help and provide the crashlog from "get link"

cheers
