### ISSUE TITLE
Advanced Alloy Smelting Factory being Stupid

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#781]
I look up how to make Lumium using the Advanced Alloy Smelting Factory (AASF)...
![2020-03-27_13 52 01](https://user-images.githubusercontent.com/10191173/77785545-bb396d00-7032-11ea-9ac1-d9ba5be9db87.png)

I gather a stack of each ingredient and place them in the input. and turn the device on.

I get this instead...
![2020-03-27_13 52 47](https://user-images.githubusercontent.com/10191173/77785623-d73d0e80-7032-11ea-8a48-a589a5d88578.png)

I've removed the ingredients and turned off/on the machine to "reset" it several times and placed all ingredients even in different slots/order, and still getting this Tin Silver Alloy.

Why's the AASF being stupid?  I should always look up more complex recipes first then go down to the simpler ones to find a recipe match. 

Please advise. ;2)

**Comment by Freebi85** [comment]
Yes there was a conflict in 7.1 about lumium and Tin Silver Alloy since the machine isn't smart enough sadly. But i fixed it in 7.2x 💪 

Cheers

**Comment by Danekjovax** [comment]
Doh!  I'm still stuck in 7.1 land.  My bad. ;2)
