### ISSUE TITLE
Recipe for Dislocator Pedestal seems a tad "Vanilla"

### ISSUE THREAD

**Issue by hyracinth** [Freebi85/Dungeons-Dragons-Space-Shuttles#784]
This recipe seems a tad un-Freebi'd. xD

![image](https://user-images.githubusercontent.com/4340055/77838119-bf52b100-713e-11ea-80bb-52d689f858cd.png)

**Comment by Freebi85** [comment]
:D

**Comment by Danekjovax** [comment]
I'd say the same about the Auto-Chisel, but then again, I'd like to afford a few things now and then. >;2)
