### ISSUE TITLE
(Question) Which pipe

### ISSUE THREAD

**Issue by gery29** [Freebi85/Dungeons-Dragons-Space-Shuttles#785]
Hello!
I have a question. I cant pull out the items from Plant gatherer (industrial forgoing). I tried everything, but i cant. 

Can someone help me?
Thank you in advance.

**Comment by md5i** [comment]
I do not know if this is your problem, but I have found that pipes will not connect to Industrial Foregoing machines when they are paused.  When unpaused, itemducts with servos seem to work just fine.
