### ISSUE TITLE
Unification/differentiation of Avaritia/Extended crafting singularities

### ISSUE THREAD

**Issue by siber-cat1** [Freebi85/Dungeons-Dragons-Space-Shuttles#786]
Starting to look at some early singularity uses, and noticed that, among others, diamonds make two different "diamond singularity" items that are used for separate things.

I know that simply using all Extended Crafting singularities would dramatically lower the cost of creative items, but I'd appreciate them either having different names (though I don't have a suggestion here) or making only one of each type of singularity in the pack. Took me a while to realize that's why my crafting wasn't working right.

**Comment by Freebi85** [comment]
It's intended to have two different "tiers" of singularitys. 
A unification would be a balance breaker and is therefore not implemented as such.
If I manage to name them differently (if it's possible with singularytis because you never know in minecraft) I will only change the names.

**Comment by siber-cat1** [comment]
Thought of a name for Avaritia's singularities if you need one. "Neutronic ____", since they're made in a Neutronium compressor. Thanks for looking into it

**Comment by Danekjovax** [comment]
I personally didn't have much problem differentiating these... they have slightly different images (at least in default textures), and if you see Avaritia in tooltips, I know I'm looking at the more expensive one.  Just my opinion. ;2)
