### ISSUE TITLE
Cake Duplication w/ Plant Interactor

### ISSUE THREAD

**Issue by doomfur** [Freebi85/Dungeons-Dragons-Space-Shuttles#789]
When a vanilla cake is placed in the world and is within the working range of an Industrial Foregoing Plant Interactor, it will drop a cake item into the world without destroying the cake.  Cakes can be generated quickly and indefinitely as long as the plant interactor has power.

To recreate:
Place plant interactor and connect to power source.
Place cake in working area of plant interactor.

**Comment by Freebi85** [comment]
@doomfur Thank you for reporting but that's a mod issue. I can't fix this myself.
Please report urgently to Induastial foregoing.
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues
Thank you for your help.
In the meantime, I'll see if I can find a workaround. But it will be rather difficult.

**Comment by doomfur** [comment]
It's possible that it's a conflict with whatever mod allows cakes to be picked up if they haven't been eaten on.
