### ISSUE TITLE
insane lag block breaking issue 

### ISSUE THREAD

**Issue by ferrium42** [Freebi85/Dungeons-Dragons-Space-Shuttles#79]
after the last update i get lag the whole time , i installed laggoggles and have made a screenshot and it shows mainly monster and nuklearcraft as the problem
![2019-02-06](https://user-images.githubusercontent.com/38369297/52342314-5fb6b500-2a15-11e9-90d7-e2df1a49a295.png)
i downgraded multimob but it doesn´t fix it someone a idea which mod it causes 
then at the moment it isn´t fun to play break a block 2 or more times to get it dropped combat is horrible to

**Comment by cyber01** [comment]
If you on server - check server tps

**Comment by ferrium42** [comment]
i´m not on a server i just opend  a lan party to get laggoggles to work

**Comment by cyber01** [comment]
i tried /kill @e (kill my self too :( ), and tps - stable 20, but monster spawns again(

**Comment by Freebi85** [comment]
I can't recreate the problem, and I don't know how to fix it. Well possible that too many entitiy on the map are causing the problem.

**Comment by Tsunayoshi** [comment]
I got the exact same problem on a complete new server
