### ISSUE TITLE
Missing fluid textures crashes RFTools Dimension

### ISSUE THREAD

**Issue by doomfur** [Freebi85/Dungeons-Dragons-Space-Shuttles#790]
Certain liquids have missing textures and cause client-side crash when loading an RFTools dimension that uses the corresponding fluid dimlet for fluid terrain.  Tested using molten iridium and blood infused iron.

**Comment by Freebi85** [comment]
https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/764

Can't interact with missing textures. Report to the mod author. Not sure if RF Tools or Thermal expansion.
pls follow the template when reporting stuff in this github

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!
