### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by josh123710** [Freebi85/Dungeons-Dragons-Space-Shuttles#793]
Hi, I have been playing this modpack for about a week, and throughout playing it has crashed on startup and while playing a couple of times. The last two days, I've tried to play but could not get on at all as it crashed over and over to where I gave up. I have been using 8 GB of ram in the Java settings on Twitch and now raised it to 12 GB but it still crashes. Any way to fix this?
[crash-2020-04-02_17.50.02-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/4432539/crash-2020-04-02_17.50.02-server.txt)

**Comment by Freebi85** [comment]
Pls move to our tech support channel in my Discord Server for Crashes and support.
Discord Server Link: https://discord.gg/eUajYmK
However, you can first try to recover from a backup.

**Comment by josh123710** [comment]
Okay thank you. I joined the Discord, I have the same username.
