### ISSUE TITLE
[Mod Suggestion] Name Pain

### ISSUE THREAD

**Issue by naqaden** [Freebi85/Dungeons-Dragons-Space-Shuttles#794]
[Name Pain](https://www.curseforge.com/minecraft/mc-mods/name-pain) is a fairly new and light client-side tweak mod. It configurably recolors nameplates based on health, visualizing overall damage without cluttering your screen. Min/Max health configs can tweak nameplate colors statically (not health-based) for cosmetic purposes, or alpha configs can hide names from your screen to increase difficulty.

**Comment by Freebi85** [comment]
Hello :)
Thank you for your suggestion!
Gonna close this because working on a pre final/ final update for DD&SS.
I will only add very specific mods for the last updates. I'm sorry.
