### ISSUE TITLE
[Suggestion] Stargate Network/SGCraft Config Change

### ISSUE THREAD

**Issue by everseeking** [Freebi85/Dungeons-Dragons-Space-Shuttles#795]
Stargate Network currently has the "preserve inventory on death by iris" config set to false.

I'd suggest changing it to true as such:
> iris {
>     B:allowRedstoneInput=true
>     B:preserveInventory=**_true_**
> }

With Corail Tombstone saving inventories on death, and whatever mod is taking a backup of each inventory on death in `/world/data/`, I figured dying by an Iris would be just like dying any other time.

There is no way to see/restore a player's inventory after death by iris because it appears the mod is clearing players' inventories *first*, before triggering their actual death.

Edit: I have already manually changed this for my server, this is more of an FYI that may have been overlooked.

**Comment by Freebi85** [comment]
thank you for the heads up. I'll take a look.
