### ISSUE TITLE
Melt Inferium Ingots (and higher tiers)

### ISSUE THREAD

**Issue by Reygok** [Freebi85/Dungeons-Dragons-Space-Shuttles#796]
At the moment, the Magma Crucible cannot melt Inferium (and higher) ingots, you need to use the Melter or the Tinkers smeltery. Is this intentional?

**Comment by Danekjovax** [comment]
Yay for Freebi!

**Comment by Reygok** [comment]
Should I make a new ticket for the same problem with Silicone Blocks :P? it would be nice to speed up the production of silicone

**Comment by Freebi85** [comment]
It's fine here^^
