### ISSUE TITLE
Concentrated Compound Recipe for Advanced Smeltery

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#799]
Is it possible to allow the Advanced Smeltery to process the ingredients to make Concentrated Compound, please?  It's so cumbersome to make large amounts of this later in the game, and with the advent of the Advanced Smeltery, all the more reason to use it for making larger quantities of component materials like Concentrated Compound.

Using this machine should allow enhanced yield on processing (2x), but taking advantage of boosting mixture should also allow a better yield than normal (5x), as with many other existing recipes.

Thanks in advance! :2)

**Comment by Freebi85** [comment]
THIS! Sound fair to me :)
