### ISSUE TITLE
Dark Ore & Pickaxe - wrong requirements

### ISSUE THREAD

**Issue by arturgaweski** [Freebi85/Dungeons-Dragons-Space-Shuttles#8]
Hey, zakraj818023 from Curseforge here :) Found issue with Dark Ore detecting Flint Pickaxe (that should be strong as iron one) as something weaker. While i have Flint Pickaxe equipped Dark Ore cannot be mined with information it requires Diamond or better pickaxe. While i eqiup normal Iron Pickaxe it allows to be mined easily.

Either Iron Pickaxe is detected as Diamond or better one or Flint is detected as weaker one.

**Comment by Freebi85** [comment]
Huhu Zekraj =)
Thanks for Reporting.
Seems to be correctly. Dark Ore have mining Level Diamond.
A Vanilla Iron Pickaxe have also Mining Level Diamond.
A Tinkers Flint Pickaxe (whitout upgrade) have only mining Level Iron.
The tooltip is a bit confusing^^ I hope I have been helpful.
Sincerely, Freebi
