### ISSUE TITLE
Cycle Saturation potion doesn't work

### ISSUE THREAD

**Issue by SummitSummit** [Freebi85/Dungeons-Dragons-Space-Shuttles#80]
Cyclic adds many potions.  I've tried a couple and they seem to work fine, but the potion of saturation (in all 3 forms) does NOT work.  The potions do not provide any potion effect.  Seems likely to be some weird mod interaction.  If it not working is actually intended, Cyclic's config seems to have a way of removing the potion entirely.

**Comment by Freebi85** [comment]
I have checked it but it seems to be a mod specific error. Unfortunately I can't fix that. You can only report it to Cofh but it is difficult because the cause is unknown.
