### ISSUE TITLE
Nuclearcraft Carbon Dioxide does not work in Rockhounding Transposer

### ISSUE THREAD

**Issue by dash16** [Freebi85/Dungeons-Dragons-Space-Shuttles#800]
Might be intentional to nerf/restrict Syngas creation, but it'd be nice if the Carbon Dioxide from Molten Sugar + Water Chemical Reaction could be imported into Rockhounding to be used in the Reforming Reactor Tower.

**Comment by dash16** [comment]
Same goes for Ammonia it looks like.  Wasn't able to import Nuclearcraft ammonia into a Rockhounding machine via Transposer either.

**Comment by Freebi85** [comment]
Alrightyy^^
