### ISSUE TITLE
Wyvern helm recipe error

### ISSUE THREAD

**Issue by siber-cat1** [Freebi85/Dungeons-Dragons-Space-Shuttles#804]
Wyvern helm requires two blocks of solarium when using Argon or Syngas, but needs one solarium, one dyonite when using Methane Gas in the Blacksmith's workshop. I imagine this isn't intended, as other wyvern armor pieces require two solarium blocks with all welding gas options.

**Comment by Freebi85** [comment]
Thank you :)
