### ISSUE TITLE
actually additions support for plusTIC not working

### ISSUE THREAD

**Issue by XxN4BxX** [Freebi85/Dungeons-Dragons-Space-Shuttles#805]
- Not working:

 # Integrate with Actually Additions [default: true]
    B:"Enable Actually Additions support"=true

this is the config on plusTIC but the materials are not supported on this pack, i cannot track the origin of this issue

**Comment by Freebi85** [comment]
This is not an issue. Those materials are supposed to not be used in ddss for balance reasons.
switching to true breaks progression.
