### ISSUE TITLE
Recipe for Storage Tablet from RFTools is requiring a battery with NBT Tag

### ISSUE THREAD

**Issue by hyracinth** [Freebi85/Dungeons-Dragons-Space-Shuttles#806]
Recipe for Storage Tablet(#12244) from RFTools is requiring a battery with NBT Tag(s)
I took a look at the other recipes using batteries and they seem to all be using the batteries with no tags.

JEI:
![image](https://user-images.githubusercontent.com/4340055/79403200-36b87b00-7f5c-11ea-808e-ba64891201e2.png)

Crafting Table (AA Battery with no NBT tags):
![image](https://user-images.githubusercontent.com/4340055/79403346-adee0f00-7f5c-11ea-8bfd-f44d2856014c.png)

Crafting Table (AA Battery with tags for changing battery mode):
![image](https://user-images.githubusercontent.com/4340055/79403388-d118be80-7f5c-11ea-8d2f-83abf38d9848.png)

**Comment by Freebi85** [comment]
oof Thank you my friend :)
