### ISSUE TITLE
[Trait change]: Big problem with terrax slautering/dupe

### ISSUE THREAD

**Issue by XxN4BxX** [Freebi85/Dungeons-Dragons-Space-Shuttles#808]
there is a big bug with terrax trait "slautering", when mobs pick up items from the ground and you kill them with a weapon with slautering, every item they pick up drops and gets duped 3 times, so you end up with 4 equal items, so far it works with every entity that is picked up by mobs, even machines

**Comment by Freebi85** [comment]
Since this trait crashes servers regularly and this mod is not maintened anymore, the trait to be replaced anyway in next update. But thank you for the heads up :)
