### ISSUE TITLE
[Mod Suggestion] small mod to complement minecarts/rails

### ISSUE THREAD

**Issue by XxN4BxX** [Freebi85/Dungeons-Dragons-Space-Shuttles#809]
Before ignoring, just want to suggest a small mod to complement a missing part on the mod, its called signals and it should complete what we are missing atm on minecarts, a huge bonus on this modpack since not even railcraft is in here

https://www.curseforge.com/minecraft/mc-mods/signals

**Comment by otakup0pe** [comment]
Oh this would be absolutely _lovely_

**Comment by Freebi85** [comment]
Hello :)
Thank you for your suggestion!
Gonna close this because working on a pre final/ final update for DD&SS.
I will only add very specific mods for the last updates. I'm sorry.
