### ISSUE TITLE
Energy Storage / Integrated Dyn Battery

### ISSUE THREAD

**Issue by scotty9090** [Freebi85/Dungeons-Dragons-Space-Shuttles#81]
From what I've been able to tell, the Integrated Dynamics Battery is fairly buggy and/or limited in its functionality.  What are the other early game power storage options available?  It looks like TE power cells aren't craftable from what I can tell in JEI - am I missing something?

I've been trying to get my ID battery to work (correctly) for a while now and, apparently depending on where I connect cables, it won't simultaneously input and output.  E.g. If I put the input cable on the bottom, the output cable on the back and apply a redstone signal it won't accept power.  Obviously if I remove the redstone signal then it will accept power but not supply it.

It behaves as expected if I have the input cable on one side, and the output cable on the opposing side but this is a bit limiting.

**Comment by cyber01** [comment]
I confirm about the batteries TE (JEI does not show the recipe of the frame of the simplest battery, shows only the reinforced and higher)

**Comment by Freebi85** [comment]
Thanks for the message but that's nothing i can fix. please always report such problems directly to the mod author. In this case I have already done that and am waiting for a solution from mod author. 

Otherwise there are Energy Cubes, Cyclic Batterys and so on.

**Comment by cyber01** [comment]
If I understand the logic of CraftTweaker correctly, then
in /scripts/Recipes/Thermal Expansion.zs you remove all frame recipes
recipes.remove(<thermalexpansion:frame:*>);
then add new recipes for:
frame:64,frame, frame:129,frame:130, 
but if you believe the dump of all items, then the whole frame names:
"<thermalexpansion:frame>"
"<thermalexpansion:frame:64>"
"<thermalexpansion:frame:128>"
"<thermalexpansion:frame:129>"
"<thermalexpansion:frame:130>"
"<thermalexpansion:frame:131>"
"<thermalexpansion:frame:132>"
"<thermalexpansion:frame:146>"
"<thermalexpansion:frame:147>"
"<thermalexpansion:frame:148>"

128,131,132,146,147,148 without recipe?

**Comment by scotty9090** [comment]
My intent was more to enquire re: other power options than report an ID bug (I saw that it was already reported).  The battery is the only option the quest book has presented me with at this point ... which isn't great considering that this battery doesn't work well at all.  

I checked the Mekanism energy cube recipe and quickly decided against it since they can't be upgraded - if I make a basic cube, and want to tier it up to an advanced cube later, then I essentially need to start from scratch.  Being able to incrementally scale power storage is a core concept in every single energy storage solution I can think of and, personally speaking, I'm not a fan of changes that break that.

**Comment by Freebi85** [comment]
The problem with the mekanism cubes has already been taken care of. They are upgradeable in the next update. Thanks for your feedback. First of all I will implement a quest for the Thermal Expansion batteries because it will be available again. Quests about further possibilities will follow later as the book is still heavy WIP. =)

**Comment by Freebi85** [comment]
But for your information: The mods are updated weekly. this battery was not always a buggy solution. But that's minecraft. One month works, another month doesn't.

**Comment by scotty9090** [comment]
Thank you - that's good to hear and I appreciate the reply.
