### ISSUE TITLE
[Suggestion] Remove recipes for Extra Cells 1024k/4096k Fluid Drives

### ISSUE THREAD

**Issue by everseeking** [Freebi85/Dungeons-Dragons-Space-Shuttles#810]
Relating to this issue: https://github.com/ExtraCells/ExtraCells2/issues/684

256k Fluid Drives work fine, 1024k & 4096k Fluid drives do not work at all - no matter which way I have tried they do not store anything.

Recommend you remove them from the modpack so people don't waste materials to find this out.

**Comment by Freebi85** [comment]
I see, well it's clearly a mod issue, i hope for a fix there. 

I can't update at the moment anyway because of the plustic shitstorm. So I still have some time. But if nothing happens I will remove it.

**Comment by Freebi85** [comment]
Gonna close this since im working on a final release of DD&SS. Maybe I will take a look at it again if it should be fixed in the future.
