### ISSUE TITLE
[Mod Suggestion] Immersion, energy, weapons and upgrades ..

### ISSUE THREAD

**Issue by VzeusV** [Freebi85/Dungeons-Dragons-Space-Shuttles#812]
First of all I wanted to say that I use the mod in the modpack without problems with lag or crash, I just wanted to know if I could incorporate it, improve the crafts and everything ... pls

The Matter Overdrive: Legacy Edition mod is a space mod but with no new dimensions, just mobs and two ores.
There you can make a fusion reactor (it interacts with other thermal expansion mods). Allows the character to become an android that has a skill tree which in part can be op but he will not be able to feed himself, he will live only on energy.
The mod also features two new hostile mobs (androids melee and range) that make a beautiful party during the blood moon

The two new ores are the dilithium (already present in the modpack) and the tritanium, the rest in the mod in general are simple things like chests and tools.
It also has a somewhat interesting quest line.

Well, I already said too much, if you read all of this I’m already very happy and I just thought I could give Galacticraft an extra life in the overworld.
(sorry about my English)  :)

**Comment by Freebi85** [comment]
Hello :)
Thank you for your suggestion!
Gonna close this because working on a pre final/ final update for DD&SS.
I will only add very specific mods for the last updates. I'm sorry.
