### ISSUE TITLE
Tier 10 Rocket is using Tier 9 Rocket Engines

### ISSUE THREAD

**Issue by hyracinth** [Freebi85/Dungeons-Dragons-Space-Shuttles#814]
Just in case the Tier 10 Heavy Duty Plates were not expensive enough...

I noticed that the Tier 10 Rocket is using Tier 9 Rocket Engines, not sure if it's intended. 
![image](https://user-images.githubusercontent.com/4340055/80239533-69cece80-862e-11ea-8115-081e3e068d0f.png)

![image](https://user-images.githubusercontent.com/4340055/80239594-81a65280-862e-11ea-8fc4-52511c8bb6a1.png)

**Comment by Freebi85** [comment]
Thank you for the heads up :)

**Comment by Danekjovax** [comment]
Time to save up a few more Ti singularities. ;2)
