### ISSUE TITLE
[Mod Suggestion] Keyboard Wizard

### ISSUE THREAD

**Issue by P3t3rU5** [Freebi85/Dungeons-Dragons-Space-Shuttles#816]
Would like to suggest [Keyboard Wizard](https://www.curseforge.com/minecraft/mc-mods/keyboard-wizard).

It allows to have visual representation when setting controls.

**Comment by Danekjovax** [comment]
A GUI to actually show the key binds and conflicts would be GREAT! I second this suggestion!

**Comment by Freebi85** [comment]
Hello :)
Thank you for your suggestion!
Gonna close this because working on a pre final/ final update for DD&SS.
I will only add very specific mods for the last updates. I'm sorry.
