### ISSUE TITLE
Dungeon Tactics Unbalanced additions

### ISSUE THREAD

**Issue by nrich61** [Freebi85/Dungeons-Dragons-Space-Shuttles#818]
Noticed a few (that i payed attention to) "features" of dungeon tactics(Hereafter referred to as DT) which seem to go against the vision you guys have for the pack.

1. The vanilla dispenser has been adjusted by DT so that it does additional actions, namely it can be used as a block placer, while the recipe for the dispenser is still super easy to make compared to an actual block placer.

Suggested solution: Make dispenser as irritating to make as the block placer.

2. Adds a feature to Ladders that if you right click on them with a bare hand you will teleport to the top or bottom (click on bottom and teleport to top), as far as i have been able to tell the length of the ladder doesn't matter. This makes elevators almost useless imo.

I am attaching the link where my buddy noticed these changes, under the current features spoiler;
https://www.curseforge.com/minecraft/mc-mods/dungeon-tactics

**Comment by Danekjovax** [comment]
From page:

> "Portable Tunnelling Device - Mines in a 3x3x1 (sneak to mine 1x1x1) - right-click blocks to tunnel (requires Gunpowder) - place in dispenser (with Sonic Boom enchant) for ghetto block breaker"
> 
> "Dispensers can use weapons, shear sheep, milk cows, and fill/empty cauldrons"
> 

Note: 
> "These features can be disabled in the config"

Viewing dungeontactics.cfg:
line 56-57:
```
# Set 'false' to disable Dispensers using weapons/tools. [default: true]
B:"U-Dispensers use weapons"=false
```

Looks like we're good on the weapon using part, but @nrich61 , are you actually seeing dispensers being used like this now?

**Comment by nrich61** [comment]
the weapons thing is off, however it can still be used as ridiculously cheap block placers.

**Comment by Danekjovax** [comment]
Confirmed.

![2020-04-26_23 43 15](https://user-images.githubusercontent.com/10191173/80332048-c50fe500-8817-11ea-811b-396474188053.png)
![2020-04-26_23 43 19](https://user-images.githubusercontent.com/10191173/80332056-c6d9a880-8817-11ea-9afc-c1f54e077cb1.png)

Not sure where this can be disabled in configs, though.

**Comment by Freebi85** [comment]
Vanilla dispenser will be reworked.

But i'm fine with the Ladder feature. It's enabled since pack release and not as comfortable as elevators.

Cheers
