### ISSUE TITLE
[Suggestion] Add Mekanism-Rustic interaction, misc

### ISSUE THREAD

**Issue by cHaOZZoNE** [Freebi85/Dungeons-Dragons-Space-Shuttles#821]
1. Similar to the Harvestcraft- Mekanism script, add support for Rustic Grapes etc. The saplings seem to be supported through dictionary already. The goal is to be able to use the rustic plants to make biofuel in mekanism.

`rustic:olives
rustic:ironberries
rustic:tomato
rustic:chili_pepper
rustic:wildberries
rustic:grapes`

In theory theres also a bunch of herbs:

`rustic:aloe_vera
rustic:blood_orchid
rustic:chamomile
rustic:cohosh
rustic:deathstalk_mushroom
rustic:horsetail
rustic:mooncap_mushroom
rustic:wind_thistle
rustic:cloudsbluff
rustic:core_root
rustic:ginseng
rustic:marsh_mallow`

2. I have no idea if the Plant Interactor of IF can be modified to support the grapes properly as of right now they dont get collected but just fly away when activated.

3. Possible JEI integration for what fuels the Gas Burning Generator from Mekanism can use?

**Comment by Freebi85** [comment]
Rustic integration for Biofuel in mekanism machines isn't a problem. Will be done in next update.

But i cant modify what the plant interactor can support neither a JEI integration.
This needs to be requestet to the mod Authors.

Cheers
