### ISSUE TITLE
Entangled chalice still not crafting new channel

### ISSUE THREAD

**Issue by Metalit** [Freebi85/Dungeons-Dragons-Space-Shuttles#823]
I saw two issues of the same sort through search, and they both were closed, but the bug still appears to be present: #285 and #460. I'm using version 7.1 due to being unable to connect to the server on 7.2b, but both of those are old issues and I saw no mention of entangled chalices in the changelog. The issue is of course the same as in those two. Hopefully this can be fixed in the next update.

**Comment by Freebi85** [comment]
The chalice will be completely removed in the next update 7.3. Because of balancing reasons  and the functionality of the channels (as modified version) it just doesn't work as it should.

Ender Tank is your friend.

**Comment by Freebi85** [comment]
hmm maybe i found another solution :)
