### ISSUE TITLE
server files

### ISSUE THREAD

**Issue by qrowrwby9** [Freebi85/Dungeons-Dragons-Space-Shuttles#825]
Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by qrowrwby9** [comment]
please may you add the latest server files

**Comment by Freebi85** [comment]
Still pending in twitch/curse to be approved. :/ 😭

**Comment by Freebi85** [comment]
Ok no 7.3 update for now. Stay with 7.2b until all problems are fixed. I'm sorry for the circumstances
