### ISSUE TITLE
[Suggestion] Quest for Corail tombstone.

### ISSUE THREAD

**Issue by VzeusV** [Freebi85/Dungeons-Dragons-Space-Shuttles#826]
Have you thought about adding a quest line to the tombstone corail? it seems a little ridiculous but at least 2 quests would be fine already.
I think about it considering that it is a complex mod and most people summarize it to a stonework and the key..but it even has a tree of skills and items that prevent death (useful things to play in hard / hardcore).
It took me a long time to understand why my key never appeared enchanted (Without using a point on the skill tree it doesn’t appear on the hard one).

sorry my english from google translator..

**Comment by Danekjovax** [comment]
I agree with this.  Other mods like PneumatiCraft are also lacking some love here and there's so much to do with them as well.

**Comment by VzeusV** [comment]
I have no idea how the creation of missions works, but it shouldn't be something simple and fast, outside write the descriptions, balance the rewards and everything ... But at least one mission to present the mod asking to create a lapid and saying "Config such a button for skill tree" in T0 would be useful.
And, unfortunately, there are mods that deserved their missions as bees, but the book for me at least serves more to guide me when I am very lost or as a motivation to create something.
Anyway, even if this request is not made, it will not make the modpack worse, it remains the best q I've ever played.

**Comment by Freebi85** [comment]
This mod was deleted from curse due to ToS breach. Any further update of ddss can’t use this mod anymore. Therefore it’s not possible to add this request anymore.

**Comment by Danekjovax** [comment]
Oof.  So what will DDSS use for a tombstone mod, moving forward?
