### ISSUE TITLE
Satchel loses inventory when upgraded

### ISSUE THREAD

**Issue by chadlupkes** [Freebi85/Dungeons-Dragons-Space-Shuttles#827]
I didn't empty my Satchel before upgrading it to Hardened, and I lost a really nice Knightmetal pick.  Grrr.  Can you fix it so that the recipe doesn't work if there is inventory in the Satchel, or have it keep the inventory it has?

**Comment by chadlupkes** [comment]
Actually, in the quest book it says to upgrade the Backpack to Reinforced, 36 slots.  The only "backpacks" are Forestry.  The Satchel with 36 slots is Signalium, not Reinforced.  And the Quest book has "Item Placeholder" and a question mark and won't detect the Reinforced Satchel.  So, some things to work out there.

**Comment by Freebi85** [comment]
HI!
Yes sorry like all other backpacks with modified recipes you need to empty it befor upgrading. There is noch much i can do :/ Backpacks have already a tooltip for this. Gonna add one for satchels as well.

If your quest is a placeholder then your Questbook isn't updatet to latest version. You (or your admind) need to use the command --> /bq_admin default load
This after every pack update :)

Cheers
