### ISSUE TITLE
free dank/null/mark II

### ISSUE THREAD

**Issue by weslumundo** [Freebi85/Dungeons-Dragons-Space-Shuttles#828]
![null error DDSS](https://user-images.githubusercontent.com/64718224/80897723-8bc8f080-8cc1-11ea-8236-c18a588d3f4c.png)

I could just click and get a free Null, happened right after I crafted the first iron mining hammer. It was just there. Don't think this is intended as so thought I would let someone know.

**Comment by Freebi85** [comment]
Hey :) yes this was a problem in the first 7.3 version. Bit the version was deleted quickly. Try to reinstall Your pack with the new 7.3 version available in curse. That should fix it :)
