### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by lays24mc** [Freebi85/Dungeons-Dragons-Space-Shuttles#83]
hi,

my server craseh with a NullPointerException. Here is the crashlog: https://pastebin.com/7nZERTbv

Cann you help me? Is the newest modpack version

**Comment by dierke9** [comment]
You have a mod called soundloader in your serverfiles. That is causing problems. Did you dowload the server files?

**Comment by lays24mc** [comment]
Ah sry. I copy the wrong file. Thanks you xD
