### ISSUE TITLE
Updating to 7.3 caused max health loss

### ISSUE THREAD

**Issue by Sarkos** [Freebi85/Dungeons-Dragons-Space-Shuttles#831]
I had 6 yellow hearts from eating different types of food. When I loaded 7.3 for the first time, I noticed that it was only showing the yellow hearts and no red hearts, but I figured that was just a UI change. Then I shot a glowing mob with my laser gun through a wall, there was a bang and I instantly died. After respawning I had only 6 red hearts and that is now my max.

**Comment by cyber01** [comment]
Hi, this problem has already been reported to the developer of the Cyclic mod, it is he who gives a debuff of at least -20 hearts.
As a fix, you can use the command /setheartmod [playername] 0

**Comment by Sarkos** [comment]
Thanks, that seems to have fixed it!
