### ISSUE TITLE
[Mod Suggeston] Diet Hoppers

### ISSUE THREAD

**Issue by rubixnoob13** [Freebi85/Dungeons-Dragons-Space-Shuttles#832]
I propose that the Diet Hoppers mod be added to the pack. It would be very useful to navigate around machines which have multiple cables and sides etc around them when there is a hopper in the way, as it adjusts the hitbox of the hoppers so you can click through them to machines that are behind/underneath them without having to physically move the hopper. Bonus is that it's only like 5.1k in size, so it's fairly lightweight itself.
Link for the mod: [(https://www.curseforge.com/minecraft/mc-mods/diet-hoppers)]

**Comment by Freebi85** [comment]
Hello :)
Thank you for your suggestion!
Gonna close this because working on a pre final/ final update for DD&SS.
Unfortunately I have no use for the implementation of this mod. I'm sorry. 😢
