### ISSUE TITLE
Fails to load up after update to 7.3

### ISSUE THREAD

**Issue by DigitalWino** [Freebi85/Dungeons-Dragons-Space-Shuttles#833]
After updating to the newest version, the game doesn't seem to want to load. I click play on the Twitch launcher, then click play on the Minecraft launcher, but the game doesn't start to load. If I try again it says that Minecraft is already running, but there is no loading screen or anything.

**Comment by Damit84** [comment]
Can you launch other modpacks and just DDSS is not working or are all your mod packs the same?

What you could try:
- Save your DDSS folder in the file system. (Path is under File - Settings - Minecraft in the Twitch Launcher)
- Remove your DDSS profile from Twitch and redownload the pack.
- Launch the pack

Does it work now?

If it works now you just have to copy over your world save from your saved DDSS modpack folder.

**Comment by Freebi85** [comment]
That's sadly a common issue on twitch after updating packs. You need to update to a new profile and move are your important files over. Or change the launcher at all to MultiMC, seems to work correctly there most of the time. If you have some more issues pls join the tech support channel in our Discord Server 👍 

Cheers

**Comment by DigitalWino** [comment]
Thanks, I was able to get it working by creating a new profile and moving over my saves and such.  Honestly, I hate Twitch and how buggy it is, but what I do like is that it lets me browse packs and it lets me know when there is an update.  As I understand it MultiMC doesn't do that.
