### ISSUE TITLE
[Mod Suggestion] Artisan Automation

### ISSUE THREAD

**Issue by Damit84** [Freebi85/Dungeons-Dragons-Space-Shuttles#834]
I would like to suggest a mod addition to your pack.

[Artisan Automation](https://www.curseforge.com/minecraft/mc-mods/artisan-automation) by the author of Artisan Worktables.

Short description:
Artisan Automation allows players to automate the crafting of Artisan Worktables recipes by using a new machine, the Mechanical Artisan.

Reason for the suggestion:
The artisan worktables are an absolute favorite of mine. I enjoy the complexity they add to the gameplay. Sadly in the late game when I tend to automate a lot of crafting, these tables often hinder my endeavor because automating them is very hard to impossible. In my eyes this makes the end game more tedious that it would have to be.

The mod even features a customizable upgrade/augment system for the automation machine. You could make the machine tediously slow in the beginning and then provide different tiered upgrades to make the machines more efficient later on.

Anyway please keep up the great work and thank you for one of my favorite modpacks of all time!
Best regards,
Seb

**Comment by Freebi85** [comment]
Hello :)
Thank you for your suggestion. 💪 

I am very interested in integrating this mod but the mod is still quite new. I will wait for some more updates and also i have to balance everything in ddss correctly.
I work closely together with the Artisan Table dev so I'm sure it can be integrated without any problems at a certain point on. 👍
