### ISSUE TITLE
Only 1 Quantum Entangloporter gets crafted though Automation Interfaces

### ISSUE THREAD

**Issue by UncleSweaty** [Freebi85/Dungeons-Dragons-Space-Shuttles#835]
When manually crafting the Mekanism Quantum Entangloporter via an advanced crafting table, I correctly get 2. However, when autocrafting via an Automation Interface from Extended Crafting, it only outputs 1. I haven't progressed far enough to see whether this is true for Refined Avaritia autorafting.
![1 output](https://user-images.githubusercontent.com/28244401/81003662-1be27380-8e43-11ea-87c4-7dea10b280ed.png)
![2 output](https://user-images.githubusercontent.com/28244401/81003664-1c7b0a00-8e43-11ea-901d-2513a1f601ec.png)

**Comment by Freebi85** [comment]
Oh that’s weird. But i cant interact with the automation interface myself to tix this. You should open a ticket for extended crafting tables. Maybe something with mekanism nbt.

**Comment by UncleSweaty** [comment]
Will do. Should I post a link to the issue page here? May I suggest an in-game tooltip message (either in JEI or mouse hover or something) warning people about this issue so people avoid crafting this expensive item via automation interfaces til the mod author fixes the issue?

**Comment by Freebi85** [comment]
Sounds hood will do 👍

**Comment by Freebi85** [comment]
Still not fixed and will probably never be in 1.12. Gonna Close this for now since im working on a final update for DD&SS.
Maybe I will take a look at it again if it should be fixed in the future.
