### ISSUE TITLE
Bug after riding dragon.

### ISSUE THREAD

**Issue by WesleyT** [Freebi85/Dungeons-Dragons-Space-Shuttles#837]
After riding the dragon I cannot interact with machines. This didnt happen before updating to 7.3a. 

This issue is fixed by logging out and back in

**Comment by Freebi85** [comment]
Hm okay sounds weird. But ICe&Fire mounts are knwown to cause some issues, Especially serverside.
I would recommand to report this to the Ice&Fire devs. 
Unfortunately there is nothing I can fix myself.
