### ISSUE TITLE
bug game 

### ISSUE THREAD

**Issue by noyeur** [Freebi85/Dungeons-Dragons-Space-Shuttles#838]
hello when i launch the mods pack ddss the game launches then tell me game crash : causes Unknow
here's what it shows me crash-2020-05-07 17.38.22-client.txt

**Comment by Freebi85** [comment]
Try to use multimc as launcher. Seems twitch have issues again. If you need some more support pls join our tech support channel in my discord server :)
 Discord Server Link: https://discord.gg/eUajYmK
