### ISSUE TITLE
Fetching addPacket for removed entity

### ISSUE THREAD

**Issue by mtimyself** [Freebi85/Dungeons-Dragons-Space-Shuttles#84]
Pack v4.4

Constant log spam of
> [Server thread/WARN] [minecraft/EntityTrackerEntry]: Fetching addPacket for removed entity

Don't know what mod causes it but it is old error that should be simple enough to fix.

**Comment by Freebi85** [comment]
Hello and Thanks for reporting =)
Yes, the problem is well known but it is nothing bad or dangerous. This will take a while until the cause can be found. But there is no reason to worry :D

**Comment by Freebi85** [comment]
seems to be Zombie Awareness. I still have some tests to do but I may have to replace the mod. Also because it causes other problems.

**Comment by Freebi85** [comment]
Bad News, it was not Zombiew Awareness. Seems every time a  mob/ passive mob or item falls out of the world this message is generated. I'm not sure yet why so many things fall into void. still investigating

**Comment by Freebi85** [comment]
Im Sorry i have no idea what the problem is. But since this isn't really a bug that affects the gameplay and is just a annoying console spam, I'll close that.
