### ISSUE TITLE
No Copper AIOT

### ISSUE THREAD

**Issue by TheOneWayTruth** [Freebi85/Dungeons-Dragons-Space-Shuttles#841]
There is no copper AIOT, would be nice to implement.

**Comment by TheOneWayTruth** [comment]
![image](https://user-images.githubusercontent.com/12105754/81340841-d1662e80-90b0-11ea-83bd-0029f0cacf8f.png)

**Comment by TheOneWayTruth** [comment]
![image](https://user-images.githubusercontent.com/12105754/81340883-dcb95a00-90b0-11ea-97c2-c81e98801db0.png)

**Comment by Freebi85** [comment]
Hehe yeah maybe but I’m not the mod creator and i don’t gonna mess with custom tools. You should put a request to actually additions for that 👍 
Cheers
