### ISSUE TITLE
Chrome Ingot Quests [Mystical Agriculture Tiers 2]

### ISSUE THREAD

**Issue by Edrig** [Freebi85/Dungeons-Dragons-Space-Shuttles#842]
the quest have wrong description
![2020-05-08_21 04 08](https://user-images.githubusercontent.com/4772903/81440392-451b4080-9170-11ea-806a-6c6b66f8d179.png)

**Comment by Freebi85** [comment]
Haha yeah but this was fixed already. If you're already on latest version run the command:
/bq_amind default load 
to update the book :)

Cheers, Freebi
