### ISSUE TITLE
[Botania] Botania flower generation

### ISSUE THREAD

**Issue by AllNaishaVariationsAreTaken** [Freebi85/Dungeons-Dragons-Space-Shuttles#844]
Hello,

I managed to create several "Botania Flower" by using an Endoflame on a flower pot. Version is Patch 7.3a, nothing else installed.

Thanks for the very good mod pack, we are having a blast. :)

Best regards,
Naisha

**Comment by Freebi85** [comment]
Hello :) 
Thank you for reporting! but i can’t fix such an interaction myself. You need to post this to the botania authors github :)
Cheers

**Comment by AllNaishaVariationsAreTaken** [comment]
Oh sorry for the inconvenience. Saw the message "please report this",
didn't realise i should report to them and not you. :)

Thanks again !

**Comment by AllNaishaVariationsAreTaken** [comment]
Hello again, i got this answer from the the Botania team :

Quote:

Modded flowers going into flower pots is a Quark feature, and by default,
Botania flowers are blacklisted. For some reason this modpack has the
config edited to not blacklist them - report it here
<https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles>.

The entry to edit in quark.cfg is decoration -> "colored flower pots"
-> "Flower
Overrides". "

/Quote

Please let me know if you prefer an issue update / new issue on Github.


Thanks for the good work. :)

**Comment by Freebi85** [comment]
Thank you for all your investigations :) Will fix this in next update :)
