### ISSUE TITLE
Suggestion Powered anvil

### ISSUE THREAD

**Issue by VzeusV** [Freebi85/Dungeons-Dragons-Space-Shuttles#845]
Wouldn't it be fair to make empowered anvil recipe more expensive? even altered it looks very cheap for an item that makes any tool / armor / weapon with infinite durability.
maybe exchange the plates for supremium and invert the diamonds. (Leave 5 blocks of diamond mana and 1 compressed in the middle). 
![411](https://user-images.githubusercontent.com/64233168/81489812-97cc2980-9250-11ea-9e96-0f216859db65.png)

**Comment by DGSitze** [comment]
2 Majestic ingots is quite expensive early game, even with dungeon Delving I found myself waiting to use them on other mahcines. I think the majestic component is just fine enough to make it expensive till the late game. There is a blood chest that repairs items using blood that is much cheaper using Ancient dust instead.

**Comment by VzeusV** [comment]
I think your argument is fair, maybe I was lucky even though I spawned in the deep ocean and even before I even created my extended crafting table I already had more than 20 majestics that I collected on boats.
I only suggested this because I thought that the anvil was not for the beginning of the game and I was not aware of this chest.
