### ISSUE TITLE
game bug 

### ISSUE THREAD

**Issue by noyeur** [Freebi85/Dungeons-Dragons-Space-Shuttles#846]
bonjour mon jeu ne veut pas se lancer, voici le rapport de plantage :
[crash-2020-05-11_11.55.32-client.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/4608909/crash-2020-05-11_11.55.32-client.txt)

**Comment by Freebi85** [comment]
Hello :)

Sry mate but you heavy altered the pack with 323 mods instead of 298...
Install the original dd&ss version and you should be fine again^^

Cheers
