### ISSUE TITLE
Wither Builder

### ISSUE THREAD

**Issue by RaidingPanda24** [Freebi85/Dungeons-Dragons-Space-Shuttles#847]
I just would like to inform you of the wither builder being broke right now. I put the soul sand in the machine and it placed that fine but wouldn't place the wither skulls so I placed one for it and then it got stuck in an infinite loop and spawned a million withers and I had to clear all entities otherwise it woulda broke the game.

**Comment by Freebi85** [comment]
Heh that's a weird one. I can't check right now but will later on.
However, can you report this directly to Industrial Foregoing and tell them if singelplayer, multiplayer or both. :) I Can't fix this myself anyway sadly :/
But thank you for the heads up!

Cheers.

**Comment by RaidingPanda24** [comment]
I will say I think with further looking into it that it was caused by the fact it was in a claimed chunk and I didn't have fake user building enabled, but it's been reported on industrial foregoing.
