### ISSUE TITLE
Astral Sorcery Armor perks not working

### ISSUE THREAD

**Issue by Critteros** [Freebi85/Dungeons-Dragons-Space-Shuttles#848]
![2020-05-14_14 29 41](https://user-images.githubusercontent.com/41534816/81934706-aec3a080-95ef-11ea-89e1-b3dc559e9aee.png)
Astral Sorcery reads incorrectly base armor amount ,thus armor perks do not grant any extra armor rendering them useless.

**Comment by Freebi85** [comment]
Hello :)
Sorry im not the astral sorcery dev and this is nothing i can fix myself. Report this to astral sorcerys github. But thank you for heads up! So i can post it in discord if someone ask.
Cheers
