### ISSUE TITLE
Ender Lilly seeds dropping from grass.

### ISSUE THREAD

**Issue by MONGOOSEBITES** [Freebi85/Dungeons-Dragons-Space-Shuttles#849]
Possible bug: I was able to get 2 ender lilly seeds from breaking grass. As far as I know, they're only supposed to be obtainable from dungeons. If it matters, I was in a Wasteland Flats Oasis when this occurred.

**Comment by Freebi85** [comment]
It's fine, Enderlilly seeds are in the regular loottable of tall grass. Just rng.
Cheers :)

**Comment by ianlavr** [comment]
what
