### ISSUE TITLE
cotton-string-wool crafting inaccuracy

### ISSUE THREAD

**Issue by VanSilke** [Freebi85/Dungeons-Dragons-Space-Shuttles#850]
It takes 9 cotton to craft 1 wool block.
It takes 3 cotton to craft 2 strings. 4 strings make a wool block, 6 cotton total.

Therefore, crafting cotton into string and then into wool is cheaper than crafting cotton directly into wool blocks. I'm not sure if it's intended or not.

**Comment by Freebi85** [comment]
i appreciate your attention^^ But this cotton recipe is nothing more than a bad recipe introduced by the Natura mod. 4 strings to craft a woolblock is correctly and intended. Using the other one is a waste of resources. But i gonna adjust it^^
