### ISSUE TITLE
Bug with quest 1365 reward

### ISSUE THREAD

**Issue by Naoya99** [Freebi85/Dungeons-Dragons-Space-Shuttles#851]
Hello,
there is a problem with the quest 1365 reward.
![image](https://user-images.githubusercontent.com/45720987/82062469-70e77a80-96ca-11ea-8139-5c9f1d8f41c4.png)

The basic control circuit has a tag and can not be stack with other one.
![image](https://user-images.githubusercontent.com/45720987/82062491-7cd33c80-96ca-11ea-8263-36ad7c6781ba.png)
![image](https://user-images.githubusercontent.com/45720987/82062528-8c528580-96ca-11ea-937f-fe6c5b560014.png)

Modpack version: 7.3a

**Comment by Freebi85** [comment]
Thank you for the heads up :)
