### ISSUE TITLE
[Mod Suggestion] Compact Machines 3 with ME Capability Adapter

### ISSUE THREAD

**Issue by Critteros** [Freebi85/Dungeons-Dragons-Space-Shuttles#852]
I suggest adding Compact Machines 3 to the modpack to overall reduce lag caused by big and complicated machine setups by moving them to the compact machine which has it's own dimension reducing the TPS lag. By moving objects like Drawers to compact machine it help also reduce FPS lag ,beacause client has less stuff to render. ME Capability Adapter adds a block to add support for the AE2 integration inside a compact machine which cannot be done by using cables without this mod.

**Comment by Danekjovax** [comment]
I'm all for testing this in a build that's very TPS/FPS heavy, so see it actually improve this situation would be a boon to SMP DDSS!

**Comment by Freebi85** [comment]
Confirmed.
