### ISSUE TITLE
Coal Coke to Coke Dust Pulverizer recipe missing

### ISSUE THREAD

**Issue by rubixnoob13** [Freebi85/Dungeons-Dragons-Space-Shuttles#853]
When making coal coke in Immersive Engineering coke oven, you get IE coal coke, which will produce coke dust when placed into the Thermal Expansion pulverizer. However, when you use a redstone furnace with pyrolytic conversion augment from TE, this produces coal coke from Thermal Foundation. Both of them seem to be oredicted as "fuelCoke", and both of them can produce the same "coke dust" from IE in IE's multiblock crusher, the Actually Additions crusher, Mekanism crusher, and TechReborn grinder, so I would assume it's just a hard coded recipe instead of an oredict for the one that uses the Thermal Expansion pulverizer to turn Thermal Foundation coal coke into coke dust.

Thanks!

**Comment by Freebi85** [comment]
I'm not sure I understand you. You want the thermal powderizer to produce IE coke dust, don't you?^^

**Comment by rubixnoob13** [comment]
Correct. There are 2 different coal cokes, the one produced from an IE coke oven multiblock is immersiveengineering:material 10345/6 (at least in my world), and the one produced by the thermal foundation redstone furnace with augment is thermalfoundation:material 5433/802. The one from TF doesn't make coke dust in the pulverizer if you try to put in the coal coke from the TF furnace. I'll add a pic :)
Pic 1 the top is IE coke, bottom is TF. Pic 2 shows that the pulverizer only accepts IE coke and not TF coke (the pic doesn't cycle thru them like the other recipes which are oredicted)

Hopefully this makes more sense! :D
![crusher1](https://user-images.githubusercontent.com/61389477/82183522-c038d100-98ab-11ea-8ae7-efbf5b53fe6e.PNG)
![crusher2](https://user-images.githubusercontent.com/61389477/82183542-cc249300-98ab-11ea-8bb9-d73bae29d247.PNG)

**Comment by Freebi85** [comment]
Gotcha 👍 😄
