### ISSUE TITLE
Recipie for carpenter with 10 different item need 

### ISSUE THREAD

**Issue by anthonyL05** [Freebi85/Dungeons-Dragons-Space-Shuttles#854]
Hi, before all i want to say thx for this amazing hard mod pack!

I already passed a lot of time to this mod and love it even if i am still in early game! ( compare to lot of other mod pack who is end after spend the same time)

I just got a functional me system and begin to autocraft.  A lot of recipies need the carpenter to be craft ( only 1 item can be auto craft in 1 carpenter) so you need a crazy amount of them. unfortunately it require 10 items to be craft with automation interface( there is no item who is near free in the recipy to reduce to 9 item need...) so it can't be encode without the encoder ( who need to be in more late game with the space requirement...).

Most of the early game recipie need the carpenter ( mekanism cable, upgrade for thermal circuit transistor, upgrade for drawer...) , In  early game you dont have the ressource for make a lot of them in 1 time ( empower, circuit, coolant...)  and need them one by one when need.. For the moment i just make 2 recipie in a chest and place them by hand in the table but its boring to need to wait the recipie end and go to the chest each time  for an item with that much use and need in early.

Lot of things in this pack is crazy to make.  Only need 9 items will not reduce the difficulty but help the playability ( already make 10 of them and need lot of more...) ..

**Comment by IMarvinTPA** [comment]
I used Integrated Dynamics to detect if the table has fewer than 2 steel plates in the first slot.  If that is true, then I export 8 at a time into the Automation Interface.  (Redstone writer to a servo).  The other 9 items are part of the recipe.  This can be solved.  Picture: https://discord.com/channels/517940323737927680/523043263553208330
