### ISSUE TITLE
Alchemy Bag Is Not Compatible With Rustic Potions

### ISSUE THREAD

**Issue by UnusedIdeas** [Freebi85/Dungeons-Dragons-Space-Shuttles#855]
I think that the Alchemy Bag from Extra Alchemy should work with Rustic potions and the alcohol drinks that they add, I've taken quite a while to get the alcohols to level 1 and it's a shame that I can't use this bag to store them all in and use whilst exploring. If this could be added in a future update that would be really cool!

**Comment by Freebi85** [comment]
Hello! I agree with you but unfortunately this is not something I can implement myself. 

For this implementation you have to ask the mod owner directly.
Best is to post this request on the Extra Alchemy github. 

Cheers 😃
