### ISSUE TITLE
[Mod Suggestion] Translocators.

### ISSUE THREAD

**Issue by warplord** [Freebi85/Dungeons-Dragons-Space-Shuttles#857]
I am here to suggest translocators mod. 
Link here:
https://www.curseforge.com/minecraft/mc-mods/translocators-1-8

It is small, should be incredibly lightwieght and adds some very useful functionality for close-range systems, like keeping an eye on certain invetory amounts and stuff. It is simple yet extremely effective.

**Comment by IMarvinTPA** [comment]
Seconded.
The translocator is an absolute beast at moving items fast between adjacent inventories.  It is how I empty drawers or ME systems into deep storage devices or deal with fast item generating mob farms into drawers.

**Comment by Freebi85** [comment]
Hello :)
Thank you for your suggestion!
Gonna close this because working on a pre final/ final update for DD&SS.
Don't gonna implement this mod. I'm sorry. 😢
