### ISSUE TITLE
Duping Glitch

### ISSUE THREAD

**Issue by ShyvanaDragon** [Freebi85/Dungeons-Dragons-Space-Shuttles#858]
With the /dank/null item, you can insert up to 128 of any item, take them out, throw the /dank/null onto the ground and pick it up back up with the items still in it as well as the ones you took out remaining in your inventory. And thus, allowing you to make infinite items of your choice.

**Comment by Freebi85** [comment]
Thanks for reporting. It's already a known issue on danknulls github. As soon as they push a new stable release version it will be fixed. That's nothing i can do on my end sadly.

Cheers
