### ISSUE TITLE
Storage Crates are making items dissapear

### ISSUE THREAD

**Issue by Oddwin** [Freebi85/Dungeons-Dragons-Space-Shuttles#859]
My friends and I are having an issue where Storage Crates seem to be eating items. 

It can be recreated. 

If the box is filled with things that where 'found' inside.. it works fine. As soon as you fill it with your own loot, the next time you open it it will be empty. 

I thought I was imagining things but I tested it again today with a crate I found in a village. Same results. All my hard work mining gone :)

**Comment by Freebi85** [comment]
Sounds like an odd serverside/lan issue:/
I’m sorry can’t do much there myself. If you have the steps to reproduce it then i would open a ticket on the actually additions github. 
I can help with recipes and quests but not with some weird item glitches 

Cheers
