### ISSUE TITLE
Several crashes a day, presumably related to Animania and other Mob Mods

### ISSUE THREAD

**Issue by Riallyyy** [Freebi85/Dungeons-Dragons-Space-Shuttles#86]
We are recently getting multiple Server Crashes a day, and most of the time i see lines in the Crash Report related to Mob AI, mainly with Animania and Primitive Mobs i think. Here is the most recent Report: https://pastebin.com/VS19fG3E
(Here another crash from just now: https://pastebin.com/iDgCNaPn)

I can upload the other Crash Reports as well if this one is not sufficient, i hope u can help me out.
(Server is running on the 4.5a Version)

**Comment by Freebi85** [comment]
Hello =)
If you see this line in the crash report: 
"ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)"

Then it just means your server got stuck doing something. There could be many possible causes. if this happens again change the max tick time to 999,999 in the server properties.

This pack is very resource intensive and can cause problems on the best servers. Especially if you leave Bloodmoond on and don't kill the animania animals regularly with the /kill @e command. 
I hope that can help you.
