### ISSUE TITLE
[Suggestion] Majestic Dust recipe

### ISSUE THREAD

**Issue by warplord** [Freebi85/Dungeons-Dragons-Space-Shuttles#860]
I just noticed majestic dust does not have a more efficient recipe in the alloy smelter multiblock factory. Maybe it should? Just a suggestion.

**Comment by Freebi85** [comment]
Sorry, majestic dust is intended to be combiner only.

**Comment by warplord** [comment]
That is fine. I just had to post it in case it was an oversight. thank you for answering.
