### ISSUE TITLE
Bug: Artisan Worktables + Tech Reborn Cells = Fluid & Cell Loss

### ISSUE THREAD

**Issue by Damit84** [Freebi85/Dungeons-Dragons-Space-Shuttles#861]
There is a bug when you try to fill a _Artisan Worktable_ with fluid from _Tech Reborn_ cells by rightclicking the table and the cell including the fluid gets voided.

How to reproduce:
- Put methane gas into a _Blacksmith's Workshop_.
- Craft something so the amount of methane gas in the table is not a full bucket anymore. ( _iron bucket_ for example)
- Now fill the table up with methane gas cells by rightclicking.

If you have a stack of cells in hand the cell will disappear (no empty cell is placed in the inventory) and the table is not filled to 16,000mb. You will always stay at 15,200mb.
If you use a single cell instead of a stack, there is no strange behaviour. The table opens up and the cell does not disappear.

It is not a inventory desync issue. Relogging shows no changes, the cells stay gone.
Pack Version is 7.4a.

I checked the _Artisan Worktables_ github but could not find anything there.

Not sure if your bug tracker is even the right place to post this but I wanted to make sure you know about this problem.

If you need additional information please feel free to shoot me a message.

**Comment by Freebi85** [comment]
Thanks for the heads up, but in order to can be fixet it requires a ticket to the mods github as well.
Also make sure if this is multiplayer/singlerplayer or both since i coudnt reproduce it. Need more tests

**Comment by Damit84** [comment]
I made a little [video](https://youtu.be/t_kXPSEwd48) for demonstration purposes.
But while testing for that video, i realized it probably is a problem with all stackable liquid containers. Forestry Cans for example also won't work.

I already made a bug report at the [Artisan Worktables](https://github.com/codetaylor/artisan-worktables/issues/236) Github. So you can probably put this one on hold.
