### ISSUE TITLE
RS Crafting Visuallity bug

### ISSUE THREAD

**Issue by Mist3rEvil** [Freebi85/Dungeons-Dragons-Space-Shuttles#862]
When a item is missing in a crafting request in Refined Storage it were highlighted slightly red.
This isn't anymore.

**Comment by Freebi85** [comment]
Can't interact with such mod issues or interactions. Pls post to Refined Storage but make sure to check their wiki, maybe it's just something that has unfortunately been deactivated. 
Pls report only issues with crafting recipes, quests. or recipes for machine integrations in this github like the template says.

Cheers
