### ISSUE TITLE
Rockhounding Chemistry mod:  Server File causing crash

### ISSUE THREAD

**Issue by chappy3825** [Freebi85/Dungeons-Dragons-Space-Shuttles#863]
I wrote a server file for Sulfuric Acid and now everytime i mouse over the file my game crashes.  The server file is stuck in my investory.  
[crash-2020-05-24_00.39.49-client.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/4672964/crash-2020-05-24_00.39.49-client.txt)

**Comment by Freebi85** [comment]
Can't help you there. Pls follow the template and report to the mod authors github.
Best you can do is recover from a Backup befor this weird file^^

Cheers
