### ISSUE TITLE
Dungeon Tactics books still delete Akashic tome.

### ISSUE THREAD

**Issue by DemonGamingLP** [Freebi85/Dungeons-Dragons-Space-Shuttles#867]
If you craft a dungeon tactics book together with the tome and then try to read the Dungeon Tactics book it stays the Dungeon Tactics book forever.

also i read the other report: if the books are still removed try to remove them out of chest loot table; i got one out of them.

**Comment by Freebi85** [comment]
i don't have any dungeon tactics books in customizable loottables neither are they craftable. Do you remeber where it is from exactly?

**Comment by DemonGamingLP** [comment]
Yeah i was scavenging my world and saw this structure in the air and it was in the chest there.  Von: Freebi85Gesendet: Donnerstag, 28. Mai 2020 17:40An: Freebi85/Dungeons-Dragons-Space-ShuttlesCc: DemonGamingLP; AuthorBetreff: Re: [Freebi85/Dungeons-Dragons-Space-Shuttles] Dungeon Tactics books still delete Akashic tome. (#867) i don't have any dungeon tactic books in customizable loottables neither are they craftable. Do you remeber where it is from exactly?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Freebi85** [comment]
Probably a Dungeon Tactic dungeon with hardcoded loottable. Need to investigate

**Comment by DemonGamingLP** [comment]
You Maybe could try to disable the tome crafting recipe so you cant craft These books andthe tome togetherThese books are at least a bit important since they describe the enchantments of the mod and if they dont cause any other Problems other than that with the tome it would be a good solution in my opinion.   Von: Freebi85Gesendet: Freitag, 29. Mai 2020 06:14An: Freebi85/Dungeons-Dragons-Space-ShuttlesCc: DemonGamingLP; AuthorBetreff: Re: [Freebi85/Dungeons-Dragons-Space-Shuttles] Dungeon Tactics books still delete Akashic tome. (#867) Probably a Dungeon Tactic dungeon with hardcoded loottable. Need to investigate—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by DemonGamingLP** [comment]
blacklisted out of the dungeon loot pool or blacklisted from being
craftable into the tome? if blacklisted from the tome are all the other
books available again then?

Freebi85 <notifications@github.com> schrieb am Di., 2. Juni 2020, 19:15:
