### ISSUE TITLE
Questbook T1, Solar Panel T1 Typo

### ISSUE THREAD

**Issue by AJFelidae** [Freebi85/Dungeons-Dragons-Space-Shuttles#868]
Hey,
The quest "The Power of the Sun!" in T1 Main incorrectly states that the first panel generates 4 RF/t, rather than 1. Also, "generate" should be "generates" in the description. 
Thanks!
*Additional:
Copper cables quest: "isolation" should be changed to "insulation".
Energy cell quest: "This values" should be changed to "These values".

**Comment by Freebi85** [comment]
Thank you :)
