### ISSUE TITLE
Too much lag sometimes

### ISSUE THREAD

**Issue by Otaku22** [Freebi85/Dungeons-Dragons-Space-Shuttles#87]
So, I am having a lot of lag at the moment. My computer is really good except for my processor. It's pretty crappy. I was playing Sev Tech Ages the other day and realized there were a few mods that only served a visual purpose and didn't affect gameplay at all. are there any mods in this pack that do the same thing? I just want to know which ones I can deactivate safely.

**Comment by Freebi85** [comment]
I'm going to close here because we're discussing this in the discord right now.
