### ISSUE TITLE
Advance Alloy Lead Platinum instead of Enderium

### ISSUE THREAD

**Issue by keebster** [Freebi85/Dungeons-Dragons-Space-Shuttles#871]
I used the computer to make the pattern for Enderium ingots and use that pattern to make them. But it pulls in lead and platinum first and in so doing starts creating Lead Platinum ingots. By the time the ender pearls show up about 40 to 60 ingots are already used if your making around 200

**Comment by Freebi85** [comment]
Gonna change lead platinum alloy with lead blocks instead of ingots, so the recipes don't mess up again. 👍 

Cheers

**Comment by keebster** [comment]
Ah are you saying I need to change it or are you saying you all are?

**Comment by keebster** [comment]
Cause if your meaning for me to change my pattern theres a bit of an issue with that. I dont have a pattern for Lead Platinum anywhere within my system.

**Comment by Freebi85** [comment]
? no i gonna fix (change) this recipe in next update to prevent some issus.
