### ISSUE TITLE
Dagger of sacrifice 2 differents items

### ISSUE THREAD

**Issue by anthonyL05** [Freebi85/Dungeons-Dragons-Space-Shuttles#873]
Hi,

I just get a new issue with the dagger of sacrifice when you use it as item stack to filter in a logistical sorter it was a different item you get back ( even if the block never change).  dont stack in me system and not accepted by the filter you just set . I you use it in the sorter then it can be sort and stack in me system its realy boring because you cant extract the one who is just craft from the altar with the filter. 
I will have a look to find another sorter ( only the use the ender io before)

**Comment by Freebi85** [comment]
Thank you for the heads up but this is more likely a mod interaction which i can't fix myself. 
Feel free to report it to Bloodmagic or mekanism. Can't help you there im sorry 😭 

Cheers
