### ISSUE TITLE
Infused/Electrolized/Glowing Silicone Recipie

### ISSUE THREAD

**Issue by RaduMihnea** [Freebi85/Dungeons-Dragons-Space-Shuttles#874]
Hi freebi!! I suggest adding 3 more recipes to the game, one for each of the infused/electrolized/glowing silicone types, that use the mystical agriculture essence and look just like the red alloy one ( from iron essence and redstone essence ) or the electrotine alloy one. I think it would ease the grind, and make the game more enjoyable, especially that these crafting materials are pretty used in the whole pack. It would be just like other crafting recipes that are existent, so i see no reason why not to add them. 
Thanks for making the pack awesome!

**Comment by VzeusV** [comment]
Wow, please consider doing that Freebi was going to help automations a lot and it really makes sense in view of the red alloy.

**Comment by Danekjovax** [comment]
I second this idea. ;2)
