### ISSUE TITLE
Industrial blast furnace not increase by 4 NHC

### ISSUE THREAD

**Issue by DraconovRyan04** [Freebi85/Dungeons-Dragons-Space-Shuttles#875]
I try to increase IBF by 4 Nicrome Heating coils, but its not working

![06-06-2020 213948](https://user-images.githubusercontent.com/66527274/83949657-8d488400-a83e-11ea-9286-3efdb6831d32.png)

**Comment by Freebi85** [comment]
Befor nichrome you have to add 4 kanthal coils like mentioned in main questline tier 3 :)

Cheers
