### ISSUE TITLE
Add a way to clear Mekanism machines settings (owner, RF, upgrades) in a crafting grid or other so they can be upgraded with autocrafting // Rework of Elite Injecting Factory

### ISSUE THREAD

**Issue by NopeDK** [Freebi85/Dungeons-Dragons-Space-Shuttles#876]
As per title, Mekanism machines that are placed get encoded with owner, settings and save their RF. This messes with autocrafting recipes as the data stored makes them count as separate machines.

Additional suggestion, remove/change coagulated blood drops from the Elite Injecting Factory, or add a recipe for crafting that does not require 5 minutes of waiting on a drying rack. Autocrafting that either takes forever or requires auto-stocking the drops which is a bit annoying.

**Comment by Freebi85** [comment]
Just to be clear, a NBT cleanup in a crafting grid means that all the machine content is lost. Upgrades, items, settings. Everything is gone. 

If you want to get the items and upgrades back, it will require more complex coding than I could ever do on my end with all the nbt. In this case, please contact the mod authors and close this issue.
