### ISSUE TITLE
Creating Salt in the Kitchen Workshop Duplicates Bucket

### ISSUE THREAD

**Issue by mcarreon** [Freebi85/Dungeons-Dragons-Space-Shuttles#877]
# Issue

When making salt in a kitchen workshop, the recipe works as intended but returns 2 buckets instead of the single original bucket.

## Comments

This occurs with both shift clicking and manually moving the bucket into the crafting grid. 
It happens with both the clay and iron version of the bucket.

## Modpack Version
DDSS 7.4a

**Comment by Freebi85** [comment]
Feelsbad.
Thank you for reporting 😉
Cheers
Merged with https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/889

**Comment by mcarreon** [comment]
No problem!
