### ISSUE TITLE
Error: Minecraft Failed to start!

### ISSUE THREAD

**Issue by JynxTheGame** [Freebi85/Dungeons-Dragons-Space-Shuttles#878]
Upon downloading and launching DD&SS Version: 7.4a
I'm prompted with an Error screen where it says "Minecraft failed to start!"
It saying that OpenComputers may be the problem but knowing that this pack has a lot of stuff linked together I'd assume that removing it would just cause more things to break

![unknown](https://user-images.githubusercontent.com/66751956/84317082-37275980-ab3a-11ea-9edb-4907e2ee01b5.png)

And here is the Text File Linked in the image
[crash-2020-06-10_16.29.33-client.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/4761135/crash-2020-06-10_16.29.33-client.txt)

Now while trying to figure out what went wrong I have seen that changing my allocated RAM should fix my problem and from trying the default 5120m I've also tried 6000m 8000m and 10000m and none of which fixes my issue. I've also deleted every version I've had of the pack before and reinstalled but nothing has changed.

**Comment by Freebi85** [comment]
Pls move to our discord server for technical issues. (as mentioned in the template)

You latest crash says still out of memory. provide new creashlogs in our tech support channel.

Cheers
