### ISSUE TITLE
Solar Ore? Intended?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#879]
Found this ore, and realized it has no uses (other than cosmetic).  Did you intend on this ore being in the modpack?
![2020-06-10_23 39 24](https://user-images.githubusercontent.com/10191173/84342537-c8ff8880-ab73-11ea-8b76-7a0d05fe170c.png)

**Comment by Freebi85** [comment]
Merged to https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/733
