### ISSUE TITLE
New server update causing crash at start

### ISSUE THREAD

**Issue by Brackiss** [Freebi85/Dungeons-Dragons-Space-Shuttles#88]
Just installed the new server update "DD+SS-Serverfiles-+4.6" and it crashes shortly after it is started.  Latest.log file and crash report attached
[2019-03-01-3.log.gz](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/2921131/2019-03-01-3.log.gz)
[latest.log](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/2921133/latest.log)

**Comment by Freebi85** [comment]
Hello =) Sorry I don't know anything about Sponge Servers.  But come to our Discord, we have some players who play with sponge and can certainly help you better than me :)

Discord Server Link: https://discord.gg/eUajYmK
