### ISSUE TITLE
Gendustry-Protein Liquifier: Add more raw meats to be processed

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#880]
Currently only some of the vanilla raw meats are supported (pork, chicken, fish, beef)

If possible, please add the other meats in the modpack (goat, lamb, dodo, prime beef/pork, etc.).

Thanks! ;2D

**Comment by Freebi85** [comment]
Sorry, i don’t have access to modify gendustry machines. They use an outdated own non crafttweaker solution for that Where I don't even know if this is possible at all. 
That's why I'm not going to mess with it sry 😞

**Comment by Danekjovax** [comment]
That's fine.  Not totally critical.
