### ISSUE TITLE
Recipe for Level3 Blood Orb is significantly more expensive than level4 Blood Orb

### ISSUE THREAD

**Issue by donqixot** [Freebi85/Dungeons-Dragons-Space-Shuttles#882]
As it stands in latest version 7.4a, recipe for Magician Blood Orb (level3) requires empowered diamantine block, which requires block of terrasteel. By comparison Master Blood Orb (leve4) only requires block of dragonstone, which is basically a diamond block processed thru Botania. Block of terrasteel is significantly more expensive than block of dragonstone! Should it be reversed?

**Comment by Freebi85** [comment]
You can’t obtain dragonstone without a elven portal which requires much more then just a block of terrasteel. (Core block) so it’s fine. 

Cheers
