### ISSUE TITLE
Acidic Bee - No Brimstone Comb?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#883]
Freebi,

Is there something preventing me from attaining the brimstone comb?  I have acidic bees and despite all my attempts to get them to produce, no brimstone combs.  Please advise.  Thanks!

Images attached.
![image](https://user-images.githubusercontent.com/10191173/84609341-a7a8e000-ae84-11ea-8305-8e179e821625.png)
![image](https://user-images.githubusercontent.com/10191173/84609374-bdb6a080-ae84-11ea-97fc-bdf3aae1a8c3.png)
![image](https://user-images.githubusercontent.com/10191173/84609390-cf984380-ae84-11ea-8969-32e7295a5162.png)

**Comment by Freebi85** [comment]
I’m sorry I’m agraid i don’t know either and i have 0 control about bee outputs. (Same problem like mentioned before)  All bee outputs are by default beside comb processing products. 
You have to consult other players/githubs for that. 
Keep in mind some of the bee mods like gendustry and career bees are very outdated and discontinued.

**Comment by Danekjovax** [comment]
https://github.com/ForestryMC/Binnie/issues/654
