### ISSUE TITLE
Crash with no report sent to minecraft

### ISSUE THREAD

**Issue by ShawnGunnels** [Freebi85/Dungeons-Dragons-Space-Shuttles#884]
I just downloaded the mod pack today and when I tried to run it it crashed with no crash report. I figured it was maybe the ram allocations but I allocated 8192Mb and my computer has 16,384Mb. Any available help would be great.

[Minecraft log DD&SS.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/4783025/Minecraft.log.DD.SS.txt)

**Comment by Freebi85** [comment]
Pls follow the template 👍 

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK
