### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by ArtElleys** [Freebi85/Dungeons-Dragons-Space-Shuttles#886]
1) You are talking about dragons, which means about magic. But I do not see such mods as Taumcraft or Embers

2) The mod that I still wanted to offer (those on top are secondary) is The Betweenlands. This world is with its own rules. he is separate.

**Comment by Freebi85** [comment]
Hello :) 
Check curseforge for the modpack description. There you can see what I’m talking about.  There is more the enough magic. :)

Also I’m in a pre final release and don’t gonna add such big mods to the pack anymore. It’s already resource intensive enough with 300 big mods.
 
Also use our discord server. There you will get the explained why mods like thaumcraft were removed from the modpack a while ago.

Cheers
