### ISSUE TITLE
Texturepack Bugs

### ISSUE THREAD

**Issue by EuFugs** [Freebi85/Dungeons-Dragons-Space-Shuttles#888]
![2020-06-24_13 48 29](https://user-images.githubusercontent.com/67364966/85550724-86cd5100-b621-11ea-9c7b-7e863a4d926b.png)

While building i noticed that sometimes ( dont know what triggers it) the brick texture looks different... am using the offical texture pack ^^

**Comment by Freebi85** [comment]
merged with https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/891

**Comment by Freebi85** [comment]
merged with https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/895
