### ISSUE TITLE
Jelly Recipe Bug | 7.4a

### ISSUE THREAD

**Issue by chfishy** [Freebi85/Dungeons-Dragons-Space-Shuttles#889]
When crafting Jelly(strawberry. raspberry, watermelon, etc.) with the saucepan sugar and the fruit in the chef's workshop it gives the item but also 2 saucepans.  Does not do it in the normal crafting table

**Comment by Freebi85** [comment]
merged to https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/877
