### ISSUE TITLE
4.6 Loot bag rebalance

### ISSUE THREAD

**Issue by Nagapito** [Freebi85/Dungeons-Dragons-Space-Shuttles#89]
Current loot bag rebalance seems way OP.

An inferium farm can quickly generate enough bags for a legendary bag, making the process of creating  majestic dust/ingot irrelevant on a chunkloaded base in a server.

I do not think the issue is with the rewards of these bags but instead with the lower tier bags, that have a lot of renewable items that are easy to obtain in an automated farm.  

Stone bricks, gravel, inferium, logs, any crop result, any common drop from mobs, etc should be removed from the bags to prevent abuse with the loot recycler and easy legendary/artefact bags.

**Comment by cyber01** [comment]
Can you post your farm of bags?) How to?)

**Comment by Nagapito** [comment]
Its just a cyclic harvester on a Inferium farm sending the enferium to a Loot Recycler. 
Loot recycler accepts any item that is on the loot bags table and recycles it into a new loot bag.
Then I pipe the common generated loot bags into a Lootbag storage, that allows me to convert between different lootbags types.  
  
3 hours running on a not that great farm and already have enough for 4 legendary bags.

And this is with Inferium. I could just make some basic cobbleworker and use brickstone. Or a tree farm and use the logs...

**Comment by Freebi85** [comment]
Yes, I'll definitely make some adjustments. The loottables and especially the bag values will change as well.

**Comment by Freebi85** [comment]
I will also blacklist some items in the recycler so that it can't be abused. Like stone or wood logs, inferium...
