### ISSUE TITLE
[Mod Suggestion] Tinkering with Blood Magic.

### ISSUE THREAD

**Issue by Bazyliii** [Freebi85/Dungeons-Dragons-Space-Shuttles#890]
This mod could help with Blood Magic progres by adding Sentient Sword like modifier to any Tinkers Construct's weapon.
Link here:
https://www.curseforge.com/minecraft/mc-mods/tinkering-with-blood-magic

**Comment by Freebi85** [comment]
Hello :)
Thank you for your suggestion!
Gonna close this because working on a pre final/ final update for DD&SS.
Unfortunately I have no use for the implementation of this mod. I'm sorry. 😢
