### ISSUE TITLE
Texturepack Sandstone Bug

### ISSUE THREAD

**Issue by EuFugs** [Freebi85/Dungeons-Dragons-Space-Shuttles#891]
![2020-06-27_00 24 45](https://user-images.githubusercontent.com/67364966/85905812-be4c2100-b80c-11ea-875a-17228092bc0b.png)  Also the Sandstone texture seems to switch to the Vanilla texture if you place another Sandstone on top ^^´

**Comment by Freebi85** [comment]
merged to https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/888
