### ISSUE TITLE
JEI Bug ( i guess?)

### ISSUE THREAD

**Issue by EuFugs** [Freebi85/Dungeons-Dragons-Space-Shuttles#892]
![2020-06-27_20 41 43](https://user-images.githubusercontent.com/67364966/85929613-b21c9e00-b8b6-11ea-88c2-3f76d83453fc.png)
![2020-06-27_20 38 52](https://user-images.githubusercontent.com/67364966/85929616-b648bb80-b8b6-11ea-9147-773da32ceed9.png)
encountered this on various recipes recently; as shown it shows 5 available recipes at first, however if you forward to the last one it turns into page 5/4 ( screenshot 2); another example would be the "Engineers Workshop" tab ( again with the underground bioms marble )

**Comment by Freebi85** [comment]
See https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/865
