### ISSUE TITLE
Bottle of Honey Inconsistency

### ISSUE THREAD

**Issue by Sixdd6** [Freebi85/Dungeons-Dragons-Space-Shuttles#894]
The Bottle of Honey that you can get from a Rustic Crushing Tub and Rustic Honeycomb is not usable in the Harvestcraft "Honeycomb Chocolate Bar".

This could be solved easily by adding the oreDict entries from the Animania bottle of honey to the two from Rustic.

**Comment by Danekjovax** [comment]
Hmm, I didn't remember having that problem back in my "food" playthrough, but perhaps there's a need for a foodDict, as oreDict is more for mined ores/metals? ;2)

Tongue-n-cheek aside, I agree that the recipe should be tweaked to allow the other honey items.

**Comment by Freebi85** [comment]
i can't oredict bottles with fluids from rustic because otherwise all bottles in rustic with any content will be assigned to these oredict. no matter what is inside. 

The Animania honey bottle is oredicted to honey, because the bottle items in animania are called differently while rustic bottle items are using all the same item tag.

**Comment by Sixdd6** [comment]
I did my own oredict entries for myself and I've had no such issues.

```
<ore:foodHoneydrop>.add(<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "honey", Amount: 1000}}));
<ore:foodHoneydrop>.add(<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "for.honey", Amount: 1000}}));

<ore:foodHoney>.add(<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "honey", Amount: 1000}}));
<ore:foodHoney>.add(<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "for.honey", Amount: 1000}}));

<ore:dropHoney>.add(<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "honey", Amount: 1000}}));
<ore:dropHoney>.add(<rustic:fluid_bottle>.withTag({Fluid: {FluidName: "for.honey", Amount: 1000}}));
```

I've used this for a while and the recipe is at least correct in JEI and does work with the new honey bottles, I can't say whether it allows other bottles as well but JEI shows it just as honey.

**Comment by Freebi85** [comment]
I had a similar problem with buckets a while ago and people started changing milk buckets to full iridium buckets. Maybe rustic bottles work differently and rustic bottles fluids aren’t that important at all but still, i don’t  gonna mess with that im sorry.

**Comment by Sixdd6** [comment]
No sweat, thanks for the answer.
