### ISSUE TITLE
Freebi's Mix: Textures for some items not loading properly

### ISSUE THREAD

**Issue by MetroxStarcaller** [Freebi85/Dungeons-Dragons-Space-Shuttles#895]
Some Items use their default textures instead of the ones provided by the texturepack.

![Mystical](https://user-images.githubusercontent.com/67740076/86352010-704c7880-bc65-11ea-854e-96dc2e484b77.jpg)

F.e. the inferium essence + upgrades and their ingots.
The marked items have 32x32 textures in the pack.

**Comment by Freebi85** [comment]
merged to https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/888
