### ISSUE TITLE
Ground Trap not working

### ISSUE THREAD

**Issue by BubblyBoar** [Freebi85/Dungeons-Dragons-Space-Shuttles#896]
I've searched resources online, but none seem to solve the issue that I'm having.

I set a ground trap and have it surrounded by grass blocks.  There's grass all around it in a 5x5 radius even though it only only checks the cardinals.  The only block not grass is at a diagonal, which is a water block.  This is on a multiplayer server.  I've waited multiple minecraft days, but nothing.

<img width="610" alt="Untitled" src="https://user-images.githubusercontent.com/67841913/86520545-9e6fbb00-be13-11ea-85c5-3d1e8e478023.png">

**Comment by Freebi85** [comment]
The trap needs to be in the ground and surrounded by dirt. Except top side. 

Pls use our discord server for such questions. Way faster to solve such kind of problems :-)
Cheers 🍻
