### ISSUE TITLE
2 Crafting + 1 Mod Suggestion

### ISSUE THREAD

**Issue by RaduMihnea** [Freebi85/Dungeons-Dragons-Space-Shuttles#897]
Hi Freebi, im coming again with 3 suggestions for you.

Tweak/Crafting suggestions: 

1) The cosmic meatballs recipe doesnt allow prime chicken or any other prime meat to be used. Considering you're not allowed to spawn vanilla mobs this is pretty stupid. The problem is more visible on the chicken meat as it does not have any way to transform it into the vanilla version, unlike how the other 2 can. Basically, you're forced to aquire all the chicken meat for the meatballs thru ground traps. The fixes would be: a) allow for prime meat to be used in the crafting recipe b) allow for transformation between prime and normal version.

2) The creative crafting terminal should have a crafting recipe, make it as insane as you want, but it should exist. the abillity to access your ME system from all dimension is something you would crave for in the end game and something that most packs give the offer to make. it just removes the need for booster cards that, while useful, are very annoying to make at mass.

Mod suggestions:

I think Compacted Machines mod would to very much good to the pack. Reaching the endgame causes a lot of TPS/FPS lag from all the complex production chains you have set up in your world. While you could tell the argument of "build a void world", Compacted Machines is much friendlier with servers and quite a better alternative than just a void rftoold dimension. this was disputed on the discord and people think it wouldn't be such a bad idea.

Thanks again!

**Comment by Danekjovax** [comment]
Nice ideas all around, though I'll only say that the wireless AE terminal does allow for inter-dimensional access through the crafting/collecting of the Infinity boosters, and even though it's a temporary "fuel" for accessing your AE from anywhere (outside your regular wifi range), it is still a doable solution in late-game as materials are pretty easy to accumulate by then.

I also second the Compact machines idea.  It was posted in another ticket, but the more chatter about it, the better.

Again, huzzah to the Great Freebi for supplying the best Modpack to the MC modding community!

**Comment by RaduMihnea** [comment]
I think that by the end-game, materials to craft infinity boosters do not represent a problem anymore, so its just a small annoying thing you have to craft again and again and again and so on. Tbh i would prefer to give 8 infinity ingots, quintuple batteries, couple of singularities and so on just to remove that inconvenience.

**Comment by Freebi85** [comment]
Heyho 😄 

I think proposal one and two can be implemented in this way. Of course creative item = expensive.
However, I do not accept any more mod suggestions. These require more profound testing than just saying "it won't crash when I start the game".
Since I'm already working on a new project I only make small changes and (fixes) in ddss. At least for now.

Cheers

**Comment by RaduMihnea** [comment]
Thanks for taking into account these suggestions. Can’t wait to see your future project then! 
Best of luck!
