### ISSUE TITLE
Recipe Conflict: Tech Reborn Compressor -> Knightmetal Block results in Ironwood Plates

### ISSUE THREAD

**Issue by Damit84** [Freebi85/Dungeons-Dragons-Space-Shuttles#899]
Title more or less says it all.
If you put a Block of Knightmetal into a Tech Reborn Compressor it will turn into 9 Ironwood Plates.
There are also two recipes for Knightmetl Blocks. One probably should be an Ironwood Block?

Please see the attached screenshot:
![grafik](https://user-images.githubusercontent.com/8322579/87037782-0eec5280-c1ed-11ea-8af9-1d7aadb91f5c.png)

**Comment by Freebi85** [comment]
For some odd reasons Tech Reborn won't accepts any changes for this specific recipe... Can't fix. im sorry :/
