### ISSUE TITLE
Lost questbook database

### ISSUE THREAD

**Issue by arturgaweski** [Freebi85/Dungeons-Dragons-Space-Shuttles#9]
Hi, can you help me solve problem with quest book? My database got somehow completly wiped out after just like another day started & played minecraft . My questbook appears clean like i just started new character. Is there any backup? Can it be restored? I tried ofc restart & start minecraft and reload questfile with /bq_admin default load
[latest.log](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/2617550/latest.log)
[debug.log.gz](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/2617553/debug.log.gz)

**Comment by Freebi85** [comment]
Huhu artugraweski =)
If you have a backup save, open the save folder. Look for the "betterquesting" folder in the save, and copy "quest database" and "quest progress" files and paste them in the same folder of your primary world. 

If you don't hava a backup, then use the "/bq_admin edit" command to complete any quests you're still needing to recover. Be sure to toss those rewards away^^
/bq_admin default load and bq_user refresh are only used to update the questbook to the newer version to have all new quests.

I hope I could help.

Sincerely, Freebi
