### ISSUE TITLE
"Evaporator!" quest gives the "wrong" vanadium ingots

### ISSUE THREAD

**Issue by ziz** [Freebi85/Dungeons-Dragons-Space-Shuttles#901]
The `Evaporator!` quest (Main Tier 4, number 1288) gives three Vanadium ingots from the Rockhounding mod (`rockhounding_chemistry:metal_items 0`). This is not the usual Vanadium ingots that vanadium ore produces through smelting, ingot casting, or Mekanism ore production, which is the Zoesteria Biomes ingot (`valoegheses_be:ingot_vanadium`), and as far as I can tell has little or no other source in the game. 

It's a very minor thing but caused me a few minutes of puzzlement trying to figure out why _these_ vanadium ingots weren't going into my storage drawers, and then finding out where they came from.

For consistency, perhaps replace this quest reward with the "default" Vanadium ingot?

**Comment by Danekjovax** [comment]
Were you able to convert them with the oredictionificator?

**Comment by ziz** [comment]
Ore Dictionary Converter from Industrial Foregoing converted them. I didn't have an Oredictionificator at the time.
