### ISSUE TITLE
Minor typos in the curseforge page for the modpack

### ISSUE THREAD

**Issue by a4358** [Freebi85/Dungeons-Dragons-Space-Shuttles#902]
The description of the modpack is very nice and appealing, but it has some rather unpleasant typographical mistakes. Fixing them is a minor thing, but still probably should be done at some point to make the whole package look more presentable. Here are some that i have found and my suggested fixes:
"They are all balanced in each other" -> They are all balanced with each other.
"advanteages" -> advantages
"a lot of usefull stuff" -> a lot of useful stuff
"Grow step for step together" -> Grow step by step together
"dimensions to explore (which includes planets..." -> dimensions to explore (which include planets
"majestic Creatures to taim, fly " -> majestic creatures to tame, fly 

Also a lot of other misc. Words are Capitalized for seemingly no Reason, but those are way too numerous to list and are not as critical. Some examples include:
"At a certain Point" -> At a certain point
"breed and Care for Animals" -> breed and care for animals

**Comment by Freebi85** [comment]
Hey there!
Thank you for the heads up. Gonna fix the most important things, but I will not invest too much time in this. 

Cheers
