### ISSUE TITLE
[Animania] Bee Hive

### ISSUE THREAD

**Issue by skitlzx** [Freebi85/Dungeons-Dragons-Space-Shuttles#903]
I can't find Bee Hives (Animania). When i played on version 7,1a i found them. After I stooped to play. Recently i have updated to 7.4a and i cant find any Bee Hives (animania). I checked change logs and i can't find log about hives (animania). What happen?

**Comment by Freebi85** [comment]
Hey There^^
Meanwhile they're intentionally disabled^^
Rustic Bee hives (and forestry of course) are the only ones you can find.

Cheers
