### ISSUE TITLE
Sanguine Roses disabled since 7.1?

### ISSUE THREAD

**Issue by donqixot** [Freebi85/Dungeons-Dragons-Space-Shuttles#905]
I played earlier version of the pack and distinctly remember finding sanguine roses from dungeon tactics in swampland. But since I updated the pack to latest version and tried new world, I can't seem to find them anymore. I checked config for dungeon tactics and it seems flowers may be disabled as of 7.1 version of the pack. I checked changelog and did not see it there. So I just wanted to confirm - is it disabled on purpose or I simply do not find them?

**Comment by Freebi85** [comment]
Hey there,
Yes i disabled all dungeon tactics flowers at some point because they crashes sometimes with industrial foregoing tile entities (machines) when placed nearby. And some of them were op anyway^^

Cheers
