### ISSUE TITLE
Framed Chest causes crash

### ISSUE THREAD

**Issue by Wolf68k** [Freebi85/Dungeons-Dragons-Space-Shuttles#906]
When piping any item into a BiblioCraft Framed Chest the pack crashes. This happens in both SSP and SMP.

To recreate the issue:
Vanilla chest with an EU2 Transfer Node and pipe connected to it. Bibliocraft Framed Chest connected to the pipe. Add an item to the vanilla chest and wait for the crash.
Hoppers seem fine. I couldn't find anything else that will connect to it and try to transfer to it.

The only fix to save the world is to use MCEdit to remove the transfer node and pipe. 

Using the latest version of the pack; V.7.4a

**Comment by Freebi85** [comment]
Thank you for the heads up! Sadly i can’t fix such a crash myself. It’s a modrelated issue. You need to post it to the bibliocraft guthub. I can only remove the chest.

But.. you should know that they stopped development of bibliocraft and eu2.  I don't know if it can ever be fixed.
