### ISSUE TITLE
Ancient Dust: Cursed version cannot be used to make Evil Infused ingots - Intended?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#907]
If the above mechanic is tended, then close the ticket.

Otherwise, please add the cursed ancient dust to the Induction Smelter recipe to make Evil Infused ingots.

Thanks!

PS: TheVongola10th gets the credit for discovering this apparent anomaly. ;2D

**Comment by Freebi85** [comment]
Hello!
That’s something that doesent work anymore after latest thermal expansion update. Most other machines atill work with both versions. Sadly i can’t change much there :/
Cheers
