### ISSUE TITLE
Ender Library duping enchantment books

### ISSUE THREAD

**Issue by krisavi** [Freebi85/Dungeons-Dragons-Space-Shuttles#908]
At least when playing on server, using enchanted book on the ender library duplicates the book. It makes the book stack size from 1 to 2 while giving message: "Enchanted books must be stack size 1 to store"

Reported bug to Cyclic as well. It can be due to mod clash, but for me it seems to be more of issue in cyclic itself. It has had many changes lately concerning the same mechanic. At least when checking closed and open tickets for Ender Library.

Issue I opened in Cyclic github:
https://github.com/Lothrazar/Cyclic/issues/1457

Quick GIF, not great, but should show the issue.
https://gyazo.com/1b7ae30753f820c17501201d21a744e5

**Comment by Freebi85** [comment]
Gonna remove it from ddss. Working on a final patch and can't wait for a fix^^
