### ISSUE TITLE
visual glitch?

### ISSUE THREAD

**Issue by vokun17** [Freebi85/Dungeons-Dragons-Space-Shuttles#909]
sorry if this is an issue for discord.

whenever i mine a block (dirt, stone, etc), the breaking animation is accelerated then it changes the block to some other type. eg. when breaking stone the block still drops as dirt but just before it breaks it flashes and changes to diamond ore, then another block, etc. even the block description (that appears at the top of the screen when looking at a block) changes to diamond ore and so on. it still drops as cobblestone. just want to know if im doing something wrong. i've tried uninstalling and reinstalling the mod but it still happens.

**Comment by Freebi85** [comment]
Hello^^
Aa far as i know, this happens every time after changing some settings or mess around with Texturenpacks. Usually a simple client restart will solve the issue. Without reinstalling the pack. 
Join our tech support in discord if it’s still a thing. 

Cheers
