### ISSUE TITLE
Clay Duping

### ISSUE THREAD

**Issue by IMarvinTPA** [Freebi85/Dungeons-Dragons-Space-Shuttles#910]
Clay can be duplicated with a compacting drawer, converting a full block to 9 clay balls.   Put 4 clay balls into a Chemical Dissolver, take the 4 Kaolinite and put them into a Chemical Combiner to get a full block of clay, repeat!

**Comment by Danekjovax** [comment]
I think this is what you're referring to?   If so, yeah, that's it. ;2)
![2020-07-27_08 53 47](https://user-images.githubusercontent.com/10191173/88544023-cbfcee00-cfe6-11ea-9d21-e480f99beed0.png)

**Comment by IMarvinTPA** [comment]
Yup, that.
