### ISSUE TITLE
Unexpected grape seed drop

### ISSUE THREAD

**Issue by emenifee** [Freebi85/Dungeons-Dragons-Space-Shuttles#911]
Playing version 7.4a, using a server.

When chopping down normal jungle AND 2x2 giant jungle trees [planted with Jungle Sapling (#0006/3)], it looks like it is dropping Cocoa Beans, however when I actually pick them up I end up with "Grape Seeds (#6374) rustic:grame_stem".  I found it surprising to be getting grape seed drops from a jungle tree.  I have not received any cocoa beans from jungle trees so far, which (at least in other mod packs) expect I should have seen some cocoa or cocoa pods by now.

So far only planting my jungle saplings in a lowlands biome (have not tried other biomes, to determine if biome specific drop)

Have not yet tried bonsai/hopping bonsai pots to see if drop is correct there per JEI for cocoa.

Have not yet tested localhost single player to determine if server side pack issue.

Have not yet re-tested with unmodified client.  [Server is unmodified Server zip 7.4a]   On client side I have installed the following client side only mods: OptiFine_1.12.2_HD_U_F5_MOD, Notes-1.12-1.1.1, SlimeModSSP-1.12.2-2.1.  Using the following Resource Packs: Freebi's Mix V. 1.3 and Soartex_Fanver (4.1.2) . Using the following shader Pack: SEUS-Renewed-v1.0.1]

**Comment by Freebi85** [comment]
Hello :)
Sorry that’s nothing i can change or fix on my end. Looks like rustic adds them to vanilla minecraft trees. If this is an issue at all you have to contact the mod maker.
You need to check the rustic github. Pls only problems around recipes or quests. Thank you 👍 

Cheers
