### ISSUE TITLE
Rockhound Syngas and Transposer Issue.

### ISSUE THREAD

**Issue by Ryansemch** [Freebi85/Dungeons-Dragons-Space-Shuttles#912]
Using Rockhound to make Syngas as it is rather easy to mass produce within its own mod, Discovered an issue. While Nothing prevents you from using their Syngas in other machines, getting it out of their system is almost impossible. RH doesn't allow other pipes to connect to it's gas machines, Online messages indicate that Using the Transposer should work to convert it to Syngas outside the mod pipes. But it doesn't seem to accept the gas after running even once(Breaking and replacing doesnt even allow it, 100% of the time, closer to 1 in 45 attempts allowed the liquid to move again. I do know the directional controls of the system.). Either Im breaking it somehow or an error is occuring. Please help

**Comment by Freebi85** [comment]
Hi^^
Yeah, Rockhound is a completely closed system which don't accept any other pipes from other mods at all. 
It is correct that to export the gases you need a transposer. If you place the transposer directly on the vessel or a gas holder it will be transmitted. Attention: the direction of the transposer is important for it to work.

With this I have already managed to export the gases.

Nevertheless, it still doesn't sound as intended to me. But I'm not the rockhound dev and can't help you here for better or other solutions. You have to open a ticket in his github.

Cheers
