### ISSUE TITLE
Liquifier- Add Chlorine

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#914]
Freebi,

There's very limited ways to process Chlorine into a liquid, but there's a lot of things in Alchemistry that seemingly like to produce Chlorine as a by-product.
![image](https://user-images.githubusercontent.com/10191173/89110186-2d252700-d416-11ea-80d2-11685fa30526.png)

There's a Liquifier in Alchemistry which converts many of the chemical/elemental items into a liquid.
![image](https://user-images.githubusercontent.com/10191173/89110193-3c0bd980-d416-11ea-8af7-3f03a4472626.png)

If it is possible, please... PLEASE... add a way to convert Alchemistry chlorine into its liquid equivalent.  This will help a LOT towards making chlorine production more feasible on large-scale operations (late and end-game).  It also makes sense to give more uses to items otherwise sitting around doing nothing, right?

Thanks! ;2D

**Comment by Freebi85** [comment]
sounds good
