### ISSUE TITLE
Duping item that are not used up in recipe

### ISSUE THREAD

**Issue by 0196071** [Freebi85/Dungeons-Dragons-Space-Shuttles#915]
If you have an item that is not used in a recipe in a crafting table then use the rftools storage scanner to craft, the item that is not used in the recipe is duped
![2020-08-02_20 11 23](https://user-images.githubusercontent.com/3613658/89135626-de9e8800-d4fc-11ea-8acd-9a75e072662f.png)
![2020-08-02_20 11 48](https://user-images.githubusercontent.com/3613658/89135627-e100e200-d4fc-11ea-9212-2acda93f8a1e.png)

![2020-08-02_20 11 51](https://user-images.githubusercontent.com/3613658/89135632-e4946900-d4fc-11ea-8909-cf838261a6c6.png)

![2020-08-02_20 11 55](https://user-images.githubusercontent.com/3613658/89135634-e65e2c80-d4fc-11ea-8146-1ba3662df3e6.png)

**Comment by Freebi85** [comment]
Hello 👍 
Thank you for the heads up but i can't fix such a dupe on my end. You have to report this to the proper mod authors github im sorry. You also have to specify if this happens in single or multiplayer or both.

Cheers
