### ISSUE TITLE
Hello Can you add Buildcraft mod to this modpack please?

### ISSUE THREAD

**Issue by BoBo45564** [Freebi85/Dungeons-Dragons-Space-Shuttles#918]
Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

**Do NOT Report here:**
-Server problems, crashes or technical issues of any kind. Use our helpdesk (tech-support-channels) in our Discord Server to get help in any of these matters.
Discord Link: https://discord.gg/eUajYmK

**Comment by Freebi85** [comment]
Hi^^

That would be very useles. There are tons of mods doing stuff better then buildcraft. In terms of pipes, energy generation or quarrys. I don’t see any useful integration with that one I’m sorry 😐

**Comment by BoBo45564** [comment]
Welp I tried ^ ^
                       -

Dňa so 8. 8. 2020, 21:05 Freebi85 <notifications@github.com> napísal(a):
