### ISSUE TITLE
 Notification Cannot find file System.Linq.Enumerable+WhereSelectListIterator`2[Curse.Radium.Minecraft.Models.ManifestResource,System.Int32] for addon 231951 in database. Aborting installation.

### ISSUE THREAD

**Issue by thetechy2** [Freebi85/Dungeons-Dragons-Space-Shuttles#921]
when trying to install i get this 
Notification
Cannot find file System.Linq.Enumerable+WhereSelectListIterator`2[Curse.Radium.Minecraft.Models.ManifestResource,System.Int32] for addon 231951 in database. Aborting installation.

**Comment by Freebi85** [comment]
Yeah it’s a twitch issue since 2 days. I would recommend to use multimc because it runs great there. For further questions pls join our support channel in discord. Cheers

**Comment by thetechy2** [comment]
Tysm
