### ISSUE TITLE
Missing entry in Minecraft.zs for natura:nether_logs2:15

### ISSUE THREAD

**Issue by GrimFred** [Freebi85/Dungeons-Dragons-Space-Shuttles#922]
Hey Freebi,
in the modpack the second type of Bloodwood_log cant' be made into planks.
Oh, i got the bloodwod_logs in an older version but upgraded to the 8.0 beta version
Just add following lines to the Minecraft.zs:
recipes.addShapeless(<natura:nether_planks:1> * 2, [ <natura:nether_logs2:15>]);
recipes.addShapeless(<natura:nether_planks:1> * 4, [<ore:artisansHandsaw>.reuse().transformDamage(5), <natura:nether_logs2:15>]);
mods.thermalexpansion.Sawmill.removeRecipe(<natura:nether_logs2:15>);
mods.thermalexpansion.Sawmill.addRecipe(<natura:nether_planks:1> * 6,  <natura:nether_logs2:15>, 1500, <thermalfoundation:material:800>, 50);

**Comment by Freebi85** [comment]
Uhm.. It's already in the code and still there? (Even in 8.0) 🤔 Just with an other kind of planks it seems. Need to check,
Anyway thx for the heads up and the code :)

**Comment by Freebi85** [comment]
Looks like Bloodwood drops 2 different kind of logs lol. One was alreday scripted. Should be fixed in final release.

Cheers
