### ISSUE TITLE
Mod Suggestion - Xtones

### ISSUE THREAD

**Issue by Cardinalstars** [Freebi85/Dungeons-Dragons-Space-Shuttles#923]
Hey, I know the mod pack is mainly focused on tech and magic and what not, but I think that Xtones could add some really nice building blocks and fill in some niches in building not already there.  Chisel is very similar, yes, but Xtones adds many more smooth tones that are lighter and less busy.  

The mod is super lightweight too, basically nothing other than just more blocks to load.

**Comment by Freebi85** [comment]
Sry DD&SS is in a pre final release state. The next and last patch won't recive any new mods^^
