### ISSUE TITLE
Bucket Duplication Bug

### ISSUE THREAD

**Issue by ChristianKernDev** [Freebi85/Dungeons-Dragons-Space-Shuttles#926]
I found a method to duplicate buckets by accident:

Steps to reproduce:
- Fill a Vanilla Bucket with water
- Put it in a Artisan Cooking Worktable with the tools to craft salt
- After crafting the salt two empty Vanilla Buckets are created instead of one

**Comment by Freebi85** [comment]
Thank you for reporting. Should already be fixed in version 8.0  
cheers :)

**Comment by kubilayerislik** [comment]
I found a similar method for bucket duplication bug. 

Steps to reproduce:

Fill a Vanilla Bucket with Friesian Cow Milk
Put it in a Artisan Cooking Worktable and Convert to vanilla Milk
After crafting it gives a bucket of vanilla milk and empty bucket.
