### ISSUE TITLE
weird recipe with no texture

### ISSUE THREAD

**Issue by 0196071** [Freebi85/Dungeons-Dragons-Space-Shuttles#927]
![2020-09-01_14 46 47](https://user-images.githubusercontent.com/3613658/91893351-fbe08680-ec61-11ea-8b34-8130651e1889.png)

**Comment by Freebi85** [comment]
Those are some items which are not in use in the pack or don’t exist anymore. For some odd reason they are still in JEI. And i can’t remove recipes that doesent properly exist. In the end nothing to worry about.
