### ISSUE TITLE
Typing/Spelling Mistakes

### ISSUE THREAD

**Issue by DarkSideofDawn** [Freebi85/Dungeons-Dragons-Space-Shuttles#93]
![image](https://user-images.githubusercontent.com/48439822/54122700-a96c3400-43f5-11e9-9205-56a1a4495964.png)

On Version 4.6b - Protectors of the Earth quest line - Turret Base T1 Quest.

"This ist the core block..." should be "This is the core block..."

![image](https://user-images.githubusercontent.com/48439822/54123105-c7866400-43f6-11e9-82c4-95e1829caae5.png)

Same Version: 
"Cannon need" should be "Cannon Needs"

**Comment by Freebi85** [comment]
Thank you :D, fixed in next update

**Comment by DarkSideofDawn** [comment]
Sorry i found another!

**Comment by Freebi85** [comment]
no problem. feel free to post all the stuff here

**Comment by DarkSideofDawn** [comment]
found another Freebs!
![image](https://user-images.githubusercontent.com/48439822/54464820-2984f780-4770-11e9-8dc8-1247b78ae21c.png)
