### ISSUE TITLE
Can't use stronger bowl of promises as weaker in recipes

### ISSUE THREAD

**Issue by Galicjanin** [Freebi85/Dungeons-Dragons-Space-Shuttles#930]
When I tried to make Promise of Productivity with a bowl of promises Strength 2, It doesn't let me.
Bowl of promises str 2 has 3 ore dictionary values:
MaterialBowlOfPromises0
MaterialBowlOfPromises1
MaterialBowlOfPromises2
As for all promises it is same recipe, It should be valid to use stronger as weaker, or otherwise you need to change promise of tenacity in blood infuser whenever you want to make something with weaker bowl of promises.

It is also painfull to lower tier of promise of tenacity, as you can't simply remove it or replace with lower lvl. You need to break the whole infuser.

**Comment by GrimFred** [comment]
yeah, if you have an infuser with the diamond Promise and then want to craft a speed or productivity Promiseyou need another blood infuser or break your one and only upgrade it to the second.

Maybe just add all recipies without promise/gold Promise to the diamond Promise?

**Comment by Freebi85** [comment]
I see :0 gonna oredict all bowls in those recipes ^^
