### ISSUE TITLE
Pushing or pulling wither skeleton statue with piston/sticky piston crashes game

### ISSUE THREAD

**Issue by Galicjanin** [Freebi85/Dungeons-Dragons-Space-Shuttles#932]
Pushing or pulling wither skeleton statue with piston/sticky piston crashes game on the server side.

I tried to enter world, but there is piston on clock and im not fast enough to break contraption.
[crash-2020-09-07_22.05.50-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/5184812/crash-2020-09-07_22.05.50-server.txt)
[crash-2020-09-07_22.06.18-client.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/5184815/crash-2020-09-07_22.06.18-client.txt)
[crash-2020-09-07_22.07.34-server.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/5184819/crash-2020-09-07_22.07.34-server.txt)

**Comment by Freebi85** [comment]
Please note the template when you open an issue and don’t report Server side issues and crashes here. I can’t fix them anyway myself.

Try in our unofficial discord channel for some help and report the problem to the appropriate mod author. In this case it seems to be an interaction between quark and hammercore. Note that many 1.12 mods are no longer supported.
