### ISSUE TITLE
With ore excavation on pick you can mine ores that are higher level than pick

### ISSUE THREAD

**Issue by Galicjanin** [Freebi85/Dungeons-Dragons-Space-Shuttles#933]
With ore excavation enchantment on pick you can mine ores that are higher level than pick. First ore is destroyed, but other connected to first one are collected.

**Comment by Freebi85** [comment]
That’s weird but i can’t interact with enchantments I’m sorry. That should be adressed to the proper mod github. Pls Report only stuff about recipes or quests, thank you.
