### ISSUE TITLE
Missing mod in Server Jar files.

### ISSUE THREAD

**Issue by icemagetv** [Freebi85/Dungeons-Dragons-Space-Shuttles#935]
Thing that happen:
- Multiplayer Server - Missing Recipe for **ME Capability Adapter**.  Thing not there.
- Single Player - Works Good and Stuff.  Thing is there.

Raeson for happen:
- Missing mod (guess which) and jar file in Server files download.

How fix:
- Download missing mod, put file in mod directory;
- link here: https://www.curseforge.com/minecraft/mc-mods/capability-adapter/files
- Restart Server.
- Hopefully you backed up before you started.

What Happen:
There's like fifty kajillion mods.  Thing Happens.

**Comment by Freebi85** [comment]
Big OOf :0
