### ISSUE TITLE
Suggestion to make target dummy spawn egg craftable

### ISSUE THREAD

**Issue by Galicjanin** [Freebi85/Dungeons-Dragons-Space-Shuttles#936]
Spawn Target Dummy (#0383) from Cyclic is useful for testing weapon damage. Would be nice to be able to craft those and place in the world to play with. As they are just for 1-2 hits for better weapons, I suggest not to difficult recipe for them and disabling loot drop for them.

**Comment by Freebi85** [comment]
Sorry, see https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/423 ^^
