### ISSUE TITLE
NuclearCraft Melter can no longer melt Salt to Brine?

### ISSUE THREAD

**Issue by Acru** [Freebi85/Dungeons-Dragons-Space-Shuttles#937]
I was just updating my DDSS 6.5 world to continue, and I notice that the NuclearCraft Melter recipe for turning Salt into Brine is missing in the 8.0 beta.  I checked the full change logs for both DDSS and for Nuclearcraft, for all intermediate versions, and found no mention of such a change.

Is the removal of this recipe intentional or accidental?

One can still convert salt to brine with a two-machine Mekanism setup, with Gaseous Brine as an intermediate product, but it isn't clear if the other recipe was removed to make brine production more difficult, or if the recipe was broken by accident at some point.

**Comment by Freebi85** [comment]
Yes the nuclearcraft one was a tiny bit too easy. Now you need just a tiny bit more effort^^
Cheers

**Comment by Acru** [comment]
Alright, thanks for confirming this~
