### ISSUE TITLE
Can't get white magic essence out of a TiC smeltery.

### ISSUE THREAD

**Issue by TheGamingGeneral** [Freebi85/Dungeons-Dragons-Space-Shuttles#939]
You can put magic essence in a smeltery and it will melt but you cannot get it out in anyway. The cell casting recipe does not work and there is no alloying.

**Comment by Freebi85** [comment]
From a faucet pour directly into a fluid tank. Or attach fluiduct with servo on the smeltery drain. Ir use a bucket in your hands a rightclick on a smeltery drain. Join our discord for more detailed help 👍
