### ISSUE TITLE
can not repair stell helmet in anvil

### ISSUE THREAD

**Issue by Jin16** [Freebi85/Dungeons-Dragons-Space-Shuttles#94]
When trying to repair steel helmet in an anvil it do not show:
https://imgur.com/a/QLftpfj
On a server, using version 4.6a

**Comment by Freebi85** [comment]
Sadly, I can't add recipes to the vanilla offshoot. At least there doesn't seem to be a way this.
If it was thermal foundation armor it would work but I assume this is a monster drop. (mekanism armor)
But I'll add the armour to the Crayfish washing machine so it can be repaired there. It should also work in Magma and Powered Anvil. 

Sorry :S
