### ISSUE TITLE
Exit Code: 0

### ISSUE THREAD

**Issue by GalacticTurtle01** [Freebi85/Dungeons-Dragons-Space-Shuttles#940]
Whenever I open it using Twitch it stops and says Exit Code: 0 on the MC launcher
![image](https://user-images.githubusercontent.com/72573516/95497103-ac733180-0956-11eb-8982-42654ad70752.png)

**Comment by Freebi85** [comment]
Well twitch is known to be wonky sometime after updating packs or new installations in general. You can try to reinstall to a new profile but the better solution would be to use the multimc launcher which works pretty well. 

If you meed some more informations on this join out discord server. Cheers 🍻 

I can’t fix twitch  myself :P
