### ISSUE TITLE
Feature request: Add Ynot (Xnet addon that gives ability to move gas)

### ISSUE THREAD

**Issue by Galicjanin** [Freebi85/Dungeons-Dragons-Space-Shuttles#941]
Would you like to add small add-on for Xnet called Ynot? That would add ability to use gases with Xnet cables. While Mekanism cables are separate objects each tile, Xnet cables are counting only connections, which is better for tick time.

**Comment by Freebi85** [comment]
I’m sorry the pack is in its final stage. There won’t be mod additions for now. Cheers
