### ISSUE TITLE
Feature request: Add Ender IO and Addons to it

### ISSUE THREAD

**Issue by Lanpingner** [Freebi85/Dungeons-Dragons-Space-Shuttles#942]
Ender io make it easier to manage energy cables and item, fluid .... 
because you can use 1 block of area to send 3 cables ,
its also gives bigger energy storage banks and gives more Mechines with you can have fun
And its also give ender quarry

**Comment by Freebi85** [comment]
There is integrated dynamics or xnet for this. Mekanism and draconic for big energy storage and 3 different quarrys^^ Also the pack is in its final state im sorry. Such an integration would be a lot of work in this state.
