### ISSUE TITLE
sorry about that

### ISSUE THREAD

**Issue by VzeusV** [Freebi85/Dungeons-Dragons-Space-Shuttles#943]
Sorry if it looks like I'm disrespecting your modpack, I'm really addicted to it, but I need to ask you this.
Since your modpack is finished, do you have anything against adding a mod (at my risk)?
I really wanted to add the betweenlands to use their blocks for decoration, outside using the ArmoreableMobs to make the modpack a little more difficult since it is very easy after the dragon steel.

**Comment by Freebi85** [comment]
Hey there^^ interesting question 🤔

Basically any changes to the pack are always at your own risk. I don’t know much about betweenlands tbh so no idea if there is op stuff or not.  

Whatever it has it’s not adapted to the pack. Finally you have to know yourself if you need it or not. I cannot predict if it will cause issues or affect your gameplay. 

 Cheers 🍻
