### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by Schnee404** [Freebi85/Dungeons-Dragons-Space-Shuttles#944]
I recently made a server for me, my brother and my cousin to play on. I am able to connect to my server, but my brother is unable to. I have made working servers in the past and recently updated my port forward for Minecraft. Every time he joins he gets connection timed out, no further information. Is there something in my server properties i need to change? do i need to set a server ip?

**Comment by Freebi85** [comment]
Hey there^^

Pls don't ignore the template...

**Do NOT Report here:**
-Server problems, crashes or technical issues of any kind. Use our helpdesk (tech-support-channels) in our Discord Server to get help in any of these matters.
Discord Link: https://discord.gg/eUajYmK
