### ISSUE TITLE
Problem with recipes.  I assume it's a CraftTweaker problem.

### ISSUE THREAD

**Issue by anonymousAwesome** [Freebi85/Dungeons-Dragons-Space-Shuttles#947]
I'm playing DD&SS_V.8.0_R1 with MultiMC.  I did disable a few mods that I wasn't going to use (MalisisDoors, MalisisCore, Chisels and Bits, AE2, and any mod that relied on AE2), but I don't see how that could have caused the problems I'm seeing.

Tiny Charcoal shows up in JEI but does not have a recipe.  Burning logs ("Oak Wood", "Spruce Wood", etc.) in a furnace just generates charcoal as usual.

Fresh Water shows up as several different recipes in JEI, but the one that converts a clay water bucket to Fresh Water doesn't work.

Wooden hooks have two recipes.  I haven't checked the more complicated one, but the simpler one does work.  I'm guessing the advanced crafting recipe doesn't work either, but I'm not gonna bother checking it.

Speaking of Advanced Crafting, there are two recipes for the Advanced Crafting Table and the one that uses plates doesn't work.

**Comment by Freebi85** [comment]
This pack doesent support removing any mods which includes items. Everything is linked to each other. Removing mods breaks all recipes and quests. Redownloading the original version will fix it. Pla don’t post issues about modifed pack versions. This is really not the kind of pack to modify  on your own. Too many issues without proper changes deeply in scripts and configs.

Cheers

**Comment by anonymousAwesome** [comment]
Ah.  I see.  

Well, sorry to have wasted your time, and thank you for your quick response.
