### ISSUE TITLE
Mekanism machines not processing Exchanged ores

### ISSUE THREAD

**Issue by chadlupkes** [Freebi85/Dungeons-Dragons-Space-Shuttles#950]
Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

I'm using the Exchangers, and finding that ores I get which still have the Underground Biomes identification cannot be processed by the Purification Chamber.  I have to break them with a pick to get the raw ores before they will work.  However, these ores do work within Thermal Expansion's Pulverizer.  Thought I would let you know.

**Do NOT Report here:**
-Server problems, crashes or technical issues of any kind. Use our helpdesk (tech-support-channels) in our Discord Server to get help in any of these matters.
Discord Link: https://discord.gg/eUajYmK

**Comment by Freebi85** [comment]
Thank you for the heads up. Silktouch ores from Underground biomes have no compatibility with mekanism at all sadly. I could do this on my end but that’s whole lot of work and honestly i moved to a new 1.16.4 expert Modpack project ^^

You can still use it in combination with an oredict coverter and make it to vanilla ores! 

Cheers 🍻
