### ISSUE TITLE
Washing Machine from CFM only accepts vanilla armor

### ISSUE THREAD

**Issue by MrScrewIt** [Freebi85/Dungeons-Dragons-Space-Shuttles#96]
Hi, I spent a little time gathering the resources to make the washing machine. My armor runs out quite frequently, and I remembered that this fixes it up. I spent the few vanishing dust I have to make it only to discover that it only accepts vanilla armor. Could you maybe change that? I don't quite find it fair that I can't repair my yeti armor and dragonscale stuff and don't really want to go and have to grind for more. Thanks :)

**Comment by Freebi85** [comment]
I think there's a way to get more armor repaired in the washer. This requires a certain amount of work so I will not be able to implement everything overnight. But I'll start with your requests until the next patch. Yeti / dragon armor.

**Comment by MrScrewIt** [comment]
THANK YOU
