### ISSUE TITLE
Cannot Join Discord Server

### ISSUE THREAD

**Issue by cjay567** [Freebi85/Dungeons-Dragons-Space-Shuttles#962]
I tried to join the discord server to ask for help with void ore miners and the stupid AltDentifier bot instabanned me because I accidentally tried to login from my work discord instead of my main discord. It IP-banned me too so I can't do anything to try and rejoin. There's literally no way I can ask for help with this modpack now and I'd hate to have to permanently quit it after playing it for 4 months because I'm stuck and literally can't ask for help.

This is extremely frustrating

**Comment by cjay567** [comment]
FIxed

**Comment by joel-alvarado** [comment]
How did you get unbanned?
