### ISSUE TITLE
Reactor Controller Recipe not working.

### ISSUE THREAD

**Issue by Xnosis** [Freebi85/Dungeons-Dragons-Space-Shuttles#98]
Nothing comes up in result. Using either manasteel or steel plates as per JEI.

![image](https://user-images.githubusercontent.com/12546871/54247111-18d54700-450e-11e9-9f4d-8bfbbe26e59f.png)

**Comment by Xnosis** [comment]
Tested in creative, only works will empty crystal.

**Comment by Freebi85** [comment]
found the problem. Thank you =) fixed in next update.
